/**
 * One-command `amc up` / `amc start` flow helpers (AMC-1486).
 *
 * Keeps first-run and returning-run startup prompt-free: resolve the vault
 * passphrase from the environment, the remembered store, an interactive
 * prompt, or non-interactive generation — then run the first 8-surface
 * baseline when the workspace has no prior assessment.
 */
import chalk from "chalk";
import inquirer from "inquirer";
import { getRememberedVaultPassphrase, rememberVaultPassphrase } from "../vault/passphraseStore.js";

export async function ensureUpVaultPassphrase(workspace: string, remember: boolean): Promise<void> {
  if (!process.env.AMC_VAULT_PASSPHRASE && remember) {
    const remembered = getRememberedVaultPassphrase(workspace);
    if (remembered) {
      process.env.AMC_VAULT_PASSPHRASE = remembered.passphrase;
      console.log(chalk.gray(`Vault passphrase loaded from ${remembered.backend === "keychain" ? "the macOS Keychain" : "the AMC credentials file"} (run \`amc vault forget\` to remove).`));
      return;
    }
  }
  if (process.env.AMC_VAULT_PASSPHRASE) {
    return;
  }
  if (process.stdin.isTTY) {
    const crypto = await import("node:crypto");
    const autoGenerated = crypto.randomBytes(16).toString("base64url");
    console.log(chalk.bold("\n🔐 AMC Vault Setup"));
    console.log(chalk.gray("  AMC needs a passphrase to protect cryptographic keys.\n"));
    const { choice } = await inquirer.prompt([{
      type: "select",
      name: "choice",
      message: "Vault passphrase:",
      choices: [
        { name: `Auto-generate (${autoGenerated})`, value: "auto" },
        { name: "Enter my own passphrase", value: "custom" },
      ]
    }]);
    if (choice === "auto") {
      process.env.AMC_VAULT_PASSPHRASE = autoGenerated;
      console.log(chalk.yellow(`\n  ⚠ Save this passphrase: ${chalk.bold.white(autoGenerated)}\n`));
    } else {
      const { customPass } = await inquirer.prompt([{
        type: "password",
        name: "customPass",
        message: "Enter passphrase (min 8 chars):",
        mask: "*",
        validate: (v: string) => v.length >= 8 || "Must be at least 8 characters"
      }]);
      process.env.AMC_VAULT_PASSPHRASE = customPass;
    }
    if (remember) {
      const { rememberChoice } = await inquirer.prompt([{
        type: "confirm",
        name: "rememberChoice",
        message: "Remember this passphrase on this machine so `amc up` starts without prompts?",
        default: true
      }]);
      if (rememberChoice) {
        const saved = rememberVaultPassphrase(workspace, process.env.AMC_VAULT_PASSPHRASE as string);
        console.log(chalk.gray(`  Passphrase remembered in ${saved.location}. Run \`amc vault forget\` to remove it.`));
      }
    }
    return;
  }
  if (remember) {
    const crypto = await import("node:crypto");
    const generated = crypto.randomBytes(16).toString("base64url");
    process.env.AMC_VAULT_PASSPHRASE = generated;
    const saved = rememberVaultPassphrase(workspace, generated);
    console.log(chalk.yellow("No vault passphrase found in a non-interactive shell; generated one for this workspace."));
    console.log(chalk.yellow(`It is remembered in ${saved.location}. Run \`amc vault forget\` to remove it, or set AMC_VAULT_PASSPHRASE to manage it yourself.`));
    return;
  }
  throw new Error(
    [
      "🔐 Vault passphrase required in non-interactive shells.",
      "",
      "Option 1 — set passphrase (recommended):",
      "  export AMC_VAULT_PASSPHRASE='your-passphrase'",
      "  amc up",
      "",
      "Option 2 — first-time setup (generates passphrase):",
      "  amc setup",
      "",
      "Option 3 — explore without signing (local demo mode):",
      "  amc up --demo",
      "  amc up --demo --dry-run"
    ].join("\n")
  );
}

export interface BaselineWorkspaceState {
  vault: { noSign: boolean; reason: string | null };
  createdWorkspace: boolean;
  createdAgentContext: boolean;
}

export async function runFirstBaselineIfNeeded(params: {
  workspace: string;
  agentId: string;
  hasLatestRun: boolean;
  baseline: boolean;
  ensureInstantWorkspace: (workspace: string, agentId: string) => BaselineWorkspaceState;
}): Promise<void> {
  if (params.hasLatestRun || !params.baseline) {
    return;
  }
  console.log(chalk.bold("\nNo prior assessment found — running the first 8-surface baseline (amc run)..."));
  try {
    const { unifiedRun, renderUnifiedResult } = await import("../unified/index.js");
    const instant = params.ensureInstantWorkspace(params.workspace, params.agentId);
    const baseline = await unifiedRun({
      workspace: params.workspace,
      agentId: params.agentId,
      window: "14d",
      ci: false,
      noSign: instant.vault.noSign,
      createdWorkspace: instant.createdWorkspace,
      createdAgentContext: instant.createdAgentContext,
      vaultReason: instant.vault.reason
    });
    console.log(renderUnifiedResult(baseline, { ci: false }));
    console.log(chalk.gray("Baseline complete. Open the Compass Console to work through all eight surfaces."));
  } catch (error) {
    console.log(chalk.yellow(`Baseline assessment could not run: ${error instanceof Error ? error.message : String(error)}. Run \`amc run\` manually.`));
  }
}
