import { readFileSync } from "node:fs";
import { describe, expect, test } from "vitest";
import { buildScoreEvidenceDrilldown } from "../src/diagnostic/evidenceDrilldown.js";
import { buildWatchObsStudioSourceArtifactLinks } from "../src/watch/evidenceDrilldown.js";
import type { DiagnosticReport } from "../src/types.js";

function report(overrides: Partial<DiagnosticReport> = {}): DiagnosticReport {
  return {
    agentId: "agent-1",
    runId: "run-1",
    ts: 1,
    windowStartTs: 1,
    windowEndTs: 2,
    status: "VALID",
    verificationPassed: true,
    trustBoundaryViolated: false,
    trustBoundaryMessage: null,
    integrityIndex: 0.91,
    trustLabel: "HIGH TRUST",
    targetProfileId: "default",
    layerScores: [],
    questionScores: [],
    inflationAttempts: [],
    unsupportedClaimCount: 0,
    contradictionCount: 0,
    correlationRatio: 1,
    invalidReceiptsCount: 0,
    correlationWarnings: [],
    evidenceCoverage: 1,
    evidenceTrustCoverage: { observed: 1, attested: 0, selfReported: 0 },
    targetDiff: [],
    prioritizedUpgradeActions: [],
    evidenceToCollectNext: [],
    runSealSig: "sig",
    reportJsonSha256: "report-hash",
    questionExplainability: {
      generatedAt: "2026-06-13T00:00:00.000Z",
      agentId: "agent-1",
      runId: "run-1",
      sourceRefs: ["amc:diagnostic-ledger"],
      replayable: true,
      failClosed: true,
      manifestHash: "a".repeat(64),
      rows: [
        {
          questionId: "AMC-1.1",
          title: "Mission Evidence",
          surfaces: ["Score", "Shield", "Watch"],
          claimedLevel: 5,
          supportedMaxLevel: 3,
          finalLevel: 3,
          status: "unsupported_claim",
          evidenceWindow: {
            eventCount: 2,
            distinctSessionCount: 2,
            firstTs: 10,
            lastTs: 11,
            durationMs: 1,
          },
          acceptedEvidenceIds: ["ev-pass"],
          signedEvidenceRefs: [
            {
              evidenceId: "ev-pass",
              eventHash: "b".repeat(64),
              writerSig: "sig-pass",
              eventType: "audit",
              sessionId: "session-pass",
              ts: 10,
              trustTier: "OBSERVED",
            },
          ],
          rejectedEvidence: [
            {
              evidenceId: "ev-reject",
              eventHash: "c".repeat(64),
              writerSig: "sig-reject",
              eventType: "review",
              sessionId: "session-review",
              ts: 11,
              trustTier: "ATTESTED",
              reason: "not accepted by selected gate",
            },
          ],
          componentDiagnostics: [
            {
              componentId: "evidence-ledger",
              componentType: "evidence",
              status: "accepted",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: [],
              repairHint: "Preserve signed evidence.",
            },
          ],
          criteriaDiagnostics: [
            {
              criterionId: "prompt-artifact-alignment",
              criterionType: "prompt_artifact_alignment",
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: [],
              judgeRef: "judge://atelier/prompt-artifact",
              repairHint: "Keep prompt-output artifact evidence attached to this question.",
            },
            {
              criterionId: "prd-file-comparison-criteria",
              criterionType: "file_comparison",
              status: "failed",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              judgeRef: "judge://eval-agent/file",
              repairHint: "Attach file comparison output that satisfies the criterion.",
            },
            {
              criterionId: "forecast-tool-trace",
              criterionType: "tool_use_trace",
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: [],
              judgeRef: "judge://forecasting/tool-trace",
              repairHint: "Keep signed tool execution evidence linked to the forecast answer.",
            },
            {
              criterionId: "runtime-code-execution-sandbox",
              criterionType: "code_execution_sandbox",
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: [],
              judgeRef: "judge://runtime/code-sandbox",
              repairHint: "Keep sandbox and execution-isolation evidence linked to the question.",
            },
            {
              criterionId: "final-executable-action-risk",
              criterionType: "final_action_risk",
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: [],
              judgeRef: "judge://tool-risk/final-action",
              repairHint: "Keep final action risk evidence linked to the question.",
            },
            {
              criterionId: "router-visible-prefix",
              criterionType: "router_visible_prefix",
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: [],
              judgeRef: "judge://routing/prefix",
              repairHint: "Keep signed router-visible prefix evidence linked to the question.",
            },
            {
              criterionId: "exploit-attempt-trace",
              criterionType: "exploit_attempt_trace",
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: [],
              judgeRef: "judge://redteam/exploit-trace",
              repairHint: "Keep exploit attempt evidence linked to the question.",
            },
          ],
          rubricLens: [
            {
              rubricId: "skilllens-general-v1",
              rubricVersion: "2026.06.13",
              rubricSource: "https://github.com/AndrewNgGirl/SkillLens",
              skillType: "pipeline",
              score0to100: 78,
              grade: "B",
              deepReviewCertificateHash: "f".repeat(64),
              marketSignalRefs: ["github:skilllens:market-signal"],
              checks: [
                {
                  checkId: "pipeline-routing",
                  pillar: "effect-stability",
                  status: "pass",
                  weight: 5,
                  evidenceRefs: ["ev-pass"],
                  rejectedEvidenceRefs: [],
                  fixHint: "Keep routing evidence linked to the question receipt.",
                },
                {
                  checkId: "subskill-quality",
                  pillar: "writing-quality",
                  status: "partial",
                  weight: 2,
                  evidenceRefs: ["ev-pass"],
                  rejectedEvidenceRefs: ["ev-reject"],
                  fixHint: "Add subskill-level evidence before claiming full readiness.",
                },
              ],
            },
          ],
          ragFlowDiagnostics: [
            {
              flowId: "rag-flow-1",
              vectorSearchBackend: "azure_search",
              flowDagHash: "1".repeat(64),
              paramConfigHash: "2".repeat(64),
              evalSetHash: "3".repeat(64),
              batchRunId: "batch-1",
              evaluatorFlowHash: "4".repeat(64),
              groundTruthColumn: "answer",
              dataMappingHash: "5".repeat(64),
              variantId: "variant-a",
              variantConfigHash: "6".repeat(64),
              deploymentArtifactHash: "7".repeat(64),
              metricIds: ["groundedness"],
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: [],
              repairHint: "Keep RAG flow evidence attached.",
            },
          ],
          landscapeLens: [
            {
              landscapeId: "ai-coding-landscape-2026",
              sourceRef: "https://github.com/joylarkin/AI-Coding-Landscape",
              category: "ai_coding_leaderboard",
              datasetRefs: ["aicodingtools.csv"],
              datasetHashes: ["8".repeat(64)],
              updateCadence: "bimonthly",
              lastVerifiedAt: "2026-06-13",
              freshnessDays: 5,
              maxAllowedFreshnessDays: 62,
              cohortRefs: ["AI Coding Agents/CLI Tools"],
              benchmarkRefs: ["AI Coding Leaderboards"],
              toolOrModelRefs: ["agent-cli-cohort"],
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              repairHint: "Refresh dataset hashes and cohort refs before external use.",
            },
          ],
          incidentTriageLens: [
            {
              environmentId: "incident-triage-openenv",
              sourceRef: "https://github.com/Harikishanth/Incident-Triage-Environment",
              taskId: "medium",
              scenarioId: "p1-cascading-failure",
              difficulty: "medium",
              severity: "p1",
              openEnvConfigHash: "9".repeat(64),
              scenarioManifestHash: "a".repeat(64),
              incidentReportHash: "b".repeat(64),
              rawLogBundleHash: "c".repeat(64),
              metricSnapshotHash: "d".repeat(64),
              userReportHash: "e".repeat(64),
              actionPayloadHash: "f".repeat(64),
              graderConfigHash: "1".repeat(64),
              feedbackHash: "2".repeat(64),
              reward0to1: 0.91,
              minReward0to1: 0.8,
              rootCauseScore0to1: 1,
              minRootCauseScore0to1: 0.8,
              redHerringFilterScore0to1: 0.88,
              minRedHerringFilterScore0to1: 0.75,
              orderedRemediationScore0to1: 0.86,
              minOrderedRemediationScore0to1: 0.75,
              maxSteps: 1,
              stepCount: 1,
              deterministicGrader: true,
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              repairHint: "Keep OpenEnv logs, metrics, grader config, action payload, and ordered remediation evidence attached.",
              rowHash: "3".repeat(64),
            },
          ],
          benchmarkSubmissionLens: [],
          testSuiteEvaluationLens: [],
          multiUserBenchmarkLens: [
            {
              benchmarkId: "multi-user-llm-agent-style-synthetic",
              sourceRef: "https://github.com/Kordi-AI/Multi-User-LLM-Agent",
              scenarioId: "synthetic-access-control-001",
              scenarioFamily: "access_control",
              capability: "privacy_access_control",
              datasetManifestHash: "4".repeat(64),
              userRoleManifestHash: "5".repeat(64),
              permissionPolicyHash: "6".repeat(64),
              preferenceProfileHash: null,
              resourceQueuePolicyHash: null,
              instructionSetHash: "7".repeat(64),
              interactionTraceHash: "8".repeat(64),
              evaluatorConfigHash: "9".repeat(64),
              resultArtifactHash: "a".repeat(64),
              metricReportHash: "b".repeat(64),
              userRoleCount: 3,
              turnCount: 8,
              privacyPassRate0to1: 0.96,
              minPrivacyPassRate0to1: 0.9,
              coordinationSuccessRate0to1: null,
              minCoordinationSuccessRate0to1: null,
              queueFairnessScore0to1: null,
              minQueueFairnessScore0to1: null,
              instructionFollowingScore0to1: 0.92,
              minInstructionFollowingScore0to1: 0.85,
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              repairHint: "Keep multi-user role, policy, trace, evaluator, result, metric, and repair proof attached.",
              rowHash: "c".repeat(64),
            },
          ],
          continualLearningBenchmarkLens: [
            {
              benchmarkId: "cl-bench-style-synthetic",
              sourceRef: "https://github.com/Arc-Computer/CL-Bench",
              domainId: "crm",
              workflowId: "lead-reassignment-multiturn",
              datasetManifestHash: "4".repeat(64),
              stateSchemaHash: "5".repeat(64),
              initialStateHash: "6".repeat(64),
              stateMutationTraceHash: "7".repeat(64),
              conversationTraceHash: "8".repeat(64),
              entityRelationshipGraphHash: "9".repeat(64),
              toolExecutionTraceHash: "a".repeat(64),
              evaluatorConfigHash: "b".repeat(64),
              resultArtifactHash: "c".repeat(64),
              replayCommandHash: "d".repeat(64),
              memoryPolicyHash: "e".repeat(64),
              adaptiveLearningTraceHash: "f".repeat(64),
              scenarioCount: 2,
              turnCount: 9,
              stateMutationCount: 4,
              entityCount: 6,
              taskCompletionRate0to1: 0.91,
              minTaskCompletionRate0to1: 0.85,
              responseQualityScore0to1: 0.88,
              minResponseQualityScore0to1: 0.82,
              stateAccuracy0to1: 0.93,
              minStateAccuracy0to1: 0.9,
              retentionScore0to1: 0.86,
              minRetentionScore0to1: 0.8,
              tokenCostUsd: 0.07,
              maxTokenCostUsd: 0.1,
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              repairHint: "Keep state schema, mutation trace, conversation, entity graph, tool execution, evaluator, replay, and retention proof attached.",
              rowHash: "2".repeat(64),
            },
          ],
          professionalTaskLens: [
            {
              benchmarkId: "occubench-professional-task",
              sourceRef: "https://github.com/GregxmHu/OccuBench",
              taskId: "professional-task-001",
              scenarioId: "domain-scenario-001",
              industryCategory: "business-enterprise",
              professionalDomain: "real-estate",
              difficultyLevel: 2,
              datasetManifestHash: "4".repeat(64),
              scenarioManifestHash: "5".repeat(64),
              worldModelConfigHash: "6".repeat(64),
              toolSchemaHash: "7".repeat(64),
              agentConfigHash: "8".repeat(64),
              faultInjectionConfigHash: "9".repeat(64),
              verifierRubricHash: "a".repeat(64),
              verifierVoteManifestHash: "b".repeat(64),
              trajectoryHash: "c".repeat(64),
              resultArtifactHash: "d".repeat(64),
              replayConfigHash: "e".repeat(64),
              debugTraceHash: "f".repeat(64),
              environmentMode: "E2",
              faultMode: "implicit",
              verifierVoteCount: 3,
              minVerifierVoteCount: 3,
              passRate0to1: 0.86,
              minPassRate0to1: 0.8,
              robustnessScore0to1: 0.82,
              minRobustnessScore0to1: 0.75,
              trajectoryStepCount: 5,
              maxTrajectoryStepCount: 12,
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              repairHint: "Keep professional task scenario, LWM environment, verifier vote, trajectory, replay, and repair proof attached.",
              rowHash: "1".repeat(64),
            },
          ],
          iotFirmwareQuestionLens: [
            {
              benchmarkId: "adsum-iot-firmware-style-synthetic",
              sourceRef: "https://github.com/adsumnetworks/Adsum-IoT-Coder",
              taskId: "ble-device-log-fix-001",
              platform: "nrf",
              boardId: "nrf52-dk",
              chipFamily: "nrf52",
              firmwareProjectHash: "4".repeat(64),
              toolchainManifestHash: "5".repeat(64),
              sdkVersionManifestHash: "6".repeat(64),
              hardwareSessionHash: "7".repeat(64),
              deviceLogBundleHash: "8".repeat(64),
              buildArtifactHash: "9".repeat(64),
              flashArtifactHash: "a".repeat(64),
              testArtifactHash: "b".repeat(64),
              knowledgePackManifestHash: "c".repeat(64),
              taskManifestHash: "d".repeat(64),
              evaluatorConfigHash: "e".repeat(64),
              resultArtifactHash: "f".repeat(64),
              privacyBoundaryHash: "1".repeat(64),
              benchmarkReportHash: "2".repeat(64),
              hardwareRunCount: 6,
              deviceCount: 2,
              bugClosureRate0to1: 0.83,
              minBugClosureRate0to1: 0.8,
              tokenEfficiencyRatio: 3.8,
              minTokenEfficiencyRatio: 1,
              logCaptureCoverage0to1: 0.95,
              minLogCaptureCoverage0to1: 0.9,
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              repairHint: "Keep IoT hardware session, device logs, build/flash/test artifacts, privacy boundary, and benchmark report proof attached.",
              rowHash: "3".repeat(64),
            },
          ],
          retailSalesQuestionLens: [
            {
              benchmarkId: "shampoo-sales-agent-style-synthetic",
              sourceRef: "https://github.com/jackfsuia/ShampooSalesAgent",
              taskId: "shampoo-consultative-sale-001",
              salesChannel: "cli",
              productCatalogHash: "4".repeat(64),
              productDescriptionHash: "5".repeat(64),
              customerScenarioHash: "6".repeat(64),
              conversationTraceHash: "7".repeat(64),
              customerIntentManifestHash: "8".repeat(64),
              orderCaptureSchemaHash: "9".repeat(64),
              orderLedgerHash: "a".repeat(64),
              pricingPolicyHash: "b".repeat(64),
              discountPolicyHash: "c".repeat(64),
              modelAdapterManifestHash: "d".repeat(64),
              modelProviderMatrixHash: "e".repeat(64),
              promptPolicyHash: "f".repeat(64),
              recommendationPolicyHash: "1".repeat(64),
              safetyPolicyHash: "2".repeat(64),
              privacyBoundaryHash: "3".repeat(64),
              evaluatorConfigHash: "4".repeat(64),
              resultArtifactHash: "5".repeat(64),
              benchmarkReportHash: "6".repeat(64),
              modelProviderCount: 4,
              customerScenarioCount: 3,
              orderCount: 12,
              orderCaptureAccuracy0to1: 0.96,
              minOrderCaptureAccuracy0to1: 0.9,
              policyComplianceRate0to1: 0.94,
              minPolicyComplianceRate0to1: 0.9,
              recommendationGrounding0to1: 0.92,
              minRecommendationGrounding0to1: 0.88,
              piiRedactionRate0to1: 1,
              minPiiRedactionRate0to1: 0.98,
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              repairHint: "Keep retail sales product, conversation, order, provider, policy, and privacy proof attached.",
              rowHash: "4".repeat(64),
            },
          ],
          scorableStudioDrilldownLens: [
            {
              drilldownId: "scorable-sdk-studio-drilldown",
              sourceRef: "https://github.com/root-signals/scorable-sdk",
              repositoryRef: "root-signals/scorable-sdk",
              licenseRef: "Apache License 2.0",
              licenseSpdxId: "Apache-2.0",
              defaultBranch: "main",
              sourceCommitSha: "3498486b9d567099d6ec9849a7391537233752d2",
              sourceTreeSha: "393540b215825e05c8976bdfae2084a8feb480c7",
              readmeArtifactHash: "7".repeat(64),
              pythonPackageManifestHash: "8".repeat(64),
              pythonOpenApiHash: "9".repeat(64),
              pythonClientHash: "a".repeat(64),
              pythonExecutionLogsHash: "b".repeat(64),
              pythonEvaluatorApiHash: "c".repeat(64),
              pythonExecutionLogApiHash: "d".repeat(64),
              cliPackageManifestHash: "e".repeat(64),
              cliLockfileHash: "f".repeat(64),
              cliEvaluatorCommandHash: "1".repeat(64),
              cliJudgeCommandHash: "2".repeat(64),
              cliExecutionLogCommandHash: "3".repeat(64),
              cliOtelTraceCommandHash: "4".repeat(64),
              cliFileUploadCommandHash: "5".repeat(64),
              typescriptPackageManifestHash: "6".repeat(64),
              typescriptLockfileHash: "7".repeat(64),
              typescriptSourceTreeHash: "8".repeat(64),
              npmPackageRef: "@root-signals/scorable@0.11.0",
              npmPackageIntegrity: "sha512-DuGI39YHi2ZOO5kRYgvJbvsBNxBS642Pkg2rNq0sz3mSdhJvCvr3nlrzMkNK0NVPMOSy5oDoExVzG8HVPNGiTw==",
              npmCliPackageRef: "@root-signals/scorable-cli@0.14.0",
              npmCliPackageIntegrity: "sha512-aWloGCEEfcP3kMFiIweKiOHPVA7BS4SN10GkXE4NX6wOoM+SS9+2PquJ5y8XVK3k0PlmDcwrrZljd0NNUsyJ4w==",
              studioSurface: "cli",
              uiRoutePath: "/api/v1/score/evidence-drilldown/run-1/AMC-1.1",
              sourceArtifactLinks: [
                "https://github.com/root-signals/scorable-sdk/tree/3498486b9d567099d6ec9849a7391537233752d2",
                "https://www.npmjs.com/package/@root-signals/scorable/v/0.11.0",
                "https://www.npmjs.com/package/@root-signals/scorable-cli/v/0.14.0",
              ],
              tracePreviewHash: "9".repeat(64),
              receiptPreviewHash: "a".repeat(64),
              policyRulePreviewHash: "b".repeat(64),
              sourceArtifactPreviewHash: "c".repeat(64),
              emptyStateHash: "d".repeat(64),
              errorStateHash: "e".repeat(64),
              evidencePreviewState: "ready",
              evidencePreviewCount: 3,
              minEvidencePreviewCount: 2,
              sourceArtifactLinkCount: 3,
              minSourceArtifactLinkCount: 3,
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              repairHint: "Keep Scorable SDK trace, receipt, policy rule, source artifact, empty-state, and error-state proof attached to the Studio drilldown row.",
              rowHash: "f".repeat(64),
            },
          ],
          obsStudioDrilldownLens: [
            {
              drilldownId: "literal-ai-product-studio-drilldown",
              sourceRef: "https://docs.literalai.com/llms.txt",
              sourceKind: "product",
              publisherRef: "Literal AI docs",
              titleRef: "Literal AI observability, evaluation, dashboard, logs, and online evals",
              venueRef: "docs.literalai.com",
              publicationDate: "2026-06-20",
              uiRoutePath: "/api/v1/score/evidence-drilldown/run-1/AMC-1.1",
              sourceArtifactLinks: buildWatchObsStudioSourceArtifactLinks({
                sourceUrl: "https://literalai.com",
                docsIndexUrl: "https://docs.literalai.com/llms.txt",
                docsPageUrls: [
                  "https://docs.literalai.com/get-started/overview.md",
                  "https://docs.literalai.com/guides/dashboard.md",
                  "https://docs.literalai.com/guides/logs.md",
                  "https://docs.literalai.com/guides/online-evals.md",
                ],
              }),
              tracePreviewHash: "1".repeat(64),
              reasoningTracePreviewHash: "2".repeat(64),
              receiptPreviewHash: "3".repeat(64),
              evidencePreviewHash: "4".repeat(64),
              sourceArtifactPreviewHash: "5".repeat(64),
              emptyStateHash: "6".repeat(64),
              errorStateHash: "7".repeat(64),
              evidencePreviewState: "ready",
              evidencePreviewCount: 4,
              minEvidencePreviewCount: 2,
              sourceArtifactLinkCount: 6,
              minSourceArtifactLinkCount: 4,
              status: "satisfied",
              evidenceRefs: ["ev-pass"],
              rejectedEvidenceRefs: ["ev-reject"],
              repairHint: "Keep Literal AI source artifact links, AMC-owned route proof, preview hashes, and empty/error state receipts attached without copying upstream UI or docs prose.",
              rowHash: "8".repeat(64),
            },
          ],
          missingGateReasons: ["failed gate 4"],
          repairHint: "Collect signed mission evidence.",
          scoreReceiptRef: "diagnostic://run-1/question/AMC-1.1",
          rowHash: "d".repeat(64),
        },
      ],
    },
    methodology: {
      id: "amc-public-scoring-methodology",
      version: "2026.06.13",
      releaseDate: "2026-06-13",
      status: "public",
      amcVersion: "1.0.0",
      methodologyDoc: "docs/SCORING_METHODOLOGY.md",
      publicUrl: "/docs/SCORING_METHODOLOGY.md",
      defaultQuestionSetVersion: "amc-legacy-240-v1",
      questionSet: {
        version: "amc-legacy-240-v1",
        title: "AMC legacy 240",
        questionCount: 240,
        includedVersions: ["amc-legacy-240-v1"],
        default: true,
      },
      hash: "e".repeat(64),
    },
    ...overrides,
  };
}

describe("buildScoreEvidenceDrilldown", () => {
  test("builds a ready drilldown with source artifact links and evidence previews", () => {
    const out = buildScoreEvidenceDrilldown(report(), "AMC-1.1");

    expect(out.state).toBe("ready");
    expect(out.questionId).toBe("AMC-1.1");
    expect(out.status).toBe("unsupported_claim");
    expect(out.levels).toEqual({ claimed: 5, supported: 3, final: 3 });
    expect(out.evidenceWindow).toEqual({
      eventCount: 2,
      distinctSessionCount: 2,
      firstTs: 10,
      lastTs: 11,
      durationMs: 1,
    });
    expect(out.sourceArtifacts.map((link) => link.kind)).toEqual([
      "score-report",
      "watch-explain",
      "shield-receipt",
      "passport-hash",
      "methodology",
      "methodology-versioning",
    ]);
    expect(out.sourceArtifacts[0]?.href).toContain("/api/v1/score/report/run-1");
    expect(out.evidencePreview.accepted[0]).toMatchObject({
      evidenceId: "ev-pass",
      eventHash: "b".repeat(64),
      writerSig: "sig-pass",
    });
    expect(out.evidencePreview.rejected[0]).toMatchObject({
      evidenceId: "ev-reject",
      reason: "not accepted by selected gate",
    });
    expect(out.criteriaPreview[0]).toMatchObject({
      criterionId: "prompt-artifact-alignment",
      criterionType: "prompt_artifact_alignment",
      status: "satisfied",
      judgeRef: "judge://atelier/prompt-artifact",
    });
    expect(out.criteriaPreview[1]).toMatchObject({
      criterionId: "prd-file-comparison-criteria",
      criterionType: "file_comparison",
      status: "failed",
    });
    expect(out.criteriaPreview[2]).toMatchObject({
      criterionId: "forecast-tool-trace",
      criterionType: "tool_use_trace",
      status: "satisfied",
      judgeRef: "judge://forecasting/tool-trace",
    });
    expect(out.criteriaPreview[3]).toMatchObject({
      criterionId: "runtime-code-execution-sandbox",
      criterionType: "code_execution_sandbox",
      status: "satisfied",
      judgeRef: "judge://runtime/code-sandbox",
    });
    expect(out.criteriaPreview[4]).toMatchObject({
      criterionId: "final-executable-action-risk",
      criterionType: "final_action_risk",
      status: "satisfied",
      judgeRef: "judge://tool-risk/final-action",
    });
    expect(out.criteriaPreview[5]).toMatchObject({
      criterionId: "router-visible-prefix",
      criterionType: "router_visible_prefix",
      status: "satisfied",
      judgeRef: "judge://routing/prefix",
    });
    expect(out.criteriaPreview[6]).toMatchObject({
      criterionId: "exploit-attempt-trace",
      criterionType: "exploit_attempt_trace",
      status: "satisfied",
      judgeRef: "judge://redteam/exploit-trace",
    });
    expect(out.rubricLensPreview[0]).toMatchObject({
      rubricId: "skilllens-general-v1",
      rubricVersion: "2026.06.13",
      skillType: "pipeline",
      score0to100: 78,
      grade: "B",
      deepReviewCertificateHash: "f".repeat(64),
    });
    expect(out.rubricLensPreview[0]?.checks[1]).toMatchObject({
      checkId: "subskill-quality",
      status: "partial",
      fixHint: "Add subskill-level evidence before claiming full readiness.",
    });
    expect(out.ragFlowPreview[0]).toMatchObject({
      flowId: "rag-flow-1",
      vectorSearchBackend: "azure_search",
      batchRunId: "batch-1",
      metricIds: ["groundedness"],
      status: "satisfied",
    });
    expect(out.landscapeLensPreview[0]).toMatchObject({
      landscapeId: "ai-coding-landscape-2026",
      category: "ai_coding_leaderboard",
      updateCadence: "bimonthly",
      freshnessDays: 5,
      maxAllowedFreshnessDays: 62,
      cohortRefs: ["AI Coding Agents/CLI Tools"],
      status: "satisfied",
      evidenceRefs: ["ev-pass"],
    });
    expect(out.incidentTriagePreview[0]).toMatchObject({
      environmentId: "incident-triage-openenv",
      sourceRef: "https://github.com/Harikishanth/Incident-Triage-Environment",
      taskId: "medium",
      scenarioId: "p1-cascading-failure",
      difficulty: "medium",
      severity: "p1",
      reward0to1: 0.91,
      rootCauseScore0to1: 1,
      redHerringFilterScore0to1: 0.88,
      orderedRemediationScore0to1: 0.86,
      maxSteps: 1,
      stepCount: 1,
      deterministicGrader: true,
      status: "satisfied",
      evidenceRefs: ["ev-pass"],
      rejectedEvidenceRefs: ["ev-reject"],
      rowHash: "3".repeat(64),
    });
    expect(out.multiUserBenchmarkPreview[0]).toMatchObject({
      benchmarkId: "multi-user-llm-agent-style-synthetic",
      sourceRef: "https://github.com/Kordi-AI/Multi-User-LLM-Agent",
      scenarioId: "synthetic-access-control-001",
      scenarioFamily: "access_control",
      capability: "privacy_access_control",
      userRoleCount: 3,
      turnCount: 8,
      privacyPassRate0to1: 0.96,
      minPrivacyPassRate0to1: 0.9,
      instructionFollowingScore0to1: 0.92,
      status: "satisfied",
      evidenceRefs: ["ev-pass"],
      rejectedEvidenceRefs: ["ev-reject"],
      rowHash: "c".repeat(64),
    });
    expect(out.continualLearningBenchmarkPreview[0]).toMatchObject({
      benchmarkId: "cl-bench-style-synthetic",
      sourceRef: "https://github.com/Arc-Computer/CL-Bench",
      domainId: "crm",
      workflowId: "lead-reassignment-multiturn",
      scenarioCount: 2,
      turnCount: 9,
      stateMutationCount: 4,
      entityCount: 6,
      taskCompletionRate0to1: 0.91,
      responseQualityScore0to1: 0.88,
      stateAccuracy0to1: 0.93,
      retentionScore0to1: 0.86,
      tokenCostUsd: 0.07,
      maxTokenCostUsd: 0.1,
      status: "satisfied",
      evidenceRefs: ["ev-pass"],
      rejectedEvidenceRefs: ["ev-reject"],
      rowHash: "2".repeat(64),
    });
    expect(out.professionalTaskPreview[0]).toMatchObject({
      benchmarkId: "occubench-professional-task",
      sourceRef: "https://github.com/GregxmHu/OccuBench",
      taskId: "professional-task-001",
      scenarioId: "domain-scenario-001",
      industryCategory: "business-enterprise",
      professionalDomain: "real-estate",
      environmentMode: "E2",
      faultMode: "implicit",
      verifierVoteCount: 3,
      passRate0to1: 0.86,
      robustnessScore0to1: 0.82,
      trajectoryStepCount: 5,
      status: "satisfied",
      evidenceRefs: ["ev-pass"],
      rejectedEvidenceRefs: ["ev-reject"],
      rowHash: "1".repeat(64),
    });
    expect(out.iotFirmwareQuestionPreview[0]).toMatchObject({
      benchmarkId: "adsum-iot-firmware-style-synthetic",
      sourceRef: "https://github.com/adsumnetworks/Adsum-IoT-Coder",
      taskId: "ble-device-log-fix-001",
      platform: "nrf",
      boardId: "nrf52-dk",
      chipFamily: "nrf52",
      hardwareRunCount: 6,
      deviceCount: 2,
      bugClosureRate0to1: 0.83,
      tokenEfficiencyRatio: 3.8,
      logCaptureCoverage0to1: 0.95,
      status: "satisfied",
      evidenceRefs: ["ev-pass"],
      rejectedEvidenceRefs: ["ev-reject"],
      rowHash: "3".repeat(64),
    });
    expect(out.retailSalesQuestionPreview[0]).toMatchObject({
      benchmarkId: "shampoo-sales-agent-style-synthetic",
      sourceRef: "https://github.com/jackfsuia/ShampooSalesAgent",
      taskId: "shampoo-consultative-sale-001",
      salesChannel: "cli",
      modelProviderCount: 4,
      customerScenarioCount: 3,
      orderCount: 12,
      orderCaptureAccuracy0to1: 0.96,
      policyComplianceRate0to1: 0.94,
      recommendationGrounding0to1: 0.92,
      piiRedactionRate0to1: 1,
      status: "satisfied",
      evidenceRefs: ["ev-pass"],
      rejectedEvidenceRefs: ["ev-reject"],
      rowHash: "4".repeat(64),
    });
    expect(out.scorableStudioDrilldownPreview[0]).toMatchObject({
      drilldownId: "scorable-sdk-studio-drilldown",
      sourceRef: "https://github.com/root-signals/scorable-sdk",
      repositoryRef: "root-signals/scorable-sdk",
      licenseSpdxId: "Apache-2.0",
      defaultBranch: "main",
      sourceCommitSha: "3498486b9d567099d6ec9849a7391537233752d2",
      sourceTreeSha: "393540b215825e05c8976bdfae2084a8feb480c7",
      npmPackageRef: "@root-signals/scorable@0.11.0",
      npmCliPackageRef: "@root-signals/scorable-cli@0.14.0",
      studioSurface: "cli",
      uiRoutePath: "/api/v1/score/evidence-drilldown/run-1/AMC-1.1",
      evidencePreviewState: "ready",
      evidencePreviewCount: 3,
      minEvidencePreviewCount: 2,
      sourceArtifactLinkCount: 3,
      minSourceArtifactLinkCount: 3,
      status: "satisfied",
      evidenceRefs: ["ev-pass"],
      rejectedEvidenceRefs: ["ev-reject"],
      rowHash: "f".repeat(64),
    });
    expect(out.scorableStudioDrilldownPreview[0]?.sourceArtifactLinks).toContain(
      "https://github.com/root-signals/scorable-sdk/tree/3498486b9d567099d6ec9849a7391537233752d2"
    );
    expect(out.obsStudioDrilldownPreview[0]).toMatchObject({
      drilldownId: "literal-ai-product-studio-drilldown",
      sourceRef: "https://docs.literalai.com/llms.txt",
      sourceKind: "product",
      publisherRef: "Literal AI docs",
      titleRef: "Literal AI observability, evaluation, dashboard, logs, and online evals",
      venueRef: "docs.literalai.com",
      uiRoutePath: "/api/v1/score/evidence-drilldown/run-1/AMC-1.1",
      evidencePreviewState: "ready",
      evidencePreviewCount: 4,
      minEvidencePreviewCount: 2,
      sourceArtifactLinkCount: 6,
      minSourceArtifactLinkCount: 4,
      status: "satisfied",
      evidenceRefs: ["ev-pass"],
      rejectedEvidenceRefs: ["ev-reject"],
      rowHash: "8".repeat(64),
    });
    expect(out.obsStudioDrilldownPreview[0]?.sourceArtifactLinks).toEqual([
      "https://literalai.com",
      "https://docs.literalai.com/llms.txt",
      "https://docs.literalai.com/get-started/overview.md",
      "https://docs.literalai.com/guides/dashboard.md",
      "https://docs.literalai.com/guides/logs.md",
      "https://docs.literalai.com/guides/online-evals.md",
    ]);
    expect(out.repairHint).toBe("Collect signed mission evidence.");
    expect(out.failClosed).toBe(true);
  });

  test("returns an empty state when a run has no question receipt pack", () => {
    const out = buildScoreEvidenceDrilldown(report({ questionExplainability: undefined }), "AMC-1.1");

    expect(out.state).toBe("empty");
    expect(out.message).toContain("does not include question-level explainability receipts");
    expect(out.evidencePreview.accepted).toEqual([]);
    expect(out.criteriaPreview).toEqual([]);
    expect(out.rubricLensPreview).toEqual([]);
    expect(out.ragFlowPreview).toEqual([]);
    expect(out.landscapeLensPreview).toEqual([]);
    expect(out.incidentTriagePreview).toEqual([]);
    expect(out.multiUserBenchmarkPreview).toEqual([]);
    expect(out.continualLearningBenchmarkPreview).toEqual([]);
    expect(out.professionalTaskPreview).toEqual([]);
    expect(out.iotFirmwareQuestionPreview).toEqual([]);
    expect(out.retailSalesQuestionPreview).toEqual([]);
    expect(out.scorableStudioDrilldownPreview).toEqual([]);
    expect(out.evidenceWindow).toBeNull();
    expect(out.sourceArtifacts.some((link) => link.kind === "score-report")).toBe(true);
    expect(out.failClosed).toBe(true);
  });

  test("returns an empty state when the requested question has no receipt row", () => {
    const out = buildScoreEvidenceDrilldown(report(), "AMC-9.9");

    expect(out.state).toBe("empty");
    expect(out.message).toContain("No question-level receipt found");
    expect(out.manifestHash).toBe("a".repeat(64));
    expect(out.scorableStudioDrilldownPreview).toEqual([]);
    expect(out.obsStudioDrilldownPreview).toEqual([]);
  });

  test("builds product source artifact links for Literal AI without duplicating docs links", () => {
    const links = buildWatchObsStudioSourceArtifactLinks({
      sourceUrl: " https://literalai.com ",
      docsIndexUrl: "https://docs.literalai.com/llms.txt",
      docsPageUrls: [
        "https://docs.literalai.com/guides/dashboard.md",
        "https://docs.literalai.com/guides/dashboard.md",
        "https://docs.literalai.com/guides/logs.md",
      ],
    });

    expect(links).toEqual([
      "https://literalai.com",
      "https://docs.literalai.com/llms.txt",
      "https://docs.literalai.com/guides/dashboard.md",
      "https://docs.literalai.com/guides/logs.md",
    ]);
  });

  test("renders the Scorable Studio drilldown table in the console bundle", () => {
    const bundle = readFileSync("src/console/assets/evidenceDrilldown.js", "utf8");

    expect(bundle).toContain("scorableStudioDrilldownPreview");
    expect(bundle).toContain("obsStudioDrilldownPreview");
    expect(bundle).toContain("Scorable Studio Drilldown");
    expect(bundle).toContain("Literal AI");
    expect(bundle).toContain("no upstream UI/prose/assets/code, SDK, importer, or subsystem");
  });
});
