import { describe, expect, test } from "vitest";
import {
  runReplayBenchmarkCorpus,
  verifyReplayBenchmarkCorpusReceipt,
  type ReplayBenchmarkLlmEvaluationSystemJudgeFamily,
  type ReplayBenchmarkLlmEvaluationSystemMode,
} from "../src/benchmarks/replayBenchmarkCorpus.js";

const h = (nibble: string) => nibble.repeat(64);

const langfuseSourceRefs = [
  "https://langfuse.com",
  "https://langfuse.com/docs/evaluation/overview.md",
  "https://langfuse.com/docs/evaluation/experiments/experiments-ci-cd.md",
];

const completeLangfuseEvalPack = {
  sourceRefHash: h("a"),
  repositorySnapshotHash: h("b"),
  licenseRefHash: h("c"),
  packageVersionRefHash: h("d"),
  sdkInstallManifestHash: h("e"),
  datasetManifestHash: h("f"),
  experimentDatasetRunHash: h("1"),
  traceExportManifestHash: h("2"),
  judgeConfigHash: h("3"),
  evaluatorRosterHash: h("4"),
  scoreConfigHash: h("5"),
  deterministicScoringPolicyHash: h("6"),
  executionManifestHash: h("7"),
  observationTraceManifestHash: h("8"),
  telemetryTraceHash: h("9"),
  modelAccessBoundaryHash: h("0"),
  resultManifestHash: h("a"),
  analysisReportHash: h("b"),
  summaryReportHash: h("c"),
  exportReceiptHash: h("d"),
  replayCommandHash: h("e"),
  ciReceiptHash: h("f"),
  noConfigOnlyBoundaryHash: h("1"),
};

function langfuseReplayRow(overrides: Record<string, unknown> = {}) {
  return {
    rowId: "langfuse-observability-eval-pack",
    fixture: {
      task: "Replay an AMC-owned Langfuse-style eval pack with datasets, traces, score configs, and CI gates.",
      inputHash: h("1"),
      expectedHash: h("2"),
      seed: 600,
      outputArtifactHashes: [h("3"), completeLangfuseEvalPack.summaryReportHash],
      runtime: {
        kind: "custom" as const,
        version: "langfuse-eval-pack-fixture-2026.06.20",
        commandHash: h("4"),
        dependencyHash: h("5"),
        sandboxProfile: "amc-owned-langfuse-eval-pack-replay",
      },
      agentBenchmarkReplay: {
        benchmarkId: "amc-langfuse-eval-pack-replay",
        benchmarkVersion: "2026.06.20",
        paperRefHash: completeLangfuseEvalPack.sourceRefHash,
        repositorySnapshotHash: completeLangfuseEvalPack.repositorySnapshotHash,
        datasetManifestHash: completeLangfuseEvalPack.datasetManifestHash,
        agentConfigHash: completeLangfuseEvalPack.sdkInstallManifestHash,
        globalConfigHash: completeLangfuseEvalPack.judgeConfigHash,
        modelServerConfigHash: completeLangfuseEvalPack.evaluatorRosterHash,
        environmentManifestHash: completeLangfuseEvalPack.executionManifestHash,
        dependencyLockHash: h("5"),
        runCommandHash: h("4"),
        replayCommandHash: completeLangfuseEvalPack.replayCommandHash,
        tracePathHash: completeLangfuseEvalPack.observationTraceManifestHash,
        sampleTraceHash: completeLangfuseEvalPack.telemetryTraceHash,
        resultManifestHash: completeLangfuseEvalPack.resultManifestHash,
        metricsReportHash: completeLangfuseEvalPack.analysisReportHash,
        architecture: "custom" as const,
        workload: "custom" as const,
        deterministicSeed: 600,
        sampleCount: 20,
        minSampleCount: 12,
        shuffled: true,
        traceSaved: true,
        baselineMetric0to1: 0.78,
        candidateMetric0to1: 0.84,
        replayPassRate0to1: 1,
        minReplayPassRate0to1: 0.99,
        traceCoverage0to1: 0.99,
        minTraceCoverage0to1: 0.95,
        maxScoreRegression0to1: 0.02,
        llmEvaluationSystemBenchmarkId: "amc-langfuse-eval-pack-replay",
        llmEvaluationSystemSourceRefHash: completeLangfuseEvalPack.sourceRefHash,
        llmEvaluationSystemRepositorySnapshotHash: completeLangfuseEvalPack.repositorySnapshotHash,
        llmEvaluationSystemLicenseRefHash: completeLangfuseEvalPack.licenseRefHash,
        llmEvaluationSystemPackageVersionRefHash: completeLangfuseEvalPack.packageVersionRefHash,
        llmEvaluationSystemMcpInstallManifestHash: completeLangfuseEvalPack.sdkInstallManifestHash,
        llmEvaluationSystemDatasetManifestHash: completeLangfuseEvalPack.datasetManifestHash,
        llmEvaluationSystemSyntheticQaManifestHash: completeLangfuseEvalPack.experimentDatasetRunHash,
        llmEvaluationSystemDocumentGroundingManifestHash: completeLangfuseEvalPack.traceExportManifestHash,
        llmEvaluationSystemJudgeConfigHash: completeLangfuseEvalPack.judgeConfigHash,
        llmEvaluationSystemJuryRosterHash: completeLangfuseEvalPack.evaluatorRosterHash,
        llmEvaluationSystemCriteriaManifestHash: completeLangfuseEvalPack.scoreConfigHash,
        llmEvaluationSystemBinaryScoringPolicyHash: completeLangfuseEvalPack.deterministicScoringPolicyHash,
        llmEvaluationSystemExecutionManifestHash: completeLangfuseEvalPack.executionManifestHash,
        llmEvaluationSystemAgentTraceManifestHash: completeLangfuseEvalPack.observationTraceManifestHash,
        llmEvaluationSystemOpenTelemetryTraceHash: completeLangfuseEvalPack.telemetryTraceHash,
        llmEvaluationSystemBedrockAccessBoundaryHash: completeLangfuseEvalPack.modelAccessBoundaryHash,
        llmEvaluationSystemResultManifestHash: completeLangfuseEvalPack.resultManifestHash,
        llmEvaluationSystemAnalysisReportHash: completeLangfuseEvalPack.analysisReportHash,
        llmEvaluationSystemPdfReportHash: completeLangfuseEvalPack.summaryReportHash,
        llmEvaluationSystemS3SyncReceiptHash: completeLangfuseEvalPack.exportReceiptHash,
        llmEvaluationSystemReplayCommandHash: completeLangfuseEvalPack.replayCommandHash,
        llmEvaluationSystemCiReceiptHash: completeLangfuseEvalPack.ciReceiptHash,
        llmEvaluationSystemNoConfigOnlyBoundaryHash: completeLangfuseEvalPack.noConfigOnlyBoundaryHash,
        llmEvaluationSystemModes: ["dataset_generation", "judge_configuration", "jury_scoring", "agent_trace"] as ReplayBenchmarkLlmEvaluationSystemMode[],
        minLlmEvaluationSystemModeCount: 4,
        llmEvaluationSystemJudgeFamilies: ["openai", "custom"] as ReplayBenchmarkLlmEvaluationSystemJudgeFamily[],
        minLlmEvaluationSystemJudgeFamilyCount: 2,
        llmEvaluationSystemDatasetCount: 2,
        minLlmEvaluationSystemDatasetCount: 2,
        llmEvaluationSystemJudgeCount: 2,
        minLlmEvaluationSystemJudgeCount: 2,
        llmEvaluationSystemCriteriaCount: 5,
        minLlmEvaluationSystemCriteriaCount: 4,
        llmEvaluationSystemEvaluationCaseCount: 20,
        minLlmEvaluationSystemEvaluationCaseCount: 12,
        llmEvaluationSystemDeterministicSeed: 600,
        llmEvaluationSystemBaselineJuryScore0to1: 0.78,
        llmEvaluationSystemCandidateJuryScore0to1: 0.84,
        maxLlmEvaluationSystemJuryScoreRegression0to1: 0.02,
        llmEvaluationSystemBinaryScoringCoverage0to1: 1,
        minLlmEvaluationSystemBinaryScoringCoverage0to1: 0.95,
        llmEvaluationSystemJudgeAgreement0to1: 0.83,
        minLlmEvaluationSystemJudgeAgreement0to1: 0.75,
        llmEvaluationSystemReplayPassRate0to1: 1,
        minLlmEvaluationSystemReplayPassRate0to1: 0.99,
        llmEvaluationSystemReportCoverage0to1: 1,
        minLlmEvaluationSystemReportCoverage0to1: 1,
        llmEvaluationSystemAgentTraceCoverage0to1: 0.99,
        minLlmEvaluationSystemAgentTraceCoverage0to1: 0.95,
        llmEvaluationSystemNoSyntheticDataCopyBoundary: true,
        llmEvaluationSystemNoPdfReportOnlyBoundary: true,
      },
      metadata: {
        reviewedSource: "Langfuse public docs and product page",
        sourceDocsIndex: "https://langfuse.com/llms-docs.txt",
        noUpstreamPayloadCopied: true,
      },
    },
    baseline: {
      score0to1: 0.78,
      evidenceRefs: ["trace:langfuse-baseline"],
      signedEvidenceRefs: ["ledger:sig-langfuse-baseline"],
    },
    candidate: {
      score0to1: 0.84,
      evidenceRefs: ["trace:langfuse-candidate"],
      signedEvidenceRefs: ["ledger:sig-langfuse-candidate"],
    },
    surfaces: ["Score", "Shield", "Watch"] as const,
    ...overrides,
  };
}

describe("Langfuse eval replay corpus source review", () => {
  test("binds Langfuse-style eval packs to replay manifests, fixture hashes, score deltas, signed rows, and CI receipts", () => {
    const result = runReplayBenchmarkCorpus({
      agentId: "langfuse-instrumented-agent",
      corpusId: "langfuse-eval-replay-corpus",
      corpusVersion: "2026.06.20",
      baselineRunId: "langfuse-eval-baseline",
      candidateRunId: "langfuse-eval-candidate",
      gateMode: "ci",
      sourceRefs: langfuseSourceRefs,
      thresholds: {
        maxScoreRegression0to1: 0.02,
        minSignedEvidenceRefs: 2,
        maxCandidateAttackSuccessRate0to1: 0.05,
        maxAttackSuccessRateRegression0to1: 0.01,
        minAttackSuccessRateReduction0to1: 0,
        requireAttackSuccessRateForRiskRows: false,
        requireOutputArtifactHashForRuntimeRows: true,
      },
      rows: [langfuseReplayRow()],
    });

    expect(result.manifest.replayable).toBe(true);
    expect(result.manifest.fixtureHash).toMatch(/^[a-f0-9]{64}$/);
    expect(result.manifest.rows[0]).toMatchObject({
      rowId: "langfuse-observability-eval-pack",
      status: "passed",
      baselineScore0to1: 0.78,
      candidateScore0to1: 0.84,
      scoreDelta0to1: 0.06,
      signedEvidenceRefs: ["ledger:sig-langfuse-baseline", "ledger:sig-langfuse-candidate"],
      surfaces: ["Score", "Shield", "Watch"],
    });
    expect(result.manifest.rows[0]?.fixtureHash).toMatch(/^[a-f0-9]{64}$/);
    expect(result.manifest.agentBenchmarkReplaySummary).toMatchObject({
      llmEvaluationSystemReplayRowCount: 1,
      failedLlmEvaluationSystemReplayRowIds: [],
      averageLlmEvaluationSystemJuryScoreDelta0to1: 0.06,
      averageLlmEvaluationSystemReplayPassRate0to1: 1,
    });
    expect(result.ciReceipt).toMatchObject({
      mode: "ci",
      passed: true,
      failClosed: false,
      fixtureHash: result.manifest.fixtureHash,
      manifestHash: result.manifest.manifestHash,
      scoreDelta0to1: result.manifest.scoreDelta0to1,
      failedRowIds: [],
      llmEvaluationSystemReplayRowCount: 1,
      failedLlmEvaluationSystemReplayRowIds: [],
    });
    expect(result.watchAlerts).toEqual([]);

    const verification = verifyReplayBenchmarkCorpusReceipt(result.manifest, result.ciReceipt);
    expect(verification).toEqual({ valid: true, errors: [] });
  });

  test("fails closed when Langfuse source proof is metadata-only and unsigned", () => {
    const result = runReplayBenchmarkCorpus({
      agentId: "langfuse-instrumented-agent",
      corpusId: "langfuse-eval-replay-corpus",
      corpusVersion: "2026.06.20",
      baselineRunId: "langfuse-eval-baseline",
      candidateRunId: "langfuse-eval-candidate-regressed",
      gateMode: "lifecycle",
      sourceRefs: langfuseSourceRefs,
      thresholds: {
        maxScoreRegression0to1: 0.02,
        minSignedEvidenceRefs: 2,
        maxCandidateAttackSuccessRate0to1: 0.05,
        maxAttackSuccessRateRegression0to1: 0.01,
        minAttackSuccessRateReduction0to1: 0,
        requireAttackSuccessRateForRiskRows: false,
        requireOutputArtifactHashForRuntimeRows: true,
      },
      rows: [
        langfuseReplayRow({
          rowId: "langfuse-metadata-only-eval-claim",
          fixture: {
            task: "Public Langfuse page metadata without an AMC-owned replay fixture, scores export, traces, or CI receipt.",
            inputHash: h("1"),
            expectedHash: h("2"),
            seed: 600,
            outputArtifactHashes: [],
            runtime: {
              kind: "custom" as const,
              version: "langfuse-eval-pack-fixture-2026.06.20",
              commandHash: h("4"),
              dependencyHash: h("5"),
              sandboxProfile: "metadata-only",
            },
            agentBenchmarkReplay: {
              benchmarkId: "amc-langfuse-eval-pack-replay",
              benchmarkVersion: "2026.06.20",
              paperRefHash: completeLangfuseEvalPack.sourceRefHash,
              repositorySnapshotHash: completeLangfuseEvalPack.repositorySnapshotHash,
              datasetManifestHash: null,
              agentConfigHash: null,
              globalConfigHash: null,
              modelServerConfigHash: null,
              environmentManifestHash: null,
              dependencyLockHash: h("5"),
              runCommandHash: h("4"),
              replayCommandHash: null,
              tracePathHash: null,
              sampleTraceHash: null,
              resultManifestHash: null,
              metricsReportHash: null,
              architecture: "custom" as const,
              workload: "custom" as const,
              deterministicSeed: null,
              sampleCount: 1,
              minSampleCount: 12,
              shuffled: false,
              traceSaved: false,
              baselineMetric0to1: 0.78,
              candidateMetric0to1: 0.69,
              replayPassRate0to1: 0.5,
              minReplayPassRate0to1: 0.99,
              traceCoverage0to1: 0.1,
              minTraceCoverage0to1: 0.95,
              maxScoreRegression0to1: 0.02,
              llmEvaluationSystemBenchmarkId: "amc-langfuse-eval-pack-replay",
              llmEvaluationSystemSourceRefHash: completeLangfuseEvalPack.sourceRefHash,
              llmEvaluationSystemRepositorySnapshotHash: completeLangfuseEvalPack.repositorySnapshotHash,
              llmEvaluationSystemLicenseRefHash: null,
              llmEvaluationSystemPackageVersionRefHash: null,
              llmEvaluationSystemMcpInstallManifestHash: null,
              llmEvaluationSystemDatasetManifestHash: null,
              llmEvaluationSystemSyntheticQaManifestHash: null,
              llmEvaluationSystemDocumentGroundingManifestHash: null,
              llmEvaluationSystemJudgeConfigHash: null,
              llmEvaluationSystemJuryRosterHash: null,
              llmEvaluationSystemCriteriaManifestHash: null,
              llmEvaluationSystemBinaryScoringPolicyHash: null,
              llmEvaluationSystemExecutionManifestHash: null,
              llmEvaluationSystemAgentTraceManifestHash: null,
              llmEvaluationSystemOpenTelemetryTraceHash: null,
              llmEvaluationSystemBedrockAccessBoundaryHash: null,
              llmEvaluationSystemResultManifestHash: null,
              llmEvaluationSystemAnalysisReportHash: null,
              llmEvaluationSystemPdfReportHash: null,
              llmEvaluationSystemS3SyncReceiptHash: null,
              llmEvaluationSystemReplayCommandHash: null,
              llmEvaluationSystemCiReceiptHash: null,
              llmEvaluationSystemNoConfigOnlyBoundaryHash: null,
              llmEvaluationSystemModes: ["custom"] as ReplayBenchmarkLlmEvaluationSystemMode[],
              minLlmEvaluationSystemModeCount: 4,
              llmEvaluationSystemJudgeFamilies: ["custom"] as ReplayBenchmarkLlmEvaluationSystemJudgeFamily[],
              minLlmEvaluationSystemJudgeFamilyCount: 2,
              llmEvaluationSystemDatasetCount: 0,
              minLlmEvaluationSystemDatasetCount: 2,
              llmEvaluationSystemJudgeCount: 1,
              minLlmEvaluationSystemJudgeCount: 2,
              llmEvaluationSystemCriteriaCount: 0,
              minLlmEvaluationSystemCriteriaCount: 4,
              llmEvaluationSystemEvaluationCaseCount: 1,
              minLlmEvaluationSystemEvaluationCaseCount: 12,
              llmEvaluationSystemDeterministicSeed: null,
              llmEvaluationSystemBaselineJuryScore0to1: 0.78,
              llmEvaluationSystemCandidateJuryScore0to1: 0.69,
              maxLlmEvaluationSystemJuryScoreRegression0to1: 0.02,
              llmEvaluationSystemBinaryScoringCoverage0to1: 0,
              minLlmEvaluationSystemBinaryScoringCoverage0to1: 0.95,
              llmEvaluationSystemJudgeAgreement0to1: 0.3,
              minLlmEvaluationSystemJudgeAgreement0to1: 0.75,
              llmEvaluationSystemReplayPassRate0to1: 0.5,
              minLlmEvaluationSystemReplayPassRate0to1: 0.99,
              llmEvaluationSystemReportCoverage0to1: 0,
              minLlmEvaluationSystemReportCoverage0to1: 1,
              llmEvaluationSystemAgentTraceCoverage0to1: 0.1,
              minLlmEvaluationSystemAgentTraceCoverage0to1: 0.95,
              llmEvaluationSystemNoSyntheticDataCopyBoundary: false,
              llmEvaluationSystemNoPdfReportOnlyBoundary: false,
            },
          },
          baseline: {
            score0to1: 0.78,
            evidenceRefs: ["trace:langfuse-baseline"],
            signedEvidenceRefs: [],
          },
          candidate: {
            score0to1: 0.69,
            evidenceRefs: ["trace:langfuse-candidate-regressed"],
            signedEvidenceRefs: [],
          },
        }),
      ],
    });

    expect(result.manifest.replayable).toBe(false);
    expect(result.manifest.rows[0]?.status).toBe("missing_evidence");
    expect(result.manifest.rows[0]?.issues).toContain("signed evidence refs below threshold");
    expect(result.manifest.rows[0]?.issues).toContain("output artifact hashes missing for runtime row");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay dataset manifest hash invalid");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay replay command hash invalid");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay trace saved disabled");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay score regression exceeds threshold");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay llm-evaluation-system ci receipt hash invalid");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay llm-evaluation-system replay pass rate below threshold");
    expect(result.ciReceipt).toMatchObject({
      mode: "lifecycle",
      passed: false,
      failClosed: true,
      failedRowIds: ["langfuse-metadata-only-eval-claim"],
      failedLlmEvaluationSystemReplayRowIds: ["langfuse-metadata-only-eval-claim"],
    });
    expect(result.watchAlerts[0]).toMatchObject({
      source: "replay-benchmark-corpus",
      severity: "critical",
      rowId: "langfuse-metadata-only-eval-claim",
    });
  });
});
