import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * Five modules justified their existence with quotations attributed to named
 * practitioners — "Raj Patel (200+ deployments)", "Lisa Chang, VP Engineering",
 * a "SOC 2 compliance officer" — and to "MiroFish V2 agents" who "unanimously"
 * identified a blocker.
 *
 * None of those people exist. They are personas from the MiroFish simulation,
 * generated by a model. A codebase whose product thesis is evidence over claims
 * was citing fabricated user research as its engineering rationale.
 *
 * The requirements themselves were sound and are kept; the false provenance is
 * not. This test stops it coming back.
 */
function sourceFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) sourceFiles(full, out);
    else if (entry.endsWith(".ts")) out.push(full);
  }
  return out;
}

describe("no fabricated attribution in source", () => {
  const files = sourceFiles(join(process.cwd(), "src"));

  it("no module presents a simulated persona as a real source", () => {
    const offenders: string[] = [];
    for (const file of files) {
      const source = readFileSync(file, "utf8");
      // The phrasing that presented generated text as testimony.
      if (/MiroFish (agent quote|V2 agents unanimously)/i.test(source)) {
        offenders.push(file.replace(`${process.cwd()}/`, ""));
      }
    }
    expect(offenders).toEqual([]);
  });

  it("modules that cite the simulation say it is a simulation", () => {
    const citing = files.filter((f) => /mirofish-simulation\//.test(readFileSync(f, "utf8")));
    expect(citing.length).toBeGreaterThan(0);
    for (const file of citing) {
      const source = readFileSync(file, "utf8");
      expect(source, file).toMatch(/synthetic scenario, not user research/i);
      expect(source, file).toMatch(/No real person said it/i);
    }
  });
});
