import { describe, expect, test } from "vitest";
import {
  runReplayBenchmarkCorpus,
  verifyReplayBenchmarkCorpusReceipt,
} from "../src/benchmarks/replayBenchmarkCorpus.js";

const h = (nibble: string) => nibble.repeat(64);

const pestPluginSourceRefs = ["https://github.com/shipfastlabs/pest-plugin-evals"];

const completePestEvalPack = {
  sourceRefHash: h("a"),
  repositorySnapshotHash: h("b"),
  licenseRefHash: h("c"),
  packageVersionRefHash: h("d"),
  composerInstallManifestHash: h("e"),
  datasetManifestHash: h("f"),
  syntheticQaManifestHash: h("1"),
  documentGroundingManifestHash: h("2"),
  judgeConfigHash: h("3"),
  scorerRosterHash: h("4"),
  criteriaManifestHash: h("5"),
  deterministicScoringPolicyHash: h("6"),
  executionManifestHash: h("7"),
  agentTraceManifestHash: h("8"),
  telemetryTraceHash: h("9"),
  modelAccessBoundaryHash: h("0"),
  resultManifestHash: h("a"),
  analysisReportHash: h("b"),
  summaryReportHash: h("c"),
  exportReceiptHash: h("d"),
  replayCommandHash: h("e"),
  ciReceiptHash: h("f"),
  noConfigOnlyBoundaryHash: h("1"),
};

function pestReplayRow(overrides: Record<string, unknown> = {}) {
  return {
    rowId: "pest-plugin-evals-laravel-agent-eval-pack",
    fixture: {
      task: "Replay an AMC-owned Laravel agent eval fixture through Pest-style deterministic and judge scorers.",
      inputHash: h("1"),
      expectedHash: h("2"),
      seed: 596,
      outputArtifactHashes: [h("3"), completePestEvalPack.summaryReportHash],
      runtime: {
        kind: "custom" as const,
        version: "php-8.3-pest-plugin-evals-fixture",
        commandHash: h("4"),
        dependencyHash: h("5"),
        sandboxProfile: "amc-owned-pest-eval-pack-replay",
      },
      agentBenchmarkReplay: {
        benchmarkId: "amc-pest-plugin-evals-pack-replay",
        benchmarkVersion: "2026.06.20",
        paperRefHash: completePestEvalPack.sourceRefHash,
        repositorySnapshotHash: completePestEvalPack.repositorySnapshotHash,
        datasetManifestHash: completePestEvalPack.datasetManifestHash,
        agentConfigHash: completePestEvalPack.composerInstallManifestHash,
        globalConfigHash: completePestEvalPack.judgeConfigHash,
        modelServerConfigHash: completePestEvalPack.scorerRosterHash,
        environmentManifestHash: completePestEvalPack.executionManifestHash,
        dependencyLockHash: h("5"),
        runCommandHash: h("4"),
        replayCommandHash: completePestEvalPack.replayCommandHash,
        tracePathHash: completePestEvalPack.agentTraceManifestHash,
        sampleTraceHash: completePestEvalPack.telemetryTraceHash,
        resultManifestHash: completePestEvalPack.resultManifestHash,
        metricsReportHash: completePestEvalPack.analysisReportHash,
        architecture: "custom" as const,
        workload: "custom" as const,
        deterministicSeed: 596,
        sampleCount: 18,
        minSampleCount: 12,
        shuffled: true,
        traceSaved: true,
        baselineMetric0to1: 0.81,
        candidateMetric0to1: 0.86,
        replayPassRate0to1: 1,
        minReplayPassRate0to1: 0.99,
        traceCoverage0to1: 0.98,
        minTraceCoverage0to1: 0.95,
        maxScoreRegression0to1: 0.02,
        llmEvaluationSystemBenchmarkId: "amc-pest-plugin-evals-pack-replay",
        llmEvaluationSystemSourceRefHash: completePestEvalPack.sourceRefHash,
        llmEvaluationSystemRepositorySnapshotHash: completePestEvalPack.repositorySnapshotHash,
        llmEvaluationSystemLicenseRefHash: completePestEvalPack.licenseRefHash,
        llmEvaluationSystemPackageVersionRefHash: completePestEvalPack.packageVersionRefHash,
        llmEvaluationSystemMcpInstallManifestHash: completePestEvalPack.composerInstallManifestHash,
        llmEvaluationSystemDatasetManifestHash: completePestEvalPack.datasetManifestHash,
        llmEvaluationSystemSyntheticQaManifestHash: completePestEvalPack.syntheticQaManifestHash,
        llmEvaluationSystemDocumentGroundingManifestHash: completePestEvalPack.documentGroundingManifestHash,
        llmEvaluationSystemJudgeConfigHash: completePestEvalPack.judgeConfigHash,
        llmEvaluationSystemJuryRosterHash: completePestEvalPack.scorerRosterHash,
        llmEvaluationSystemCriteriaManifestHash: completePestEvalPack.criteriaManifestHash,
        llmEvaluationSystemBinaryScoringPolicyHash: completePestEvalPack.deterministicScoringPolicyHash,
        llmEvaluationSystemExecutionManifestHash: completePestEvalPack.executionManifestHash,
        llmEvaluationSystemAgentTraceManifestHash: completePestEvalPack.agentTraceManifestHash,
        llmEvaluationSystemOpenTelemetryTraceHash: completePestEvalPack.telemetryTraceHash,
        llmEvaluationSystemBedrockAccessBoundaryHash: completePestEvalPack.modelAccessBoundaryHash,
        llmEvaluationSystemResultManifestHash: completePestEvalPack.resultManifestHash,
        llmEvaluationSystemAnalysisReportHash: completePestEvalPack.analysisReportHash,
        llmEvaluationSystemPdfReportHash: completePestEvalPack.summaryReportHash,
        llmEvaluationSystemS3SyncReceiptHash: completePestEvalPack.exportReceiptHash,
        llmEvaluationSystemReplayCommandHash: completePestEvalPack.replayCommandHash,
        llmEvaluationSystemCiReceiptHash: completePestEvalPack.ciReceiptHash,
        llmEvaluationSystemNoConfigOnlyBoundaryHash: completePestEvalPack.noConfigOnlyBoundaryHash,
        llmEvaluationSystemModes: ["dataset_generation", "judge_configuration", "agent_trace", "custom"] as const,
        minLlmEvaluationSystemModeCount: 4,
        llmEvaluationSystemJudgeFamilies: ["openai", "custom"] as const,
        minLlmEvaluationSystemJudgeFamilyCount: 2,
        llmEvaluationSystemDatasetCount: 2,
        minLlmEvaluationSystemDatasetCount: 2,
        llmEvaluationSystemJudgeCount: 2,
        minLlmEvaluationSystemJudgeCount: 2,
        llmEvaluationSystemCriteriaCount: 6,
        minLlmEvaluationSystemCriteriaCount: 4,
        llmEvaluationSystemEvaluationCaseCount: 18,
        minLlmEvaluationSystemEvaluationCaseCount: 12,
        llmEvaluationSystemDeterministicSeed: 596,
        llmEvaluationSystemBaselineJuryScore0to1: 0.81,
        llmEvaluationSystemCandidateJuryScore0to1: 0.86,
        maxLlmEvaluationSystemJuryScoreRegression0to1: 0.02,
        llmEvaluationSystemBinaryScoringCoverage0to1: 1,
        minLlmEvaluationSystemBinaryScoringCoverage0to1: 0.95,
        llmEvaluationSystemJudgeAgreement0to1: 0.82,
        minLlmEvaluationSystemJudgeAgreement0to1: 0.75,
        llmEvaluationSystemReplayPassRate0to1: 1,
        minLlmEvaluationSystemReplayPassRate0to1: 0.99,
        llmEvaluationSystemReportCoverage0to1: 1,
        minLlmEvaluationSystemReportCoverage0to1: 1,
        llmEvaluationSystemAgentTraceCoverage0to1: 0.98,
        minLlmEvaluationSystemAgentTraceCoverage0to1: 0.95,
        llmEvaluationSystemNoSyntheticDataCopyBoundary: true,
        llmEvaluationSystemNoPdfReportOnlyBoundary: true,
      },
      metadata: {
        reviewedSource: "shipfastlabs/pest-plugin-evals",
        sourceCommit: "dadb27cadb6e6447c60c0d7410a9ae10db24fd5b",
        sourceTree: "0698885eaec66fbb664b1f01370d1925eae551fb",
        sourceLicense: "MIT",
      },
    },
    baseline: {
      score0to1: 0.81,
      evidenceRefs: ["trace:pest-plugin-evals-baseline"],
      signedEvidenceRefs: ["ledger:sig-pest-plugin-evals-baseline"],
    },
    candidate: {
      score0to1: 0.86,
      evidenceRefs: ["trace:pest-plugin-evals-candidate"],
      signedEvidenceRefs: ["ledger:sig-pest-plugin-evals-candidate"],
    },
    surfaces: ["Score", "Shield", "Watch"] as const,
    ...overrides,
  };
}

describe("pest-plugin-evals replay corpus source review", () => {
  test("binds Pest-style eval packs to replay manifests, fixture hashes, score deltas, signed rows, and CI receipts", () => {
    const result = runReplayBenchmarkCorpus({
      agentId: "laravel-agent",
      corpusId: "pest-plugin-evals-replay-corpus",
      corpusVersion: "2026.06.20",
      baselineRunId: "pest-plugin-evals-baseline",
      candidateRunId: "pest-plugin-evals-candidate",
      gateMode: "ci",
      sourceRefs: pestPluginSourceRefs,
      thresholds: {
        maxScoreRegression0to1: 0.02,
        minSignedEvidenceRefs: 2,
        maxCandidateAttackSuccessRate0to1: 0.05,
        maxAttackSuccessRateRegression0to1: 0.01,
        minAttackSuccessRateReduction0to1: 0,
        requireAttackSuccessRateForRiskRows: false,
        requireOutputArtifactHashForRuntimeRows: true,
      },
      rows: [pestReplayRow()],
    });

    expect(result.manifest.replayable).toBe(true);
    expect(result.manifest.fixtureHash).toMatch(/^[a-f0-9]{64}$/);
    expect(result.manifest.rows[0]).toMatchObject({
      rowId: "pest-plugin-evals-laravel-agent-eval-pack",
      status: "passed",
      baselineScore0to1: 0.81,
      candidateScore0to1: 0.86,
      scoreDelta0to1: 0.05,
      signedEvidenceRefs: ["ledger:sig-pest-plugin-evals-baseline", "ledger:sig-pest-plugin-evals-candidate"],
      surfaces: ["Score", "Shield", "Watch"],
    });
    expect(result.manifest.rows[0]?.fixtureHash).toMatch(/^[a-f0-9]{64}$/);
    expect(result.manifest.agentBenchmarkReplaySummary).toMatchObject({
      llmEvaluationSystemReplayRowCount: 1,
      failedLlmEvaluationSystemReplayRowIds: [],
      averageLlmEvaluationSystemJuryScoreDelta0to1: 0.05,
      averageLlmEvaluationSystemReplayPassRate0to1: 1,
    });
    expect(result.ciReceipt).toMatchObject({
      mode: "ci",
      passed: true,
      failClosed: false,
      fixtureHash: result.manifest.fixtureHash,
      manifestHash: result.manifest.manifestHash,
      scoreDelta0to1: result.manifest.scoreDelta0to1,
      failedRowIds: [],
      llmEvaluationSystemReplayRowCount: 1,
      failedLlmEvaluationSystemReplayRowIds: [],
    });
    expect(result.watchAlerts).toEqual([]);

    const verification = verifyReplayBenchmarkCorpusReceipt(result.manifest, result.ciReceipt);
    expect(verification).toEqual({ valid: true, errors: [] });
  });

  test("fails closed when Pest source proof is metadata-only and unsigned", () => {
    const result = runReplayBenchmarkCorpus({
      agentId: "laravel-agent",
      corpusId: "pest-plugin-evals-replay-corpus",
      corpusVersion: "2026.06.20",
      baselineRunId: "pest-plugin-evals-baseline",
      candidateRunId: "pest-plugin-evals-candidate-regressed",
      gateMode: "lifecycle",
      sourceRefs: pestPluginSourceRefs,
      thresholds: {
        maxScoreRegression0to1: 0.02,
        minSignedEvidenceRefs: 2,
        maxCandidateAttackSuccessRate0to1: 0.05,
        maxAttackSuccessRateRegression0to1: 0.01,
        minAttackSuccessRateReduction0to1: 0,
        requireAttackSuccessRateForRiskRows: false,
        requireOutputArtifactHashForRuntimeRows: true,
      },
      rows: [
        pestReplayRow({
          rowId: "pest-plugin-evals-metadata-only",
          fixture: {
            task: "Repository metadata-only Pest eval claim without an AMC-owned replay fixture.",
            inputHash: h("1"),
            expectedHash: h("2"),
            seed: 596,
            outputArtifactHashes: [],
            runtime: {
              kind: "custom" as const,
              version: "php-8.3-pest-plugin-evals-fixture",
              commandHash: h("4"),
              dependencyHash: h("5"),
              sandboxProfile: "metadata-only",
            },
            agentBenchmarkReplay: {
              benchmarkId: "amc-pest-plugin-evals-pack-replay",
              benchmarkVersion: "2026.06.20",
              paperRefHash: completePestEvalPack.sourceRefHash,
              repositorySnapshotHash: completePestEvalPack.repositorySnapshotHash,
              datasetManifestHash: null,
              agentConfigHash: null,
              globalConfigHash: null,
              modelServerConfigHash: null,
              environmentManifestHash: null,
              dependencyLockHash: h("5"),
              runCommandHash: h("4"),
              replayCommandHash: null,
              tracePathHash: null,
              sampleTraceHash: null,
              resultManifestHash: null,
              metricsReportHash: null,
              architecture: "custom" as const,
              workload: "custom" as const,
              deterministicSeed: null,
              sampleCount: 1,
              minSampleCount: 12,
              shuffled: false,
              traceSaved: false,
              baselineMetric0to1: 0.81,
              candidateMetric0to1: 0.7,
              replayPassRate0to1: 0.5,
              minReplayPassRate0to1: 0.99,
              traceCoverage0to1: 0.1,
              minTraceCoverage0to1: 0.95,
              maxScoreRegression0to1: 0.02,
              llmEvaluationSystemBenchmarkId: "amc-pest-plugin-evals-pack-replay",
              llmEvaluationSystemSourceRefHash: completePestEvalPack.sourceRefHash,
              llmEvaluationSystemRepositorySnapshotHash: completePestEvalPack.repositorySnapshotHash,
              llmEvaluationSystemLicenseRefHash: null,
              llmEvaluationSystemPackageVersionRefHash: null,
              llmEvaluationSystemMcpInstallManifestHash: null,
              llmEvaluationSystemDatasetManifestHash: null,
              llmEvaluationSystemSyntheticQaManifestHash: null,
              llmEvaluationSystemDocumentGroundingManifestHash: null,
              llmEvaluationSystemJudgeConfigHash: null,
              llmEvaluationSystemJuryRosterHash: null,
              llmEvaluationSystemCriteriaManifestHash: null,
              llmEvaluationSystemBinaryScoringPolicyHash: null,
              llmEvaluationSystemExecutionManifestHash: null,
              llmEvaluationSystemAgentTraceManifestHash: null,
              llmEvaluationSystemOpenTelemetryTraceHash: null,
              llmEvaluationSystemBedrockAccessBoundaryHash: null,
              llmEvaluationSystemResultManifestHash: null,
              llmEvaluationSystemAnalysisReportHash: null,
              llmEvaluationSystemPdfReportHash: null,
              llmEvaluationSystemS3SyncReceiptHash: null,
              llmEvaluationSystemReplayCommandHash: null,
              llmEvaluationSystemCiReceiptHash: null,
              llmEvaluationSystemNoConfigOnlyBoundaryHash: null,
              llmEvaluationSystemModes: ["custom"] as const,
              minLlmEvaluationSystemModeCount: 4,
              llmEvaluationSystemJudgeFamilies: ["custom"] as const,
              minLlmEvaluationSystemJudgeFamilyCount: 2,
              llmEvaluationSystemDatasetCount: 0,
              minLlmEvaluationSystemDatasetCount: 2,
              llmEvaluationSystemJudgeCount: 1,
              minLlmEvaluationSystemJudgeCount: 2,
              llmEvaluationSystemCriteriaCount: 0,
              minLlmEvaluationSystemCriteriaCount: 4,
              llmEvaluationSystemEvaluationCaseCount: 1,
              minLlmEvaluationSystemEvaluationCaseCount: 12,
              llmEvaluationSystemDeterministicSeed: null,
              llmEvaluationSystemBaselineJuryScore0to1: 0.81,
              llmEvaluationSystemCandidateJuryScore0to1: 0.7,
              maxLlmEvaluationSystemJuryScoreRegression0to1: 0.02,
              llmEvaluationSystemBinaryScoringCoverage0to1: 0,
              minLlmEvaluationSystemBinaryScoringCoverage0to1: 0.95,
              llmEvaluationSystemJudgeAgreement0to1: 0.3,
              minLlmEvaluationSystemJudgeAgreement0to1: 0.75,
              llmEvaluationSystemReplayPassRate0to1: 0.5,
              minLlmEvaluationSystemReplayPassRate0to1: 0.99,
              llmEvaluationSystemReportCoverage0to1: 0,
              minLlmEvaluationSystemReportCoverage0to1: 1,
              llmEvaluationSystemAgentTraceCoverage0to1: 0.1,
              minLlmEvaluationSystemAgentTraceCoverage0to1: 0.95,
              llmEvaluationSystemNoSyntheticDataCopyBoundary: false,
              llmEvaluationSystemNoPdfReportOnlyBoundary: false,
            },
          },
          baseline: {
            score0to1: 0.81,
            evidenceRefs: ["trace:pest-plugin-evals-baseline"],
            signedEvidenceRefs: [],
          },
          candidate: {
            score0to1: 0.7,
            evidenceRefs: ["trace:pest-plugin-evals-candidate-regressed"],
            signedEvidenceRefs: [],
          },
        }),
      ],
    });

    expect(result.manifest.replayable).toBe(false);
    expect(result.manifest.rows[0]?.status).toBe("missing_evidence");
    expect(result.manifest.rows[0]?.issues).toContain("signed evidence refs below threshold");
    expect(result.manifest.rows[0]?.issues).toContain("output artifact hashes missing for runtime row");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay dataset manifest hash invalid");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay replay command hash invalid");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay trace saved disabled");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay score regression exceeds threshold");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay llm-evaluation-system ci receipt hash invalid");
    expect(result.manifest.rows[0]?.issues).toContain("agent benchmark replay llm-evaluation-system replay pass rate below threshold");
    expect(result.ciReceipt).toMatchObject({
      mode: "lifecycle",
      passed: false,
      failClosed: true,
      failedRowIds: ["pest-plugin-evals-metadata-only"],
      failedLlmEvaluationSystemReplayRowIds: ["pest-plugin-evals-metadata-only"],
    });
    expect(result.watchAlerts[0]).toMatchObject({
      source: "replay-benchmark-corpus",
      severity: "critical",
      rowId: "pest-plugin-evals-metadata-only",
    });
  });
});
