import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * The MiroFish pages present model-generated personas quoting AMC, including
 * words attributed to a real third-party project team. Rendered on GitHub, a
 * .md file arrives without the page title that said "Simulation", so a reader
 * meets the quotations before any framing.
 *
 * For a product whose thesis is evidence over claims, shipping fabricated
 * testimony that reads as real is the thing it exists to catch. These files
 * must carry an unmissable disclaimer.
 */
const SYNTHETIC_PAGES = [
  "mirofish-simulation/mirofish-report.md",
  "mirofish-simulation/mirofish-report-100agents.md",
  "mirofish-simulation/index.html"
];

describe("synthetic simulation content is labelled as synthetic", () => {
  for (const page of SYNTHETIC_PAGES) {
    it(`${page} states up front that nobody real said this`, () => {
      const raw = readFileSync(join(process.cwd(), page), "utf8");
      // For HTML the disclaimer sits after the inline stylesheet, so measure
      // from <body> — what the reader actually meets first — not from byte 0.
      const bodyStart = raw.indexOf("<body");
      const opening = (bodyStart === -1 ? raw : raw.slice(bodyStart)).slice(0, 4000);
      expect(opening).toMatch(/Synthetic simulation/i);
      expect(opening).toMatch(/No real person said/i);
      expect(opening).toMatch(/generated by a model/i);
    });

    it(`${page} shows the disclaimer before any quoted testimony`, () => {
      const raw = readFileSync(join(process.cwd(), page), "utf8");
      const disclaimer = raw.search(/Synthetic simulation/i);
      const firstQuote = raw.search(/[">]\s*[""]|^> "/m);
      expect(disclaimer).toBeGreaterThan(-1);
      if (firstQuote > -1) expect(disclaimer).toBeLessThan(firstQuote);
    });
  }
});
