/**
 * Every CLI command that prints a score, level, verdict, compliance status, certificate, passport, bundle
 * verification or attestation (P0-22). Each one prints a claim label (src/cli/claimOutput.ts); the postAction
 * hook (src/cli/claimLabelHooks.ts) enforces it. A new result command must be added here, or to
 * NON_RESULT_COMMANDS with the reason it prints no result. See docs/CLAIM_KINDS.md, "CLI and reports".
 */
import type { ClaimKind } from "../claims/eligibility/types.js";

export interface ResultCommand {
  /** The registered command path, e.g. "score fail-secure". */
  readonly path: string;
  /** The `provenance.producer` the command's envelope carries (a prefix where it names the run or framework). */
  readonly producer: string;
  /** The kind the command prints when nothing stronger is proven. */
  readonly defaultKind: ClaimKind;
  /** For a command that prints a result only in some modes: true when these options select one. */
  readonly when?: (opts: Readonly<Record<string, unknown>>) => boolean;
}

export interface NonResultCommand {
  readonly path: string;
  readonly reason: string;
}

const self = (path: string, producer: string, when?: ResultCommand["when"]): ResultCommand =>
  ({ path, producer, defaultKind: "self_reported", ...(when ? { when } : {}) });
const example = (path: string, producer: string): ResultCommand => ({ path, producer, defaultKind: "synthetic_example" });
const non = (path: string, reason: string): NonResultCommand => ({ path, reason });

export const RESULT_COMMANDS: readonly ResultCommand[] = [
  // Scores and levels. A diagnostic run is observed only when its seal verifies and it has observed evidence.
  self("quickscore", "diagnostic:quickscore"),
  self("lite-score", "diagnostic"),
  self("run", "unified:run"),
  self("report", "diagnostic"),
  self("why-capped", "diagnostic"),
  self("unknowns", "diagnostic:knownUnknowns"),
  self("meta-confidence", "diagnostic:metaConfidence"),
  self("confidence-drift", "claims:confidenceDrift"),
  self("agent diagnose", "studio:diagnostic-self-run"),
  self("eval run", "diagnostic"),
  self("eval status", "eval:status"),
  self("executive brief", "diagnostic"),
  self("memory assess", "score:memoryMaturity"),
  self("ci check", "diagnostic"),
  self("improve", "diagnostic:rapidQuickscore"),
  self("fix", "fix:quickScore"),
  self("quickstart", "score:quickScore",
    (o) => !o.startupPlan && !o.whatBroken && !o.answersOut && !o.json && !o.minimal),
  self("loop run", "diagnostic"),
  self("score", "score:quickScore"),
  self("score formal-spec", "score:formalSpec"),
  self("score adversarial", "score:gamingResistanceTest"),
  self("score collect-evidence", "score:evidenceCollector"),
  self("score production-ready", "score:productionReadiness"),
  self("score operational-independence", "score:operationalIndependence"),
  self("score behavioral-contract", "score:behavioralContractMaturity"),
  self("score fail-secure", "score:failSecureGovernance"),
  self("score output-integrity", "score:outputIntegrityMaturity"),
  self("score state-portability", "score:agentStatePortability"),
  self("score eu-ai-act", "score:euAIActCompliance"),
  self("score owasp-llm", "score:owaspLLMCoverage"),
  self("score regulatory-readiness", "score:regulatoryReadiness"),
  self("score self-knowledge", "score:selfKnowledgeMaturity"),
  self("score kernel-sandbox", "score:kernelSandboxMaturity"),
  self("score runtime-identity", "score:runtimeIdentityMaturity"),
  self("score calibration-gap", "score:calibrationGap"),
  self("score evidence-conflict", "score:evidenceConflict"),
  self("score density-map", "score:densityMap"),
  self("score evidence-ingest", "score:evidenceIngestion"),
  self("score level-transition", "score:levelTransition"),
  self("score gaming-resistance", "score:gamingResistance"),
  self("score sleeper-detection", "score:sleeperDetection"),
  self("score audit-depth", "score:auditDepth"),
  self("score policy-consistency", "score:policyConsistency"),
  self("score autonomy-duration", "score:autonomyDuration"),
  self("score pause-quality", "score:pauseQuality"),
  self("score task-horizon", "score:taskHorizon"),
  self("score factuality", "score:factuality"),
  self("score alignment-index", "score:alignmentIndex"),
  self("score interpretability", "score:interpretability"),
  self("score faithfulness", "score:faithfulness"),
  self("score a2a-protocol", "score:a2aProtocol"),
  self("score distributed-agents", "score:distributedAgents"),
  self("score memory-integrity", "score:memoryIntegrity"),
  self("score memory-depth", "score:memoryDepth"),
  self("score output-attestation", "score:outputAttestation"),
  self("score mutual-verification", "score:mutualVerification"),
  self("score transparency-log", "score:networkTransparencyLog"),
  self("score tier", "score:quickScore"),
  self("score industry-adjust", "score:industryAdjusted"),
  self("score industry-benchmark", "score:industryBenchmark"),
  self("score simulation-lane", "lanes:simulationForecast"),
  self("score safety-research", "lanes:safetyResearch"),
  self("product autonomy", "product:autonomyDial"),
  self("strategy compare", "strategy:compare"),

  // Fleet and organisation: no more than the weakest member run.
  self("fleet score", "fleet:score"),
  self("fleet report", "fleet:report"),
  self("fleet overview", "fleet:health"),
  self("fleet status", "fleet:health"),
  self("fleet health", "fleet:health"),
  self("fleet trust-report", "fleet:trust-composition"),
  self("fleet slo status", "fleet:health"),
  self("org score", "org:scorecard"),
  self("org community score", "org:communityGovernance"),
  self("dag score", "score:orchestrationDAG"),
  self("leaderboard show", "leaderboard"),
  self("leaderboard export", "leaderboard"),
  self("leaderboard public-export", "leaderboard:public-export"),
  self("insider-risk-scores", "audit:insiderRisk"),
  self("observe timeline", "observe:timeline"),

  // Badges
  self("badge", "badge"),
  self("export badge", "diagnostic"),
  self("passport badge", "passport:badge"),

  // Domains and packs
  self("domain assess", "domain"),
  self("domain gaps", "domain"),
  self("domain report", "domain"),
  self("domain roadmap", "domain"),
  self("domain assurance", "domain"),
  self("domain apply", "industry-pack", (o) => o.audit === true),
  self("domain pack run", "industry-pack"),
  self("domain conformance", "conformance"),

  // Assurance, shield, benchmarks. Tests AMC executed against the agent are observed when they reached it.
  self("assurance run", "assurance"),
  self("assurance runs", "assurance:store"),
  self("assurance show", "assurance:store"),
  self("assurance verify", "assurance"),
  self("assurance cert-issue", "assurance:certificate"),
  self("assurance cert-verify", "assurance:certificate"),
  self("assurance scheduler run-now", "assurance:store"),
  self("assurance toctou", "lab:toctou"),
  self("assurance compound-threats", "lab:compoundThreat"),
  self("assurance shutdown-compliance", "lab:shutdownCompliance"),
  self("assurance advanced-threats", "lab:advancedThreats"),
  self("ci redteam", "redteam:ci"),
  self("shield posture", "shield:posture"),
  self("shield trust-pipeline", "shield:trustPipeline"),
  self("shield analyze-mcp", "shield:mcpSecurity"),
  self("shield analyze-runtime", "shield:runtimeAnalyzer"),
  self("shield reputation", "shield:toolReputation"),
  self("benchmark run", "benchmark"),
  self("benchmark report", "benchmark:report"),
  self("benchmark compare", "benchmark"),
  self("benchmark stats", "benchmark:stats"),
  self("benchmark verify", "benchmark"),
  self("benchmark provider-drift", "benchmark:providerDrift"),
  self("benchmark replay-corpus", "benchmark:replayCorpus"),

  // Compliance and audit: regulated results, never a pass without an applicability decision.
  // Without --framework, a non-interactive call lists the frameworks instead.
  self("compliance report", "compliance", (o) => typeof o.framework === "string"),
  self("compliance matrix", "compliance:matrix"),
  self("compliance fleet", "compliance:fleet"),
  self("compliance diff", "compliance:diff"),
  self("compliance risk-classify", "compliance:euAiActRiskTier"),
  self("compliance roadmap", "compliance:euAiActRoadmap"),
  self("comms-check", "comms-check"),
  self("audit binder create", "audit:binder"),
  self("audit binder verify", "audit:binder"),
  self("audit verify", "audit:workspace"),
  self("residency-report", "residency"),
  self("export grc", "diagnostic"),
  self("business grc-export", "business:grcTreatmentPlan"),
  self("business report", "business:impactReport"),
  self("business risk", "business:riskQuantification"),
  self("business kpi", "business:kpi"),

  // Certificates, passports, bundles, attestations. A valid signature proves integrity, never a stronger kind.
  self("certify", "diagnostic"),
  self("cert generate", "diagnostic"),
  self("cert inspect", "certificate"),
  self("cert verify", "certificate"),
  self("enforce verify-certificate", "enforce:proofCertificate"),
  self("enforce formal-verify", "enforce:formalVerification"),
  self("passport create", "passport"),
  self("passport show", "passport"),
  self("passport verify", "passport"),
  self("passport verify-token", "passport:trust-token"),
  self("passport compare", "passport:compare"),
  self("passport translate-score", "passport:translate-score"),
  self("passport export-latest", "passport"),
  self("passport share", "passport"),
  self("passport search", "passport:discovery"),
  self("bundle export", "diagnostic"),
  self("bundle verify", "bundle"),
  self("bundle inspect", "bundle"),
  self("bundle diff", "bundle:diff"),
  self("gate", "bundle"),
  self("attest", "ingest:attest"),
  self("attestation-export", "audit:insiderRiskAttestation"),
  self("notary attest", "notary:attestation"),
  self("notary verify-attest", "notary:attestation"),
  self("outcomes attest", "outcomes:attest"),
  self("transform attest", "transform:attest"),
  self("transform attest-verify", "transform:attest"),
  self("watch attest", "watch:outputAttestation"),
  self("transparency report", "transparency"),
  self("transparency verify", "transparency:log"),
  self("transparency verify-bundle", "transparency:log"),
  self("verify all", "verify:workspace"),
  self("session verify", "ledger:sessions"),

  // Imports: what the source reported, never observed by AMC.
  self("eval import", "eval:import"),
  self("import", "import:neutral"),
  self("ingest", "ingest"),

  // Synthetic producers
  example("demo run", "demo:run"),
  example("demo prospect", "demo:prospect"),
  example("demo share", "demo:prospect"),
  example("mirofish run", "mirofish:run"),
  example("mirofish compare", "mirofish:compare"),
  example("mirofish stress", "mirofish:stress"),
  example("lab-simulate", "lab:simulate")
];

const GROUP = "command group: lists its subcommands";

export const NON_RESULT_COMMANDS: readonly NonResultCommand[] = [
  non("history", "lists run IDs, times and signature statuses; no score or level (amc report <runId> labels each run)"),
  non("assurance history", "lists assurance run IDs, modes and signature statuses; no score (amc assurance runs labels them)"),
  non("score lean-profile", "describes AMC's lean module profile; no agent is assessed"),
  non("score evidence-coverage", "counts which AMC questions have automated evidence sources; no agent is assessed"),
  non("score industry-list", "lists the built-in industry trust models; reference data"),
  non("trust status", "reports the workspace trust mode and notary health; no agent result"),
  non("compliance verify", "verifies the compliance-maps configuration signature; no result is evaluated"),
  non("compliance init", "creates and signs the compliance-maps configuration"),
  non("compliance regulatory-check", "lists changes in regulatory feeds; no agent is assessed"),
  non("compliance regulatory-gap", "lists regulatory changes that need review; no agent is assessed"),
  non("audit init", "initialises the audit policy and compliance maps"),
  non("audit map verify", "verifies the audit compliance-map configuration signatures; no result is evaluated"),
  non("enterprise audit-export", "exports raw audit events to a SIEM format; no result is evaluated"),
  non("acp providers", "describes bundled provider adapters; no assessment"),
  non("agent-loop providers", "describes bundled provider adapters; no assessment"),
  non("adapters capabilities", "records declared and effective adapter capabilities; no assessment"),
  non("assurance", GROUP),
  non("assurance describe", "prints an assurance pack definition; catalog data"),
  non("assurance init", "initialises the signed assurance policy"),
  non("assurance list", "lists assurance packs; catalog data"),
  non("assurance patch", "applies a remediation patch kit; no result is evaluated"),
  non("assurance policy", "prints the assurance policy"),
  non("assurance policy-apply", "applies an assurance policy file"),
  non("assurance scheduler", GROUP),
  non("assurance scheduler disable", "disables the assurance scheduler"),
  non("assurance scheduler enable", "enables the assurance scheduler"),
  non("assurance verify-policy", "verifies the assurance policy signature; no result is evaluated"),
  non("assurance waiver", GROUP),
  non("assurance waiver request", "requests a dual-control waiver approval; no result is evaluated"),
  non("audit", GROUP),
  non("audit map", GROUP),
  non("backup create", "creates an encrypted backup; no result is evaluated"),
  non("backup verify", "verifies a backup's integrity; it carries no result of its own"),
  non("bench", GROUP),
  non("benchmark", GROUP),
  non("bundle", GROUP),
  non("cert", GROUP),
  non("cert revoke", "writes a revocation file for a certificate"),
  non("compliance", GROUP),
  non("dashboard view", "builds and opens the dashboard UI; its figures come from stored runs (amc report labels each)"),
  non("doctor", "checks runtime availability; no agent result"),
  non("domain", GROUP),
  non("domain pack access", "shows Industry Packs entitlement; payment never changes a result"),
  non("evidence decisions", "lists decision receipts; no new result"),
  non("evidence decisions observe", "records observed outcomes on decision receipts; no new result"),
  non("export", GROUP),
  non("fleet slo define", "defines a fleet SLO"),
  non("fp-submit", "files a false-positive report"),
  non("identity init", "creates the host identity configuration"),
  non("leaderboard", GROUP),
  non("lint", "lints configuration files for schema errors; no maturity or compliance result"),
  non("monitor live", "a long-running monitor; per-event output, no final result"),
  non("monitor start", "a long-running monitor; per-event output, no final result"),
  non("native-extension sign", "signs a reviewed extension manifest"),
  non("observe anomalies", "lists anomalies in evidence streams; no score, level or verdict"),
  non("org", GROUP),
  non("pack", GROUP),
  non("pack install", "installs an assurance pack"),
  non("passport", GROUP),
  non("passport capabilities-add", "records a capability declaration"),
  non("passport init", "creates the passport policy"),
  non("passport link", "links a passport to a platform identity"),
  non("passport policy", GROUP),
  non("passport policy apply", "applies a passport policy file"),
  non("passport policy print", "prints the passport policy"),
  non("passport verify-policy", "verifies the passport policy signature; no result is evaluated"),
  non("redteam plugins", "lists red-team plugins; catalog data"),
  non("release pack", "builds a release bundle"),
  non("release print", "prints a release manifest"),
  non("release scan", "scans a release bundle for secrets"),
  non("release verify", "verifies a release bundle's integrity"),
  non("session verify-proof", "verifies a transparency inclusion proof; it carries no result of its own"),
  non("setup", "setup wizard"),
  non("standard", GROUP),
  non("standard generate", "generates the Open Compass schema bundle"),
  non("standard verify", "verifies the schema bundle signatures"),
  non("studio healthcheck", "a deployment readiness probe; no agent result"),
  non("transform", GROUP),
  non("transparency export", "exports the transparency log"),
  non("transparency merkle prove", "exports an inclusion proof"),
  non("transparency merkle verify-proof", "verifies an inclusion proof; it carries no result of its own"),
  non("vault classify", "classifies the sensitivity of the caller's text; no maturity or compliance result"),
  non("vault zk-range-proof", "creates a commitment to a score threshold; it states no result of its own"),
  non("watch", GROUP)
];

export const RESULT_COMMAND_BY_PATH: ReadonlyMap<string, ResultCommand> = new Map(RESULT_COMMANDS.map((command) => [command.path, command]));
