/**
 * International standards, treaties, frameworks and guidance cited by industry
 * packs. Editions marked in-force (current edition) or repealed (superseded
 * edition, with supersededBy) were checked against the issuing
 * body's own catalogue or page on the review date (iso.org listings: the page
 * body returns HTTP 403 to automated fetches, so the edition is taken from the
 * iso.org catalogue title). Everything else is "unverified".
 */
import type { RegulatoryInstrument } from "./regulatorySchema.js";
import { milestones, unverified, verified } from "./catalogueHelpers.js";

const ISO_NOTE = "Edition and status taken from the iso.org catalogue listing on the review date.";

function iso(id: string, citation: string, status: "in-force" | "repealed", url: string, aliases: string[], supersededBy?: string): RegulatoryInstrument {
  return verified(id, citation, "INT", "standard", status, url, aliases, { note: ISO_NOTE, ...(supersededBy ? { supersededBy } : {}) });
}

export const INTL_INSTRUMENTS: readonly RegulatoryInstrument[] = [
  // ISO / IEC management-system and sector standards
  iso("iso-9001-2026", "ISO 9001:2026 Quality management systems — Requirements", "in-force", "https://www.iso.org/standard/9001", ["ISO 9001:2026", "ISO 9001"]),
  iso("iso-9001-2015", "ISO 9001:2015 Quality management systems — Requirements", "repealed", "https://www.iso.org/standard/62085.html", ["ISO 9001:2015"], "iso-9001-2026"),
  iso("iso-14001-2026", "ISO 14001:2026 Environmental management systems", "in-force", "https://www.iso.org/news/2026/04/iso-14001-2026-published", ["ISO 14001:2026", "ISO 14001"]),
  iso("iso-14001-2015", "ISO 14001:2015 Environmental management systems", "repealed", "https://www.iso.org/standard/60857.html", ["ISO 14001:2015"], "iso-14001-2026"),
  iso("iso-13485", "ISO 13485:2016 Medical devices — Quality management systems", "in-force", "https://www.iso.org/standard/59752.html", ["ISO 13485:2016", "ISO 13485"]),
  iso("iso-14971", "ISO 14971:2019 Medical devices — Application of risk management", "in-force", "https://www.iso.org/standard/72704.html", ["ISO 14971:2019", "ISO 14971"]),
  iso("iso-14155-2026", "ISO 14155:2026 Clinical investigation of medical devices for human subjects — Good clinical practice", "in-force", "https://www.iso.org/standard/14155", ["ISO 14155:2026", "ISO 14155"]),
  iso("iso-14155-2020", "ISO 14155:2020 Clinical investigation of medical devices for human subjects — Good clinical practice", "repealed", "https://www.iso.org/standard/71690.html", ["ISO 14155:2020"], "iso-14155-2026"),
  verified("iso-27001", "ISO/IEC 27001:2022 Information security management systems (with Amd 1:2024)", "INT", "standard", "in-force", "https://www.iso.org/standard/27001",
    ["ISO/IEC 27001:2022", "ISO 27001:2022", "ISO/IEC 27001", "ISO 27001"], { frameworkId: "ISO_27001", note: ISO_NOTE }),
  iso("iso-27701-2025", "ISO/IEC 27701:2025 Privacy information management systems — Requirements and guidance", "in-force", "https://www.iso.org/standard/27701", ["ISO/IEC 27701:2025", "ISO 27701:2025"]),
  iso("iso-27701-2019", "ISO/IEC 27701:2019 Extension to ISO/IEC 27001 and ISO/IEC 27002 for privacy information management", "repealed", "https://www.iso.org/standard/71670.html", ["ISO/IEC 27701:2019", "ISO 27701:2019"], "iso-27701-2025"),
  iso("iso-27799-2025", "ISO 27799:2025 Health informatics — Information security controls in health based on ISO/IEC 27002", "in-force", "https://www.iso.org/standard/84647.html", ["ISO 27799:2025", "ISO 27799"]),
  iso("iso-27799-2016", "ISO 27799:2016 Health informatics — Information security management in health using ISO/IEC 27002", "repealed", "https://www.iso.org/standard/62777.html", ["ISO 27799:2016"], "iso-27799-2025"),
  verified("iso-42001", "ISO/IEC 42001:2023 Artificial intelligence — Management system", "INT", "standard", "in-force", "https://www.iso.org/standard/42001",
    ["ISO/IEC 42001:2023", "ISO/IEC 42001", "ISO 42001"], { frameworkId: "ISO_42001", note: ISO_NOTE }),
  iso("iso-28000", "ISO 28000:2022 Security and resilience — Security management systems (with Amd 1:2024)", "in-force", "https://www.iso.org/standard/79612.html", ["ISO 28000:2022", "ISO 28000"]),
  iso("iso-22301", "ISO 22301:2019 Security and resilience — Business continuity management systems (with Amd 1:2024)", "in-force", "https://www.iso.org/standard/88412.html", ["ISO 22301:2019", "ISO 22301"]),
  iso("iso-45001", "ISO 45001:2018 Occupational health and safety management systems (with Amd 1:2024)", "in-force", "https://www.iso.org/standard/45001", ["ISO 45001:2018", "ISO 45001"]),
  iso("iso-50001", "ISO 50001:2018 Energy management systems (with Amd 1:2024)", "in-force", "https://www.iso.org/standard/88430.html", ["ISO 50001:2018", "ISO 50001"]),
  iso("iso-21434", "ISO/SAE 21434:2021 Road vehicles — Cybersecurity engineering", "in-force", "https://www.iso.org/standard/70918.html", ["ISO/SAE 21434:2021", "ISO 21434:2021", "ISO 21434"]),
  iso("iso-9241-210", "ISO 9241-210:2019 Human-centred design for interactive systems", "in-force", "https://www.iso.org/standard/77520.html", ["ISO 9241-210:2019", "ISO 9241-210"]),
  iso("iso-20000-1", "ISO/IEC 20000-1:2018 Service management system requirements", "in-force", "https://www.iso.org/standard/70636.html", ["ISO/IEC 20000-1:2018", "ISO/IEC 20000-1"]),
  iso("iso-29115", "ISO/IEC 29115:2013 Entity authentication assurance framework", "in-force", "https://www.iso.org/standard/45138.html", ["ISO/IEC 29115:2013", "ISO/IEC 29115"]),
  iso("iso-14044", "ISO 14044:2006 Life cycle assessment — Requirements and guidelines (with amendments 2017, 2020)", "in-force", "https://www.iso.org/standard/38498.html", ["ISO 14044:2006", "ISO 14044"]),
  iso("iso-29990", "ISO 29990:2010 Learning services for non-formal education and training", "repealed", "https://www.iso.org/contents/data/standard/05/33/53392.html", ["ISO 29990:2010", "ISO 29990"], "iso-21001"),
  unverified("iso-21001", "ISO 21001 Educational organizations — Management systems (edition not confirmed)", "INT", "standard", ["ISO 21001"],
    "iso.org lists ISO 21001:2018 and its Amd 1:2024; whether a newer edition replaced it was not confirmed."),
  verified("iec-62304", "IEC 62304:2006 + Amd 1:2015 Medical device software — Software life cycle processes", "INT", "standard", "in-force", "https://www.iso.org/standard/64686.html",
    ["IEC 62304:2006/AMD1:2015", "IEC 62304:2006", "IEC 62304"], { note: "Edition 2 (health software) is in development per IEC SC 62A documents; not yet published on the review date." }),
  unverified("iso-22000", "ISO 22000:2018 Food safety management systems", "INT", "standard", ["ISO 22000:2018", "ISO 22000"]),
  unverified("iso-26000", "ISO 26000:2010 Guidance on social responsibility", "INT", "guidance", ["ISO 26000:2010", "ISO 26000"]),
  unverified("iso-37120", "ISO 37120:2018 Sustainable cities and communities — Indicators", "INT", "standard", ["ISO 37120:2018", "ISO 37120"]),
  unverified("iso-37122", "ISO 37122:2019 Sustainable cities and communities — Indicators for smart cities", "INT", "standard", ["ISO 37122:2019", "ISO 37122"]),
  unverified("iso-20022", "ISO 20022 Financial services — Universal financial industry message scheme", "INT", "standard", ["ISO 20022"]),
  unverified("iso-24510", "ISO 24510 / ISO 24512 Water services", "INT", "standard", ["ISO 24510/24512", "ISO 24510:2007"]),
  unverified("iso-25000", "ISO/IEC 25000 SQuaRE", "INT", "standard", ["ISO 25000 SQuaRE", "ISO/IEC 25000"]),
  unverified("iec-62430", "IEC 62430:2019 Environmentally conscious design", "INT", "standard", ["IEC 62430:2019", "IEC 62430"]),
  unverified("iec-61968-61970", "IEC 61968 / IEC 61970 Common Information Model", "INT", "standard", ["IEC 61968/61970"]),
  unverified("iso-11135", "ISO 11135:2014 Sterilization of health-care products — Ethylene oxide", "INT", "standard", ["ISO 11135:2014", "ISO 11135"]),
  unverified("iso-13131", "ISO 13131:2021 Health informatics — Telehealth services", "INT", "standard", ["ISO 13131:2021", "ISO 13131"]),
  unverified("iso-17511", "ISO 17511:2020 In vitro diagnostic medical devices — metrological traceability", "INT", "standard", ["ISO 17511:2020", "ISO 17511"]),
  unverified("iso-tc307", "ISO/TC 307 Blockchain and distributed ledger technologies standards", "INT", "standard", ["ISO/TC 307"]),
  unverified("iso-jtc1-sc41", "ISO/IEC JTC 1/SC 41 Internet of things and digital twin standards", "INT", "standard", ["ISO/IEC JTC 1/SC 41"]),
  unverified("ieee-2030", "IEEE 2030-2011 Smart grid interoperability", "INT", "standard", ["IEEE 2030"]),
  unverified("ieee-7001", "IEEE 7001-2021 Transparency of autonomous systems", "INT", "standard", ["IEEE 7001:2021", "IEEE 7001"]),
  unverified("etsi-en-303-645", "ETSI EN 303 645 Cyber security for consumer IoT", "INT", "standard", ["ETSI EN 303 645"]),
  unverified("unece-r155-r156", "UN Regulations No. 155 (cybersecurity) and No. 156 (software updates), UNECE WP.29", "INT", "law", ["UNECE WP.29"]),

  // NIST, W3C, payment-card and security frameworks
  verified("nist-ai-rmf", "NIST AI 100-1 Artificial Intelligence Risk Management Framework (AI RMF 1.0)", "US", "framework", "in-force", "https://www.nist.gov/itl/ai-risk-management-framework",
    ["NIST AI RMF 1.0", "NIST AI RMF", "NIST AI 100-1"], { frameworkId: "NIST_AI_RMF" }),
  verified("nist-csf-2", "NIST Cybersecurity Framework 2.0", "US", "framework", "in-force", "https://www.nist.gov/cyberframework", ["NIST CSF 2.0", "NIST CSF"]),
  verified("nist-sp-800-161", "NIST SP 800-161 Rev. 1 (update 1, 2024-11-01) Cybersecurity Supply Chain Risk Management Practices", "US", "standard", "in-force",
    "https://csrc.nist.gov/pubs/sp/800/161/r1/upd1/final", ["NIST SP 800-161r1-upd1", "NIST SP 800-161"]),
  verified("w3c-wcag-21", "W3C Web Content Accessibility Guidelines 2.1", "INT", "standard", "in-force", "https://www.w3.org/TR/WCAG22/",
    ["WCAG 2.1 AA", "WCAG 2.1"], { note: "W3C states WCAG 2.2 does not deprecate or supersede WCAG 2.1 and advises WCAG 2.2 as the conformance target." }),
  verified("w3c-wcag-22", "W3C Web Content Accessibility Guidelines 2.2", "INT", "standard", "in-force", "https://www.w3.org/TR/WCAG22/", ["WCAG 2.2 AA", "WCAG 2.2"]),
  verified("pci-dss-401", "PCI DSS v4.0.1", "INT", "standard", "in-force", "https://www.pcisecuritystandards.org/document_library/",
    ["PCI DSS v4.0.1", "PCI DSS"], { frameworkId: "PCI_DSS" }),
  verified("pci-dss-40", "PCI DSS v4.0", "INT", "standard", "repealed", "https://www.pcisecuritystandards.org/document_library/",
    ["PCI DSS v4.0"], { frameworkId: "PCI_DSS", supersededBy: "pci-dss-401", note: "The PCI SSC document library lists v4.0.1 as current, with a v4.0 to v4.0.1 summary of changes." }),
  unverified("soc2", "AICPA SOC 2 (Trust Services Criteria)", "US", "framework", ["SOC 2 Type II", "SOC 2"]),
  unverified("owasp-api-2023", "OWASP API Security Top 10 (2023)", "INT", "guidance", ["OWASP API Security Top 10 2023", "OWASP API Top 10 2023", "OWASP API"]),
  unverified("csa-star", "Cloud Security Alliance STAR", "INT", "framework", ["CSA STAR"]),
  unverified("emv", "EMVCo specifications", "INT", "standard", ["EMV Specifications", "EMV"]),
  unverified("swift-csp", "SWIFT Customer Security Programme", "INT", "framework", ["SWIFT Customer Security Programme"]),
  unverified("itil-4", "ITIL 4", "INT", "framework", ["ITIL v4"]),
  unverified("oidc-oauth21", "OpenID Connect / OAuth 2.1", "INT", "standard", ["OpenID Connect / OAuth 2.1", "OAuth 2.1"], "OAuth 2.1 was an IETF draft when last checked; not confirmed in this review."),

  // Health and life-sciences standards and guidance
  verified("ich-e6-r3", "ICH E6(R3) Guideline for Good Clinical Practice", "INT", "guidance", "in-force", "https://www.ema.europa.eu/en/ich-e6-good-clinical-practice-scientific-guideline",
    ["ICH E6(R3)"], {
      effectiveDate: "2025-01-06",
      milestones: milestones(["2025-07-23", "Principles and Annex 1 effective in the EU"], ["2027-01-15", "Annex 2 effective in the EU"]),
      note: "Step 4 date and section numbering read from the ICH Step 4 guideline (database.ich.org); EU dates from the EMA page.",
    }),
  verified("ich-e6-r2", "ICH E6(R2) Guideline for Good Clinical Practice", "INT", "guidance", "repealed", "https://www.ema.europa.eu/en/ich-e6-good-clinical-practice-scientific-guideline",
    ["ICH E6(R2)"], { supersededBy: "ich-e6-r3" }),
  verified("consort-2025", "CONSORT 2025 Statement", "INT", "guidance", "in-force", "https://www.consort-spirit.org/published-statements", ["CONSORT 2025"]),
  verified("consort-2010", "CONSORT 2010 Statement", "INT", "guidance", "repealed", "https://www.consort-spirit.org/published-statements", ["CONSORT 2010"], { supersededBy: "consort-2025" }),
  unverified("ich-q8-q12", "ICH Q8(R2)-Q12 quality guidelines", "INT", "guidance", ["ICH Q8(R2)-Q12", "ICH Q8(R2)"]),
  unverified("ich-m4", "ICH M4 Common Technical Document", "INT", "guidance", ["ICH M4 CTD", "ICH M4"]),
  unverified("cdisc", "CDISC CDASH / SDTM / ADaM", "INT", "standard", ["CDISC"]),
  unverified("hl7-fhir-r4", "HL7 FHIR Release 4 (4.0.1)", "INT", "standard", ["HL7 FHIR R4", "HL7 FHIR"]),
  unverified("ihe", "IHE IT Infrastructure profiles (XDS.b, XCA)", "INT", "standard", ["IHE XDS.b", "IHE ITI Profiles", "IHE"]),
  unverified("jci", "Joint Commission International accreditation standards", "INT", "standard", ["JCI Accreditation Standards", "JCI Standards", "JCI 7th ed."]),
  unverified("who-ictrp", "WHO International Clinical Trials Registry Platform standards", "INT", "guidance", ["WHO ICTRP Registration Standards", "WHO ICTRP"]),
  unverified("who-dwq", "WHO Guidelines for Drinking-water Quality", "INT", "guidance", ["WHO Guidelines for Drinking-water Quality", "WHO Drinking-water Quality Guidelines"]),
  unverified("who-icf", "WHO International Classification of Functioning, Disability and Health", "INT", "framework", ["WHO ICF Framework", "WHO ICF"]),
  unverified("who-gappa", "WHO Global Action Plan on Physical Activity 2018-2030", "INT", "policy", ["WHO Global Action Plan on Physical Activity"]),
  unverified("who-clinical-guidelines", "WHO clinical practice guidelines", "INT", "guidance", ["WHO Clinical Practice Guidelines"]),
  unverified("nqf", "NQF standards", "US", "standard", ["NQF Standards"]),

  // Financial-sector frameworks
  verified("fatf-recs", "FATF Recommendations (R.16 revised June 2025)", "INT", "framework", "in-force",
    "https://www.fatf-gafi.org/en/publications/Fatfrecommendations/update-Recommendation-16-payment-transparency-june-2025.html",
    ["FATF Recommendations", "FATF Recommendation", "FATF R1", "FATF R16", "FATF R.16"], { note: "Update title read from fatf-gafi.org search listing; the page body returned HTTP 403." }),
  unverified("fatf-va-guidance", "FATF Updated Guidance for a Risk-Based Approach to Virtual Assets and VASPs (2021)", "INT", "guidance", ["FATF VA/VASP Guidelines"]),
  unverified("basel-iii", "Basel III framework (BCBS)", "INT", "framework", ["Basel III"]),
  unverified("bis-cpmi", "BIS CPMI guidance on stablecoin arrangements", "INT", "guidance", ["BIS CPMI"]),
  unverified("iosco-crypto", "IOSCO Policy Recommendations for Crypto and Digital Asset Markets", "INT", "guidance", ["IOSCO Policy Recommendations for Crypto", "IOSCO Crypto Recommendations"]),
  unverified("cgap", "CGAP microfinance standards", "INT", "guidance", ["CGAP Microfinance Standards", "CGAP Standards"]),
  unverified("gsma-mobile-money", "GSMA Mobile Money guidelines", "INT", "guidance", ["GSMA Mobile Money"]),
  unverified("world-bank-fi", "World Bank financial inclusion guidelines", "INT", "guidance", ["World Bank Financial Inclusion Guidelines", "World Bank FI Guidelines"]),
  unverified("world-bank-ppp", "World Bank PPP guidelines", "INT", "guidance", ["World Bank PPP Guidelines"]),
  unverified("unhcr-fi", "UNHCR guidance on financial inclusion of refugees", "INT", "guidance", ["UNHCR Guidelines on Financial Inclusion", "UNHCR FI Guidelines"]),
  unverified("ifc-ps", "IFC Performance Standards on Environmental and Social Sustainability", "INT", "framework", ["IFC Performance Standards", "IFC PS"]),
  unverified("un-pri", "UN Principles for Responsible Investment", "INT", "framework", ["UN PRI"]),

  // ESG, buildings, materials and food schemes
  unverified("gri", "GRI Standards", "INT", "standard", ["GRI Standards"]),
  unverified("sasb", "SASB Standards (IFRS Foundation)", "INT", "standard", ["SASB Standards"]),
  unverified("tcfd", "TCFD Recommendations", "INT", "framework", ["TCFD Recommendations"]),
  unverified("gresb", "GRESB Real Estate Assessment", "INT", "framework", ["GRESB"]),
  unverified("leed-v4", "USGBC LEED v4", "INT", "standard", ["LEED v4"]),
  unverified("breeam", "BREEAM In-Use", "INT", "standard", ["BREEAM In-Use", "BREEAM"]),
  unverified("well-v2", "WELL Building Standard v2", "INT", "standard", ["WELL Building Standard v2"]),
  unverified("c40", "C40 Cities framework", "INT", "framework", ["C40 Cities"]),
  unverified("oeko-tex", "OEKO-TEX Standard 100", "INT", "standard", ["OEKO-TEX Standard 100"]),
  unverified("grs", "Global Recycled Standard 4.0", "INT", "standard", ["Global Recycled Standard (GRS) 4.0", "GRS 4.0"]),
  unverified("zdhc-mrsl", "ZDHC Manufacturing Restricted Substances List v3.1", "INT", "standard", ["ZDHC Manufacturing Restricted Substances List (MRSL) v3.1", "ZDHC MRSL v3.1", "ZDHC MRSL"]),
  unverified("higg", "Higg Index (Cascale, formerly Sustainable Apparel Coalition)", "INT", "framework", ["Higg Index (SAC)", "Higg FEM/FSLM", "Higg"]),
  unverified("fashion-pact", "The Fashion Pact", "INT", "framework", ["The Fashion Pact"]),
  unverified("fsc-pefc", "FSC forest management standard v5.3 / PEFC ST 1003:2018", "INT", "standard", ["FSC Standard v5.3", "FSC v5.3"]),
  unverified("emf-ce", "Ellen MacArthur Foundation circular economy principles", "INT", "framework", ["Ellen MacArthur Foundation CE Principles", "Ellen MacArthur"]),
  unverified("fssc-22000", "FSSC 22000 Version 6", "INT", "standard", ["FSSC 22000"]),
  unverified("globalgap", "GLOBALG.A.P. Integrated Farm Assurance v6", "INT", "standard", ["GLOBALG.A.P."]),
  unverified("codex", "Codex Alimentarius (incl. General Principles of Food Hygiene CXC 1-1969)", "INT", "standard", ["Codex Alimentarius", "Codex CAC/RCP"]),
  unverified("fao-guidelines", "FAO Voluntary Guidelines", "INT", "guidance", ["FAO Voluntary Guidelines", "FAO VGGT"]),
  unverified("fao-ccrf", "FAO Code of Conduct for Responsible Fisheries (1995)", "INT", "guidance", ["FAO Code of Conduct for Responsible Fisheries"]),
  unverified("gs1-epcis", "GS1 EPCIS 2.0", "INT", "standard", ["GS1 EPCIS 2.0", "GS1 EPCIS"]),

  // Treaties, conventions and intergovernmental principles
  verified("oecd-ai", "OECD Recommendation of the Council on Artificial Intelligence (OECD/LEGAL/0449), as amended 2024-05-03", "INT", "guidance", "in-force",
    "https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0449", ["OECD AI Principles", "OECD AI"], { note: "Amendment date read from the OECD legal-instruments listing." }),
  unverified("coe-ai-convention", "Council of Europe Framework Convention on Artificial Intelligence (CETS No. 225)", "INT", "treaty", ["Council of Europe AI Convention 2024", "CoE AI Convention", "CoE AI"],
    "Entry into force requires five ratifications incl. three CoE member States; ratification status was not read from the treaty office page (HTTP 403)."),
  unverified("coe-rec-2017-5", "Council of Europe Recommendation CM/Rec(2017)5 on e-voting standards", "INT", "guidance", ["Council of Europe Recommendation CM/Rec(2017)5", "Council of Europe Rec CM/Rec(2017)5"]),
  unverified("unesco-ai-ethics", "UNESCO Recommendation on the Ethics of Artificial Intelligence (2021)", "INT", "guidance", ["UNESCO AI Ethics Recommendation 2021", "UNESCO AI Ethics", "UNESCO Recommendation"]),
  unverified("g20-ai", "G20 AI Principles (2019)", "INT", "guidance", ["G20 Principles for Responsible AI in Government", "G20 Responsible AI Principles", "G20 AI"]),
  unverified("venice-elections-ai", "Venice Commission guidance on AI and elections", "INT", "guidance", ["Venice Commission AI in Elections Guidelines"]),
  unverified("osce-odihr", "OSCE/ODIHR election observation standards", "INT", "guidance", ["OSCE/ODIHR Electoral Standards"]),
  unverified("un-egov", "UN E-Government Survey methodology", "INT", "guidance", ["UN E-Government Development Index Standards", "UN E-Government Survey Guidelines", "UN E-Government"]),
  unverified("un-sdgs", "UN 2030 Agenda Sustainable Development Goals", "INT", "policy", ["UN SDG"]),
  unverified("ungps", "UN Guiding Principles on Business and Human Rights (2011)", "INT", "guidance", ["UN Guiding Principles on Business and Human Rights (UNGPs)", "UNGPs"]),
  unverified("oecd-mne", "OECD Guidelines for Multinational Enterprises on Responsible Business Conduct (2023)", "INT", "guidance", ["OECD Guidelines for Multinational Enterprises (2023)", "OECD MNE Guidelines 2023"]),
  unverified("oecd-ppp", "OECD Recommendation on Principles for Public Governance of Public-Private Partnerships (2012)", "INT", "guidance", ["OECD PPP Framework", "OECD PPP"]),
  unverified("uncac", "United Nations Convention against Corruption (2003)", "INT", "treaty", ["UNCAC (UN Convention Against Corruption)", "UNCAC"]),
  unverified("ilo-c087-c098", "ILO Conventions C087 and C098 (freedom of association, collective bargaining)", "INT", "treaty", ["ILO Conventions C087/C098 (Freedom of Association)", "ILO C087/C098"]),
  unverified("ilo-vet", "ILO standards on vocational education and training (incl. R195)", "INT", "guidance", ["ILO VET Standards", "ILO R195"]),
  unverified("crpd", "UN Convention on the Rights of Persons with Disabilities (2006)", "INT", "treaty", ["CRPD (UN Convention on Rights of Persons with Disabilities)", "CRPD"]),
  unverified("un-crc", "UN Convention on the Rights of the Child (1989)", "INT", "treaty", ["UN CRC"]),
  unverified("unesco-education", "UNESCO education guidelines (higher education, arts education, TVET, Salamanca Statement)", "INT", "guidance",
    ["UNESCO Higher Education Guidelines", "UNESCO Arts Education Guidelines", "UNESCO TVET Framework", "UNESCO Salamanca Statement", "UNESCO TVET", "UNESCO Guidelines", "UNESCO Seoul"]),
  unverified("aacsb", "AACSB accreditation standards", "INT", "standard", ["AACSB/Regional Accreditation Standards", "AACSB Standards", "AACSB Standard"]),
  unverified("bologna", "Bologna Process / Qualifications Framework of the EHEA", "INT", "framework", ["Bologna Process"]),
  unverified("iste", "ISTE Standards", "INT", "standard", ["ISTE Standards"]),
  unverified("udl", "CAST Universal Design for Learning Guidelines", "INT", "guidance", ["UDL Guidelines 2.2", "UDL Principles"]),
  unverified("wipo-internet-treaties", "WIPO Copyright Treaty and WIPO Internet Treaties (1996)", "INT", "treaty", ["WIPO Copyright Treaty", "WIPO Internet Treaties"]),
  unverified("trips", "WTO TRIPS Agreement", "INT", "treaty", ["TRIPS Agreement", "WTO IP Framework"]),
  unverified("creative-commons", "Creative Commons licences", "INT", "framework", ["Creative Commons Licensing", "Creative Commons"]),
  unverified("fair", "FAIR Guiding Principles for scientific data", "INT", "guidance", ["FAIR Data Principles", "FAIR Principles"]),
  unverified("wef-future-jobs", "WEF Future of Jobs Report", "INT", "guidance", ["WEF Future of Jobs Report Framework", "WEF Future of Jobs"]),
  unverified("cbd", "Convention on Biological Diversity and Kunming-Montreal Global Biodiversity Framework", "INT", "treaty", ["Convention on Biological Diversity (CBD)", "CBD Kunming-Montreal GBF"]),
  unverified("nagoya", "Nagoya Protocol on Access and Benefit-sharing", "INT", "treaty", ["Nagoya Protocol"]),
  unverified("cites", "Convention on International Trade in Endangered Species (CITES)", "INT", "treaty", ["CITES"]),
  unverified("ramsar", "Ramsar Convention on Wetlands", "INT", "treaty", ["Ramsar Convention"]),
  unverified("paris-agreement", "Paris Agreement (2015)", "INT", "treaty", ["Paris Agreement"]),
  unverified("redd-plus", "UNFCCC REDD+ (Warsaw Framework)", "INT", "framework", ["UN REDD+"]),
  unverified("ipbes", "IPBES assessment framework", "INT", "framework", ["IPBES Assessment Framework"]),
  unverified("helcom-bsap", "HELCOM Baltic Sea Action Plan", "INT", "policy", ["HELCOM Baltic Sea Action Plan"]),
  unverified("marpol", "IMO MARPOL Convention (incl. Annex IV)", "INT", "treaty", ["IMO MARPOL", "MARPOL Annex IV", "MARPOL"]),
  unverified("imdg", "IMO International Maritime Dangerous Goods Code", "INT", "standard", ["IMDG Code"]),
  unverified("isps", "IMO International Ship and Port Facility Security Code", "INT", "standard", ["ISPS Code"]),
  unverified("un-tir", "UN TIR Convention (1975)", "INT", "treaty", ["UN TIR Convention"]),
  { ...unverified("unesco-genai-2023", "UNESCO Guidance for generative AI in education and research (2023)", "INT", "guidance",
    ["UNESCO Guidance for generative AI in education and research"],
    "Non-binding. Page read on unesco.org (the issuing body) 2026-10-03 per round2/content/education/questions.json; that host is not on OFFICIAL_SOURCE_HOSTS, so the status stays unverified."),
    lastReviewed: "2026-10-04" },
  // Technology station round 2 (2026-10-04): cited by TECH-NE-10.
  { ...unverified("ietf-rfc-9700", "IETF RFC 9700 Best Current Practice for OAuth 2.0 Security (BCP 240), January 2025", "INT", "standard", ["IETF RFC 9700", "RFC 9700", "BCP 240"],
    "Read on rfc-editor.org 2026-10-04 (public clients MUST use PKCE; implicit grant SHOULD NOT be used); rfc-editor.org is not on OFFICIAL_SOURCE_HOSTS, so the status stays unverified."), lastReviewed: "2026-10-04" },
  // Technology station round 2 (2026-10-04): cited by TECH-PP-4.
  { ...unverified("etsi-ipr-policy", "ETSI IPR Policy (Annex 6, ETSI Rules of Procedure, 29-30 November 2022)", "INT", "policy", ["ETSI IPR Policy"],
    "Clauses 4.1 and 6.1 read in the etsi.org PDF 2026-10-04 by the technology round-2 content pass; etsi.org is not on OFFICIAL_SOURCE_HOSTS."), lastReviewed: "2026-10-04" },
  // Technology station round 2 (2026-10-04): cited by TECH-PP-2.
  { ...unverified("spdx-3", "SPDX Specification 3.0", "INT", "standard", ["SPDX 3.0"],
    "spdx.dev lists 3.0 as the current specification (read 2026-10-04 by the technology round-2 content pass); not an official-source host."), lastReviewed: "2026-10-04" },
  // Technology station round 2 (2026-10-04): cited by TECH-PP-11.
  { ...unverified("wipo-wppt", "WIPO Performances and Phonograms Treaty (1996)", "INT", "treaty", ["WIPO WPPT", "WPPT"],
    "Art. 7 read on WIPO Lex (wipo.int/wipolex/en/text/295578) 2026-10-04 by the technology round-2 content pass; wipo.int is not on OFFICIAL_SOURCE_HOSTS."), lastReviewed: "2026-10-04" },
];
