/**
 * Hand-written deep questions. Education station: EU AI Act Annex III point 3 and Art. 5/26, FERPA (34 CFR Part 99),
 * COPPA (16 CFR Part 312), PPRA (34 CFR Part 98), IDEA (34 CFR Part 300), ADA Title II (28 CFR §35.200) and Title IX (34 CFR Part 106).
 * Each question anchors one provision and lists the industry packs it applies to.
 */

import { AI_ACT_DESK, OMNIBUS_DATES, aiActSource, cfrSource, levels, source, readOn, REPAIR_RETRIEVED_AT, type DeepIndustryQuestion } from "./shared.js";

export const DEEP_EDUCATION_QUESTIONS: DeepIndustryQuestion[] = [
  {
    id: "education-deep-01", industry: "education", station: "education",
    packIds: ["higher-education", "skills-training", "k12-pm3"],
    regulation: "EU AI Act", section: "Annex III point 3(a) — access, admission and assignment",
    question: "Where the agent determines access or admission to, or assigns learners to, an educational or vocational training institution, is it run as an Annex III high-risk system with human review of every adverse decision and a log of the inputs behind it?",
    evaluationCriteria: ["Use case classified against Annex III point 3(a)", "Adverse decisions reviewed by a named person", "Decision inputs logged per applicant", "Applicant can contest the outcome"],
    levels: levels("Admission decisions are fully automated and unlogged", "Classification noted but reviews are ad hoc", "Every adverse decision is human-reviewed with logged inputs", "Review quality is sampled and disparities by cohort are measured", "Contest outcomes feed back into a monitored, documented risk-management loop"),
    evidenceTypes: ["risk_classification", "reviewer_signoff", "decision_log", "appeal_record"],
    source: source("Regulation (EU) 2024/1689 Annex III (AI Act Service Desk)", `${AI_ACT_DESK}/annex-3`),
  },
  {
    id: "education-deep-02", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "skills-training", "specialized-education"],
    regulation: "EU AI Act", section: "Annex III point 3(b)-(c) — evaluating learning outcomes and level of education",
    question: "When the agent evaluates learning outcomes or assesses the level of education a learner will receive, are its accuracy and error rates measured per cohort and are educators able to override and record the override?",
    evaluationCriteria: ["Assessment use cases inventoried", "Accuracy measured per learner cohort", "Educator override path exists", "Overrides recorded with reason"],
    levels: levels("Agent grades or places learners with no accuracy evidence", "Spot checks of outputs without cohort breakdown", "Cohort-level accuracy reported and educator overrides logged", "Override rates trigger re-validation of the model", "Independent validation and published limitations for each assessment use"),
    evidenceTypes: ["validation_report", "cohort_metrics", "override_log"],
    source: source("Regulation (EU) 2024/1689 Annex III (AI Act Service Desk)", `${AI_ACT_DESK}/annex-3`),
  },
  {
    id: "education-deep-03", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "skills-training", "specialized-education", "differently-abled"],
    regulation: "EU AI Act", section: "Art. 5(1)(f) — emotion inference in education institutions",
    question: "Is the agent technically prevented from inferring learners' emotions in an education institution, with any medical or safety exception documented and approved?",
    evaluationCriteria: ["Emotion-inference features disabled in education deployments", "Exceptions limited to medical or safety reasons", "Exception approvals recorded", "Configuration drift detected"],
    levels: levels("Emotion inference is available or in use", "Policy forbids it but nothing enforces it", "Feature is disabled by configuration and exceptions are approved in writing", "Deployment checks block re-enabling and alert on drift", "Prohibited-practice screening runs on every release with signed results"),
    evidenceTypes: ["feature_flag_config", "exception_register", "release_check"],
    source: source("Regulation (EU) 2024/1689 Art. 5 (AI Act Service Desk)", `${AI_ACT_DESK}/article-5`),
  },
  {
    id: "education-deep-04", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education"],
    regulation: "FERPA", section: "34 CFR §99.31(a)(1) — school officials with legitimate educational interest",
    question: "Does the agent release education-record PII only to school officials whose legitimate educational interest has been determined, using access controls rather than policy alone?",
    evaluationCriteria: ["Legitimate-interest criteria defined", "Access scoped per official role", "Agent requests carry the requesting official", "Denied requests logged"],
    levels: levels("Any staff account can retrieve any student record through the agent", "Role list exists but the agent does not check it", "Agent enforces role-scoped access tied to legitimate educational interest", "Access is reviewed each term and anomalies investigated", "Per-request purpose binding with automated revocation when the interest ends"),
    evidenceTypes: ["access_policy", "role_matrix", "access_log"],
    source: source("FERPA FAQ: disclosure to school officials (U.S. Department of Education)", "https://studentprivacy.ed.gov/faq/under-ferpa-may-educational-agency-or-institution-disclose-education-records-any-its-employees"),
  },
  {
    id: "education-deep-05", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education"],
    regulation: "FERPA", section: "34 CFR §99.32(a)(1) — record of requests and disclosures",
    question: "Does the agent keep, for each student, a record of every request for and disclosure of PII from education records, including who received it and their legitimate interest?",
    evaluationCriteria: ["Every disclosure recorded per student", "Recipient and interest captured", "Record retained with the education record", "Record available to parents or eligible students"],
    levels: levels("Disclosures by the agent are not recorded", "Some disclosures logged in system logs only", "Per-student disclosure record with recipient and interest", "Records reconciled against agent activity logs", "Tamper-evident disclosure records available on request"),
    evidenceTypes: ["disclosure_record", "activity_log", "retention_policy"],
    source: source("34 CFR §99.32 Record of requests and disclosures (CFR 2024 edition)", "https://www.govinfo.gov/content/pkg/CFR-2024-title34-vol1/xml/CFR-2024-title34-vol1-sec99-32.xml"),
  },
  {
    id: "education-deep-06", industry: "education", station: "education",
    packIds: ["k12-pm3", "infotainment"],
    regulation: "COPPA", section: "16 CFR §312.5(a)(2) — separate consent for third-party disclosure",
    question: "For users under 13, does the agent obtain separate verifiable parental consent before disclosing a child's personal information to third parties, unless the disclosure is integral to the service?",
    evaluationCriteria: ["Third-party disclosures inventoried", "Separate consent captured per disclosure purpose", "Integral disclosures justified", "Consent withdrawal stops disclosure"],
    levels: levels("Child data flows to third parties without parental consent", "One bundled consent covers collection and disclosure", "Separate verifiable parental consent gates third-party disclosure", "Disclosure inventory reconciled against consent records", "Withdrawal propagates to third parties with confirmation"),
    evidenceTypes: ["consent_record", "data_flow_inventory", "withdrawal_log"],
    source: source("16 CFR §312.5 Parental consent (CFR 2026 edition, as amended April 2025)", "https://www.govinfo.gov/content/pkg/CFR-2026-title16-vol1/xml/CFR-2026-title16-vol1-sec312-5.xml"),
  },
  {
    id: "education-deep-07", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "skills-training"],
    regulation: "EU AI Act", section: "Annex III point 3(d) — monitoring and detecting prohibited behaviour of students during tests",
    question: "If the agent proctors tests by flagging suspected cheating, is every flag treated as an allegation that a person reviews before any sanction, and are false-positive rates tracked by student group?",
    evaluationCriteria: ["Proctoring use classified against Annex III point 3(d)", "No sanction issued on an unreviewed flag", "False-positive rate measured per student group", "Students told how to dispute a flag"],
    levels: levels("Flags trigger sanctions automatically", "Flags reviewed only when a student complains", "Every flag reviewed by a person before any sanction, with the review recorded", "False-positive rates per group reported each exam period", "Flagging thresholds recalibrated from dispute outcomes under documented change control"),
    evidenceTypes: ["proctoring_flag_log", "reviewer_decision", "false_positive_report", "dispute_record"],
    source: readOn(aiActSource("annex-3", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "education-deep-08", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "skills-training", "differently-abled"],
    regulation: "EU AI Act", section: "Art. 26(11) — informing natural persons subject to an Annex III high-risk system",
    question: "When the agent makes or assists decisions about learners or applicants, are those learners (or their guardians) told that a high-risk AI system is being used on them, before the decision reaches them?",
    evaluationCriteria: ["Decision points that touch learners inventoried", "Notice given before or with the decision", "Notice reaches guardians for minors", "Notice wording reviewed for the audience's age and needs"],
    levels: levels("Learners are not told an AI system is involved", "A general statement sits in a privacy policy", "A notice is given at each decision point, including to guardians of minors", "Notice delivery is logged and checked for every decision", "Notice comprehension tested with learners, including those with disabilities"),
    evidenceTypes: ["notice_text", "decision_point_inventory", "notice_delivery_log"],
    source: readOn(aiActSource("article-26", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "education-deep-09", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education"],
    regulation: "FERPA", section: "34 CFR §99.31(a)(1)(i)(B) — outsourced party as a school official",
    question: "If the agent is run by a vendor, does the vendor qualify as a school official: it performs a function staff would otherwise do, the institution directly controls its use and maintenance of education records, and it is bound by the redisclosure limits of §99.33(a)?",
    evaluationCriteria: ["Outsourced function documented", "Contract gives the institution direct control over record use and maintenance", "Redisclosure limits under §99.33(a) bind the vendor and its model providers", "Vendor access reviewed when the function changes"],
    levels: levels("Vendor receives education records with no school-official basis", "Contract mentions FERPA in general terms only", "All three §99.31(a)(1)(i)(B) conditions are met in contract and configuration", "Vendor and sub-processor use of records is audited each year", "Record use by the vendor's agent is logged and reported to the institution on demand"),
    evidenceTypes: ["vendor_contract", "data_processing_terms", "subprocessor_list", "vendor_audit"],
    source: readOn(cfrSource(34, 1, "99.31", "Under what conditions is prior consent not required to disclose information?", 2024), REPAIR_RETRIEVED_AT),
  },
  {
    id: "education-deep-10", industry: "education", station: "education",
    packIds: ["k12-pm3", "infotainment"],
    regulation: "COPPA", section: "16 CFR §312.10 — written data retention policy and deletion",
    question: "Does the agent keep children's personal information only as long as needed for the purpose it was collected for, under a written retention policy that states the purposes, the business need and a deletion timeframe, and is disclosed in the online notice?",
    evaluationCriteria: ["Written retention policy covers agent conversations and derived data", "Purposes, business need and deletion timeframe stated", "Policy disclosed in the online notice", "Deletion is secure and verified"],
    levels: levels("Children's data kept indefinitely, including chat transcripts", "Retention policy exists but omits agent data", "Written policy covers all agent data with purposes, need and timeframe, and is published", "Deletion jobs verified against the policy each cycle", "Derived data, embeddings and backups included in verified deletion"),
    evidenceTypes: ["retention_policy", "online_notice", "deletion_job_log", "backup_inventory"],
    source: readOn(cfrSource(16, 1, "312.10", "Data retention and deletion requirements", 2026), REPAIR_RETRIEVED_AT),
  },
  // Round 2 (2026-10-04): round2/content/education/deep-questions.json, renumbered after education-deep-10;
  // its proposed 16 CFR §312.10 and Annex III 3(d) items were dropped as duplicates of education-deep-10 and -07.
  {
    id: "education-deep-11", industry: "education", station: "education",
    packIds: ["k12-pm3"],
    regulation: "COPPA", section: "16 CFR §312.8(b) — written information security program",
    question: "Does the operator maintain a written information security program for children's personal information handled by the agent, with a designated coordinator, at-least-annual risk assessments, safeguards, regular testing and monitoring, and an at-least-annual evaluation of the program?",
    evaluationCriteria: ["Program is written and names a coordinator", "Risk assessment covers the agent's data flows and third parties", "Safeguards mapped to assessed risks", "Testing and monitoring records exist", "Program evaluated at least annually"],
    levels: levels("No written program", "Program written but no coordinator or risk assessment", "Coordinator named and risk assessment covers the agent", "Safeguard testing and monitoring records kept", "Annual evaluation updates the program after changes or incidents"),
    evidenceTypes: ["security_program", "risk_assessment", "control_test_record"],
    source: readOn(cfrSource(16, 1, "312.8", "Confidentiality, security, and integrity of personal information collected from children", 2026), REPAIR_RETRIEVED_AT),
  },
  {
    id: "education-deep-12", industry: "education", station: "education",
    packIds: ["k12-pm3"],
    regulation: "PPRA", section: "34 CFR §98.4(a) — prior consent before psychological examination or testing",
    question: "Is the agent prevented from requiring a student, without prior consent, to take part in a psychological examination or test — including an AI-led wellbeing check-in — whose primary purpose is to reveal information in a PPRA-protected category?",
    evaluationCriteria: ["Protected categories detected in prompts and flows", "Consent status checked before elicitation", "Refusal or redirect path when consent is absent", "Protected responses segregated and access-logged"],
    levels: levels("Agent asks about protected categories freely", "Topic list exists but consent is not checked", "Elicitation gated on recorded consent", "Gating tested on each release with seeded prompts", "Protected responses segregated with access logs reviewed each term"),
    evidenceTypes: ["consent_record", "prompt_policy", "test_run", "access_log"],
    source: readOn(cfrSource(34, 1, "98.4", "Protection of students' privacy in examination, testing, or treatment", 2025), REPAIR_RETRIEVED_AT),
  },
  {
    id: "education-deep-13", industry: "education", station: "education",
    packIds: ["k12-pm3", "differently-abled"],
    regulation: "IDEA", section: "34 CFR §300.614 — record of access",
    question: "When a party other than a parent or an authorized employee of the participating agency — for example the agent's vendor — obtains access to special-education records through the agent, is a record kept naming the party, the date access was given and the purpose for which the party is authorized to use the records?",
    evaluationCriteria: ["Every non-exempt access through the agent recorded", "Party, date and purpose captured", "Record retrievable for parents", "Access by unauthorized parties denied and logged"],
    levels: levels("Vendor or agent access to IEP or evaluation data is not recorded", "Access is in general system logs without purpose", "Per-access record with party, date and purpose", "Records reconciled against agent activity each term", "Access records exportable to parents on request with tamper evidence"),
    evidenceTypes: ["access_record", "activity_log", "parent_export"],
    source: readOn(cfrSource(34, 2, "300.614", "Record of access", 2025), REPAIR_RETRIEVED_AT),
  },
  {
    id: "education-deep-14", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "differently-abled"],
    regulation: "ADA Title II", section: "28 CFR §35.200 — web content and mobile apps (WCAG 2.1 Level A and AA)",
    question: "For a public school or university, do the agent's web and mobile interfaces and generated content — including content provided through contractual, licensing or other arrangements — conform to WCAG 2.1 Level A and AA by the entity's compliance date (2027-04-26 for a population of 50,000 or more; 2028-04-26 for smaller entities and special districts)?",
    evaluationCriteria: ["Entity's compliance date identified", "Interfaces tested to WCAG 2.1 A/AA", "Generated content tested", "Contracted and licensed content in scope", "Remediation tracked"],
    levels: levels("No conformance evidence", "Interfaces partially tested; generated content untested", "Interfaces and generated content tested to WCAG 2.1 A/AA", "Testing runs each release with assistive-technology checks", "Conformance reports per release and defects closed before the compliance date"),
    evidenceTypes: ["conformance_report", "test_run", "remediation_ticket"],
    source: readOn(source(
      "28 CFR §35.200 Requirements for web and mobile accessibility (CFR 2025 edition)",
      "https://www.govinfo.gov/content/pkg/CFR-2025-title28-vol1/xml/CFR-2025-title28-vol1-sec35-200.xml",
      "The 2025 edition shows the original dates (2026-04-24 and 2027-04-26); the interim final rule FR 2026-07663 (govinfo FR-2026-04-20) extended them to 2027-04-26 and 2028-04-26 without changing the WCAG 2.1 Level AA standard. Both read 2026-10-04.",
      true,
    ), REPAIR_RETRIEVED_AT),
  },
  {
    id: "education-deep-15", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "skills-training"],
    regulation: "EU AI Act", section: "Art. 26(6) — deployer retention of automatically generated logs",
    question: "Does the deploying institution keep the logs automatically generated by each high-risk education AI system under its control for at least six months, or longer where Union or national law requires?",
    evaluationCriteria: ["High-risk education uses inventoried", "Retention period configured at six months or more", "Longer legal retention identified where applicable", "Retention verified"],
    levels: levels("Logs not retained or provider defaults unknown", "Retention set for some uses only", "Six-month minimum configured for all high-risk uses", "Retention verified each term", "Retention policy tied to a legal-retention register with alerts on deletion before expiry"),
    evidenceTypes: ["retention_config", "use_inventory", "log_sample"],
    source: readOn(aiActSource("article-26", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "education-deep-16", industry: "education", station: "education",
    packIds: ["higher-education"],
    regulation: "Title IX", section: "34 CFR §106.45(b)(7)(i) — written determination by a decision-maker who is not the Coordinator or investigator",
    question: "If the agent supports Title IX grievance processing, is every written determination issued by a human decision-maker who is not the Title IX Coordinator or an investigator, with the agent limited to support functions and the records kept for seven years (§106.45(b)(10))?",
    evaluationCriteria: ["Agent cannot issue determinations", "Decision-maker role separated from coordinator and investigator", "Determination authored and signed by the decision-maker", "Records kept for seven years"],
    levels: levels("Agent output is used as the determination", "A person signs but role separation is not enforced", "Role separation enforced and agent limited to support", "Records retained seven years with access logs", "Periodic audit confirms no agent-authored determinations"),
    evidenceTypes: ["role_matrix", "determination_record", "retention_policy"],
    source: readOn(source(
      "34 CFR §106.45 Grievance process for formal complaints of sexual harassment (CFR 2023 edition)",
      "https://www.govinfo.gov/content/pkg/CFR-2023-title34-vol1/xml/CFR-2023-title34-vol1-sec106-45.xml",
      "The 2023 edition holds the text in force before 2024-04-29, which FR 2026-19929 (govinfo FR-2026-09-29, effective 2026-09-29) restored after repealing the vacated 2024 rule. Both read 2026-10-04.",
      true,
    ), REPAIR_RETRIEVED_AT),
  },
];
