/**
 * Hand-written deep questions. Education station: EU AI Act Annex III point 3 and Art. 5/26, FERPA (34 CFR Part 99) and COPPA (16 CFR Part 312).
 * Each question anchors one provision and lists the industry packs it applies to.
 */

import { AI_ACT_DESK, OMNIBUS_DATES, aiActSource, cfrSource, levels, source, type DeepIndustryQuestion } from "./shared.js";

export const DEEP_EDUCATION_QUESTIONS: DeepIndustryQuestion[] = [
  {
    id: "education-deep-01", industry: "education", station: "education",
    packIds: ["higher-education", "skills-training", "k12-pm3"],
    regulation: "EU AI Act", section: "Annex III point 3(a) — access, admission and assignment",
    question: "Where the agent determines access or admission to, or assigns learners to, an educational or vocational training institution, is it run as an Annex III high-risk system with human review of every adverse decision and a log of the inputs behind it?",
    evaluationCriteria: ["Use case classified against Annex III point 3(a)", "Adverse decisions reviewed by a named person", "Decision inputs logged per applicant", "Applicant can contest the outcome"],
    levels: levels("Admission decisions are fully automated and unlogged", "Classification noted but reviews are ad hoc", "Every adverse decision is human-reviewed with logged inputs", "Review quality is sampled and disparities by cohort are measured", "Contest outcomes feed back into a monitored, documented risk-management loop"),
    evidenceTypes: ["risk_classification", "reviewer_signoff", "decision_log", "appeal_record"],
    source: source("Regulation (EU) 2024/1689 Annex III (AI Act Service Desk)", `${AI_ACT_DESK}/annex-3`),
  },
  {
    id: "education-deep-02", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "skills-training", "specialized-education"],
    regulation: "EU AI Act", section: "Annex III point 3(b)-(c) — evaluating learning outcomes and level of education",
    question: "When the agent evaluates learning outcomes or assesses the level of education a learner will receive, are its accuracy and error rates measured per cohort and are educators able to override and record the override?",
    evaluationCriteria: ["Assessment use cases inventoried", "Accuracy measured per learner cohort", "Educator override path exists", "Overrides recorded with reason"],
    levels: levels("Agent grades or places learners with no accuracy evidence", "Spot checks of outputs without cohort breakdown", "Cohort-level accuracy reported and educator overrides logged", "Override rates trigger re-validation of the model", "Independent validation and published limitations for each assessment use"),
    evidenceTypes: ["validation_report", "cohort_metrics", "override_log"],
    source: source("Regulation (EU) 2024/1689 Annex III (AI Act Service Desk)", `${AI_ACT_DESK}/annex-3`),
  },
  {
    id: "education-deep-03", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "skills-training", "specialized-education", "differently-abled"],
    regulation: "EU AI Act", section: "Art. 5(1)(f) — emotion inference in education institutions",
    question: "Is the agent technically prevented from inferring learners' emotions in an education institution, with any medical or safety exception documented and approved?",
    evaluationCriteria: ["Emotion-inference features disabled in education deployments", "Exceptions limited to medical or safety reasons", "Exception approvals recorded", "Configuration drift detected"],
    levels: levels("Emotion inference is available or in use", "Policy forbids it but nothing enforces it", "Feature is disabled by configuration and exceptions are approved in writing", "Deployment checks block re-enabling and alert on drift", "Prohibited-practice screening runs on every release with signed results"),
    evidenceTypes: ["feature_flag_config", "exception_register", "release_check"],
    source: source("Regulation (EU) 2024/1689 Art. 5 (AI Act Service Desk)", `${AI_ACT_DESK}/article-5`),
  },
  {
    id: "education-deep-04", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education"],
    regulation: "FERPA", section: "34 CFR §99.31(a)(1) — school officials with legitimate educational interest",
    question: "Does the agent release education-record PII only to school officials whose legitimate educational interest has been determined, using access controls rather than policy alone?",
    evaluationCriteria: ["Legitimate-interest criteria defined", "Access scoped per official role", "Agent requests carry the requesting official", "Denied requests logged"],
    levels: levels("Any staff account can retrieve any student record through the agent", "Role list exists but the agent does not check it", "Agent enforces role-scoped access tied to legitimate educational interest", "Access is reviewed each term and anomalies investigated", "Per-request purpose binding with automated revocation when the interest ends"),
    evidenceTypes: ["access_policy", "role_matrix", "access_log"],
    source: source("FERPA FAQ: disclosure to school officials (U.S. Department of Education)", "https://studentprivacy.ed.gov/faq/under-ferpa-may-educational-agency-or-institution-disclose-education-records-any-its-employees"),
  },
  {
    id: "education-deep-05", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education"],
    regulation: "FERPA", section: "34 CFR §99.32(a)(1) — record of requests and disclosures",
    question: "Does the agent keep, for each student, a record of every request for and disclosure of PII from education records, including who received it and their legitimate interest?",
    evaluationCriteria: ["Every disclosure recorded per student", "Recipient and interest captured", "Record retained with the education record", "Record available to parents or eligible students"],
    levels: levels("Disclosures by the agent are not recorded", "Some disclosures logged in system logs only", "Per-student disclosure record with recipient and interest", "Records reconciled against agent activity logs", "Tamper-evident disclosure records available on request"),
    evidenceTypes: ["disclosure_record", "activity_log", "retention_policy"],
    source: source("34 CFR §99.32 Record of requests and disclosures (CFR 2024 edition)", "https://www.govinfo.gov/content/pkg/CFR-2024-title34-vol1/xml/CFR-2024-title34-vol1-sec99-32.xml"),
  },
  {
    id: "education-deep-06", industry: "education", station: "education",
    packIds: ["k12-pm3", "infotainment"],
    regulation: "COPPA", section: "16 CFR §312.5(a)(2) — separate consent for third-party disclosure",
    question: "For users under 13, does the agent obtain separate verifiable parental consent before disclosing a child's personal information to third parties, unless the disclosure is integral to the service?",
    evaluationCriteria: ["Third-party disclosures inventoried", "Separate consent captured per disclosure purpose", "Integral disclosures justified", "Consent withdrawal stops disclosure"],
    levels: levels("Child data flows to third parties without parental consent", "One bundled consent covers collection and disclosure", "Separate verifiable parental consent gates third-party disclosure", "Disclosure inventory reconciled against consent records", "Withdrawal propagates to third parties with confirmation"),
    evidenceTypes: ["consent_record", "data_flow_inventory", "withdrawal_log"],
    source: source("16 CFR §312.5 Parental consent (CFR 2026 edition, as amended April 2025)", "https://www.govinfo.gov/content/pkg/CFR-2026-title16-vol1/xml/CFR-2026-title16-vol1-sec312-5.xml"),
  },
  {
    id: "education-deep-07", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "skills-training"],
    regulation: "EU AI Act", section: "Annex III point 3(d) — monitoring and detecting prohibited behaviour of students during tests",
    question: "If the agent proctors tests by flagging suspected cheating, is every flag treated as an allegation that a person reviews before any sanction, and are false-positive rates tracked by student group?",
    evaluationCriteria: ["Proctoring use classified against Annex III point 3(d)", "No sanction issued on an unreviewed flag", "False-positive rate measured per student group", "Students told how to dispute a flag"],
    levels: levels("Flags trigger sanctions automatically", "Flags reviewed only when a student complains", "Every flag reviewed by a person before any sanction, with the review recorded", "False-positive rates per group reported each exam period", "Flagging thresholds recalibrated from dispute outcomes under documented change control"),
    evidenceTypes: ["proctoring_flag_log", "reviewer_decision", "false_positive_report", "dispute_record"],
    source: aiActSource("annex-3", OMNIBUS_DATES),
  },
  {
    id: "education-deep-08", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education", "skills-training", "differently-abled"],
    regulation: "EU AI Act", section: "Art. 26(11) — informing natural persons subject to an Annex III high-risk system",
    question: "When the agent makes or assists decisions about learners or applicants, are those learners (or their guardians) told that a high-risk AI system is being used on them, before the decision reaches them?",
    evaluationCriteria: ["Decision points that touch learners inventoried", "Notice given before or with the decision", "Notice reaches guardians for minors", "Notice wording reviewed for the audience's age and needs"],
    levels: levels("Learners are not told an AI system is involved", "A general statement sits in a privacy policy", "A notice is given at each decision point, including to guardians of minors", "Notice delivery is logged and checked for every decision", "Notice comprehension tested with learners, including those with disabilities"),
    evidenceTypes: ["notice_text", "decision_point_inventory", "notice_delivery_log"],
    source: aiActSource("article-26", OMNIBUS_DATES),
  },
  {
    id: "education-deep-09", industry: "education", station: "education",
    packIds: ["k12-pm3", "higher-education"],
    regulation: "FERPA", section: "34 CFR §99.31(a)(1)(i)(B) — outsourced party as a school official",
    question: "If the agent is run by a vendor, does the vendor qualify as a school official: it performs a function staff would otherwise do, the institution directly controls its use and maintenance of education records, and it is bound by the redisclosure limits of §99.33(a)?",
    evaluationCriteria: ["Outsourced function documented", "Contract gives the institution direct control over record use and maintenance", "Redisclosure limits under §99.33(a) bind the vendor and its model providers", "Vendor access reviewed when the function changes"],
    levels: levels("Vendor receives education records with no school-official basis", "Contract mentions FERPA in general terms only", "All three §99.31(a)(1)(i)(B) conditions are met in contract and configuration", "Vendor and sub-processor use of records is audited each year", "Record use by the vendor's agent is logged and reported to the institution on demand"),
    evidenceTypes: ["vendor_contract", "data_processing_terms", "subprocessor_list", "vendor_audit"],
    source: cfrSource(34, 1, "99.31", "Under what conditions is prior consent not required to disclose information?", 2024),
  },
  {
    id: "education-deep-10", industry: "education", station: "education",
    packIds: ["k12-pm3", "infotainment"],
    regulation: "COPPA", section: "16 CFR §312.10 — written data retention policy and deletion",
    question: "Does the agent keep children's personal information only as long as needed for the purpose it was collected for, under a written retention policy that states the purposes, the business need and a deletion timeframe, and is disclosed in the online notice?",
    evaluationCriteria: ["Written retention policy covers agent conversations and derived data", "Purposes, business need and deletion timeframe stated", "Policy disclosed in the online notice", "Deletion is secure and verified"],
    levels: levels("Children's data kept indefinitely, including chat transcripts", "Retention policy exists but omits agent data", "Written policy covers all agent data with purposes, need and timeframe, and is published", "Deletion jobs verified against the policy each cycle", "Derived data, embeddings and backups included in verified deletion"),
    evidenceTypes: ["retention_policy", "online_notice", "deletion_job_log", "backup_inventory"],
    source: cfrSource(16, 1, "312.10", "Data retention and deletion requirements", 2026),
  },];
