/**
 * Hand-written deep questions. Environment station: critical-infrastructure supply (Annex III point 2), NIS2, the CER Directive, AI Act provider/deployer duties, and (from 11) NERC CIP, FDA traceability, SDWA 1433, green claims, EUDR and CRA reporting.
 * Each question anchors one provision and lists the industry packs it applies to.
 */

import { AI_ACT_DESK, OMNIBUS_DATES, aiActSource, levels, source, readOn, REPAIR_RETRIEVED_AT, type DeepIndustryQuestion } from "./shared.js";

export const DEEP_ENVIRONMENT_QUESTIONS: DeepIndustryQuestion[] = [
  {
    id: "environment-deep-01", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "EU AI Act", section: "Annex III point 2 — safety components in water, gas, heating or electricity supply",
    question: "Where the agent acts as a safety component in the supply of water, gas, heating or electricity, can operators stop it and fall back to a manual mode, and is that fallback tested?",
    evaluationCriteria: ["Safety-component role identified", "Operator stop and manual fallback exist", "Fallback tested on a schedule", "Test results retained"],
    levels: levels("Agent controls supply operations with no stop or fallback", "Fallback exists on paper only", "Operator stop and manual fallback tested at least annually", "Fallback drills after every material model change", "Fallback performance tracked as a safety KPI with independent review"),
    evidenceTypes: ["safety_case", "fallback_drill", "operator_procedure"],
    source: source("Regulation (EU) 2024/1689 Annex III (AI Act Service Desk)", `${AI_ACT_DESK}/annex-3`, OMNIBUS_DATES, true),
  },
  {
    id: "environment-deep-02", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "NIS2", section: "Art. 21 — cybersecurity risk-management measures (supply chain security)",
    question: "Are the agent and its model, data and tool suppliers covered by the entity's NIS2 risk-management measures, including supply-chain security and vulnerability handling?",
    evaluationCriteria: ["Agent suppliers in the supplier register", "Supplier security requirements contracted", "Vulnerability handling covers agent components", "Measures reviewed by management"],
    levels: levels("Agent suppliers are outside the security programme", "Suppliers listed without security requirements", "Supplier requirements and vulnerability handling cover the agent stack", "Supplier assurance evidence collected and reviewed", "Continuous supplier risk monitoring with management sign-off"),
    evidenceTypes: ["supplier_register", "contract_clause", "vulnerability_log"],
    source: source("NIS2 Directive FAQs (European Commission)", "https://digital-strategy.ec.europa.eu/en/faqs/directive-measures-high-common-level-cybersecurity-across-union-nis2-directive-faqs",
      "FAQ confirms the risk-management measures include supply chain security; the article number (21) was not read from the Directive text."),
  },
  {
    id: "environment-deep-03", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "NIS2", section: "Art. 23(4) — 24-hour early warning, 72-hour notification, one-month final report",
    question: "Can a significant incident involving the agent be reported to the CSIRT or competent authority within the NIS2 timeline: early warning within 24 hours, notification within 72 hours, and a final report within one month?",
    evaluationCriteria: ["Agent incidents classified for significance", "24h early-warning path rehearsed", "72h notification content prepared from agent logs", "Final report template covers root cause"],
    levels: levels("No path to report agent incidents", "Reporting depends on manual log digging", "Rehearsed 24h/72h/one-month reporting using agent telemetry", "Reporting drills timed and gaps remediated", "Incident evidence assembled automatically with signed timelines"),
    evidenceTypes: ["incident_runbook", "notification_record", "drill_timing"],
    source: source("NIS2 Directive FAQs (European Commission)", "https://digital-strategy.ec.europa.eu/en/faqs/directive-measures-high-common-level-cybersecurity-across-union-nis2-directive-faqs",
      "FAQ confirms the 24-hour, 72-hour and one-month timelines; the article reference (23(4)) comes from europa.eu search results, not a read of the Directive text."),
  },
  {
    id: "environment-deep-04", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation", "farm-to-fork"],
    regulation: "CER Directive", section: "Art. 13 — resilience measures and resilience plan",
    question: "Is the agent included in the critical entity's resilience plan, with technical, security and organisational measures for its failure, misuse or loss?",
    evaluationCriteria: ["Agent listed in the resilience plan", "Failure and misuse scenarios assessed", "Measures assigned to owners", "Plan reviewed after incidents"],
    levels: levels("Agent is absent from resilience planning", "Mentioned without scenarios or owners", "Scenarios, measures and owners recorded in the resilience plan", "Measures exercised and lessons fed back", "Resilience of the agent measured and reported to the competent authority on request"),
    evidenceTypes: ["resilience_plan", "risk_assessment", "exercise_report"],
    source: source("Critical infrastructure resilience at EU level (European Commission, Migration and Home Affairs)", "https://home-affairs.ec.europa.eu/policies/internal-security/counter-terrorism-and-radicalisation/protection/critical-infrastructure-resilience-eu-level_en",
      "Commission page confirms risk assessments, resilience measures and incident notification; the article number (13) comes from a EUR-Lex search result, not a full read of Directive (EU) 2022/2557."),
  },
  {
    id: "environment-deep-05", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation", "farm-to-fork", "material-to-machines", "source-to-sustenance"],
    regulation: "EU AI Act", section: "Art. 73(3) — two-day serious incident report for critical infrastructure disruption",
    question: "If the agent causes a serious and irreversible disruption of critical infrastructure, can the provider or deployer report it within two days of becoming aware?",
    evaluationCriteria: ["Serious-incident criteria mapped to Art. 3(49)(b)", "Two-day reporting path owned", "Causal-link analysis procedure", "Market surveillance authority contacts current"],
    levels: levels("No serious-incident reporting path", "Generic incident process without AI Act timelines", "Two-day path defined with owners and authority contacts", "Path rehearsed and timed", "Causal analysis and report drafts generated from preserved agent evidence"),
    evidenceTypes: ["incident_procedure", "authority_contacts", "drill_timing"],
    source: source("Regulation (EU) 2024/1689 Art. 73 (AI Act Service Desk)", `${AI_ACT_DESK}/article-73`, OMNIBUS_DATES, true),
  },
  {
    id: "environment-deep-06", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation", "farm-to-fork", "material-to-machines", "source-to-sustenance"],
    regulation: "EU AI Act", section: "Art. 9(2) — risk management as a continuous iterative process over the lifecycle",
    question: "Is there a documented risk-management process for the agent that is rerun through its lifecycle, covering foreseeable misuse in the supply operation and risks surfaced by post-market monitoring, not only the risks known at launch?",
    evaluationCriteria: ["Known and foreseeable risks to health, safety and fundamental rights identified", "Foreseeable misuse of the agent analysed", "Post-market data feeds risk re-evaluation", "Targeted measures adopted and tested"],
    levels: levels("No documented risk analysis for the agent", "One-off risk assessment at launch", "Lifecycle risk process with misuse analysis and owned measures", "Post-market findings reopen the risk assessment on a set trigger", "Residual risk tracked against acceptance criteria and tested after each change"),
    evidenceTypes: ["risk_register", "misuse_analysis", "test_report", "risk_acceptance"],
    source: readOn(aiActSource("article-9", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-07", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "EU AI Act", section: "Art. 12(1)-(2) — automatic event logging over the system lifetime",
    question: "Does the agent automatically log the events needed to spot situations where it could present a risk, to support post-market monitoring, and to let the operator monitor it, for its whole lifetime?",
    evaluationCriteria: ["Logging is automatic, not opt-in", "Logged events chosen to identify risk situations", "Logs usable for post-market monitoring", "Logs retained across model and software versions"],
    levels: levels("No event logs, or logs that operators can switch off", "Application logs kept without a defined event set", "A defined event set logged automatically for the system lifetime", "Logs used routinely in operator monitoring and incident review", "Logs integrity-protected and linked to the model version that produced each event"),
    evidenceTypes: ["logging_specification", "log_sample", "retention_config"],
    source: readOn(aiActSource("article-12", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-08", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "EU AI Act", section: "Art. 15(5) — resilience against attempts to alter use, outputs or performance",
    question: "Is the agent protected against tampering with its sensor feeds, training data or model, such as data poisoning or adversarial inputs that could change setpoints or dispatch decisions?",
    evaluationCriteria: ["AI-specific threats in the threat model (data poisoning, model poisoning, adversarial examples)", "Sensor and telemetry inputs validated", "Model artefacts integrity-checked", "Adversarial testing performed"],
    levels: levels("No AI-specific security controls", "General IT security only", "AI-specific threats modelled and input and model integrity controls in place", "Adversarial testing run before each release", "Attack detection in operation with tested containment"),
    evidenceTypes: ["threat_model", "input_validation_config", "model_integrity_check", "adversarial_test_report"],
    source: readOn(aiActSource("article-15", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-09", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation", "farm-to-fork"],
    regulation: "EU AI Act", section: "Art. 26(1)-(2) — deployer use per instructions and competent human oversight",
    question: "As the operator deploying the agent, do you use it within the provider's instructions for use and assign oversight to named staff who have the competence, training, authority and support to act on it?",
    evaluationCriteria: ["Instructions for use mapped to operating procedures", "Oversight staff named per site or shift", "Training and authority to intervene documented", "Use outside the instructions detected"],
    levels: levels("Agent used with no reference to the instructions for use", "Instructions filed but oversight roles unassigned", "Oversight assigned to trained staff with authority, and use follows the instructions", "Oversight competence re-checked after model changes", "Out-of-instruction use is detected automatically and escalated"),
    evidenceTypes: ["operating_procedure", "oversight_roster", "training_record"],
    source: readOn(aiActSource("article-26", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-10", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "EU AI Act", section: "Art. 14(4)(b) — awareness of automation bias",
    question: "Are control-room operators equipped to resist automation bias, for example by seeing the agent's confidence and inputs and by being measured on how often they accept its recommendations unchanged?",
    evaluationCriteria: ["Operators trained on automation bias", "Confidence and key inputs shown with each recommendation", "Acceptance rate of recommendations measured", "Unchallenged acceptance reviewed"],
    levels: levels("Recommendations applied without operator scrutiny", "Training mentions over-reliance once", "Confidence and inputs shown, and acceptance rates measured", "High acceptance with low challenge triggers review", "Operator challenge quality tested with seeded faulty recommendations"),
    evidenceTypes: ["training_record", "hmi_capture", "acceptance_rate_report"],
    source: readOn(aiActSource("article-14", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-11", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility"],
    regulation: "NERC CIP-015-1", section: "R1-R3 — internal network security monitoring (detect and evaluate anomalies, retain and protect INSM data)",
    question: "Is the agent's network activity inside the electronic security perimeters of high impact BES Cyber Systems and medium impact BES Cyber Systems with External Routable Connectivity visible to the entity's internal network security monitoring, with anomalies involving the agent evaluated, and the related monitoring data retained and protected?",
    evaluationCriteria: ["Agent hosts and traffic included in INSM network data feeds", "Detection baseline includes agent traffic", "Anomalies involving the agent evaluated with recorded action", "INSM data retained until action is complete and protected from deletion or modification"],
    levels: levels("Agent traffic is outside INSM data feeds", "Agent traffic is collected but not baselined", "Agent traffic is baselined and anomalies are evaluated with recorded actions", "Agent action logs are correlated with INSM detections and retention and protection are evidenced", "Correlation, retention and protection are tested on a schedule with results reviewed"),
    evidenceTypes: ["insm_feed_config", "anomaly_evaluation_record", "retention_config", "integrity_protection_evidence"],
    source: readOn(source("FERC Order No. 907: Critical Infrastructure Protection Reliability Standard CIP-015-1 (Federal Register 2025-12309, govinfo)", "https://www.govinfo.gov/content/pkg/FR-2025-07-02/html/2025-12309.htm",
      "Final rule approves CIP-015-1 (effective 2 Sep 2025) for high impact BES Cyber Systems with and without External Routable Connectivity and medium impact BES Cyber Systems with it: R1 monitor, detect and evaluate anomalous activity, R2 retain INSM data, R3 protect INSM data. The NERC implementation plan (compliance date) was not read.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-12", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility"],
    regulation: "NERC CIP-013-2", section: "R1 Part 1.2.5 — verification of software integrity and authenticity of vendor software and patches",
    question: "Before a vendor-supplied model, tool or software update reaches a BES Cyber System or its EACMS/PACS through the agent, is its integrity and authenticity verified and recorded?",
    evaluationCriteria: ["Agent models, tools and software are in the CIP-013 plan's vendor scope", "Integrity and authenticity check defined per artifact type", "Check result recorded before deployment", "Failed checks block deployment"],
    levels: levels("Updates deploy without verification", "Verification exists for some vendors only", "Every update is verified and the result recorded before deployment", "Failed verifications block deployment and open a vendor notification", "Verification evidence is sampled in each plan review with exceptions tracked"),
    evidenceTypes: ["software_hash_record", "signature_verification_log", "deployment_gate_record", "vendor_notification"],
    source: readOn(source("FERC Order No. 912: Supply Chain Risk Management Reliability Standards Revisions (Federal Register 2025-18394, govinfo)", "https://www.govinfo.gov/content/pkg/FR-2025-09-23/html/2025-18394.htm",
      "The order (effective 24 Nov 2025) describes CIP-013-2 as the currently effective supply chain standard and software integrity and authenticity as one of its objectives, and directs further revisions. The Part 1.2.5 number is from the NERC CIP-013-2 standard PDF read by the round-2 content author on 2026-10-04 (round2/content/environment/deep-questions.json), not from this record.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-13", industry: "environment", station: "environment",
    packIds: ["farm-to-fork"],
    regulation: "FDA Food Traceability Rule", section: "21 CFR 1.1455 — records to FDA within 24 hours, electronic sortable spreadsheet",
    question: "For Food Traceability List foods, can the operator produce from the agent's records an electronic sortable spreadsheet of the Key Data Elements for the requested Critical Tracking Events within 24 hours of an FDA request?",
    evaluationCriteria: ["Food Traceability List coverage determined", "KDEs captured per applicable CTE", "Spreadsheet export tested against the 24-hour window", "Compliance date tracked"],
    levels: levels("No KDE/CTE records", "KDEs for some CTEs only", "KDEs for all applicable CTEs with a tested 24-hour export", "Export drills timed and gaps remediated", "Export completeness checked automatically against lot movements"),
    evidenceTypes: ["kde_record", "cte_log", "export_drill_timing", "ftl_scope_list"],
    source: readOn(source("21 CFR §1.1455 Records availability (CFR 2025 edition, govinfo)", "https://www.govinfo.gov/content/pkg/CFR-2025-title21-vol1/xml/CFR-2025-title21-vol1-sec1-1455.xml",
      "Section confirms records within 24 hours of an FDA request and the electronic sortable spreadsheet for the §§1.1325-1.1350 information. The 20 Jul 2028 date is from the FDA FSMA traceability page read by the round-2 content author on 2026-10-04, not from this section.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-14", industry: "environment", station: "environment",
    packIds: ["sip-to-sanitation"],
    regulation: "SDWA Section 1433 (42 U.S.C. 300i-2)", section: "(a)(1)(A)(ii) automated systems in the risk and resilience assessment; (b)(1) cybersecurity in the emergency response plan",
    question: "Does the water system's risk and resilience assessment cover the automated systems the agent operates, including their security, and does the emergency response plan include cybersecurity strategies and a tested fallback for agent failure or compromise?",
    evaluationCriteria: ["Agent-operated automated systems listed in the RRA", "Security of those systems assessed", "ERP includes cybersecurity strategies covering the agent", "Fallback exercised and certification dates tracked"],
    levels: levels("Agent and its systems absent from RRA/ERP", "Agent listed without scenarios", "Agent failure and compromise scenarios assessed and ERP fallback defined", "Fallback exercised with results recorded", "RRA/ERP updated after each material agent change with certification dates tracked"),
    evidenceTypes: ["risk_resilience_assessment", "emergency_response_plan", "exercise_report", "certification_record"],
    source: readOn(source("42 U.S.C. 300i-2 Community water system risk and resilience (U.S. Code 2023, govinfo)", "https://www.govinfo.gov/content/pkg/USCODE-2023-title42/html/USCODE-2023-title42-chap6A-subchapXII-partD-sec300i-2.htm",
      "Confirms systems serving more than 3,300 persons; the assessment covers electronic, computer or other automated systems including their security; the emergency response plan includes physical security and cybersecurity strategies. Certification deadlines by population band are from the EPA AWIA page read by the round-2 content author, not from this text.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-15", industry: "environment", station: "environment",
    packIds: ["weave-to-wear"],
    regulation: "Directive (EU) 2024/825", section: "Annex I points 2a and 4a of Directive 2005/29/EC as inserted; applies from 27 Sep 2026 (Art. 4(1))",
    question: "Does the agent refuse to generate generic environmental claims it cannot substantiate with recognised excellent environmental performance, and sustainability labels that are not based on a certification scheme or established by public authorities?",
    evaluationCriteria: ["Claim types in generated content inventoried", "Each claim linked to substantiating evidence or scheme", "Unsubstantiated generic claims blocked", "Decisions logged for review"],
    levels: levels("Claims generated without checks", "Keyword filter only", "Every claim linked to evidence or scheme before release", "Blocked claims reviewed and filter gaps fixed", "Claim evidence sampled by an independent reviewer"),
    evidenceTypes: ["claim_register", "evidence_link", "block_log", "review_record"],
    source: readOn(source("Directive (EU) 2024/825 (EUR-Lex, CELEX 32024L0825)", "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32024L0825"), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-16", industry: "environment", station: "environment",
    packIds: ["farm-to-fork", "source-to-sustenance"],
    regulation: "Regulation (EU) 2023/1115 as amended by Regulation (EU) 2025/2650", section: "Downstream operators and traders: collect and retain the upstream declaration reference; five-year records",
    question: "When the agent handles products as a downstream operator or trader, does it collect and retain the reference number of the primary operator's declaration and keep supplier and recipient records for five years?",
    evaluationCriteria: ["Operator role determined per product", "Upstream reference captured for every relevant product", "Supplier and recipient details retained", "Five-year retention enforced"],
    levels: levels("No reference numbers kept", "References kept for some products", "References kept for every relevant product with supplier and recipient details", "Retention enforced and gaps reported", "Reference validity checked against the Information System"),
    evidenceTypes: ["declaration_reference", "supplier_record", "recipient_record", "retention_policy"],
    source: readOn(source("European Commission Access2Markets: Delay until December 2026 and other developments in the implementation of the EUDR", "https://trade.ec.europa.eu/access-to-markets/en/news/delay-until-december-2026-and-other-developments-implementation-eudr-regulation",
      "Confirms Regulation (EU) 2025/2650; application 30 Dec 2026 (downstream operators, traders, large and medium) and 30 Jun 2027 (natural persons, micro); downstream operators and traders collect and retain the primary operator's reference number; five-year records. Article numbers are not on the page.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-17", industry: "environment", station: "environment",
    packIds: ["material-to-machines"],
    regulation: "Cyber Resilience Act (Regulation (EU) 2024/2847)", section: "Manufacturer reporting of actively exploited vulnerabilities and severe incidents (from 11 Sep 2026)",
    question: "Can the manufacturer of a connected product the agent runs on or manages send a 24-hour early warning, a 72-hour notification and the final report for an actively exploited vulnerability or severe incident through the CRA Single Reporting Platform?",
    evaluationCriteria: ["Reportable-event criteria defined for agent-managed products", "24h and 72h paths rehearsed", "Final-report content assembled from logs", "Reports retained"],
    levels: levels("No reporting path", "Manual path, untested", "Rehearsed 24h/72h path with owners", "Drills timed and gaps remediated", "Report drafts assembled from preserved product and agent evidence"),
    evidenceTypes: ["reporting_runbook", "srp_submission_record", "drill_timing", "final_report"],
    source: readOn(source("European Commission (DG CNECT): CRA reporting obligations", "https://digital-strategy.ec.europa.eu/en/policies/cra-reporting",
      "Confirms reporting from 11 Sep 2026: 24-hour early warning, 72-hour notification, final report 14 days after a corrective measure (vulnerabilities) or one month after the notification (incidents), via the Single Reporting Platform. The article number was not confirmed, so none is cited.", true), REPAIR_RETRIEVED_AT),
  },
];
