/**
 * Hand-written deep questions. Environment station: critical-infrastructure supply (Annex III point 2), NIS2, the CER Directive and AI Act provider/deployer duties.
 * Each question anchors one provision and lists the industry packs it applies to.
 */

import { AI_ACT_DESK, OMNIBUS_DATES, aiActSource, levels, source, readOn, REPAIR_RETRIEVED_AT, type DeepIndustryQuestion } from "./shared.js";

export const DEEP_ENVIRONMENT_QUESTIONS: DeepIndustryQuestion[] = [
  {
    id: "environment-deep-01", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "EU AI Act", section: "Annex III point 2 — safety components in water, gas, heating or electricity supply",
    question: "Where the agent acts as a safety component in the supply of water, gas, heating or electricity, can operators stop it and fall back to a manual mode, and is that fallback tested?",
    evaluationCriteria: ["Safety-component role identified", "Operator stop and manual fallback exist", "Fallback tested on a schedule", "Test results retained"],
    levels: levels("Agent controls supply operations with no stop or fallback", "Fallback exists on paper only", "Operator stop and manual fallback tested at least annually", "Fallback drills after every material model change", "Fallback performance tracked as a safety KPI with independent review"),
    evidenceTypes: ["safety_case", "fallback_drill", "operator_procedure"],
    source: source("Regulation (EU) 2024/1689 Annex III (AI Act Service Desk)", `${AI_ACT_DESK}/annex-3`, OMNIBUS_DATES, true),
  },
  {
    id: "environment-deep-02", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "NIS2", section: "Art. 21 — cybersecurity risk-management measures (supply chain security)",
    question: "Are the agent and its model, data and tool suppliers covered by the entity's NIS2 risk-management measures, including supply-chain security and vulnerability handling?",
    evaluationCriteria: ["Agent suppliers in the supplier register", "Supplier security requirements contracted", "Vulnerability handling covers agent components", "Measures reviewed by management"],
    levels: levels("Agent suppliers are outside the security programme", "Suppliers listed without security requirements", "Supplier requirements and vulnerability handling cover the agent stack", "Supplier assurance evidence collected and reviewed", "Continuous supplier risk monitoring with management sign-off"),
    evidenceTypes: ["supplier_register", "contract_clause", "vulnerability_log"],
    source: source("NIS2 Directive FAQs (European Commission)", "https://digital-strategy.ec.europa.eu/en/faqs/directive-measures-high-common-level-cybersecurity-across-union-nis2-directive-faqs",
      "FAQ confirms the risk-management measures include supply chain security; the article number (21) was not read from the Directive text."),
  },
  {
    id: "environment-deep-03", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "NIS2", section: "Art. 23(4) — 24-hour early warning, 72-hour notification, one-month final report",
    question: "Can a significant incident involving the agent be reported to the CSIRT or competent authority within the NIS2 timeline: early warning within 24 hours, notification within 72 hours, and a final report within one month?",
    evaluationCriteria: ["Agent incidents classified for significance", "24h early-warning path rehearsed", "72h notification content prepared from agent logs", "Final report template covers root cause"],
    levels: levels("No path to report agent incidents", "Reporting depends on manual log digging", "Rehearsed 24h/72h/one-month reporting using agent telemetry", "Reporting drills timed and gaps remediated", "Incident evidence assembled automatically with signed timelines"),
    evidenceTypes: ["incident_runbook", "notification_record", "drill_timing"],
    source: source("NIS2 Directive FAQs (European Commission)", "https://digital-strategy.ec.europa.eu/en/faqs/directive-measures-high-common-level-cybersecurity-across-union-nis2-directive-faqs",
      "FAQ confirms the 24-hour, 72-hour and one-month timelines; the article reference (23(4)) comes from europa.eu search results, not a read of the Directive text."),
  },
  {
    id: "environment-deep-04", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation", "farm-to-fork"],
    regulation: "CER Directive", section: "Art. 13 — resilience measures and resilience plan",
    question: "Is the agent included in the critical entity's resilience plan, with technical, security and organisational measures for its failure, misuse or loss?",
    evaluationCriteria: ["Agent listed in the resilience plan", "Failure and misuse scenarios assessed", "Measures assigned to owners", "Plan reviewed after incidents"],
    levels: levels("Agent is absent from resilience planning", "Mentioned without scenarios or owners", "Scenarios, measures and owners recorded in the resilience plan", "Measures exercised and lessons fed back", "Resilience of the agent measured and reported to the competent authority on request"),
    evidenceTypes: ["resilience_plan", "risk_assessment", "exercise_report"],
    source: source("Critical infrastructure resilience at EU level (European Commission, Migration and Home Affairs)", "https://home-affairs.ec.europa.eu/policies/internal-security/counter-terrorism-and-radicalisation/protection/critical-infrastructure-resilience-eu-level_en",
      "Commission page confirms risk assessments, resilience measures and incident notification; the article number (13) comes from a EUR-Lex search result, not a full read of Directive (EU) 2022/2557."),
  },
  {
    id: "environment-deep-05", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation", "farm-to-fork", "material-to-machines", "source-to-sustenance"],
    regulation: "EU AI Act", section: "Art. 73(3) — two-day serious incident report for critical infrastructure disruption",
    question: "If the agent causes a serious and irreversible disruption of critical infrastructure, can the provider or deployer report it within two days of becoming aware?",
    evaluationCriteria: ["Serious-incident criteria mapped to Art. 3(49)(b)", "Two-day reporting path owned", "Causal-link analysis procedure", "Market surveillance authority contacts current"],
    levels: levels("No serious-incident reporting path", "Generic incident process without AI Act timelines", "Two-day path defined with owners and authority contacts", "Path rehearsed and timed", "Causal analysis and report drafts generated from preserved agent evidence"),
    evidenceTypes: ["incident_procedure", "authority_contacts", "drill_timing"],
    source: source("Regulation (EU) 2024/1689 Art. 73 (AI Act Service Desk)", `${AI_ACT_DESK}/article-73`, OMNIBUS_DATES, true),
  },
  {
    id: "environment-deep-06", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation", "farm-to-fork", "material-to-machines", "source-to-sustenance"],
    regulation: "EU AI Act", section: "Art. 9(2) — risk management as a continuous iterative process over the lifecycle",
    question: "Is there a documented risk-management process for the agent that is rerun through its lifecycle, covering foreseeable misuse in the supply operation and risks surfaced by post-market monitoring, not only the risks known at launch?",
    evaluationCriteria: ["Known and foreseeable risks to health, safety and fundamental rights identified", "Foreseeable misuse of the agent analysed", "Post-market data feeds risk re-evaluation", "Targeted measures adopted and tested"],
    levels: levels("No documented risk analysis for the agent", "One-off risk assessment at launch", "Lifecycle risk process with misuse analysis and owned measures", "Post-market findings reopen the risk assessment on a set trigger", "Residual risk tracked against acceptance criteria and tested after each change"),
    evidenceTypes: ["risk_register", "misuse_analysis", "test_report", "risk_acceptance"],
    source: readOn(aiActSource("article-9", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-07", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "EU AI Act", section: "Art. 12(1)-(2) — automatic event logging over the system lifetime",
    question: "Does the agent automatically log the events needed to spot situations where it could present a risk, to support post-market monitoring, and to let the operator monitor it, for its whole lifetime?",
    evaluationCriteria: ["Logging is automatic, not opt-in", "Logged events chosen to identify risk situations", "Logs usable for post-market monitoring", "Logs retained across model and software versions"],
    levels: levels("No event logs, or logs that operators can switch off", "Application logs kept without a defined event set", "A defined event set logged automatically for the system lifetime", "Logs used routinely in operator monitoring and incident review", "Logs integrity-protected and linked to the model version that produced each event"),
    evidenceTypes: ["logging_specification", "log_sample", "retention_config"],
    source: readOn(aiActSource("article-12", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-08", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "EU AI Act", section: "Art. 15(5) — resilience against attempts to alter use, outputs or performance",
    question: "Is the agent protected against tampering with its sensor feeds, training data or model, such as data poisoning or adversarial inputs that could change setpoints or dispatch decisions?",
    evaluationCriteria: ["AI-specific threats in the threat model (data poisoning, model poisoning, adversarial examples)", "Sensor and telemetry inputs validated", "Model artefacts integrity-checked", "Adversarial testing performed"],
    levels: levels("No AI-specific security controls", "General IT security only", "AI-specific threats modelled and input and model integrity controls in place", "Adversarial testing run before each release", "Attack detection in operation with tested containment"),
    evidenceTypes: ["threat_model", "input_validation_config", "model_integrity_check", "adversarial_test_report"],
    source: readOn(aiActSource("article-15", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-09", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation", "farm-to-fork"],
    regulation: "EU AI Act", section: "Art. 26(1)-(2) — deployer use per instructions and competent human oversight",
    question: "As the operator deploying the agent, do you use it within the provider's instructions for use and assign oversight to named staff who have the competence, training, authority and support to act on it?",
    evaluationCriteria: ["Instructions for use mapped to operating procedures", "Oversight staff named per site or shift", "Training and authority to intervene documented", "Use outside the instructions detected"],
    levels: levels("Agent used with no reference to the instructions for use", "Instructions filed but oversight roles unassigned", "Oversight assigned to trained staff with authority, and use follows the instructions", "Oversight competence re-checked after model changes", "Out-of-instruction use is detected automatically and escalated"),
    evidenceTypes: ["operating_procedure", "oversight_roster", "training_record"],
    source: readOn(aiActSource("article-26", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "environment-deep-10", industry: "environment", station: "environment",
    packIds: ["ubiquity-to-utility", "sip-to-sanitation"],
    regulation: "EU AI Act", section: "Art. 14(4)(b) — awareness of automation bias",
    question: "Are control-room operators equipped to resist automation bias, for example by seeing the agent's confidence and inputs and by being measured on how often they accept its recommendations unchanged?",
    evaluationCriteria: ["Operators trained on automation bias", "Confidence and key inputs shown with each recommendation", "Acceptance rate of recommendations measured", "Unchallenged acceptance reviewed"],
    levels: levels("Recommendations applied without operator scrutiny", "Training mentions over-reliance once", "Confidence and inputs shown, and acceptance rates measured", "High acceptance with low challenge triggers review", "Operator challenge quality tested with seeded faulty recommendations"),
    evidenceTypes: ["training_record", "hmi_capture", "acceptance_rate_report"],
    source: readOn(aiActSource("article-14", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },];
