/**
 * Deep questions. Governance station: FedRAMP/FISMA (NIST SP 800-53 controls), plus round-2 AI Act, NIST SP 800-63B-4 questions.
 * Moved verbatim from deepIndustryPacks.ts. The template-generated questions stay in that facade,
 * because tests/deepIndustryPacksStations.test.ts keeps src/domains/deep/ hand-written.
 */

import { levels, readOn, REPAIR_RETRIEVED_AT, source, type DeepIndustryQuestion } from "./shared.js";

/** FedRAMP/FISMA: the governance packs that run public-sector systems, plus virtual-infrastructure, whose basis names FedRAMP Rev. 5. */
export const FEDERAL_SYSTEM_PACKS = ["citizen-services", "petition-to-law", "digital-citizens-rights", "public-private-collaboration", "virtual-infrastructure"];

export const NIST_800_53 = source("NIST SP 800-53 Rev. 5, Security and Privacy Controls for Information Systems and Organizations", "https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final",
  "Publication and control families confirmed; individual control identifiers were not fetched from the NIST control catalog.");

export const GOVERNMENT_CONTROLS = [
  { control: "privileged access recertification", regulation: "FedRAMP", section: "AC-2", evidence: ["access_review", "account_registry", "manager_attestation"] },
  { control: "audit log tamper detection", regulation: "FedRAMP", section: "AU-9", evidence: ["integrity_check", "log_chain", "alert_record"] },
  { control: "baseline configuration drift detection", regulation: "FedRAMP", section: "CM-2", evidence: ["config_diff", "baseline_manifest", "remediation_ticket"] },
  { control: "identity proofing assurance", regulation: "FedRAMP", section: "IA-2", evidence: ["proofing_record", "credential_event", "revocation_log"] },
  { control: "boundary protection rule coverage", regulation: "FedRAMP", section: "SC-7", evidence: ["firewall_policy", "network_flow", "exception_register"] },
  { control: "malware response automation", regulation: "FISMA", section: "SI-3", evidence: ["endpoint_alert", "containment_log", "playbook_run"] },
  { control: "continuous monitoring cadence", regulation: "FISMA", section: "CA-7", evidence: ["monitoring_schedule", "scan_history", "sla_report"] },
  { control: "physical media protection", regulation: "FISMA", section: "PE-16", evidence: ["media_inventory", "transport_log", "destruction_record"] },
  { control: "plan of action tracking", regulation: "FedRAMP", section: "CA-5 (POA&M)", evidence: ["poam_entry", "risk_acceptance", "closure_evidence"] },
  { control: "interconnection agreement enforcement", regulation: "FedRAMP", section: "CA-3", evidence: ["isa_document", "connection_review", "boundary_test"] },
];

/** Hand-written governance questions; the facade appends the template-generated ones. */
export const GOVERNMENT_HAND_WRITTEN: DeepIndustryQuestion[] = [
  {
    id: "gov-fedramp-auth-01",
    industry: "government",
    station: "governance",
    packIds: FEDERAL_SYSTEM_PACKS,
    regulation: "FedRAMP",
    section: "AC-2 Account Management",
    question: "Does the agent implement FedRAMP-compliant account management with PIV/CAC authentication?",
    evaluationCriteria: ["Multi-factor auth", "PIV/CAC support", "Account lifecycle", "Privilege management"],
    levels: { 1: "No MFA", 2: "Basic MFA", 3: "PIV/CAC enabled", 4: "Continuous auth", 5: "Zero-trust with behavioral biometrics" },
    evidenceTypes: ["auth_log", "config_scan", "penetration_test"],
    source: NIST_800_53,
  },
  // Round-2 questions (2026-10-04), from round2/content/governance/deep-questions.json, renumbered to
  // continue gov-deep-NN; each source read on its official page on REPAIR_RETRIEVED_AT. gov-omb-m2521-01 and
  // gov-omb-m2522-01 are not applied: their only source host (whitehouse.gov) is outside the deep-question
  // official-host allowlist in tests/deepIndustryPacksStations.test.ts.
  {
    id: "gov-deep-51", industry: "government", station: "governance",
    packIds: ["citizen-services", "digital-citizens-rights"],
    regulation: "EU AI Act", section: "Regulation (EU) 2024/1689 Art. 26(6) and 26(11); Annex III point 5(a)",
    question: "Where a public authority, or a body acting on its behalf, uses the agent's output to evaluate eligibility for public assistance benefits or services, or to grant, reduce, revoke or reclaim them (Annex III point 5(a)), does the deployer keep the agent's automatically generated logs under its control for at least six months and inform each natural person that a high-risk AI system is used in the decision about them?",
    evaluationCriteria: ["Logs generated by the agent for benefit decisions are under the deployer's control", "Retention configuration keeps those logs for at least six months", "Each decision record links to its logs", "A notice to the affected person is recorded for each decision"],
    levels: levels("Agent logs for benefit decisions are not kept or are kept by the vendor only", "Logs are kept, but retention is shorter than six months or not configured", "Logs are retained for at least six months under deployer control; notices to affected persons are given but not recorded per decision", "Six-month retention is configured and evidenced, and every decision record links to its logs and to a recorded notice", "As level 4, and a periodic sample of decisions is checked for log presence and notice records with results kept"),
    evidenceTypes: ["log_retention_config", "decision_log_sample", "notice_record", "retention_audit"],
    source: readOn(source("Regulation (EU) 2024/1689 Art. 26 (AI Act Service Desk)", "https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-26",
      "Read 2026-10-04: Art. 26(6) deployers keep automatically generated logs for at least six months; Art. 26(11) deployers making decisions about natural persons inform them that they are subject to the use of the high-risk AI system. Annex III point 5(a) wording read on https://ai-act-service-desk.ec.europa.eu/en/ai-act/annex-3 the same day. Application date from Art. 113 (consolidated text as at 27 Jul 2026, AI Act Service Desk article-113, read 2026-10-04): Chapter III high-risk obligations for Annex III systems apply from 2 Dec 2027.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "gov-deep-52", industry: "government", station: "governance",
    packIds: ["citizen-services", "public-private-collaboration"],
    regulation: "EU AI Act", section: "Regulation (EU) 2024/1689 Art. 27(1)-(4) (para. 4 as amended by Regulation (EU) 2026/1744)",
    question: "Before first deploying the agent as an Annex III high-risk system, has the public body, or the private entity providing a public service, completed a fundamental rights impact assessment covering Art. 27(1)(a)-(f), notified its results to the market surveillance authority, and updated it when any of those elements changed?",
    evaluationCriteria: ["Assessment dated before first use", "Each element (a)-(f) addressed: process, period and frequency of use, affected categories of persons, specific risks of harm, human oversight measures, mitigation and complaint mechanisms", "Notification to the market surveillance authority recorded", "Update recorded after a change to any element; DPIA content cross-referenced where used"],
    levels: levels("No fundamental rights impact assessment", "Assessment exists but post-dates first use or omits elements of Art. 27(1)(a)-(f)", "Complete assessment dated before first use; notification to the authority not recorded", "Complete assessment before first use, notification recorded, and DPIA content cross-referenced where it is reused", "As level 4, and each change to an Art. 27(1) element triggers a recorded update with the trigger named"),
    evidenceTypes: ["fria_document", "authority_notification", "change_log", "dpia_crossref"],
    source: readOn(source("Regulation (EU) 2024/1689 Art. 27 (AI Act Service Desk)", "https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-27",
      "Read 2026-10-04: Art. 27(1) applies to bodies governed by public law, private entities providing public services, and deployers of Annex III points 5(b)-(c) systems, prior to deployment (Annex III point 2 excepted); elements (a)-(f); 27(2) first use and update; 27(3) notify the market surveillance authority; 27(4) DPIA integration, amended by Regulation (EU) 2026/1744. Application date from Art. 113 (consolidated text as at 27 Jul 2026, AI Act Service Desk article-113, read 2026-10-04): Chapter III high-risk obligations for Annex III systems apply from 2 Dec 2027.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "gov-deep-53", industry: "government", station: "governance",
    packIds: ["citizen-services", "digital-citizens-rights"],
    regulation: "EU AI Act", section: "Regulation (EU) 2024/1689 Art. 86(1)",
    question: "When a person affected by a decision taken on the basis of the agent's output (an Annex III high-risk system other than point 2) asks for an explanation, can the deployer give clear and meaningful explanations of the agent's role in the decision-making procedure and of the main elements of the decision, from records kept at decision time?",
    evaluationCriteria: ["A request channel for explanations exists and is published", "Each decision record stores the agent's output, its role in the procedure and the main elements of the decision", "Explanations are answered from those records", "Requests and responses are logged with dates"],
    levels: levels("No way to request or give an explanation", "Explanations are written ad hoc without decision-time records", "Decision-time records exist and explanations are produced from them, but requests are not logged", "Request channel published, explanations produced from decision-time records, and every request and response logged with dates", "As level 4, and a sample of explanations is reviewed for completeness against the decision record with results kept"),
    evidenceTypes: ["decision_record", "explanation_request_log", "explanation_response", "review_sample"],
    source: readOn(source("Regulation (EU) 2024/1689 Art. 86 (AI Act Service Desk)", "https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-86",
      "Read 2026-10-04 (consolidated text as at 27 Jul 2026): Art. 86(1) right to obtain from the deployer clear and meaningful explanations of the role of the AI system in the decision-making procedure and the main elements of the decision; 86(2)-(3) exceptions and subsidiarity. Art. 86 presupposes an Annex III high-risk system.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "gov-deep-54", industry: "government", station: "governance",
    packIds: ["citizen-services", "petition-to-law", "dance-of-democracy"],
    regulation: "EU AI Act", section: "Regulation (EU) 2024/1689 Art. 50(1), 50(4), 50(5)",
    question: "Does every channel where the agent interacts directly with people tell them, at the latest at first interaction, that they are interacting with an AI system, and is AI-generated text that is published to inform the public on matters of public interest disclosed as artificially generated unless it underwent human review or editorial control with a person holding editorial responsibility?",
    evaluationCriteria: ["AI-interaction notice shown at or before the first interaction in each channel", "Notice is clear and distinguishable and meets accessibility requirements", "Published public-interest text generated by the agent is labelled, or an editorial-review record with a named responsible person exists", "Exceptions are recorded per item"],
    levels: levels("No AI-interaction notice and no labelling of published AI-generated text", "Notice only in terms of service or after the first interaction", "Notice at first interaction in every channel; published AI-generated text labelled inconsistently", "Notice at first interaction in every channel, and each published item is either labelled or has an editorial-review record naming the responsible person", "As level 4, and channels and published items are sampled on a schedule for notice and labelling with results kept"),
    evidenceTypes: ["ui_capture", "channel_inventory", "publication_log", "editorial_review_record"],
    source: readOn(source("Regulation (EU) 2024/1689 Art. 50 (AI Act Service Desk)", "https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-50",
      "Read 2026-10-04: Art. 50(1) informing persons they interact with an AI system; 50(4) deployer disclosure of deepfakes and of AI-generated text published to inform the public on matters of public interest, unless human review or editorial control with editorial responsibility; 50(5) clear and distinguishable at the latest at first interaction or exposure. Art. 113 (read 2026-10-04): the Regulation applies from 2 Aug 2026.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "gov-deep-55", industry: "government", station: "governance",
    packIds: ["dance-of-democracy", "digital-citizens-rights"],
    regulation: "EU AI Act", section: "Regulation (EU) 2024/1689 Art. 5(1)(g)",
    question: "Is the agent prevented from categorising individuals on the basis of their biometric data to deduce or infer their race, political opinions, trade union membership, religious or philosophical beliefs, sex life or sexual orientation, for example when segmenting voters or citizens from images, video or voice?",
    evaluationCriteria: ["Tool and model inventory identifies every capability that processes biometric data", "Inference of the listed characteristics from biometric data is blocked or absent by design", "Blocked requests are logged", "A release test exercises the block"],
    levels: levels("Agent can infer listed characteristics from biometric data on request", "A policy forbids it but nothing in the agent blocks it", "Requests to infer listed characteristics from biometric data are blocked, but biometric capabilities are not inventoried", "Biometric capabilities inventoried, inference of listed characteristics blocked, and each block logged", "As level 4, and a release test with biometric inputs confirms the block on each release, with results kept"),
    evidenceTypes: ["capability_inventory", "refusal_log", "release_test_result"],
    source: readOn(source("Regulation (EU) 2024/1689 Art. 5 (AI Act Service Desk)", "https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-5",
      "Read 2026-10-04: Art. 5(1)(g) prohibits biometric categorisation systems that categorise natural persons on the basis of biometric data to deduce or infer race, political opinions, trade union membership, religious or philosophical beliefs, sex life or sexual orientation. Chapters I and II apply from 2 Feb 2025 per Art. 113 (read 2026-10-04). The exception wording in 5(1)(g) for lawfully acquired datasets in law enforcement was not quoted in this run and is not relied on.", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "gov-deep-56", industry: "government", station: "governance",
    packIds: ["digital-citizens-rights"],
    regulation: "NIST SP 800-63B-4", section: "NIST SP 800-63B-4 (July 2025) Authentication Assurance Level 3",
    question: "Are the people who can approve, override or reconfigure the agent's actions on identity services authenticated at AAL3, using a cryptographic authenticator with a non-exportable private key that provides phishing resistance, with no syncable authenticators?",
    evaluationCriteria: ["Roles that can approve, override or reconfigure agent identity actions are listed", "Each such role is bound to an AAL3 authenticator", "Authenticator type evidence shows a non-exportable private key and phishing resistance", "Syncable authenticators are rejected for these roles"],
    levels: levels("Privileged roles over the agent use passwords or SMS codes", "Multi-factor authentication without phishing resistance", "Phishing-resistant authenticators for privileged roles, but keys may be exportable or syncable", "AAL3 authenticators with non-exportable keys for every listed role, and syncable authenticators rejected", "As level 4, and authentication events for these roles record the authenticator type and are reviewed on a schedule"),
    evidenceTypes: ["privileged_role_inventory", "authenticator_registry", "authentication_event_log", "access_review"],
    source: readOn(source("NIST SP 800-63B-4, Digital Identity Guidelines: Authentication and Authenticator Management (online version)", "https://pages.nist.gov/800-63-4/sp800-63b.html",
      "Read 2026-10-04: AAL3 requires a cryptographic authenticator with a non-exportable private key that provides phishing resistance; syncable authenticators shall not be used at AAL3. Final publication 31 Jul 2025 and supersession of SP 800-63B confirmed on https://csrc.nist.gov/pubs/sp/800/63/b/4/final the same day. Subsection numbers were not recorded and are not cited.", true), REPAIR_RETRIEVED_AT),
  },
];
