/**
 * Hand-written deep questions. Mobility station: road traffic and transport safety components, UN R155/R156, ADS type-approval, AI Act lifecycle duties and C-SCRM.
 * Each question anchors one provision and lists the industry packs it applies to.
 */

import { AI_ACT_DESK, OMNIBUS_DATES, aiActSource, levels, source, readOn, REPAIR_RETRIEVED_AT, type DeepIndustryQuestion } from "./shared.js";

export const DEEP_MOBILITY_QUESTIONS: DeepIndustryQuestion[] = [
  {
    id: "mobility-deep-01", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "freight-3pl-warehouse"],
    regulation: "EU AI Act", section: "Annex III point 2 — safety components in road traffic management",
    question: "Where the agent is a safety component in road traffic management, is its operating envelope documented and does it hand control back safely when inputs leave that envelope?",
    evaluationCriteria: ["Safety-component role identified", "Operating envelope documented", "Out-of-envelope detection", "Safe handback tested"],
    levels: levels("No defined operating envelope", "Envelope described informally", "Envelope documented with tested out-of-envelope handback", "Handback performance monitored in operation", "Envelope and handback validated independently after each change"),
    evidenceTypes: ["operating_envelope", "handback_test", "monitoring_report"],
    source: source("Regulation (EU) 2024/1689 Annex III (AI Act Service Desk)", `${AI_ACT_DESK}/annex-3`, OMNIBUS_DATES, true),
  },
  {
    id: "mobility-deep-02", industry: "mobility", station: "mobility",
    packIds: ["privacy-security-mobility"],
    regulation: "UN R155", section: "Cyber Security Management System (CSMS) certificate of compliance",
    question: "Is the in-vehicle or fleet agent within the scope of the manufacturer's certified Cyber Security Management System, with its threats and mitigations recorded?",
    evaluationCriteria: ["Agent in CSMS scope", "Threat analysis covers the agent", "Mitigations traced to threats", "CSMS certificate current"],
    levels: levels("Agent outside any CSMS", "Agent known to the CSMS team but not analysed", "Threats and mitigations for the agent recorded in the CSMS", "Monitoring detects attacks on the agent in the field", "Agent threat model updated from field monitoring each release"),
    evidenceTypes: ["csms_scope", "threat_analysis", "csms_certificate"],
    source: source("UN Regulation No. 155 — Cyber security and cyber security management system (OJ L 2025/5)", "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=OJ%3AL_202500005",
      "Title and CSMS approval requirement confirmed from UNECE and EUR-Lex search results; unece.org and the EUR-Lex PDF did not render for review, so paragraph numbers are not cited."),
  },
  {
    id: "mobility-deep-03", industry: "mobility", station: "mobility",
    packIds: ["privacy-security-mobility"],
    regulation: "UN R156", section: "Software Update Management System (SUMS)",
    question: "Are updates to the agent's models, prompts and policies delivered through the Software Update Management System, with version identification and integrity protection?",
    evaluationCriteria: ["Model and prompt changes treated as software updates", "Versions identifiable in the vehicle or fleet", "Update integrity protected", "Update impact on approvals assessed"],
    levels: levels("Agent behaviour changes outside any update process", "Some changes versioned manually", "All agent changes go through SUMS with versioning and integrity checks", "Impact on type approval assessed per update", "Signed, reproducible update records with rollback tested"),
    evidenceTypes: ["sums_record", "version_manifest", "integrity_check"],
    source: source("UN Regulation No. 156 — Software update and software update management system (UNECE)", "https://unece.org/sites/default/files/2024-03/R156e%20(2).pdf",
      "SUMS definition confirmed from UNECE search results; unece.org did not render for review, so paragraph numbers are not cited."),
  },
  {
    id: "mobility-deep-04", industry: "mobility", station: "mobility",
    packIds: ["privacy-security-mobility", "freight-3pl-warehouse"],
    regulation: "Implementing Regulation (EU) 2022/1426", section: "Annex II — ADS technical specifications for fully automated vehicles",
    question: "For a fully automated vehicle use case (hub-to-hub, predefined area or automated valet parking), does the agent's automated driving system evidence its operational design domain and a safety management system as required for type-approval?",
    evaluationCriteria: ["Use case matches a covered category", "Operational design domain specified", "Safety management system documented", "Scenario-based validation evidence"],
    levels: levels("No ODD or safety management documentation", "ODD described without validation", "ODD, safety management system and scenario validation documented", "In-service monitoring feeds the safety management system", "Validation evidence reproducible by the approval authority"),
    evidenceTypes: ["odd_specification", "sms_manual", "scenario_validation"],
    source: source("Commission Implementing Regulation (EU) 2022/1426 (EUR-Lex)", "https://eur-lex.europa.eu/eli/reg_impl/2022/1426/oj/eng",
      "Scope and Annex II/III structure confirmed from EUR-Lex search results; the page did not render for review. A consolidated version dated 2026-03-24 exists."),
  },
  {
    id: "mobility-deep-05", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "sustainable-ports", "freight-3pl-warehouse"],
    regulation: "EU AI Act", section: "Art. 26(5)-(6) — deployer monitoring and log retention (at least six months)",
    question: "As deployer of a high-risk mobility agent, do you monitor its operation per the instructions for use and keep its automatically generated logs for at least six months?",
    evaluationCriteria: ["Monitoring follows the instructions for use", "Provider informed of risks found", "Logs retained six months or longer", "Retention reconciled with data-protection law"],
    levels: levels("No deployer monitoring and logs discarded", "Monitoring ad hoc and retention unspecified", "Monitoring per instructions and logs kept at least six months", "Findings reported to the provider with tracking", "Log integrity protected and retention audited"),
    evidenceTypes: ["monitoring_plan", "log_retention_policy", "provider_notice"],
    source: source("Regulation (EU) 2024/1689 Art. 26 (AI Act Service Desk)", `${AI_ACT_DESK}/article-26`, OMNIBUS_DATES, true),
  },
  {
    id: "mobility-deep-06", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "sustainable-ports", "freight-3pl-warehouse"],
    regulation: "EU AI Act", section: "Art. 72(1)-(2) — post-market monitoring system",
    question: "As provider of a high-risk mobility agent, do you run a documented post-market monitoring system that actively collects performance data from deployers and the field, and checks continuing compliance through the system's lifetime?",
    evaluationCriteria: ["Post-market monitoring plan documented", "Field and deployer data collected systematically", "Interaction with other AI systems analysed where relevant", "Findings trigger corrective action"],
    levels: levels("No post-market monitoring", "Complaints handled case by case", "Documented plan collecting field and deployer data", "Monitoring results reviewed against compliance requirements each period", "Monitoring drives corrective actions with measured effect"),
    evidenceTypes: ["pmm_plan", "field_data_report", "corrective_action_log"],
    source: readOn(aiActSource("article-72", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-07", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "sustainable-ports"],
    regulation: "EU AI Act", section: "Art. 13(3)(b)(ii) — declared accuracy, robustness and cybersecurity in the instructions for use",
    question: "Do the instructions for use state the accuracy metrics, robustness and cybersecurity levels the agent was tested and validated against, so a traffic or port operator knows what performance to expect?",
    evaluationCriteria: ["Accuracy metrics stated with test conditions", "Robustness level stated", "Cybersecurity level stated", "Field performance compared with the declared levels"],
    levels: levels("No performance information for deployers", "Marketing claims without metrics", "Instructions state tested accuracy, robustness and cybersecurity levels", "Deployers report field performance against declared levels", "Declared levels updated from field evidence with version history"),
    evidenceTypes: ["instructions_for_use", "validation_report", "field_performance_report"],
    source: readOn(aiActSource("article-13", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-08", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "privacy-security-mobility", "freight-3pl-warehouse"],
    regulation: "EU AI Act", section: "Art. 10(3) — relevant and sufficiently representative data sets",
    question: "Are the agent's training, validation and test data representative of the places and conditions it operates in, such as weather, lighting, road types and regions, with gaps recorded?",
    evaluationCriteria: ["Operating conditions enumerated", "Data coverage measured per condition", "Data gaps and known errors recorded", "Bias in coverage examined"],
    levels: levels("Data provenance and coverage unknown", "Coverage described anecdotally", "Coverage measured per operating condition with gaps recorded", "Gaps closed or the operating envelope narrowed to match", "Coverage re-measured when the deployment area changes"),
    evidenceTypes: ["datasheet", "coverage_matrix", "data_gap_register"],
    source: readOn(aiActSource("article-10", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-09", industry: "mobility", station: "mobility",
    packIds: ["sustainable-ports", "freight-3pl-warehouse", "sustainable-communities"],
    regulation: "EU AI Act", section: "Art. 14(4)(d) — deciding not to use, or overriding, the output",
    question: "Can a dispatcher, berth planner or traffic controller decline or override the agent's routing or scheduling output in any situation, and is each override recorded with a reason?",
    evaluationCriteria: ["Override available in every operating mode", "Override does not need vendor support", "Overrides recorded with reason", "Override patterns reviewed"],
    levels: levels("Outputs executed with no override path", "Override possible only through a support ticket", "Operators can override in any mode and overrides are logged with reasons", "Override patterns reviewed to find model weaknesses", "Override reasons feed retraining or rule changes under change control"),
    evidenceTypes: ["override_log", "operator_procedure", "override_review"],
    source: readOn(aiActSource("article-14", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-10", industry: "mobility", station: "mobility",
    packIds: ["freight-3pl-warehouse", "virtual-infrastructure"],
    regulation: "NIST SP 800-161r1", section: "C-SCRM practices for systems and organizations (Rev. 1 Update 1)",
    question: "Are the agent's model, data and software suppliers covered by a cybersecurity supply-chain risk management plan, with supplier risk assessed before onboarding and reassessed when a supplier changes?",
    evaluationCriteria: ["Agent suppliers inventoried, including model and data providers", "Supplier risk assessed before use", "C-SCRM requirements in supplier agreements", "Reassessment on supplier or component change"],
    levels: levels("No view of the agent's suppliers", "Supplier list without risk assessment", "C-SCRM plan covers agent suppliers with pre-onboarding assessment", "Supplier changes trigger reassessment and are tracked", "Supplier risk monitored continuously and reported to leadership"),
    evidenceTypes: ["supplier_inventory", "cscrm_plan", "supplier_risk_assessment"],
    source: readOn(source("NIST SP 800-161 Rev. 1 Update 1, Cybersecurity Supply Chain Risk Management Practices for Systems and Organizations (Nov 2024)", "https://csrc.nist.gov/pubs/sp/800/161/r1/upd1/final"), REPAIR_RETRIEVED_AT),
  },
  // Round 2 (round2/content/mobility/deep-questions.json, author ids 06, 08-12 renumbered to 11-16).
  {
    id: "mobility-deep-11", industry: "mobility", station: "mobility",
    packIds: ["privacy-security-mobility"],
    regulation: "NHTSA Standing General Order 2021-01 (Third Amended)", section: "Crash reporting for ADS and Level 2 ADAS (amended 2025-04-24; reporting period from 2025-06-16)",
    question: "If the agent is part of an ADS or Level 2 ADAS deployed in the US, does the operator capture the crash data the Third Amended Standing General Order requires and file reports within the order's timeframes?",
    evaluationCriteria: ["Vehicles and features in SGO scope identified", "Crash-data capture covers the fields the order requires", "Reporting deadlines tracked per crash", "Reports reconcile to retained vehicle data"],
    levels: levels("No SGO scope determination", "Scope known; crash data collected ad hoc", "Crash data captured for every in-scope crash and reports filed on time", "Filing timeliness monitored and late filings root-caused", "Reports regenerate from retained vehicle data and are audited"),
    evidenceTypes: ["sgo_scope_record", "crash_report", "filing_log"],
    source: readOn(source("NHTSA, AV Framework Updates and Request for Comments on Interim Guidance, 91 FR 48485 (2026-07-31), FR Doc 2026-15483 (govinfo)", "https://www.govinfo.gov/content/pkg/FR-2026-07-31/html/2026-15483.htm",
      "Notice read: the SGO was amended on 2025-04-24 with a reporting period from 2025-06-16, and NHTSA is developing a rule to codify it. The order's own reporting timeframes are in the NHTSA PDF, which was not read (nhtsa.gov returned 403).", true), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-12", industry: "mobility", station: "mobility",
    packIds: ["sustainable-ports"],
    regulation: "33 CFR Part 101 Subpart F (USCG, Cybersecurity in the Marine Transportation System)", section: "§101.650 cybersecurity measures; §101.655 submission and approval of the Cybersecurity Plan; reportable cyber incidents to the National Response Center; effective 2025-07-16",
    question: "For a US-regulated facility, are the systems the agent operates inside the facility's Cybersecurity Assessment and Cybersecurity Plan (due for Coast Guard review within 24 months of 2025-07-16), and does the agent route reportable cyber incidents to the National Response Center?",
    evaluationCriteria: ["Agent systems in the Cybersecurity Assessment", "Cybersecurity Plan names controls for those systems", "Cybersecurity Officer designated", "Reportable cyber incidents routed to the National Response Center"],
    levels: levels("Agent systems outside the facility's cyber programme", "Systems listed but no controls in the plan", "Assessment and plan cover the agent's systems and the NRC reporting path is documented", "Reporting path exercised in a drill", "Plan updated after each drill or incident with recorded changes"),
    evidenceTypes: ["cyber_assessment", "cybersecurity_plan", "nrc_report_log"],
    source: readOn(source("USCG final rule 'Cybersecurity in the Marine Transportation System', 90 FR 6298 (2025-01-17), FR Doc 2025-00708 (govinfo)", "https://www.govinfo.gov/content/pkg/FR-2025-01-17/html/2025-00708.htm"), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-13", industry: "mobility", station: "mobility",
    packIds: ["sustainable-ports"],
    regulation: "Regulation (EU) 2023/1805 (FuelEU Maritime)", section: "Art. 6(1): zero-emission energy at berth from 1 January 2030 in ports covered by Art. 9 of Regulation (EU) 2023/1804",
    question: "Does the port agent record, per call from 1 January 2030, whether a ship moored at a covered quayside connected to onshore power supply or used an allowed alternative, so the ship operator's FuelEU evidence and any exception are traceable?",
    evaluationCriteria: ["Covered berths identified", "Connection status recorded per call", "Exceptions recorded with reason", "Records available to the ship operator and verifier"],
    levels: levels("No record of onshore power use", "Usage recorded for some calls", "Connection status and exceptions recorded for every call at covered berths", "Records reconciled with metered supply", "Records shared with operators and verifiers through a controlled interface"),
    evidenceTypes: ["berth_register", "ops_connection_log", "exception_record"],
    source: source("Regulation (EU) 2023/1805 (FuelEU Maritime), Art. 6 zero-emission at berth (OJ text)", "https://publications.europa.eu/resource/celex/32023R1805"),
  },
  {
    id: "mobility-deep-14", industry: "mobility", station: "mobility",
    packIds: ["privacy-security-mobility"],
    regulation: "Regulation (EU) 2019/2144 (General Safety Regulation)", section: "Art. 6(3): driver drowsiness, attention and distraction warning data stay in a closed loop",
    question: "Where the agent processes driver-monitoring data from drowsiness or distraction warning systems, does it avoid continuous recording or retention beyond what the closed-loop purpose needs, and never make those data available to third parties?",
    evaluationCriteria: ["Driver-monitoring data sources identified", "No continuous recording or retention beyond purpose", "No third-party access", "Deletion after closed-loop use evidenced"],
    levels: levels("Driver-monitoring data stored or exported freely", "Retention limited by policy only", "Configuration enforces closed-loop use with no export path", "Deletion verified by test", "Independent review confirms no retention or export path"),
    evidenceTypes: ["data_flow_map", "retention_config", "deletion_test"],
    source: source("Regulation (EU) 2019/2144 (General Safety Regulation), Arts. 6 and 11 (OJ text)", "https://publications.europa.eu/resource/celex/32019R2144"),
  },
  {
    id: "mobility-deep-15", industry: "mobility", station: "mobility",
    packIds: ["virtual-infrastructure"],
    regulation: "Regulation (EU) 2023/2854 (Data Act)", section: "Art. 25(2): switching contract terms (notice of at most two months; data retrieval for at least 30 calendar days)",
    question: "Do the agent's cloud contracts and runbooks state a notice period of at most two months to initiate switching and a data-retrieval period of at least 30 calendar days, and is retrieval tested against those periods?",
    evaluationCriteria: ["Contract states notice period of at most two months", "Contract states retrieval period of at least 30 days", "Export tooling covers all exportable data", "Retrieval tested within the period"],
    levels: levels("No switching terms in contract", "Terms present but periods not stated", "Periods stated as required and export tooling documented", "Retrieval test completed within the period", "Retrieval tested on each major release with results retained"),
    evidenceTypes: ["contract_clause", "export_runbook", "retrieval_test"],
    source: source("Regulation (EU) 2023/2854 (Data Act), Arts. 23 and 25 (OJ text)", "https://publications.europa.eu/resource/celex/32023R2854"),
  },
  {
    id: "mobility-deep-16", industry: "mobility", station: "mobility",
    packIds: ["privacy-security-mobility"],
    regulation: "Regulation (EU) 2024/2847 (Cyber Resilience Act)", section: "Art. 2(2)(c) and 2(4): products under Regulation (EU) 2019/2144 and equipment under Directive 2014/90/EU are outside the CRA",
    question: "Before applying CRA obligations to a mobility product, does the operator record whether it is a type-approved vehicle product (Regulation (EU) 2019/2144) or marine equipment (Directive 2014/90/EU), and route those to their sectoral cybersecurity regime instead?",
    evaluationCriteria: ["Scope decision recorded per product", "Vehicle products routed to type-approval cybersecurity requirements", "Marine equipment routed to its regime", "In-scope products tracked to CRA dates (11 September 2026 reporting; 11 December 2027 general)"],
    levels: levels("CRA applied or ignored with no scope analysis", "Scope analysed informally", "Scope decision recorded per product with the legal basis", "Scope decisions reviewed on product change", "Scope decisions audited and reconciled with the product register"),
    evidenceTypes: ["scope_decision", "product_register", "regime_mapping"],
    source: source("Regulation (EU) 2024/2847 (Cyber Resilience Act), Arts. 2, 13, 14, 32 and 71 (OJ text)", "https://publications.europa.eu/resource/celex/32024R2847"),
  },
];
