/**
 * Hand-written deep questions. Mobility station: road traffic and transport safety components, UN R155/R156, ADS type-approval, AI Act lifecycle duties and C-SCRM.
 * Each question anchors one provision and lists the industry packs it applies to.
 */

import { AI_ACT_DESK, OMNIBUS_DATES, aiActSource, levels, source, readOn, REPAIR_RETRIEVED_AT, type DeepIndustryQuestion } from "./shared.js";

export const DEEP_MOBILITY_QUESTIONS: DeepIndustryQuestion[] = [
  {
    id: "mobility-deep-01", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "freight-3pl-warehouse"],
    regulation: "EU AI Act", section: "Annex III point 2 — safety components in road traffic management",
    question: "Where the agent is a safety component in road traffic management, is its operating envelope documented and does it hand control back safely when inputs leave that envelope?",
    evaluationCriteria: ["Safety-component role identified", "Operating envelope documented", "Out-of-envelope detection", "Safe handback tested"],
    levels: levels("No defined operating envelope", "Envelope described informally", "Envelope documented with tested out-of-envelope handback", "Handback performance monitored in operation", "Envelope and handback validated independently after each change"),
    evidenceTypes: ["operating_envelope", "handback_test", "monitoring_report"],
    source: source("Regulation (EU) 2024/1689 Annex III (AI Act Service Desk)", `${AI_ACT_DESK}/annex-3`, OMNIBUS_DATES, true),
  },
  {
    id: "mobility-deep-02", industry: "mobility", station: "mobility",
    packIds: ["privacy-security-mobility"],
    regulation: "UN R155", section: "Cyber Security Management System (CSMS) certificate of compliance",
    question: "Is the in-vehicle or fleet agent within the scope of the manufacturer's certified Cyber Security Management System, with its threats and mitigations recorded?",
    evaluationCriteria: ["Agent in CSMS scope", "Threat analysis covers the agent", "Mitigations traced to threats", "CSMS certificate current"],
    levels: levels("Agent outside any CSMS", "Agent known to the CSMS team but not analysed", "Threats and mitigations for the agent recorded in the CSMS", "Monitoring detects attacks on the agent in the field", "Agent threat model updated from field monitoring each release"),
    evidenceTypes: ["csms_scope", "threat_analysis", "csms_certificate"],
    source: source("UN Regulation No. 155 — Cyber security and cyber security management system (OJ L 2025/5)", "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=OJ%3AL_202500005",
      "Title and CSMS approval requirement confirmed from UNECE and EUR-Lex search results; unece.org and the EUR-Lex PDF did not render for review, so paragraph numbers are not cited."),
  },
  {
    id: "mobility-deep-03", industry: "mobility", station: "mobility",
    packIds: ["privacy-security-mobility"],
    regulation: "UN R156", section: "Software Update Management System (SUMS)",
    question: "Are updates to the agent's models, prompts and policies delivered through the Software Update Management System, with version identification and integrity protection?",
    evaluationCriteria: ["Model and prompt changes treated as software updates", "Versions identifiable in the vehicle or fleet", "Update integrity protected", "Update impact on approvals assessed"],
    levels: levels("Agent behaviour changes outside any update process", "Some changes versioned manually", "All agent changes go through SUMS with versioning and integrity checks", "Impact on type approval assessed per update", "Signed, reproducible update records with rollback tested"),
    evidenceTypes: ["sums_record", "version_manifest", "integrity_check"],
    source: source("UN Regulation No. 156 — Software update and software update management system (UNECE)", "https://unece.org/sites/default/files/2024-03/R156e%20(2).pdf",
      "SUMS definition confirmed from UNECE search results; unece.org did not render for review, so paragraph numbers are not cited."),
  },
  {
    id: "mobility-deep-04", industry: "mobility", station: "mobility",
    packIds: ["privacy-security-mobility", "freight-3pl-warehouse"],
    regulation: "Implementing Regulation (EU) 2022/1426", section: "Annex II — ADS technical specifications for fully automated vehicles",
    question: "For a fully automated vehicle use case (hub-to-hub, predefined area or automated valet parking), does the agent's automated driving system evidence its operational design domain and a safety management system as required for type-approval?",
    evaluationCriteria: ["Use case matches a covered category", "Operational design domain specified", "Safety management system documented", "Scenario-based validation evidence"],
    levels: levels("No ODD or safety management documentation", "ODD described without validation", "ODD, safety management system and scenario validation documented", "In-service monitoring feeds the safety management system", "Validation evidence reproducible by the approval authority"),
    evidenceTypes: ["odd_specification", "sms_manual", "scenario_validation"],
    source: source("Commission Implementing Regulation (EU) 2022/1426 (EUR-Lex)", "https://eur-lex.europa.eu/eli/reg_impl/2022/1426/oj/eng",
      "Scope and Annex II/III structure confirmed from EUR-Lex search results; the page did not render for review. A consolidated version dated 2026-03-24 exists."),
  },
  {
    id: "mobility-deep-05", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "sustainable-ports", "freight-3pl-warehouse"],
    regulation: "EU AI Act", section: "Art. 26(5)-(6) — deployer monitoring and log retention (at least six months)",
    question: "As deployer of a high-risk mobility agent, do you monitor its operation per the instructions for use and keep its automatically generated logs for at least six months?",
    evaluationCriteria: ["Monitoring follows the instructions for use", "Provider informed of risks found", "Logs retained six months or longer", "Retention reconciled with data-protection law"],
    levels: levels("No deployer monitoring and logs discarded", "Monitoring ad hoc and retention unspecified", "Monitoring per instructions and logs kept at least six months", "Findings reported to the provider with tracking", "Log integrity protected and retention audited"),
    evidenceTypes: ["monitoring_plan", "log_retention_policy", "provider_notice"],
    source: source("Regulation (EU) 2024/1689 Art. 26 (AI Act Service Desk)", `${AI_ACT_DESK}/article-26`, OMNIBUS_DATES, true),
  },
  {
    id: "mobility-deep-06", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "sustainable-ports", "freight-3pl-warehouse"],
    regulation: "EU AI Act", section: "Art. 72(1)-(2) — post-market monitoring system",
    question: "As provider of a high-risk mobility agent, do you run a documented post-market monitoring system that actively collects performance data from deployers and the field, and checks continuing compliance through the system's lifetime?",
    evaluationCriteria: ["Post-market monitoring plan documented", "Field and deployer data collected systematically", "Interaction with other AI systems analysed where relevant", "Findings trigger corrective action"],
    levels: levels("No post-market monitoring", "Complaints handled case by case", "Documented plan collecting field and deployer data", "Monitoring results reviewed against compliance requirements each period", "Monitoring drives corrective actions with measured effect"),
    evidenceTypes: ["pmm_plan", "field_data_report", "corrective_action_log"],
    source: readOn(aiActSource("article-72", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-07", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "sustainable-ports"],
    regulation: "EU AI Act", section: "Art. 13(3)(b)(ii) — declared accuracy, robustness and cybersecurity in the instructions for use",
    question: "Do the instructions for use state the accuracy metrics, robustness and cybersecurity levels the agent was tested and validated against, so a traffic or port operator knows what performance to expect?",
    evaluationCriteria: ["Accuracy metrics stated with test conditions", "Robustness level stated", "Cybersecurity level stated", "Field performance compared with the declared levels"],
    levels: levels("No performance information for deployers", "Marketing claims without metrics", "Instructions state tested accuracy, robustness and cybersecurity levels", "Deployers report field performance against declared levels", "Declared levels updated from field evidence with version history"),
    evidenceTypes: ["instructions_for_use", "validation_report", "field_performance_report"],
    source: readOn(aiActSource("article-13", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-08", industry: "mobility", station: "mobility",
    packIds: ["sustainable-communities", "privacy-security-mobility", "freight-3pl-warehouse"],
    regulation: "EU AI Act", section: "Art. 10(3) — relevant and sufficiently representative data sets",
    question: "Are the agent's training, validation and test data representative of the places and conditions it operates in, such as weather, lighting, road types and regions, with gaps recorded?",
    evaluationCriteria: ["Operating conditions enumerated", "Data coverage measured per condition", "Data gaps and known errors recorded", "Bias in coverage examined"],
    levels: levels("Data provenance and coverage unknown", "Coverage described anecdotally", "Coverage measured per operating condition with gaps recorded", "Gaps closed or the operating envelope narrowed to match", "Coverage re-measured when the deployment area changes"),
    evidenceTypes: ["datasheet", "coverage_matrix", "data_gap_register"],
    source: readOn(aiActSource("article-10", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-09", industry: "mobility", station: "mobility",
    packIds: ["sustainable-ports", "freight-3pl-warehouse", "sustainable-communities"],
    regulation: "EU AI Act", section: "Art. 14(4)(d) — deciding not to use, or overriding, the output",
    question: "Can a dispatcher, berth planner or traffic controller decline or override the agent's routing or scheduling output in any situation, and is each override recorded with a reason?",
    evaluationCriteria: ["Override available in every operating mode", "Override does not need vendor support", "Overrides recorded with reason", "Override patterns reviewed"],
    levels: levels("Outputs executed with no override path", "Override possible only through a support ticket", "Operators can override in any mode and overrides are logged with reasons", "Override patterns reviewed to find model weaknesses", "Override reasons feed retraining or rule changes under change control"),
    evidenceTypes: ["override_log", "operator_procedure", "override_review"],
    source: readOn(aiActSource("article-14", OMNIBUS_DATES), REPAIR_RETRIEVED_AT),
  },
  {
    id: "mobility-deep-10", industry: "mobility", station: "mobility",
    packIds: ["freight-3pl-warehouse", "virtual-infrastructure"],
    regulation: "NIST SP 800-161r1", section: "C-SCRM practices for systems and organizations (Rev. 1 Update 1)",
    question: "Are the agent's model, data and software suppliers covered by a cybersecurity supply-chain risk management plan, with supplier risk assessed before onboarding and reassessed when a supplier changes?",
    evaluationCriteria: ["Agent suppliers inventoried, including model and data providers", "Supplier risk assessed before use", "C-SCRM requirements in supplier agreements", "Reassessment on supplier or component change"],
    levels: levels("No view of the agent's suppliers", "Supplier list without risk assessment", "C-SCRM plan covers agent suppliers with pre-onboarding assessment", "Supplier changes trigger reassessment and are tracked", "Supplier risk monitored continuously and reported to leadership"),
    evidenceTypes: ["supplier_inventory", "cscrm_plan", "supplier_risk_assessment"],
    source: readOn(source("NIST SP 800-161 Rev. 1 Update 1, Cybersecurity Supply Chain Risk Management Practices for Systems and Organizations (Nov 2024)", "https://csrc.nist.gov/pubs/sp/800/161/r1/upd1/final"), REPAIR_RETRIEVED_AT),
  },];
