/**
 * Hand-written deep questions. Technology station: AI Act transparency and GPAI duties, the CRA, the DSA, the Data Act and GDPR Art. 22.
 * Each question anchors one provision and lists the industry packs it applies to.
 */

import { AI_ACT_DESK, aiActSource, levels, source, type DeepIndustryQuestion } from "./shared.js";

export const DEEP_TECHNOLOGY_QUESTIONS: DeepIndustryQuestion[] = [
  {
    id: "technology-deep-01", industry: "technology", station: "technology",
    packIds: ["cognition-to-intelligence", "infotainment"],
    regulation: "EU AI Act", section: "Art. 50(1) — informing people they interact with an AI system",
    question: "Does the agent tell people they are interacting with an AI system, unless that is obvious from the context?",
    evaluationCriteria: ["Disclosure shown at first interaction", "Disclosure persists across channels", "Exceptions justified", "Disclosure tested in each locale"],
    levels: levels("No AI disclosure", "Disclosure in terms of service only", "Disclosure at first interaction on every channel", "Disclosure comprehension tested with users", "Disclosure coverage monitored with alerts on regressions"),
    evidenceTypes: ["ui_capture", "channel_inventory", "test_result"],
    source: source("Regulation (EU) 2024/1689 Art. 50 (AI Act Service Desk)", `${AI_ACT_DESK}/article-50`),
  },
  {
    id: "technology-deep-02", industry: "technology", station: "technology",
    packIds: ["infotainment", "cognition-to-intelligence"],
    regulation: "EU AI Act", section: "Art. 50(2) — machine-readable marking of synthetic content",
    question: "Are the agent's synthetic audio, image, video or text outputs marked in a machine-readable format and detectable as artificially generated?",
    evaluationCriteria: ["Generative output types inventoried", "Machine-readable marking applied", "Detection verified", "Marking robust to common transformations"],
    levels: levels("Outputs unmarked", "Marking for some media types only", "All generated media marked and detection verified", "Robustness to transformations tested", "Marking and detection monitored in production"),
    evidenceTypes: ["marking_config", "detection_test", "robustness_report"],
    source: source("Regulation (EU) 2024/1689 Art. 50 (AI Act Service Desk)", `${AI_ACT_DESK}/article-50`,
      "Regulation (EU) 2026/1744 gives providers whose systems were on the market before 2 August 2026 a four-month transitional period for Art. 50(2) (recital 38, read on EUR-Lex); the operative wording was not read in full.", true),
  },
  {
    id: "technology-deep-03", industry: "technology", station: "technology",
    packIds: ["networked-ecosystems", "partnerships-prosperity", "cognition-to-intelligence"],
    regulation: "EU AI Act", section: "Art. 53(1)(a)-(d) — general-purpose AI model provider obligations",
    question: "If you provide a general-purpose AI model behind the agent, do you keep its technical documentation current, give downstream providers what they need, operate a copyright policy, and publish a training-content summary?",
    evaluationCriteria: ["Technical documentation maintained", "Downstream integrator information available", "Copyright compliance policy in place", "Training-content summary published"],
    levels: levels("None of the Art. 53 artefacts exist", "Some artefacts drafted", "All four artefacts exist and are current", "Artefacts versioned with each model release", "Artefacts reviewed externally and requests from integrators tracked"),
    evidenceTypes: ["technical_documentation", "integrator_pack", "copyright_policy", "training_summary"],
    source: source("Regulation (EU) 2024/1689 Art. 53 (AI Act Service Desk)", `${AI_ACT_DESK}/article-53`),
  },
  {
    id: "technology-deep-04", industry: "technology", station: "technology",
    packIds: ["networked-ecosystems", "partnerships-prosperity", "virtual-infrastructure"],
    regulation: "EU AI Act", section: "Art. 55(1) — general-purpose AI models with systemic risk",
    question: "For a general-purpose AI model with systemic risk, do you run state-of-the-art evaluations including adversarial testing, track and report serious incidents, and protect the model and its infrastructure?",
    evaluationCriteria: ["Model evaluations with adversarial testing documented", "Systemic risks assessed and mitigated", "Serious incidents tracked and reported", "Cybersecurity protection for model and infrastructure"],
    levels: levels("No systemic-risk programme", "Evaluations run without adversarial testing", "Evaluations, incident reporting and security controls documented", "Red-team findings tracked to closure", "Independent evaluation and incident reporting rehearsed with the AI Office path"),
    evidenceTypes: ["evaluation_report", "red_team_log", "incident_register", "security_assessment"],
    source: source("Regulation (EU) 2024/1689 Art. 55 (AI Act Service Desk)", `${AI_ACT_DESK}/article-55`),
  },
  {
    id: "technology-deep-05", industry: "technology", station: "technology",
    packIds: ["networked-ecosystems", "os-sustainable-outcomes"],
    regulation: "Cyber Resilience Act", section: "Art. 14 — reporting actively exploited vulnerabilities and severe incidents",
    question: "If the agent ships as a product with digital elements, can you send a 24-hour early warning and a 72-hour notification for an actively exploited vulnerability or severe incident through the CRA single reporting platform?",
    evaluationCriteria: ["Agent product in CRA scope assessed", "24h and 72h reporting path owned", "Final-report timelines tracked", "Reporting rehearsed"],
    levels: levels("No CRA reporting path", "Generic vulnerability process without CRA timelines", "24h/72h/final-report path defined with owners", "Path rehearsed and timed", "Exploitation detection feeds reporting automatically with preserved evidence"),
    evidenceTypes: ["psirt_runbook", "notification_record", "drill_timing"],
    source: source("Cyber Resilience Act — reporting obligations (European Commission)", "https://digital-strategy.ec.europa.eu/en/policies/cra-reporting"),
  },
  {
    id: "technology-deep-06", industry: "technology", station: "technology",
    packIds: ["infotainment"],
    regulation: "EU AI Act", section: "Art. 50(4) — disclosure of deep fakes by deployers",
    question: "When the agent generates or manipulates image, audio or video that is a deep fake, does the deploying service disclose that the content is artificially generated or manipulated?",
    evaluationCriteria: ["Deep-fake-capable features inventoried", "Disclosure shown with the content", "Disclosure survives sharing and download", "Exceptions documented"],
    levels: levels("Deep fakes published with no disclosure", "Disclosure in terms of use only", "Visible disclosure attached to every deep fake", "Disclosure persistence tested across sharing paths", "Disclosure coverage monitored with alerts on gaps"),
    evidenceTypes: ["feature_inventory", "ui_capture", "persistence_test"],
    source: aiActSource("article-50"),
  },
  {
    id: "technology-deep-07", industry: "technology", station: "technology",
    packIds: ["cognition-to-intelligence", "infotainment"],
    regulation: "EU AI Act", section: "Art. 50(3) — informing people exposed to emotion recognition or biometric categorisation",
    question: "If the agent infers emotions or sorts people into biometric categories, are the people exposed to it informed that the system is operating?",
    evaluationCriteria: ["Emotion-recognition and biometric-categorisation features identified", "Exposed people informed", "Personal data processed lawfully for the feature", "Feature disabled where it would be prohibited"],
    levels: levels("Feature runs without informing anyone", "Notice buried in a policy", "People informed at the point of exposure", "Notices audited for every deployment context", "Feature use reviewed against Art. 5 prohibitions before each new context"),
    evidenceTypes: ["feature_inventory", "notice_text", "deployment_review"],
    source: aiActSource("article-50"),
  },
  {
    id: "technology-deep-08", industry: "technology", station: "technology",
    packIds: ["infotainment", "dance-of-democracy"],
    regulation: "Digital Services Act", section: "Art. 34 — systemic risk assessment by very large online platforms and search engines",
    question: "If the agent runs on a very large online platform or search engine (more than 45 million monthly EU users), is it included in the annual systemic risk assessment, covering illegal content, fundamental rights, civic discourse and public security?",
    evaluationCriteria: ["Agent features in the systemic risk assessment scope", "Risks to fundamental rights and civic discourse assessed", "Mitigations recorded", "Assessment evidence available to the annual independent audit"],
    levels: levels("Agent outside the systemic risk assessment", "Agent mentioned without risk analysis", "Agent risks assessed with mitigations recorded", "Mitigation effectiveness measured between assessments", "Audit findings on the agent closed with evidence"),
    evidenceTypes: ["systemic_risk_assessment", "mitigation_register", "audit_report"],
    source: source("Very large online platforms and search engines (European Commission)", "https://digital-strategy.ec.europa.eu/en/policies/dsa-vlops",
      "Commission page confirms the 45 million user threshold, the duty to identify, analyse and assess systemic risks, and the annual independent audit; article numbers come from the Regulation's structure, not read from the DSA text.", true),
  },
  {
    id: "technology-deep-09", industry: "technology", station: "technology",
    packIds: ["networked-ecosystems"],
    regulation: "Data Act", section: "Art. 3(1) — product data accessible to the user by design",
    question: "Where the agent is part of a connected product, is the product data it generates easily and securely accessible to the user, free of charge, in a structured, commonly used, machine-readable format?",
    evaluationCriteria: ["Product data generated by the agent inventoried", "User access path exists without charge", "Format structured and machine-readable", "Access secured and authenticated"],
    levels: levels("Users cannot obtain the data", "Data available on request only, in ad hoc formats", "Self-service access in a machine-readable format at no charge", "Access completeness checked against the data inventory", "Access path tested on every product release"),
    evidenceTypes: ["data_inventory", "access_api_spec", "release_test"],
    source: source("Regulation (EU) 2023/2854 (Data Act), EUR-Lex", "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32023R2854"),
  },
  {
    id: "technology-deep-10", industry: "technology", station: "technology",
    packIds: ["cognition-to-intelligence"],
    regulation: "GDPR", section: "Art. 22(1) — decisions based solely on automated processing",
    question: "Does the agent avoid making decisions with legal or similarly significant effects on people based solely on automated processing, unless an exception applies and safeguards such as human intervention are in place?",
    evaluationCriteria: ["Solely automated decisions identified", "Legal or similarly significant effects assessed", "Applicable exception documented", "Human intervention and contest path available"],
    levels: levels("Significant decisions made solely by the agent with no exception analysis", "Decisions listed without legal analysis", "Each solely automated decision has a documented exception and human intervention path", "Human interventions tracked and their outcomes reviewed", "Decision logic explanations and contest outcomes audited"),
    evidenceTypes: ["decision_inventory", "dpia", "human_review_log"],
    source: source("Regulation (EU) 2016/679 (GDPR), EUR-Lex", "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679",
      "Art. 22(1) was read on EUR-Lex; the exceptions in Art. 22(2) and the safeguards in Art. 22(3) are paraphrased in the question and were not re-read.", true),
  },];
