/** AUTHORED UNEXECUTED. Original binary fixtures and actual ACP/driver/runtime.
 * No test-owned workspace, credential store, HTTP peer or child starts at import.
 * Scripted bytes are the HTTP edge only, never a core success substitute.
 */
import { randomUUID } from "node:crypto";
import { hostname } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { expect } from "vitest";
import { createAcpAgent } from "../../src/acp/acpAgentServer.js";
import { prepareAcpNativeSession } from "../../src/acp/acpNativeSession.js";
import { acpRouteFor } from "../../src/acp/acpStdioMain.js";
import { paramsFor } from "../../src/cli-agent-options.js";
import type { AgentSession, AgentSessionInit } from "../../src/agent/agentSession.js";
import { AgentDriver } from "../../src/agent/agentDriver.js";
import { readAgentRunSummary } from "../../src/agent/runReport.js";
import type { LoopHooks } from "../../src/agent/loopTypes.js";
import { LocalCredentialsService } from "../../src/credentials/localCredentialsService.js";
import { AdapterRegistry } from "../../src/llm/adapter/adapterRegistry.js";
import { LlmRuntime } from "../../src/llm/adapter/llmRuntime.js";
import type { HttpRequest, HttpTransport } from "../../src/llm/adapter/transport.js";
import { SessionService } from "../../src/session/sessionService.js";
import { sha256Hex } from "../../src/utils/hash.js";
import { NATIVE_AUDIO_INPUT_FORMAT, type NativeAudioInput, type NativeAudioPart } from "../../src/attachments/nativeAudioInput.js";
import { orderedCleanup, orderedWorkspace, type Frame } from "./nativeOrderedImageHarness.js";
import { imageInput, IMAGE_PNG_BASE64 } from "./nativeAcpImageRuntime.js";
import { geminiFrame, geminiResponse } from "./nativeGeminiStream.js";

/** Two signed PCM samples include non-UTF8 binary; not a speech/transcription oracle. */
export function wavBytes(sample = 0xff81, dataLength = 4): Buffer {
  if (dataLength < 2 || dataLength % 2 !== 0) throw new Error("Fixture PCM sample framing");
  const bytes = Buffer.alloc(44 + dataLength);
  bytes.write("RIFF", 0, "ascii"); bytes.writeUInt32LE(bytes.length - 8, 4); bytes.write("WAVEfmt ", 8, "ascii");
  bytes.writeUInt32LE(16, 16); bytes.writeUInt16LE(1, 20); bytes.writeUInt16LE(1, 22);
  bytes.writeUInt32LE(16000, 24); bytes.writeUInt32LE(32000, 28); bytes.writeUInt16LE(2, 32); bytes.writeUInt16LE(16, 34);
  bytes.write("data", 36, "ascii"); bytes.writeUInt32LE(dataLength, 40); bytes.writeUInt16LE(sample, 44);
  return bytes;
}
export const audioInput = (sample = 0xff81): NativeAudioInput => ({ filename: "original.wav", mediaType: "audio/wav", bytes: wavBytes(sample) });
export function audioParts(): NativeAudioPart[] {
  return [{ type: "text", text: "  before\n" }, { type: "audio", audio: audioInput() }, { type: "text", text: "" },
    { type: "image", image: imageInput() }, { type: "text", text: "between α" },
    { type: "audio", audio: { ...audioInput(0x80ff), filename: "second.wav" } }, { type: "text", text: "after  " }];
}
export function audioBlocks() {
  return [{ type: "text", text: "  before\n" }, { type: "audio", mimeType: "audio/wav", data: wavBytes().toString("base64") },
    { type: "text", text: "" }, { type: "image", mimeType: "image/png", data: IMAGE_PNG_BASE64 },
    { type: "text", text: "between α" }, { type: "audio", mimeType: "audio/wav", data: wavBytes(0x80ff).toString("base64") },
    { type: "text", text: "after  " }];
}
/** Independent wire oracle, not generated by a production encoder. */
export function expectedAudioWire() {
  return [{ text: "  before\n" }, { inlineData: { mimeType: "audio/wav", data: wavBytes().toString("base64") } }, { text: "" },
    { inlineData: { mimeType: "image/png", data: IMAGE_PNG_BASE64 } }, { text: "between α" },
    { inlineData: { mimeType: "audio/wav", data: wavBytes(0x80ff).toString("base64") } }, { text: "after  " }];
}
export const audioRequest = (sessionId: string, prompt: unknown[] = audioBlocks()) => ({ sessionId, prompt,
  _meta: { "dev.agentmaturity.amc": { inputFormat: NATIVE_AUDIO_INPUT_FORMAT } } });
export const AUDIO_USAGE = { promptTokenCount: 12, cachedContentTokenCount: 5, candidatesTokenCount: 4, thoughtsTokenCount: 3, totalTokenCount: 19,
  promptTokensDetails: [{ modality: "TEXT", tokenCount: 2 }, { modality: "IMAGE", tokenCount: 1 }, { modality: "AUDIO", tokenCount: 9 }],
  cacheTokensDetails: [{ modality: "AUDIO", tokenCount: 5 }], candidatesTokensDetails: [{ modality: "TEXT", tokenCount: 4 }] };
export const audioResponse = (id = "audio-fixture") => geminiResponse([geminiFrame(['{"text":"Original audio fixture answer","thoughtSignature":"YQ=="}'], id, "STOP", AUDIO_USAGE)]);
const fixtures: { close(): Promise<void> }[] = [];
export const audioWorkspace = orderedWorkspace;
export async function audioCleanup(): Promise<void> {
  try { for (const fixture of fixtures.splice(0).reverse()) await fixture.close(); }
  finally { await orderedCleanup(); }
}
export function audioHarness(workspace: string, options: { provider?: string; transport?: HttpTransport; hooks?: LoopHooks; policyDigest?: string; audioInput?: boolean } = {}) {
  const configured = acpRouteFor({ workspace, agentId: "default", providerId: options.provider ?? "gemini-audio", model: "fixture-model", systemPrompt: "Audio fixture" });
  if ("error" in configured) throw new Error(configured.error);
  const route = { ...configured, credentialRef: null }, registry = new AdapterRegistry(); registry.register(route);
  const credentials = new LocalCredentialsService({ env: {}, projectDir: null, homeDir: join(workspace, "empty-home"), includeDotenv: false, watch: false });
  const sessions = new Map<string, AgentSession>(), sent: HttpRequest[] = [], frames: Frame[] = [];
  const pending = new Map<number, (frame: Frame) => void>(); let serial = 0, response = 0;
  const transport: HttpTransport = async request => {
    sent.push({ ...request, headers: { ...request.headers }, body: Buffer.from(request.body) });
    return options.transport ? options.transport(request) : audioResponse(`audio-${++response}`);
  };
  const factory = async (sessionId: string, signal: AbortSignal, resume: boolean): Promise<AgentSession> => {
    const init: AgentSessionInit & { sessionId: string } = { workspace, sessionId, agentId: "default", tools: "none", maxSteps: 3,
      route: { providerId: route.providerId, model: "fixture-model", params: paramsFor(route.providerId, 64) },
      systemPrompt: "Audio fixture", harnessVersion: "native-audio-fixture", compositionDigest: sha256Hex(`audio:${route.adapter.encoderVersion}`),
      policyDigest: options.policyDigest ?? sha256Hex("audio-fixture:no-tools"), makeLlm: session => new LlmRuntime({ session, registry, credentials, transport }) };
    let session: AgentSession;
    if (options.hooks) {
      if (resume) throw new Error("Hook fixture cannot resume");
      const writer = new SessionService(workspace); writer.open(init); const system = writer.recordSystemPrompt(init.systemPrompt);
      const driver = new AgentDriver({ session: writer, llm: init.makeLlm(writer), route: init.route, systemPromptEventId: system.eventId,
        hooks: options.hooks, config: { maxStepsPerTurn: 3 } });
      const run = async (submit: () => void) => { submit(); await driver.whenIdle(); const summary = readAgentRunSummary(workspace, sessionId, driver.status);
        return driver.status === "failed" || summary.unsignedRows ? { ok: false as const, reason: "real fixture driver failed" }
          : { ok: true as const, text: summary.assistantText.join("\n"), status: driver.status, validation: summary.validation }; };
      session = { sessionId, readEvents: () => writer.readEvents(), prompt: (text, images) => run(() => { driver.followup(text, images); }),
        promptParts: parts => run(() => { driver.followupParts(parts); }), promptAudioParts: parts => run(() => { driver.followupAudioParts(parts); }),
        cancel: (cause, by) => driver.cancel(cause, { by, keepInbox: true }), close: () => { writer.close({ reason: "fixture-completed" }); } };
    } else session = await prepareAcpNativeSession({ session: init, signal, onApprovalRaised: () => {},
      ...(resume ? { claimant: { pid: process.pid, hostId: hostname(), bootId: randomUUID(), startedAt: Date.now() } } : {}) });
    sessions.set(sessionId, session); return session;
  };
  const agent = createAcpAgent({ workspace, agentId: "default", orderedImageInput: true, audioInput: options.audioInput ?? true,
    promptRoute: registry.pin({ providerId: route.providerId, model: "fixture-model" }), write: bytes => {
      for (const line of bytes.toString("utf8").trimEnd().split("\n")) { const frame = JSON.parse(line) as Frame; frames.push(frame); if (frame.id !== undefined) pending.get(frame.id)?.(frame); }
    }, sessionFactory: ({ sessionId, signal }) => factory(sessionId, signal, false),
    ...(options.hooks ? {} : { resumeSessionFactory: ({ sessionId, signal }: { sessionId: string; signal: AbortSignal }) => factory(sessionId, signal, true) }) });
  const begin = (method: string, params: unknown) => {
    const id = ++serial, bytes = Buffer.from(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n");
    const result = new Promise<Frame>((resolve, reject) => {
      const timer = setTimeout(() => { pending.delete(id); reject(new Error(`Audio ACP fixture timed out: ${method}`)); }, 15_000);
      pending.set(id, frame => { clearTimeout(timer); pending.delete(id); resolve(frame); });
    });
    agent.connection.ingest(bytes); return { bytes, result };
  };
  let closed: Promise<void> | undefined;
  const close = () => closed ??= (async () => { try { await agent.close(); } finally { await credentials.close(); } })();
  const fixture = { agent, sessions, sent, frames, begin, close, call: (method: string, params: unknown) => begin(method, params).result,
    cancel: (sessionId: string) => agent.connection.ingest(Buffer.from(JSON.stringify({ jsonrpc: "2.0", method: "session/cancel", params: { sessionId } }) + "\n")) };
  fixtures.push(fixture); return fixture;
}
export async function openedAudio(root = audioWorkspace(), options: Parameters<typeof audioHarness>[1] = {}) {
  const h = audioHarness(root, options), initialized = await h.call("initialize", { protocolVersion: 1, clientCapabilities: {} });
  expect(initialized.error).toBeUndefined();
  const created = await h.call("session/new", { cwd: root, mcpServers: [] }); expect(created.error).toBeUndefined();
  return { h, root, initialized, sessionId: created.result!.sessionId as string };
}
export function audioCold(workspace: string, sessionId: string, env: NodeJS.ProcessEnv = {}) {
  const child = spawnSync(process.execPath, ["--import", import.meta.resolve("tsx"), fileURLToPath(new URL("./nativeSignedAudioCold.ts", import.meta.url)), workspace, sessionId],
    { encoding: "utf8", timeout: 30_000, maxBuffer: 32 * 1024 * 1024, env: { ...process.env, ...env } });
  expect(child.error).toBeUndefined(); expect(child.status, child.stderr).toBe(0);
  return JSON.parse(child.stdout) as { status: string; bytes: string | null; derivedDigest: string | null; detail: string | null }[];
}
