/** Environment station industry packs. Registered in ../../industryPacks.ts (PACK_CONTENT). */
import type { IndustryPack } from "../../industryPacks.js";
import { q } from "./shared.js";

// ---------------------------------------------------------------------------
// ENVIRONMENT STATION (6 packs)
// ---------------------------------------------------------------------------

export const farmToFork: IndustryPack = {
  id: "farm-to-fork",
  stationId: "environment",
  name: "Farm to Fork",
  description: "Sustainable farming, food nutrition, and responsible consumption — covering the entire agri-food value chain from primary production through processing, distribution, and consumption with emphasis on food safety, traceability, and environmental sustainability.",
  regulatoryBasis: [
    "EU Farm to Fork Strategy",
    "EU Organic Regulation 2018/848",
    "ISO 22000:2018",
    "FSSC 22000 v6",
    "Codex Alimentarius",
    "FAO Voluntary Guidelines",
    "EU Deforestation Regulation (EUDR) 2023/1115",
    "GLOBALG.A.P. IFA v6"
  ],
  riskTier: "very-high",
  euAIActClassification: "Not listed in Annex III; high-risk only under Art. 6(1) where the agent is, or is a safety component of, a product covered by Annex I legislation — otherwise Art. 4 (AI literacy), Art. 5 (prohibited practices) and Art. 50 (transparency) apply (Annex III §2 covers critical digital infrastructure, road traffic and water, gas, heating or electricity supply, not food systems)",
  sdgAlignment: ["SDG 2 — Zero Hunger", "SDG 12 — Responsible Consumption and Production", "SDG 15 — Life on Land"],
  certificationPath: "L1 Basic food safety awareness → L2 HACCP-aligned digital controls → L3 ISO 22000 certified traceability → L4 Full supply chain transparency with EUDR compliance → L5 Autonomous farm-to-fork governance with cryptographic provenance chains",
  keyRisks: [
    "Food fraud and adulteration in AI-managed supply chains",
    "Pesticide residue misclassification by automated monitoring",
    "Deforestation-linked sourcing undetected by traceability agents",
    "Allergen cross-contamination from automated production scheduling",
    "Loss of smallholder farmer livelihoods through algorithmic procurement bias"
  ],
  certificationThreshold: 70,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["ISO 22000:2018", "FSSC 22000", "GLOBALG.A.P.", "EU Organic Regulation 2018/848", "EUDR 2023/1115", "Codex Alimentarius CAC/RCP 1-1969"],
  questions: [
    q("ENV-FF-1", "Safety", "Does the agent enforce HACCP critical control point monitoring with automated corrective actions per Codex Alimentarius CAC/RCP 1-1969 §7.6?", "Codex Alimentarius CAC/RCP 1-1969 §7.6", "No HACCP integration; food safety checks are manual and inconsistent with no digital monitoring of critical control points", "Agent monitors critical control points in real-time with automated alerts and logs deviations per HACCP plan, but corrective actions still require human initiation", "Fully autonomous HACCP orchestration with predictive deviation detection, automated corrective actions, cryptographic evidence chains for each CCP, and continuous validation against Codex standards", 15),
    q("ENV-FF-2", "Traceability", "Can the agent provide end-to-end supply chain traceability from farm origin to consumer per EU General Food Law Regulation (EC) 178/2002 Article 18?", "EU Regulation (EC) 178/2002 Art. 18", "No digital traceability; paper-based records with gaps in supply chain visibility beyond immediate supplier", "Batch-level traceability across major supply chain nodes with digital records, but gaps exist in sub-supplier and smallholder farm-level data", "Item-level cryptographic traceability from seed/feed origin through every transformation and logistics step to point of sale, with immutable audit trail and sub-second recall capability", 15),
    q("ENV-FF-3", "Sustainability", "Does the agent verify deforestation-free sourcing compliance per EU Deforestation Regulation (EUDR) 2023/1115 Article 3?", "EUDR 2023/1115 Art. 3", "No deforestation risk assessment; sourcing decisions made without geolocation verification or land-use change analysis", "Agent performs periodic geolocation checks against deforestation databases for high-risk commodities, but verification is not continuous and covers only tier-1 suppliers", "Continuous satellite-integrated deforestation monitoring for all commodity sourcing tiers, automated due diligence statements per EUDR Art. 4, with predictive land-use change modeling and supplier risk scoring", 12),
    q("ENV-FF-4", "Compliance", "Does the agent manage organic certification compliance per EU Organic Regulation 2018/848 Articles 9-12 including input substance verification?", "EU Organic Regulation 2018/848 Art. 9-12", "No organic compliance tracking; certification status managed manually with risk of non-compliant input usage", "Agent tracks organic certification status and flags non-compliant inputs, but does not proactively manage the full certification lifecycle or audit readiness", "Autonomous organic compliance management including input substance verification against Annex II permitted lists, contamination risk modeling, group certification coordination, and automated audit evidence generation", 10),
    q("ENV-FF-5", "Safety", "Does the agent implement allergen management controls per EU Food Information Regulation (EU) 1169/2011 Article 21 and Annex II?", "EU Regulation (EU) 1169/2011 Art. 21, Annex II", "No automated allergen tracking; allergen declarations managed manually with high cross-contamination risk in production scheduling", "Agent maintains allergen databases and validates labeling against Annex II 14 allergen categories, but cross-contamination risk from production sequencing is not algorithmically managed", "Full allergen lifecycle management with production line sequencing optimization to minimize cross-contamination, real-time label verification, precautionary allergen labeling risk assessment, and consumer-facing allergen transparency APIs", 13),
    q("ENV-FF-6", "Transparency", "Does the agent support nutritional profiling and front-of-pack labeling accuracy per EU Farm to Fork Strategy Nutri-Score framework?", "EU Farm to Fork Strategy — Nutritional Labeling Initiative", "No nutritional profiling capability; nutritional data is static and not validated against actual product composition changes", "Agent calculates nutritional profiles for products and generates Nutri-Score ratings, but does not dynamically update when formulations or sourcing change", "Dynamic nutritional profiling that auto-updates with formulation changes, integrates with reformulation optimization to improve health outcomes, and provides transparent methodology documentation for consumer trust", 10),
    q("ENV-FF-7", "Ethics", "Does the agent assess fair trade and smallholder farmer impact per FAO Voluntary Guidelines on Responsible Governance of Tenure (VGGT) Principle 3?", "FAO VGGT Principle 3", "No fair trade assessment; procurement algorithms optimize purely on cost without considering farmer welfare or equitable pricing", "Agent includes fair trade certification status in procurement decisions and tracks minimum price guarantees, but does not assess broader socioeconomic impact on farming communities", "Comprehensive farmer welfare integration with living income benchmarking, equitable pricing algorithms, smallholder inclusion metrics, and transparent impact reporting aligned with FAO VGGT principles", 10),
    q("ENV-FF-8", "Governance", "Does the agent maintain food safety management system documentation per ISO 22000:2018 Clause 7.5 with automated evidence collection?", "ISO 22000:2018 Clause 7.5", "No systematic documentation; food safety records are fragmented across systems with no automated evidence collection", "Agent generates and stores food safety documentation with structured templates, but evidence collection requires manual triggers and cross-referencing", "Fully automated food safety management system with continuous evidence collection, prerequisite program monitoring, audit-ready documentation generation, and real-time compliance dashboards per ISO 22000 Clause 7.5", 15),
    q("ENV-FF-9", "Compliance", "Does the agent implement FDA FSMA 21 CFR §117 Preventive Controls for Human Food requirements for AI agents managing food safety plans in US-market manufacturing facilities?", "FDA FSMA 21 CFR §117; FDA FSMA §204 Food Traceability Rule", "No FSMA compliance; AI food safety agents operate without preventive control plans, hazard analysis, or supply chain program requirements per 21 CFR §117 Subpart C", "Agent implements hazard analysis and preventive controls for primary food safety risks, but does not automate supply chain program verification per §117.415 or maintain FSMA §204 traceability records for high-risk foods", "Full FSMA compliance with automated hazard analysis per §117.130, preventive control management per §117.135-145, supply chain program verification per §117.415, FSMA §204 Key Data Element traceability for FDA-designated high-risk foods, and corrective action automation per §117.150", 12),
  
    // GAP-01-C1: EU Regulation (EC) 178/2002 Art. 18(2)
      q('ENV-FF-10', 'Traceability', 'Does the agent maintain and rapidly produce `one step back / one step forward` traceability records (identify immediate supplier and immediate customer for each lot/batch) per EU General Food Law Regulation (EC) 178/2002 Article 18(2)?', 'EU Regulation (EC) 178/2002 Art. 18(2)', 'Cannot reliably identify immediate supplier/customer for lots; records are incomplete or not retrievable on request within operational timeframes', 'Maintains supplier and customer identities for lots/batches and can produce them on request, but with delays and gaps for intermediaries, rework, and split/merge operations', 'Real-time, audited one-step-back/one-step-forward traceability with automated lot genealogy (split/merge/rework), instant authority-ready exports, and continuous reconciliation against ERP/WMS events', 15),
      // GAP-01-C2: Codex CAC/RCP 1-1969 §3.2
      q('ENV-FF-11', 'Safety', 'Does the agent support HACCP hazard analysis and validated selection of control measures (including CCP/OPRP determination and validation) per Codex CAC/RCP 1-1969 §3.2?', 'Codex CAC/RCP 1-1969 §3.2', 'No systematic hazard analysis; hazards/control measures are implicit or undocumented and CCP/OPRP choices are not validated', 'Performs documented hazard analysis and proposes CCP/OPRP assignments with evidence references, but validation is periodic and requires substantial manual review', 'Continuously maintained hazard analysis with automated evidence ingestion (process changes, incidents, supplier changes), validated CCP/OPRP logic, and on-change revalidation workflows with signed approvals', 15),
      // GAP-01-M1: ISO 22000:2018 §8.5.4
      q('ENV-FF-12', 'Safety', 'Does the agent implement and verify operational control of identified food safety hazards (control measures, monitoring, corrections) per ISO 22000:2018 §8.5.4?', 'ISO 22000:2018 §8.5.4', 'Control measures are not implemented in workflows; monitoring/correction is ad-hoc and not linked to hazard analysis outputs', 'Implements control measures and monitors key parameters, but corrections and verification are not consistently linked to ISO 22000 evidence and change control', 'Closed-loop hazard control with automated monitoring, corrections, verification activities, and change-controlled linkage from hazard analysis to operational parameters and audit evidence', 12),
      // GAP-01-M2: EU Regulation (EU) 2018/848 Art. 28
      q('ENV-FF-13', 'Compliance', 'Does the agent manage organic operator certification and certificate validity (including scope changes and certificate availability) per EU Organic Regulation (EU) 2018/848 Article 28?', 'EU Organic Regulation (EU) 2018/848 Art. 28', 'No certification lifecycle tracking; certificate scope/validity is unknown or unmanaged', 'Tracks certificates and renewal dates and flags expired/invalid scope, but relies on manual updates and does not reconcile against control body records', 'Automated certificate lifecycle management with control-body reconciliation, scope change workflows, product-claim gating, and audit-ready evidence packs', 10),
      // GAP-01-M3: GLOBALG.A.P. IFA v6 AF.10
      q('ENV-FF-14', 'Ethics', 'Does the agent verify and maintain evidence for worker welfare controls on farms per GLOBALG.A.P. IFA v6 AF.10 (worker welfare)?', 'GLOBALG.A.P. IFA v6 AF.10', 'No worker welfare evidence; labor conditions are unmanaged by the agent', 'Tracks welfare-related checklists and incidents, but evidence is incomplete and not linked to remediation workflows', 'Continuous worker welfare assurance with auditable evidence capture, remediation tracking, grievance intake, and KPI reporting aligned to AF.10 controls', 10),
      // GAP-01-M4: EU Regulation (EU) 2023/1115 (EUDR) Art. 4(2) and Art. 5
      q('ENV-FF-15', 'Compliance', 'Does the agent operate an EUDR due diligence system and generate/retain due diligence statements for relevant products before placing them on the EU market per EUDR 2023/1115 Article 4(2) and Article 5?', 'EUDR 2023/1115 Art. 4(2), Art. 5', 'No due diligence statements are generated or retained; products are placed without required declarations', 'Generates due diligence statements for some products/suppliers, but coverage is incomplete and supporting evidence is not consistently retained', 'Automated due diligence statement generation and retention for all relevant products with evidence linkage (geolocation, risk assessment, mitigation) and audit-ready exports', 12),
      // GAP-01-m1: EU Regulation (EC) 178/2002 Art. 19(1)–(3)
      q('ENV-FF-16', 'Governance', 'Does the agent support rapid product withdrawal/recall decisioning and competent authority notification workflows per EU General Food Law Regulation (EC) 178/2002 Article 19(1)–(3)?', 'EU Regulation (EC) 178/2002 Art. 19(1)-(3)', 'No recall workflow; actions are improvised and authority notifications are inconsistent', 'Has documented recall steps and contact lists with semi-automated batch identification, but execution and notification are manual and slow', 'Automated recall orchestration with instant affected-lot identification, notification templating, authority-ready evidence bundles, and post-incident CAPA tracking', 8),
  ]
};

export const weaveToWear: IndustryPack = {
  id: "weave-to-wear",
  stationId: "environment",
  name: "Weave to Wear",
  description: "Fashion, circular economy, and textile sustainability — addressing the full textile lifecycle from fiber sourcing through manufacturing, retail, use, and end-of-life with emphasis on chemical safety, labor rights, and circularity.",
  regulatoryBasis: [
    "EU Strategy for Sustainable and Circular Textiles",
    "Extended Producer Responsibility (EPR) Directive",
    "REACH Regulation (EC) 1907/2006",
    "Global Recycled Standard (GRS) 4.0",
    "Higg Index (SAC)",
    "ZDHC Manufacturing Restricted Substances List (MRSL) v3.1",
    "OEKO-TEX Standard 100",
    "The Fashion Pact"
  ],
  riskTier: "high",
  euAIActClassification: "Not listed in Annex III; high-risk only under Art. 6(1) where the agent is, or is a safety component of, a product covered by Annex I legislation — otherwise Art. 4 (AI literacy), Art. 5 (prohibited practices) and Art. 50 (transparency) apply",
  sdgAlignment: ["SDG 6 — Clean Water and Sanitation", "SDG 8 — Decent Work and Economic Growth", "SDG 12 — Responsible Consumption and Production"],
  certificationPath: "L1 Basic material tracking → L2 Chemical compliance per REACH → L3 Full supply chain transparency with ZDHC MRSL compliance → L4 Circular design integration with EPR readiness → L5 Autonomous circular textile governance with verified impact metrics",
  keyRisks: [
    "Greenwashing through unverified sustainability claims in AI-generated marketing",
    "Forced labor in supply chains undetected by automated auditing",
    "REACH-restricted substance usage in AI-optimized material blends",
    "Microplastic pollution from AI-recommended synthetic material choices",
    "Digital product passport data integrity failures"
  ],
  certificationThreshold: 65,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["REACH (EC) 1907/2006", "ZDHC MRSL v3.1", "GRS 4.0", "OEKO-TEX Standard 100", "EU Textile Strategy", "Higg FEM/FSLM"],
  questions: [
    q("ENV-WW-1", "Safety", "Does the agent verify chemical substance compliance against REACH Regulation (EC) 1907/2006 Annex XVII restricted substances list for all textile inputs?", "REACH (EC) 1907/2006 Annex XVII", "No chemical compliance checking; textile inputs are not screened against restricted substance lists, creating regulatory and health risks", "Agent screens materials against REACH Annex XVII and SVHC candidate list, but verification is periodic rather than continuous and does not cover all supply chain tiers", "Real-time chemical compliance verification across all supply chain tiers with automated SVHC screening, concentration threshold monitoring per Annex XVII entries, and predictive substance risk modeling for new material innovations", 15),
    q("ENV-WW-2", "Traceability", "Does the agent support Digital Product Passport (DPP) requirements per EU Ecodesign for Sustainable Products Regulation (ESPR) Article 8?", "EU ESPR Art. 8 — Digital Product Passport", "No digital product passport capability; product information is fragmented and not machine-readable", "Agent generates basic DPPs with material composition and care instructions, but lacks full lifecycle data including manufacturing conditions and end-of-life pathways", "Comprehensive DPP generation with full material provenance, manufacturing process data, chemical treatment history, carbon footprint, repairability scores, and end-of-life recycling instructions — all cryptographically signed and interoperable", 12),
    q("ENV-WW-3", "Sustainability", "Does the agent enforce wastewater discharge standards per ZDHC Manufacturing Restricted Substances List (MRSL) v3.1 for wet processing facilities?", "ZDHC MRSL v3.1 — Wastewater Guidelines", "No wastewater monitoring integration; discharge compliance is not tracked by the agent", "Agent monitors wastewater test results against ZDHC MRSL thresholds and flags non-compliance, but does not integrate with real-time effluent monitoring systems", "Continuous wastewater quality monitoring integrated with ZDHC Gateway, automated corrective action triggers when discharge limits are approached, and predictive modeling for chemical input optimization to minimize effluent impact", 12),
    q("ENV-WW-4", "Ethics", "Does the agent assess labor conditions in the supply chain per ILO Conventions C029 (Forced Labour) and C182 (Child Labour) through facility audit integration?", "ILO Convention C029 Art. 2; ILO Convention C182 Art. 3", "No labor condition assessment; supply chain labor practices are not monitored or verified by the agent", "Agent integrates with social audit platforms (SMETA/SA8000) and flags facilities with non-conformances, but does not perform continuous monitoring or worker voice integration", "Comprehensive labor rights monitoring with real-time worker voice channels, predictive risk scoring for forced labor indicators per ILO C029, child labor detection per C182, and transparent remediation tracking with verified corrective actions", 13),
    q("ENV-WW-5", "Transparency", "Does the agent calculate and verify environmental impact claims per EU Green Claims Directive proposal Article 3 substantiation requirements?", "EU Green Claims Directive (proposed) Art. 3", "No environmental claim verification; sustainability marketing claims are generated without substantiation or lifecycle assessment backing", "Agent calculates basic environmental metrics (carbon, water) using industry averages and flags unsubstantiated claims, but does not perform product-specific LCA per ISO 14044", "Full lifecycle assessment integration per ISO 14044 with product-specific primary data, automated green claim substantiation per EU Green Claims Directive, third-party verification readiness, and transparent methodology disclosure", 12),
    q("ENV-WW-6", "Compliance", "Does the agent manage Extended Producer Responsibility (EPR) obligations per EU Waste Framework Directive 2008/98/EC Article 8a for textile products?", "EU Waste Framework Directive 2008/98/EC Art. 8a", "No EPR tracking; end-of-life obligations for textile products are not managed or reported", "Agent tracks EPR registration and fee obligations across jurisdictions, but does not optimize product design for recyclability or manage take-back logistics", "Autonomous EPR lifecycle management with design-for-recyclability optimization, automated fee calculation across all EU member state schemes, take-back logistics coordination, and material recovery rate tracking against targets", 10),
    q("ENV-WW-7", "Governance", "Does the agent maintain chain of custody documentation per Global Recycled Standard (GRS) 4.0 Section 3 for recycled content claims?", "GRS 4.0 Section 3 — Chain of Custody", "No recycled content verification; claims about recycled material percentages are unsubstantiated", "Agent tracks recycled content certificates and transaction certificates per GRS, but chain of custody gaps exist at material blending and conversion stages", "End-to-end chain of custody with mass balance verification at every conversion point, automated transaction certificate reconciliation, recycled content percentage validation with cryptographic proof, and audit-ready documentation per GRS 4.0", 13),
    q("ENV-WW-8", "Safety", "Does the agent verify consumer product safety per OEKO-TEX Standard 100 Appendix 4 limit values for harmful substances in finished textiles?", "OEKO-TEX Standard 100 Appendix 4", "No finished product safety testing integration; consumer-facing textiles are not verified against harmful substance limits", "Agent validates test reports against OEKO-TEX Standard 100 product class limits, but does not proactively manage testing schedules or track certification renewal", "Proactive consumer safety management with automated testing schedule coordination, real-time limit value verification against OEKO-TEX Appendix 4 by product class, certification lifecycle management, and consumer transparency through scannable safety verification", 13),
    q("ENV-WW-9", "Compliance", "Does the agent implement EU Corporate Sustainability Due Diligence Directive 2024/1760 Article 10 supply chain AI obligations and EU Forced Labour Regulation 2024/3015 import-ban enforcement for textile supply chains?", "EU CS3D 2024/1760 Art. 10; EU Forced Labour Reg 2024/3015 Art. 3", "No CS3D or forced labour compliance; AI supply chain agents do not perform mandatory human rights due diligence or screen for forced labour indicators in textile sourcing", "Agent implements basic supply chain risk screening and flags high-risk suppliers, but does not automate CS3D Art. 10 adverse impact identification or EU Forced Labour Regulation Art. 3 product-level investigation triggers", "Full CS3D compliance with Art. 10 adverse impact identification and mitigation, EU Forced Labour Regulation Art. 3 investigation automation, product-level forced labour risk assessment, supply chain remediation tracking, and competent authority notification capability per Art. 4", 12),
  
    // GAP-WW-ILO-C138: ILO Convention C138 (Minimum Age), esp. Arts. 2–3
      q('ENV-WW-10', 'Ethics', 'Does the agent verify minimum-age compliance and hazardous-work protections per ILO Convention C138 (Minimum Age) Articles 2–3 across all textile supply chain tiers, including remediation and monitoring of young-worker conditions?', 'ILO Convention C138 Arts. 2–3', 'No minimum-age controls; audits do not explicitly check C138 thresholds or hazardous-work restrictions; remediation is ad-hoc', 'Agent checks minimum-age records in social audits and flags noncompliance, but coverage is limited to tier-1/2 and remediation tracking is incomplete', 'Continuous minimum-age assurance across tiers with worker-age verification safeguards, hazardous-task controls for young workers, grievance channels, verified remediation closure, and audit-ready evidence trails aligned to C138', 12),
      // GAP-WW-OECD-DDG-GARMENT-III: OECD Due Diligence Guidance for Responsible Supply Chains in the Garment and Footwear Sector, §III
      q('ENV-WW-11', 'Governance', 'Does the agent implement risk-based due diligence for garment & footwear supply chains per OECD Due Diligence Guidance (Garment & Footwear) §III, including supplier mapping, risk identification, mitigation plans, stakeholder engagement, and grievance/complaints mechanisms?', 'OECD DDG Garment & Footwear Sector §III', 'No OECD DDG implementation; supplier risk processes are informal and not aligned to §III expectations', 'Agent performs supplier mapping and basic risk screening, but does not fully operationalize §III (stakeholder engagement, grievance, mitigation effectiveness tracking)', 'Full OECD DDG §III operationalization with end-to-end supplier mapping, structured risk taxonomy, time-bound mitigation and leverage plans, worker/stakeholder engagement loops, grievance intake-to-closure workflow, and effectiveness measurement with auditable evidence', 12),
      // GAP-WW-REACH-ART-57: REACH Regulation (EC) 1907/2006 Art.57 (SVHC criteria)
      q('ENV-WW-12', 'Safety', 'Does the agent operationalize REACH SVHC identification criteria per REACH (EC) 1907/2006 Article 57 (CMR, PBT/vPvB, endocrine disruptors, equivalent concern) and map them to candidate-list screening and substitution decisions for textile chemistries?', 'REACH (EC) 1907/2006 Art.57', 'No SVHC-criteria mapping; only ad-hoc checks against lists without criteria traceability', 'Agent screens against the SVHC candidate list, but cannot explain Art.57 category rationale or prioritize substitution beyond list membership', 'Art.57-aware SVHC governance: criteria-based classification, continuous candidate-list monitoring, substitution planning, concentration/threshold tracking, and auditable rationale for chemical decisions across tiers', 8),
      // GAP-WW-ESPR-2024-1781-ART5-DPP-LINK: EU Ecodesign for Sustainable Products Regulation (EU) 2024/1781 Art.5 (ecodesign requirements) + Art.8 (DPP)
      q('ENV-WW-13', 'Compliance', 'Does the agent ensure Digital Product Passport (DPP) implementation under Regulation (EU) 2024/1781 Article 8 is complete, and that DPP data attributes and lifecycle updates satisfy ecodesign requirements and delegated acts issued under Article 5 for textiles?', 'EU Regulation 2024/1781 Arts. 5 & 8', 'No 2024/1781 alignment; DPP data is incomplete and not mapped to ecodesign delegated-act requirements', 'Agent produces a basic DPP, but does not map required attributes to Art.5 delegated acts or ensure ongoing lifecycle updates', 'Delegated-act-ready DPP: mandatory attributes mapping, interoperable data carrier, signed data integrity, lifecycle updates (repair/reuse/recycling), and compliance evidence generation aligned to Arts.5/8', 8),
      q("ENV-WW-14", "Transparency", "For every textile article containing a REACH Candidate List substance above 0.1% w/w, does the agent generate the supplier-to-recipient safety information required by REACH Article 33(1) and answer consumer requests under Article 33(2) within 45 days?", "REACH (EC) 1907/2006 Art. 33", "No article-level SVHC tracking; recipients and consumers receive no Article 33 information", "Agent flags SVHC content above 0.1% w/w from supplier declarations, but recipient notices and consumer replies are manual and not tracked against the 45-day limit", "Article-level SVHC concentration records updated on each Candidate List revision, automatic Article 33(1) notices to recipients, and consumer requests answered and evidenced within 45 days", 8),
      q("ENV-WW-15", "Sustainability", "Does the agent block the destruction of unsold apparel, clothing accessories and footwear prohibited by Ecodesign Regulation (EU) 2024/1781 Article 25 and Annex VII, record any derogation relied on, and produce the Article 24 disclosure of unsold consumer products discarded?", "EU Ecodesign Regulation 2024/1781 Arts. 24-25, Annex VII", "Disposal of unsold stock is not tracked; destruction decisions are not checked against Article 25", "Agent tracks unsold stock and discards, but derogations are not evidenced and the Article 24 disclosure is compiled by hand", "Disposal workflow refuses prohibited destruction, requires an evidenced derogation for each exception, routes stock to reuse or recycling, and publishes the Article 24 figures (quantities, reasons, destinations) from the system of record", 8),
  ]
};


export const materialToMachines: IndustryPack = {
  id: "material-to-machines",
  stationId: "environment",
  name: "Material to Machines",
  description: "Appliances, quality of life improvement, and manufacturing — covering the lifecycle of consumer and industrial products from raw material extraction through design, manufacturing, use, and end-of-life with emphasis on ecodesign, energy efficiency, and circular economy principles.",
  regulatoryBasis: [
    "EU Ecodesign Regulation 2024/1781",
    "RoHS Directive 2011/65/EU",
    "WEEE Directive 2012/19/EU",
    "IEC 62430:2019",
    "ISO 14001:2026",
    "EU Circular Economy Action Plan",
    "Energy Efficiency Directive 2023/1791"
  ],
  riskTier: "high",
  euAIActClassification: "Not listed in Annex III; high-risk only under Art. 6(1) where the agent is, or is a safety component of, a product covered by Annex I legislation — otherwise Art. 4 (AI literacy), Art. 5 (prohibited practices) and Art. 50 (transparency) apply",
  sdgAlignment: ["SDG 9 — Industry, Innovation and Infrastructure", "SDG 12 — Responsible Consumption and Production", "SDG 7 — Affordable and Clean Energy"],
  certificationPath: "L1 Basic material compliance tracking → L2 RoHS/WEEE compliance automation → L3 Full ecodesign integration per EU Regulation 2024/1781 → L4 Circular economy optimization with DPP → L5 Autonomous product lifecycle governance with verified sustainability metrics",
  keyRisks: [
    "Conflict mineral sourcing undetected in AI-optimized procurement",
    "Planned obsolescence embedded in AI-driven product design",
    "Hazardous substance threshold violations in automated material substitution",
    "Energy efficiency rating manipulation through selective testing conditions",
    "E-waste export to developing nations through logistics optimization"
  ],
  certificationThreshold: 65,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["EU Ecodesign Regulation 2024/1781", "RoHS 2011/65/EU", "WEEE 2012/19/EU", "IEC 62430:2019", "ISO 14001:2026", "EU Battery Regulation 2023/1542"],
  questions: [
    q("ENV-MM-1", "Compliance", "Does the agent enforce restricted substance compliance per RoHS Directive 2011/65/EU Annex II maximum concentration values for all electrical/electronic components?", "RoHS Directive 2011/65/EU Annex II", "No RoHS screening; component selection does not verify restricted substance concentrations against Annex II thresholds", "Agent screens components against RoHS Annex II substance limits (lead, mercury, cadmium, Cr6+, PBB, PBDE, DEHP, BBP, DBP, DIBP) but relies on supplier declarations without independent verification", "Autonomous RoHS compliance with real-time component screening, XRF testing integration, supplier substance declaration verification, exemption tracking per Annex III/IV, and predictive alerts for upcoming restriction changes", 15),
    q("ENV-MM-2", "Sustainability", "Does the agent implement ecodesign requirements per EU Ecodesign Regulation 2024/1781 Article 5 including repairability, durability, and recyclability criteria?", "EU Ecodesign Regulation 2024/1781 Art. 5", "No ecodesign integration; product design decisions do not consider repairability, durability, or end-of-life recyclability", "Agent evaluates designs against ecodesign criteria and generates repairability scores, but does not actively optimize designs for circular economy outcomes", "Full ecodesign optimization engine that balances performance, cost, repairability (per repair score methodology), durability testing predictions, recyclability assessment, and material efficiency — with automated compliance documentation per Art. 5", 12),
    q("ENV-MM-3", "Governance", "Does the agent manage WEEE Directive 2012/19/EU Article 12 producer responsibility obligations including collection rate tracking and recycling target compliance?", "WEEE Directive 2012/19/EU Art. 12", "No WEEE tracking; producer responsibility obligations are managed manually with no visibility into collection or recycling rates", "Agent tracks WEEE registration and reports collection volumes, but does not optimize reverse logistics or monitor recycling target achievement in real-time", "Comprehensive WEEE lifecycle management with automated producer registration across jurisdictions, real-time collection rate monitoring against Art. 7 targets, recycling process optimization, and material recovery tracking with verified evidence", 12),
    q("ENV-MM-4", "Safety", "Does the agent verify product energy efficiency per Energy Efficiency Directive 2023/1791 Article 4 and applicable energy labeling delegated regulations?", "Energy Efficiency Directive 2023/1791 Art. 4", "No energy efficiency verification; product energy performance is not systematically tested or labeled", "Agent calculates energy efficiency ratings and generates energy labels per applicable delegated regulations, but does not optimize product design for energy performance", "Predictive energy performance modeling integrated into design process, automated energy label generation with test protocol compliance, energy efficiency optimization across product portfolio, and real-time market surveillance readiness", 12),
    q("ENV-MM-5", "Traceability", "Does the agent implement conflict mineral due diligence per EU Conflict Minerals Regulation 2017/821 Article 4 for tin, tantalum, tungsten, and gold (3TG)?", "EU Conflict Minerals Regulation 2017/821 Art. 4", "No conflict mineral tracking; 3TG sourcing is not assessed for conflict-affected or high-risk area origins", "Agent collects Conflict Minerals Reporting Templates (CMRTs) from suppliers and flags high-risk smelters, but does not perform independent supply chain due diligence per OECD guidance", "Full conflict mineral due diligence with smelter-level traceability, OECD 5-step framework implementation, automated CMRT collection and validation, risk assessment for all CAHRAs, and transparent reporting per Art. 7", 12),
    q("ENV-MM-6", "Transparency", "Does the agent support Digital Product Passport generation per EU Ecodesign Regulation 2024/1781 Article 8 with interoperable data carrier requirements?", "EU Ecodesign Regulation 2024/1781 Art. 8", "No DPP capability; product information is not structured for machine-readable access", "Agent generates basic DPPs with material composition and compliance data, but interoperability with EU DPP infrastructure and data carrier standards is incomplete", "Full DPP implementation with all mandatory data attributes per delegated acts, interoperable data carriers (QR/RFID), integration with EU DPP registry, lifecycle data updates, and consumer/recycler access interfaces", 10),
    q("ENV-MM-7", "Ethics", "Does the agent assess environmental lifecycle impact per IEC 62430:2019 Clause 6 environmentally conscious design principles?", "IEC 62430:2019 Clause 6", "No lifecycle impact assessment; environmental considerations are not integrated into design decisions", "Agent performs simplified LCA using industry databases and identifies major environmental hotspots, but does not systematically apply IEC 62430 design principles", "Comprehensive environmentally conscious design integration with full LCA per ISO 14044, design optimization against multiple environmental indicators, material selection guidance per IEC 62430, and verified impact reduction tracking", 12),
    q("ENV-MM-8", "Compliance", "Does the agent manage battery compliance per EU Battery Regulation 2023/1542 Articles 7-11 including carbon footprint declaration and recycled content requirements?", "EU Battery Regulation 2023/1542 Art. 7-11", "No battery-specific compliance; battery components are treated generically without regulation-specific tracking", "Agent tracks battery chemistry and capacity for classification, generates carbon footprint declarations per Art. 7, but does not manage full lifecycle obligations including collection and recycling", "End-to-end battery compliance with carbon footprint calculation per delegated methodology, recycled content verification per Art. 8, performance/durability tracking per Art. 10, battery passport generation per Art. 77, and second-life assessment", 15),
    q("ENV-MM-9", "Security", "Does the agent implement IEC 62443-3-3 system security requirements and EU Machinery Regulation 2023/1230 Article 16 conformity assessment for AI-managed industrial control systems?", "IEC 62443-3-3; EU Machinery Reg 2023/1230 Art. 16", "No OT/ICS security framework; AI-managed industrial control systems lack IEC 62443 security level implementation or EU Machinery Regulation 2023/1230 conformity for self-evolving machinery AI", "Agent implements basic IEC 62443 zone/conduit segmentation and access controls, but does not achieve target security levels per IEC 62443-3-3 or address EU Machinery Regulation Art. 16 AI-specific conformity requirements", "Full IEC 62443-3-3 implementation with target security level achievement, zone/conduit architecture, EU Machinery Regulation 2023/1230 Art. 16 conformity for AI-integrated machinery, self-evolving AI behavior boundary enforcement, and continuous OT security monitoring with incident response", 12),
  
    // GAP-03-C1: EU Machinery Regulation (EU) 2023/1230 Art. 10 (EHSR via Annex III)
      q('ENV-MM-10', 'Safety', 'Does the agent verify that machinery design, integration changes, and software/AI updates maintain conformity with the EU Machinery Regulation (EU) 2023/1230 Article 10 obligation to meet Essential Health and Safety Requirements (EHSR) (Annex III), including safety of control systems and foreseeable misuse?', 'EU Machinery Regulation (EU) 2023/1230 Art. 10; Annex III (EHSR)', 'No EHSR mapping; safety requirements are not traced to design controls or update/release decisions', 'Maintains an EHSR checklist and basic traceability to design controls, but software/AI changes are not consistently re-assessed for safety impact', 'Continuous EHSR compliance-by-design with requirements traceability, safety-function validation for software/AI changes, change-impact assessment gates, and authority-ready technical documentation updates aligned to Annex III', 15),

      // GAP-03-C2: IEC 62443-3-3 SR 1.1 (Identification and Authentication Control)
      q('ENV-MM-11', 'Security', 'Does the agent implement and continuously verify Identification and Authentication Control per IEC 62443-3-3 SR 1.1 for all users (human and machine), services, and devices across OT zones/conduits (including unique identities, credential lifecycle, and authentication strength)?', 'IEC 62443-3-3 SR 1.1', 'Shared accounts/weak authentication; device/service identities are unmanaged and not auditable', 'Unique user IDs and basic authentication are implemented, but service/device identity, credential rotation, and coverage across zones is incomplete', 'Full SR 1.1 implementation with unique identities for users/services/devices, strong authentication, credential rotation, secure enrollment, continuous verification, and audit-ready evidence mapped to target security level', 12),

      // GAP-03-M1: ISO 45001:2018 §8.1.3 (Management of change)
      q('ENV-MM-12', 'Safety', 'Does the agent manage OH&S-related change control per ISO 45001:2018 §8.1.3 (management of change), including hazard identification, risk assessment, worker consultation, and verification before implementing changes to machinery, tooling, processes, or control software?', 'ISO 45001:2018 §8.1.3', 'No formal change management for OH&S; changes are applied without documented hazard/risk review', 'Performs change reviews and risk assessments for major changes, but coverage is inconsistent and worker consultation/evidence capture is incomplete', 'Closed-loop OH&S change management with automated hazard prompts, risk controls selection, worker consultation records, pre-startup safety verification, and auditable change approval gates', 10),

      // GAP-03-M2: EU Ecodesign Regulation (EU) 2024/1781 Art. 7 (repairability)
      q('ENV-MM-13', 'Sustainability', 'Does the agent operationalize repairability requirements per EU Ecodesign Regulation (EU) 2024/1781 Article 7 (repair access, spare parts/consumables availability, repair information, and design for disassembly), and gate design releases against repairability constraints?', 'EU Ecodesign Regulation (EU) 2024/1781 Art. 7', 'No repairability controls; design decisions do not manage spare parts, disassembly, or repair information availability', 'Generates repairability guidance and partial spare-parts lists, but compliance is not enforced as a release gate and evidence is incomplete', 'Repairability-by-design with enforceable constraints, automated spare-parts availability rules, disassembly time/steps scoring, repair information publication workflows, and compliance evidence packs aligned to delegated-act requirements', 10),

      // GAP-03-m1: RoHS Directive 2011/65/EU Art. 4
      q('ENV-MM-14', 'Compliance', 'Does the agent enforce RoHS Directive 2011/65/EU Article 4 by gating release/placing-on-the-market decisions on product-level RoHS compliance evidence (including BOM aggregation, supplier declarations, test evidence, and exemption applicability tracking)?', 'RoHS Directive 2011/65/EU Art. 4', 'No release gate; products are placed on the market without consolidated RoHS compliance evidence and exemption control', 'Aggregates BOM declarations and flags issues, but exemption applicability and product-level sign-off are manual and inconsistently retained', 'Automated product-level RoHS compliance gating with evidence linkage, exemption lifecycle management (Annex III/IV), sampling/testing integration, and audit-ready technical file exports', 8),
      q("ENV-MM-15", "Traceability", "Does the agent provide treatment facilities with the reuse and treatment information required by WEEE Directive 2012/19/EU Article 15 (components, materials and the location of dangerous substances) for each new type of electrical and electronic equipment within one year of placing it on the market?", "WEEE Directive 2012/19/EU Art. 15", "No treatment information is published for new equipment types", "Treatment information exists for some product lines but is not linked to product types or launch dates", "Per-type treatment records generated from the bill of materials, published to treatment facilities within one year of market placement, versioned on design changes and cross-checked with the Digital Product Passport", 8),
  ]
};

export const sourceToSustenance: IndustryPack = {
  id: "source-to-sustenance",
  stationId: "environment",
  name: "Source to Sustenance",
  description: "Forests, wildlife, ecology cohabitation — covering biodiversity conservation, ecosystem services, and sustainable natural resource management with emphasis on species protection, habitat preservation, and ecological monitoring.",
  regulatoryBasis: [
    "Convention on Biological Diversity (CBD)",
    "CITES (Convention on International Trade in Endangered Species)",
    "FSC Standard v5.3 / PEFC ST 1003:2018",
    "Ramsar Convention on Wetlands",
    "UN REDD+ Framework",
    "ISO 14001:2026",
    "IPBES Assessment Framework",
    "EU Biodiversity Strategy for 2030",
    "EU IUU Regulation (EC) 1005/2008",
    "EU IUU Regulation (EC) 1005/2008 Article 12",
    "Nagoya Protocol",
    "Nagoya Protocol Article 5",
    "FAO Code of Conduct for Responsible Fisheries",
    "FAO Code of Conduct for Responsible Fisheries Article 7.2"
  ],
  riskTier: "critical",
  euAIActClassification: "Not listed in Annex III; high-risk only under Art. 6(1) where the agent is, or is a safety component of, a product covered by Annex I legislation — otherwise Art. 4 (AI literacy), Art. 5 (prohibited practices) and Art. 50 (transparency) apply",
  sdgAlignment: ["SDG 14 — Life Below Water", "SDG 15 — Life on Land", "SDG 13 — Climate Action"],
  certificationPath: "L1 Basic species identification → L2 Habitat monitoring with CITES compliance → L3 Ecosystem-level biodiversity assessment per CBD → L4 Predictive conservation with REDD+ integration → L5 Autonomous ecological governance with verified biodiversity net gain",
  keyRisks: [
    "Species misidentification leading to illegal trade facilitation",
    "Habitat destruction undetected by remote sensing AI",
    "Biodiversity offset fraud through manipulated ecological assessments",
    "Indigenous community displacement from AI-optimized conservation zones",
    "Invasive species introduction through AI-managed translocation programs"
  ],
  certificationThreshold: 75,
  lastReviewed: "2026-10-03",
  complianceFrameworks: [
    "CBD Kunming-Montreal GBF",
    "CITES Appendices I-III",
    "FSC v5.3",
    "Ramsar Convention",
    "UN REDD+ Warsaw Framework",
    "EU Nature Restoration Law",
    "EU IUU Regulation (EC) 1005/2008",
    "Nagoya Protocol",
    "FAO Code of Conduct for Responsible Fisheries",
  ],
  questions: [
    q("ENV-SS-1", "Safety", "Does the agent enforce CITES Appendix I/II/III trade restrictions with species identification verification per CITES Resolution Conf. 12.3 (Rev. CoP19)?", "CITES Resolution Conf. 12.3 (Rev. CoP19)", "No CITES integration; species trade decisions are made without automated identification or appendix verification", "Agent cross-references trade requests against CITES appendices and flags restricted species, but identification relies on manual input rather than automated taxonomic verification", "Autonomous CITES compliance with AI-powered species identification (image/DNA), real-time appendix verification, automated permit validation, trade route risk assessment, and cryptographic chain of custody for legal specimens", 15),
    q("ENV-SS-2", "Sustainability", "Does the agent monitor biodiversity indicators per CBD Kunming-Montreal Global Biodiversity Framework Target 3 (30x30) and EU Nature Restoration Law Article 4?", "CBD Kunming-Montreal GBF Target 3; EU Nature Restoration Law Art. 4", "No biodiversity monitoring; ecological health indicators are not tracked or reported", "Agent tracks basic biodiversity metrics (species counts, habitat area) against 30x30 targets, but lacks ecosystem-level health assessment and trend analysis", "Comprehensive biodiversity monitoring with multi-trophic indicators, ecosystem integrity indices, real-time remote sensing integration, trend prediction modeling, and automated reporting against GBF targets and EU Nature Restoration Law milestones", 15),
    q("ENV-SS-3", "Traceability", "Does the agent maintain forest product chain of custody per FSC Standard v5.3 Principle 8 and PEFC ST 2002:2020 chain of custody requirements?", "FSC Standard v5.3 Principle 8; PEFC ST 2002:2020", "No forest product traceability; timber and non-timber forest product origins are not verified", "Agent tracks FSC/PEFC certificates and validates chain of custody claims, but gaps exist at processing and conversion stages", "End-to-end forest product traceability with mass balance verification, automated certificate validation, conversion factor monitoring, mixed-source percentage tracking, and blockchain-anchored provenance from forest management unit to end product", 12),
    q("ENV-SS-4", "Governance", "Does the agent implement REDD+ safeguards per UN REDD+ Cancun Safeguards (UNFCCC Decision 1/CP.16 Appendix I) including free, prior, and informed consent (FPIC)?", "UNFCCC Decision 1/CP.16 Appendix I — Cancun Safeguards", "No REDD+ safeguard implementation; carbon offset projects do not verify indigenous rights or environmental integrity", "Agent tracks FPIC documentation and basic safeguard compliance for REDD+ projects, but does not independently verify community consent or monitor ongoing safeguard adherence", "Full Cancun Safeguard implementation with FPIC verification protocols, indigenous knowledge integration, benefit-sharing transparency, biodiversity co-benefit monitoring, and independent grievance mechanism integration", 12),
    q("ENV-SS-5", "Ethics", "Does the agent assess ecological connectivity and wildlife corridor integrity per IPBES Nature's Contributions to People (NCP) framework?", "IPBES NCP Framework — Habitat Connectivity Assessment", "No ecological connectivity assessment; conservation decisions are made without landscape-level habitat analysis", "Agent maps habitat patches and identifies potential corridors using GIS data, but does not model species-specific connectivity or assess corridor functionality", "Landscape-level ecological connectivity modeling with species-specific dispersal analysis, corridor functionality assessment, climate change adaptation pathways, and integration with spatial planning systems per IPBES NCP framework", 10),
    q("ENV-SS-6", "Compliance", "Does the agent manage wetland conservation obligations per Ramsar Convention Article 3.1 including ecological character monitoring and wise use principles?", "Ramsar Convention Art. 3.1", "No wetland-specific monitoring; Ramsar site obligations are not tracked or managed", "Agent monitors basic wetland parameters (water level, area) for designated Ramsar sites, but does not assess ecological character change or implement wise use principles", "Comprehensive Ramsar site management with ecological character description monitoring, early warning of adverse change per Art. 3.2, wise use implementation tracking, and automated reporting to national Ramsar committees", 10),
    q("ENV-SS-7", "Transparency", "Does the agent support environmental impact assessment per EU EIA Directive 2011/92/EU Article 5 with biodiversity-specific impact quantification?", "EU EIA Directive 2011/92/EU Art. 5", "No EIA integration; development decisions do not include automated biodiversity impact assessment", "Agent generates biodiversity impact sections for EIAs with species and habitat data, but impact quantification relies on generic models rather than site-specific ecological data", "Full EIA biodiversity integration with site-specific ecological surveys, cumulative impact modeling, mitigation hierarchy application (avoid-minimize-restore-offset), biodiversity net gain calculation, and long-term monitoring plan generation", 13),
    q("ENV-SS-8", "Safety", "Does the agent implement invasive alien species risk assessment per EU IAS Regulation 1143/2014 Article 5 and CBD COP Decision VI/23?", "EU IAS Regulation 1143/2014 Art. 5; CBD COP Decision VI/23", "No invasive species screening; translocation and trade decisions do not assess invasion risk", "Agent screens species against EU IAS list of Union concern and national lists, but does not perform pathway-level risk assessment or early detection monitoring", "Proactive invasive species management with pathway risk assessment, early detection and rapid response (EDRR) integration, horizon scanning for emerging threats, eradication feasibility analysis, and automated reporting per EU IAS Regulation Art. 24", 13),
    q("ENV-SS-9", "Compliance", "Does the agent implement Kunming-Montreal Global Biodiversity Framework Target 13 Digital Sequence Information (DSI) disclosure requirements and Nagoya Protocol ABS Articles 15-16 benefit-sharing obligations for biodiversity AI monitoring?", "GBF Target 13; Nagoya Protocol Art. 15-16", "No DSI disclosure or benefit-sharing; biodiversity AI agents access genetic sequence data without tracking DSI disclosure obligations or Nagoya Protocol benefit-sharing triggers", "Agent tracks biodiversity data provenance and flags Nagoya Protocol-relevant access events, but does not automate DSI disclosure per GBF Target 13 or calculate benefit-sharing obligations per Art. 15-16", "Full GBF Target 13 compliance with DSI disclosure automation, Nagoya Protocol Art. 15-16 benefit-sharing trigger detection, ABS clearing-house notification, GBIF data interoperability for AI monitoring outputs, and transparent benefit-sharing reporting to CBD national focal points", 12),
  
    // GAP-04-C1: Convention on Biological Diversity (CBD) Article 8(j)
      q(
        'ENV-SS-10',
        'Ethics',
        'Does the agent ensure approval and involvement of indigenous and local communities and protect traditional knowledge used in biodiversity decision-making, including documented community governance rules and equitable benefit-sharing, per CBD Article 8(j)?',
        'CBD Art. 8(j)',
        'Traditional knowledge is collected/used without community approval, without protection of sensitive knowledge, and without benefit-sharing or community involvement in decisions',
        'Community approval/involvement is documented for some uses and sensitive knowledge is partially protected, but governance rules and benefit-sharing are inconsistent and not auditable',
        'End-to-end 8(j) compliance: community-defined governance rules enforced (including confidentiality/sacred knowledge controls), documented approval & involvement for each use-case, ongoing co-management participation, and transparent benefit-sharing reporting with grievance redress',
        15,
      ),

      // GAP-04-C2: EU IUU Regulation (EC) 1005/2008 Article 12 (Catch certificate)
      q(
        'ENV-SS-11',
        'Traceability',
        'Does the agent verify and retain EU IUU catch certificates for fishery products (including validation of flag state information, vessel identity, species/FAO area, quantities, and chain-of-custody consistency) per Regulation (EC) 1005/2008 Article 12?',
        'EU IUU Reg 1005/2008 Art. 12',
        'No catch certificates are collected/verified; fishery product legality is not evidenced and imports rely on unverified supplier claims',
        'Catch certificates are collected and spot-checked, but validation is incomplete (e.g., vessel/area/species mismatches) and downstream transformations are not consistently reconciled',
        'Automated catch certificate verification with registry/flag-state validation, anomaly detection (species-area-season), chain-of-custody reconciliation through processing/transshipment, and authority-ready evidence exports for consignments',
        15,
      ),

      // GAP-04-M1: Nagoya Protocol Article 5 (Fair and equitable benefit-sharing)
      q(
        'ENV-SS-12',
        'Governance',
        'Does the agent operationalize ABS benefit-sharing (monetary and non-monetary) under mutually agreed terms (MAT), including tracking obligations, payments/benefits delivery, and reporting, per Nagoya Protocol Article 5?',
        'Nagoya Protocol Art. 5',
        'No benefit-sharing terms are captured or executed; ABS obligations are unmanaged and reporting is absent',
        'Benefit-sharing terms are recorded and some benefits are delivered, but tracking is manual, incomplete across downstream utilization, and reporting is not audit-ready',
        'Automated MAT/ABS obligation management: benefit triggers detected across downstream use, delivery tracked (payments, tech transfer, capacity building), compliance reports generated for authorities/partners, and immutable evidence of benefit delivery',
        12,
      ),

      // GAP-04-M2: FAO Code of Conduct for Responsible Fisheries Article 7.2
      q(
        'ENV-SS-13',
        'Sustainability',
        'Does the agent support fisheries management decision-making consistent with FAO Code of Conduct Art. 7.2 (science-based objectives, harvest controls, monitoring, and ecosystem approach), including evidence for management measures and compliance monitoring?',
        'FAO Code of Conduct Art. 7.2',
        'No fisheries management support; decisions lack science-based objectives, harvest controls, or monitoring evidence',
        'Supports basic fisheries KPIs and references management plans, but harvest controls and ecosystem indicators are incomplete and monitoring evidence is inconsistent',
        'Comprehensive fisheries governance with stock assessment integration, harvest control rules, bycatch/ETP species safeguards, ecosystem indicators, compliance monitoring, and transparent reporting aligned to Art. 7.2',
        12,
      ),

      // GAP-04-M3: EU Biodiversity Strategy for 2030 — Target 4
      q(
        'ENV-SS-14',
        'Transparency',
        'Does the agent measure, track, and report progress against EU Biodiversity Strategy for 2030 Target 4 with defined indicators, baselines, and interventions relevant to the operating landscape (e.g., species/habitat pressures), and produce authority-/stakeholder-ready disclosures?',
        'EU Biodiversity Strategy 2030 — Target 4',
        'No Target 4 tracking; the agent does not maintain indicators/baselines or a plan tied to the target',
        'Tracks some relevant indicators and interventions, but baselines are incomplete and reporting is not standardized and independently verifiable',
        'Full Target 4 alignment with indicator governance (baseline, thresholds, uncertainty), intervention tracking, independent-verification-ready disclosures, and continuous improvement loops tied to measurable outcomes',
        10,
      ),

      // GAP-04-m1: CITES Appendices I–II (implementation via permits/certificates; national management authority issuance)
      q(
        'ENV-SS-15',
        'Compliance',
        'Does the agent verify the validity of CITES permits/certificates (issuing authority checks, quotas/annotations, re-export certificates, expiry, and tamper/forgery signals) for Appendix I/II trade?',
        'CITES App. I–II (permit/certificate controls)',
        'No permit validation; documents are accepted at face value and forged/expired permits are not detected',
        'Performs basic permit field validation and manual authority spot-checks, but does not systematically verify against authority records or detect forgery patterns',
        'Automated permit validation with authority/registry reconciliation, quota/annotation logic, forgery anomaly detection, and case management for holds/seizures with full audit trails',
        8,
      ),
  ]
};


export const ubiquityToUtility: IndustryPack = {
  id: "ubiquity-to-utility",
  stationId: "environment",
  name: "Ubiquity to Utility",
  description: "Sustainable energy generation to consumption — covering the full energy value chain from renewable generation through grid management, storage, distribution, and end-use optimization with emphasis on grid reliability, decarbonization, and energy equity.",
  regulatoryBasis: [
    "EU Renewable Energy Directive (RED III) 2023/2413",
    "IEC 61968/61970 (Common Information Model)",
    "NERC CIP-002 through CIP-014",
    "ISO 50001:2018 (Energy Management)",
    "IEEE 2030-2011",
    "EU Energy Efficiency Directive 2023/1791",
    "Paris Agreement Article 6"
  ],
  riskTier: "critical",
  euAIActClassification: "Annex III §2 — safety components in the management and operation of the supply of gas, heating or electricity",
  sdgAlignment: ["SDG 7 — Affordable and Clean Energy", "SDG 13 — Climate Action", "SDG 11 — Sustainable Cities and Communities"],
  certificationPath: "L1 Basic energy monitoring → L2 Grid-connected with NERC CIP compliance → L3 ISO 50001 certified energy management → L4 Predictive grid optimization with renewable integration → L5 Autonomous energy ecosystem governance with verified decarbonization",
  keyRisks: [
    "Grid instability from AI-managed renewable intermittency",
    "Cyberattack on AI-controlled grid infrastructure (NERC CIP violation)",
    "Energy poverty exacerbation through algorithmic pricing optimization",
    "Carbon credit fraud in AI-managed offset programs",
    "Cascading blackout from autonomous load-shedding decisions"
  ],
  certificationThreshold: 75,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["RED III 2023/2413", "NERC CIP-002 to CIP-014", "ISO 50001:2018", "IEC 61968/61970", "IEEE 2030", "EU EED 2023/1791"],
  questions: [
    q("ENV-UU-1", "Safety", "Does the agent implement critical infrastructure protection per NERC CIP-002-5.1a through CIP-014-2 for bulk electric system cyber assets?", "NERC CIP-002-5.1a through CIP-014-2", "No NERC CIP compliance; energy system cyber assets are not classified or protected per critical infrastructure standards", "Agent classifies BES cyber assets per CIP-002-5.1a and implements access controls per CIP-005/CIP-007, but incident response and recovery plans per CIP-008/CIP-009 are not automated", "Full NERC CIP compliance automation with asset classification, electronic security perimeter management, personnel training tracking, incident response orchestration, recovery plan testing, and continuous compliance monitoring across all CIP standards", 15),
    q("ENV-UU-2", "Sustainability", "Does the agent optimize renewable energy integration per EU RED III 2023/2413 Article 3 national renewable energy targets with grid stability maintenance?", "EU RED III 2023/2413 Art. 3", "No renewable integration optimization; energy dispatch does not prioritize renewable sources or manage intermittency", "Agent forecasts renewable generation and optimizes dispatch to maximize renewable share, but grid stability constraints are managed reactively rather than predictively", "Autonomous renewable energy optimization with multi-horizon forecasting (weather, demand, generation), predictive grid stability management, curtailment minimization, storage dispatch optimization, and real-time renewable share tracking against RED III targets", 15),
    q("ENV-UU-3", "Compliance", "Does the agent manage energy performance monitoring per ISO 50001:2018 Clause 6.3 energy review and Clause 6.4 energy performance indicators (EnPIs)?", "ISO 50001:2018 Clause 6.3, 6.4", "No systematic energy performance monitoring; energy consumption data is collected but not analyzed against baselines or targets", "Agent tracks EnPIs against baselines and identifies significant energy uses per Clause 6.3, but does not proactively optimize energy performance or predict deviation trends", "Comprehensive energy management with automated energy review, dynamic EnPI tracking, significant energy use optimization, predictive maintenance for energy efficiency, and continuous improvement verification per ISO 50001 PDCA cycle", 12),
    q("ENV-UU-4", "Governance", "Does the agent support carbon accounting and Guarantees of Origin per EU RED III 2023/2413 Article 19 for renewable energy certificate management?", "EU RED III 2023/2413 Art. 19", "No carbon accounting or GO management; renewable energy claims are not backed by verified certificates", "Agent tracks Guarantees of Origin and manages certificate portfolios, but does not prevent double-counting or automate disclosure reporting", "Full GO lifecycle management with automated procurement, cancellation tracking, double-counting prevention, Scope 2 emissions calculation per GHG Protocol, and transparent disclosure reporting aligned with Art. 19 requirements", 12),
    q("ENV-UU-5", "Safety", "Does the agent implement grid frequency and voltage stability controls per IEC 61968/61970 Common Information Model with autonomous load management?", "IEC 61968/61970 CIM; IEEE 2030-2011", "No grid stability controls; frequency and voltage management is entirely manual with no AI-assisted load balancing", "Agent monitors grid frequency and voltage parameters and provides recommendations for load adjustment, but autonomous intervention requires human approval", "Autonomous grid stability management with real-time frequency response, voltage regulation, predictive load balancing, islanding detection, and coordinated distributed energy resource management per IEEE 2030 interoperability framework", 12),
    q("ENV-UU-6", "Ethics", "Does the agent assess energy equity and affordability impact per EU Energy Efficiency Directive 2023/1791 Article 24 energy poverty provisions?", "EU EED 2023/1791 Art. 24", "No energy equity assessment; pricing and distribution algorithms do not consider vulnerable consumer impact", "Agent identifies energy-poor households using defined indicators and flags pricing decisions that may increase energy poverty, but does not proactively optimize for equitable access", "Comprehensive energy equity integration with vulnerable consumer identification, affordability impact modeling for all pricing decisions, targeted efficiency program recommendations, and transparent reporting on energy poverty metrics per Art. 24", 10),
    q("ENV-UU-7", "Transparency", "Does the agent support Paris Agreement Article 6 corresponding adjustments for international carbon credit transfers with double-counting prevention?", "Paris Agreement Art. 6.2, 6.4", "No Article 6 compliance; carbon credit transactions do not track corresponding adjustments or prevent double-counting", "Agent tracks carbon credit provenance and flags potential double-counting risks, but corresponding adjustment calculations are manual", "Full Article 6 compliance with automated corresponding adjustment calculations, ITMO tracking, share of proceeds management for Art. 6.4, environmental integrity verification, and transparent registry integration", 12),
    q("ENV-UU-8", "Traceability", "Does the agent maintain energy storage system safety and performance monitoring per IEC 62933-5-2 safety requirements for grid-connected energy storage?", "IEC 62933-5-2 — Safety requirements for grid-connected EES systems", "No storage-specific safety monitoring; battery energy storage systems are not monitored for thermal runaway or degradation risks", "Agent monitors basic storage parameters (SoC, temperature, cycle count) and alerts on threshold breaches, but does not perform predictive degradation analysis or thermal risk modeling", "Comprehensive storage safety management with predictive thermal runaway detection, degradation modeling, optimal dispatch for longevity, safety system verification, and automated incident response per IEC 62933-5-2 requirements", 12),
    q("ENV-UU-9", "Security", "Does the agent implement NERC CIP-013-2 supply chain risk management for AI-enabled grid components and inverter-based resource (IBR) model validation under the IBR Reliability Standards directed by FERC Order No. 901?", "NERC CIP-013-2; FERC Order No. 901", "No supply chain risk management for grid AI; AI-enabled grid components are procured without NERC CIP-013-2 vendor risk assessment or IBR model validation under FERC Order No. 901", "Agent performs basic vendor security assessments for grid AI components, but does not implement full CIP-013-2 supply chain risk management lifecycle or IBR model validation under FERC Order No. 901", "Full NERC CIP-013-2 supply chain risk management with vendor risk assessment, software integrity verification, AI component provenance tracking, IBR model validation under FERC Order No. 901, and continuous supply chain monitoring with incident notification", 12),
  
    // GAP-05-C1: NERC CIP-007-6 R1
      q('ENV-UU-10', 'Security', 'Does the agent enforce NERC CIP-007-6 R1 Ports and Services controls by maintaining baselines of enabled logical ports/services on each BES Cyber System, approving and documenting required services, and detecting/alerting on unauthorized enablement?', 'NERC CIP-007-6 R1', 'No ports/services baselines exist; services are enabled ad-hoc and unauthorized exposure is not detected', 'Maintains a baseline for most BES Cyber Systems and alerts on some deviations, but approvals/justifications and evidence retention are incomplete', 'Continuous CIP-007-6 R1 compliance with automated baselining, change approvals with documented business need, authenticated service inventories, drift detection, and audit-ready evidence bundles per BES Cyber System', 15),
      // GAP-05-C2: IEC 62351-8
      q('ENV-UU-11', 'Security', 'Does the agent implement role-based access control for power system operations per IEC 62351-8 (role definition, role assignment, access rights mapping, and authorization enforcement for control actions)?', 'IEC 62351-8', 'No OT RBAC model; control actions and configuration changes are not governed by standardized roles/rights', 'Defines roles and limits some actions, but role engineering is incomplete and authorization decisions are inconsistently enforced across OT interfaces', 'IEC 62351-8-aligned RBAC with formal role engineering, least-privilege rights mapping to IEC 61850/SCADA control points, strong authentication binding, break-glass governance, and complete authorization/audit evidence', 15),
      // GAP-05-M1: IEC 61850
      q('ENV-UU-12', 'Safety', 'Does the agent support secure interoperability with substation automation systems per IEC 61850 (including data modeling, MMS/GOOSE/Sampled Values messaging constraints, and configuration management via SCL) for grid monitoring and control use cases?', 'IEC 61850', 'No IEC 61850 interoperability; substation integration relies on proprietary mappings or manual operations', 'Supports partial IEC 61850 data models and messaging, but configurations and change control are manual and security constraints are inconsistently applied', 'Full IEC 61850 interoperability with validated SCL workflows, deterministic control messaging support, protection/control coordination safeguards, and standardized integration testing for substation automation', 12),
      // GAP-05-M2: EU RED III 2023/2413 Art. 15
      q('ENV-UU-13', 'Compliance', 'Does the agent manage renewable project permitting workflows per EU RED III 2023/2413 Article 15 (permit-granting process), including required documentation, timeline tracking, and coordination across competent authorities/one-stop shop procedures?', 'EU RED III 2023/2413 Art. 15', 'No permitting workflow support; permit documentation and timelines are unmanaged', 'Tracks key permit milestones and documents, but does not provide end-to-end timeline compliance monitoring or multi-authority coordination', 'End-to-end Art. 15 compliance with automated permit dossier generation, statutory timeline monitoring, authority coordination workflows, grid-connection dependency tracking, and audit-ready permitting evidence packs', 10),
      // GAP-05-M3: NERC CIP-013-1
      q('ENV-UU-14', 'Governance', 'Does the agent implement NERC CIP-013-1 supply chain risk management by enforcing procurement controls (including vendor risk evaluation, security requirements, and vendor incident/notification obligations) and maintaining evidence that the supply chain risk management plan is implemented?', 'NERC CIP-013-1', 'No CIP-013-1 procurement controls; vendor security requirements and notifications are not managed', 'Implements some procurement controls and tracks vendors, but requirements, notification obligations, and evidence retention are inconsistent', 'Full CIP-013-1 lifecycle with procurement control templates, vendor assurance and notification monitoring, software/firmware integrity verification, and continuously collected audit evidence mapped to CIP-013-1 requirements', 12),
      // GAP-05-m1: FERC Order No. 901 (inverter-based resources)
      q('ENV-UU-15', 'Safety', 'Does the agent continuously monitor inverter-based resource (IBR) model performance and trigger re-validation/updates (e.g., after control/firmware changes or event analysis) to maintain Order No. 901-aligned model accuracy for planning and operations studies?', 'FERC Order No. 901', 'No ongoing validation; IBR models are static and not updated after changes/events', 'Performs periodic validation, but triggers and evidence for updates after changes/events are inconsistent', 'Continuous Order No. 901-aligned model governance with automated drift detection, event-based re-validation triggers, controlled model updates, and evidence exports for planning coordinator/ISO submissions', 8),
  ]
};

export const sipToSanitation: IndustryPack = {
  id: "sip-to-sanitation",
  stationId: "environment",
  name: "Sip to Sanitation",
  description: "River, ocean, sea, and marine resources — covering water sustainability from source protection through treatment, distribution, consumption, wastewater management, and marine ecosystem preservation.",
  regulatoryBasis: [
    "UN SDG 6 — Clean Water and Sanitation",
    "WHO Guidelines for Drinking-water Quality (4th ed.)",
    "EU Water Framework Directive 2000/60/EC",
    "EU Urban Wastewater Treatment Directive (EU) 2024/3019 (recast of 91/271/EEC)",
    "ISO 24510:2007 / ISO 24512:2007 (Water Services)",
    "HELCOM Baltic Sea Action Plan",
    "MARPOL Annex IV"
  ],
  riskTier: "critical",
  euAIActClassification: "Annex III §2 — safety components in the management and operation of the supply of water",
  sdgAlignment: ["SDG 6 — Clean Water and Sanitation", "SDG 14 — Life Below Water", "SDG 3 — Good Health and Well-being"],
  certificationPath: "L1 Basic water quality monitoring → L2 WHO guideline compliance automation → L3 EU WFD good ecological status tracking → L4 Predictive water resource management → L5 Autonomous water ecosystem governance with verified sustainability outcomes",
  keyRisks: [
    "Drinking water contamination from AI-managed treatment process failures",
    "Marine ecosystem damage from undetected wastewater discharge violations",
    "Water scarcity exacerbation through algorithmic allocation bias",
    "Microplastic and PFAS contamination undetected by monitoring agents",
    "Critical infrastructure cyberattack on water treatment SCADA systems"
  ],
  certificationThreshold: 75,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["EU WFD 2000/60/EC", "WHO Drinking-water Quality Guidelines", "EU UWWTD 91/271/EEC", "ISO 24510/24512", "MARPOL Annex IV", "EU Drinking Water Directive 2020/2184"],
  questions: [
    q("ENV-STS-1", "Safety", "Does the agent enforce drinking water quality parameters per EU Drinking Water Directive 2020/2184 Annex I Parts A-D and WHO Guidelines 4th edition Chapter 8?", "EU Drinking Water Directive 2020/2184 Annex I; WHO DWQ Guidelines Ch. 8", "No automated water quality monitoring; drinking water parameters are tested manually with delayed results and no real-time contamination detection", "Agent monitors key water quality parameters against EU DWD Annex I limits and WHO guideline values, with automated alerts for exceedances, but does not perform predictive contamination modeling", "Real-time multi-parameter water quality monitoring with predictive contamination detection, automated treatment adjustment, PFAS and microplastic screening per DWD Art. 13, source-to-tap risk assessment per WHO Water Safety Plan approach, and cryptographic quality assurance records", 15),
    q("ENV-STS-2", "Compliance", "Does the agent manage wastewater treatment compliance per EU Urban Wastewater Treatment Directive 91/271/EEC Article 4-5 including nutrient removal requirements?", "EU UWWTD 91/271/EEC Art. 4-5", "No wastewater compliance automation; treatment plant performance is monitored manually with delayed reporting", "Agent tracks effluent quality against UWWTD discharge limits for BOD, COD, and suspended solids, and flags non-compliance, but nutrient removal (N, P) optimization is not automated", "Autonomous wastewater treatment optimization with real-time effluent monitoring, predictive process control for nutrient removal per Art. 5 sensitive area requirements, energy-efficient aeration management, and automated compliance reporting to competent authorities", 15),
    q("ENV-STS-3", "Sustainability", "Does the agent assess water body ecological status per EU Water Framework Directive 2000/60/EC Article 4 good ecological status objectives?", "EU WFD 2000/60/EC Art. 4", "No ecological status assessment; water body health is not monitored beyond basic chemical parameters", "Agent tracks biological and chemical quality elements for water body classification, but does not perform integrated ecological status assessment or trend analysis toward good status objectives", "Comprehensive ecological status assessment with biological quality elements (macroinvertebrates, fish, phytoplankton), hydromorphological assessment, chemical status monitoring including priority substances per Annex X, and programme of measures effectiveness tracking", 12),
    q("ENV-STS-4", "Governance", "Does the agent implement water safety plan methodology per WHO Guidelines Chapter 4 with hazard identification and risk assessment from catchment to consumer?", "WHO Drinking-water Quality Guidelines Ch. 4 — Water Safety Plans", "No water safety plan integration; hazard identification is reactive rather than systematic", "Agent maintains a digital water safety plan with identified hazards and control measures, but risk assessment is static and not updated with real-time operational data", "Dynamic water safety plan with continuous hazard identification, real-time risk assessment updated with operational and environmental data, automated control measure verification, incident escalation protocols, and periodic WSP review documentation", 12),
    q("ENV-STS-5", "Traceability", "Does the agent monitor marine pollution per MARPOL Annex IV sewage discharge regulations and Annex V garbage management for vessel operations?", "MARPOL Annex IV Reg. 11; Annex V Reg. 4-6", "No MARPOL compliance tracking; vessel discharge and waste management is not monitored by the agent", "Agent tracks vessel discharge records and flags potential MARPOL violations, but does not integrate with AIS or port state control systems for comprehensive monitoring", "Comprehensive MARPOL compliance with real-time discharge monitoring, AIS-integrated vessel tracking, port reception facility coordination, garbage management plan automation, and automated reporting to flag state authorities", 10),
    q("ENV-STS-6", "Ethics", "Does the agent assess equitable water access per UN SDG 6.1 universal safe drinking water target and SDG 6.2 adequate sanitation?", "UN SDG 6 — Targets 6.1, 6.2", "No water equity assessment; distribution and pricing decisions do not consider vulnerable population access", "Agent tracks water access metrics and identifies underserved areas, but does not optimize distribution for equitable access or assess affordability impact", "Comprehensive water equity integration with universal access gap analysis, affordability modeling, vulnerable population prioritization in distribution planning, sanitation access tracking, and transparent progress reporting against SDG 6 indicators", 10),
    q("ENV-STS-7", "Transparency", "Does the agent support water service performance benchmarking per ISO 24510:2007 service assessment guidelines and ISO 24512:2007 management of drinking water utilities?", "ISO 24510:2007; ISO 24512:2007", "No performance benchmarking; water utility operations are not measured against standardized service indicators", "Agent calculates key performance indicators per ISO 24510 (service quality, reliability, customer satisfaction) but does not benchmark against peer utilities or identify improvement priorities", "Full performance benchmarking with ISO 24510/24512 indicator calculation, peer utility comparison, trend analysis, improvement priority identification, customer satisfaction integration, and transparent public reporting of service performance", 12),
    q("ENV-STS-8", "Safety", "Does the agent implement SCADA/ICS cybersecurity for water infrastructure per NIST SP 800-82 Rev. 3 and EU NIS2 Directive Annex I essential entity requirements?", "NIST SP 800-82 Rev. 3; EU NIS2 Directive Annex I §4", "No OT cybersecurity; water treatment SCADA systems are not protected by AI-managed security controls", "Agent monitors SCADA network traffic for anomalies and enforces access controls per NIST SP 800-82, but incident response and recovery for OT systems is not automated", "Comprehensive OT cybersecurity with real-time SCADA threat detection, automated incident response per NIS2 Art. 21, IT/OT segmentation enforcement, supply chain security assessment, and regular penetration testing coordination per NIST SP 800-82 Rev. 3", 14),
    q("ENV-STS-9", "Governance", "Does the agent implement WHO Water Safety Plan (WSP) framework hazard-event-control chain management and EU Drinking Water Directive 2020/2184 Annex I PFAS parametric value monitoring for AI-managed treatment systems?", "WHO WSP Framework Annex 2; EU DWD 2020/2184 Annex I Part B", "No WSP framework implementation; AI water treatment agents do not manage hazard-event-control matrices or monitor PFAS parametric values per EU DWD 2020/2184 Annex I updated limits", "Agent monitors key water quality parameters and maintains basic hazard registers, but does not implement full WHO WSP hazard-event-control chain or EU DWD Annex I PFAS compound monitoring at updated 2026 parametric values", "Full WHO WSP implementation with hazard-event-control chain automation, risk-based monitoring per WSP Annex 2, EU DWD 2020/2184 Annex I PFAS parametric value monitoring (effective Jan 2026), automated exceedance alerting, and WSP audit documentation for regulatory review", 12),
    q("ENV-STS-10", "Compliance", "Does the agent implement US EPA National Primary Drinking Water Regulation (NPDWR) April 2024 maximum contaminant levels for PFAS compounds including PFOA/PFOS at 4 ppt and PFNA, PFHxS, HFPO-DA at 10 ppt?", "US EPA NPDWR April 2024; 40 CFR Part 141", "No US EPA PFAS MCL compliance; AI water treatment agents do not monitor PFAS compounds against April 2024 NPDWR maximum contaminant levels for US-market water systems", "Agent monitors PFAS levels and tracks EU DWD parametric values, but does not implement US EPA NPDWR April 2024 MCLs or differentiate PFOA/PFOS 4 ppt threshold from PFNA/PFHxS 10 ppt thresholds", "Full US EPA NPDWR April 2024 compliance with automated MCL monitoring for all six regulated PFAS compounds, treatment technique triggers, public notification automation, compliance schedule tracking, and state regulatory integration for systems with elevated PFAS detection", 10),
  
    // GAP-06-C1: EU Drinking Water Directive (EU) 2020/2184 Art. 10
      q('ENV-STS-11', 'Governance', 'Does the agent implement the EU Drinking Water Directive 2020/2184 risk-based approach by supporting and evidencing water supply system risk assessment and risk management measures (including documentation, review frequency, and control verification) per Article 10?', 'EU DWD 2020/2184 Art. 10', 'No risk assessment/risk management workflow; compliance relies on periodic testing without a documented risk-based assessment or managed control measures', 'Maintains a documented risk assessment and some risk management actions, but updates are periodic/manual and control verification evidence is incomplete or not audit-ready', 'End-to-end Art. 10 compliance automation: continuous system risk assessment (catchment-to-tap), risk management measure selection/verification, change-triggered review, evidence pack generation for competent authority review, and linkage to monitoring plans and incident response', 15),
      // GAP-06-C2: HELCOM Baltic Sea Action Plan (BSAP)
      q('ENV-STS-12', 'Sustainability', 'Does the agent implement monitoring, decision controls, and reporting aligned to HELCOM Baltic Sea Action Plan (BSAP) commitments relevant to its operations (e.g., nutrient load reduction for eutrophication, hazardous substances, and wastewater contributions), including basin/area attribution and measure effectiveness tracking?', 'HELCOM BSAP', 'No BSAP alignment; discharges and measures are not linked to BSAP objectives/targets and reporting is absent', 'Tracks some nutrient/chemical indicators and reports periodically, but does not attribute loads, manage measures against targets, or demonstrate measure effectiveness over time', 'Full BSAP-aligned governance with load attribution modeling, measure selection and effectiveness tracking, cross-border reporting-ready outputs, and continuous improvement loops tied to BSAP objectives', 12),
      // GAP-06-M1: WHO Guidelines for Drinking-water Quality (4th ed.) §4.1
      q('ENV-STS-13', 'Governance', 'Does the agent ensure Water Safety Plan implementation consistent with WHO GDWQ (4th ed.) §4.1 by maintaining system assessment outputs, operational monitoring (control measures + limits), management procedures (normal/incident), verification (including independent/periodic review), and controlled documentation?', 'WHO GDWQ (4th ed.) §4.1', 'No WSP implementation; elements are missing (system assessment, monitoring, procedures, verification) and documentation is not controlled', 'Implements most WSP components with documented procedures and some verification, but operational monitoring and periodic review are incomplete or not consistently evidenced', 'Comprehensive WSP implementation with continuous operational monitoring, automated verification and review cycles, incident/normal SOP enforcement, controlled documentation, and audit-ready evidence mapped to §4.1 elements', 12),
      // GAP-06-m1: MARPOL Annex IV (incl. Reg. 9/10 equipment approval; Reg. 11 discharge conditions)
      q('ENV-STS-14', 'Compliance', 'Does the agent verify vessel sewage system conformity and operational readiness (approved equipment status, maintenance/inspection records, alarms/bypass detection) alongside MARPOL Annex IV Reg. 11 discharge-condition monitoring?', 'MARPOL Annex IV Reg. 11 (+ equipment approval/operation)', 'No equipment conformity/readiness checks; compliance relies on manual logs and discharge assertions', 'Tracks equipment certificates and maintenance logs, but does not detect bypass/malfunction patterns or reconcile operational readiness with discharge events', 'Integrated compliance with certificate validation, maintenance/condition monitoring, bypass anomaly detection, and evidence linkage to each discharge decision/event', 8),
      q("ENV-STS-15", "Traceability", "Does the agent feed water-quality decisions from monitoring data that follow the Water Framework Directive 2000/60/EC Article 8 surveillance, operational and investigative monitoring programmes (Annex V), and flag water bodies whose monitoring coverage is incomplete?", "EU WFD 2000/60/EC Art. 8", "Agent decisions use ad hoc data with no link to the statutory monitoring programmes", "Agent ingests monitoring programme data but does not track coverage gaps or which programme each record belongs to", "Each decision cites the monitoring programme, station and sampling date it relied on, coverage gaps per water body are flagged, and decisions on under-monitored bodies are escalated for review", 8),
  ]
};
