/** Governance station industry packs. Registered in ../../industryPacks.ts (PACK_CONTENT). */
import type { IndustryPack } from "../../industryPacks.js";
import { q } from "./shared.js";

// ---------------------------------------------------------------------------
// GOVERNANCE STATION (5 packs)
// ---------------------------------------------------------------------------

export const digitalCitizensRights: IndustryPack = {
  id: "digital-citizens-rights",
  stationId: "governance",
  name: "Digital Citizens & Rights",
  description: "Citizen data tied with digital identity and tagged with government identities — supporting tax, travel documents, and rights to private and secure data — AI agents managing digital identity ecosystems, citizen data rights, and public trust infrastructure.",
  regulatoryBasis: ["EU eIDAS 2.0 Regulation 2024/1183", "GDPR Art. 6/9/22", "UN Guiding Principles on Business and Human Rights (UNGPs)", "EU AI Act Annex III §8", "Council of Europe AI Convention 2024", "ISO/IEC 29115:2013", "EU Digital Identity Wallet Architecture"],
  riskTier: "critical",
  euAIActClassification: "Annex III §1 (biometrics) and §5(a) (public assistance benefits and services) where used; Art. 5(1)(c) prohibits social scoring",
  sdgAlignment: ["SDG 16 — Peace, Justice and Strong Institutions", "SDG 10 — Reduced Inequalities", "SDG 17 — Partnerships for the Goals"],
  certificationPath: "L1 Basic identity verification → L2 GDPR compliant identity processing → L3 eIDAS 2.0 aligned digital identity → L4 Full EU Digital Identity Wallet compliance → L5 Autonomous citizen rights governance with verified sovereignty and contestability",
  keyRisks: ["Mass surveillance through digital identity AI integration", "Identity fraud amplification through AI-weakened verification", "Exclusion of vulnerable populations from digital identity systems", "Government data abuse enabled by AI identity correlation", "Loss of anonymous participation rights through identity AI requirements"],
  certificationThreshold: 80,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["EU eIDAS 2.0 2024/1183", "GDPR Art. 6/9/22", "EU AI Act Annex III §8", "ISO/IEC 29115:2013", "Council of Europe AI Convention 2024"],
  questions: [
    q("GOV-DCR-1", "Compliance", "Does the agent implement EU eIDAS 2.0 Regulation 2024/1183 Article 6a European Digital Identity Wallet requirements for identity verification assurance levels?", "EU eIDAS 2.0 2024/1183 Art. 6a, 8", "No eIDAS compliance; digital identity verification does not meet eIDAS assurance levels (low/substantial/high) or EU Digital Identity Wallet requirements", "Agent implements eIDAS assurance level verification for core use cases, but does not support EU Digital Identity Wallet integration or Art. 6a wallet-based identity attestation", "Full eIDAS 2.0 compliance with EU Digital Identity Wallet integration, Art. 8 assurance level high verification, qualified electronic signature support, selective disclosure of identity attributes, and cross-border recognition per Art. 6a", 20),
    q("GOV-DCR-2", "Privacy", "Does the agent prevent unlawful biometric identification per EU AI Act Article 5 prohibited practices including real-time biometric identification in publicly accessible spaces?", "EU AI Act Art. 5(1)(a)-(d)", "No safeguards against prohibited biometric AI; systems may enable real-time remote biometric identification in public spaces without exemption authorization", "Agent implements controls to prevent unauthorized biometric identification, but does not maintain comprehensive Art. 5 prohibited practice assessment or exception documentation", "Full Art. 5 compliance with prohibited practice prevention, biometric identification exception management (law enforcement exemptions with judicial authorization), impact assessment for biometric systems, and transparent prohibited practice reporting", 20),
    q("GOV-DCR-3", "Ethics", "Does the agent implement human rights impact assessment per UN Guiding Principles on Business and Human Rights §18 for AI systems affecting citizen rights?", "UNGPs §18-21; Council of Europe AI Convention 2024 Art. 5", "No human rights impact assessment; AI affecting citizen rights is deployed without systematic rights impact analysis or remediation mechanisms", "Agent performs periodic human rights impact assessment and implements identified mitigation measures, but does not maintain continuous rights monitoring or UNGPs §18-21 due diligence framework", "Full UNGPs due diligence with §18-21 human rights impact assessment, continuous rights monitoring, stakeholder consultation with affected communities, grievance mechanism per §29, and transparent human rights reporting aligned with Council of Europe AI Convention", 15),
    q("GOV-DCR-4", "Governance", "Does the agent implement data sovereignty controls ensuring citizens can access, correct, and delete government-held digital identity data per GDPR Articles 15-17 and eIDAS 2.0 Article 6a §3?", "GDPR Art. 15-17; eIDAS 2.0 Art. 6a §3", "No citizen data sovereignty; government AI systems do not support rights of access, correction, or deletion for digital identity data", "Agent supports GDPR rights requests and implements basic identity data correction, but does not provide self-sovereign identity control or eIDAS 2.0 wallet-based attribute management", "Full citizen data sovereignty with automated GDPR rights fulfillment, eIDAS 2.0 wallet attribute self-management, citizen data access dashboards, correction workflows with audit trails, and deletion with lawful retention exception management", 15),
    q("GOV-DCR-5", "Transparency", "Does the agent implement AI transparency for government identity systems per EU AI Act Articles 13-14 information obligations and Council of Europe AI Convention Article 8?", "EU AI Act Art. 13-14; CoE AI Convention Art. 8", "No AI transparency in government identity systems; citizens are unaware when AI influences identity verification, benefits access, or government service delivery", "Agent discloses AI involvement in identity processes and provides explanations for adverse AI decisions, but does not implement full EU AI Act Art. 13-14 documentation or CoE Convention Art. 8 notification", "Full AI transparency with EU AI Act Art. 13-14 system documentation, citizen notification of AI involvement, explanation of AI-influenced decisions affecting rights, contestability mechanisms, and national authority AI system register compliance", 15),
    q("GOV-DCR-6", "Safety", "Does the agent implement digital inclusion safeguards per UN Convention on the Rights of Persons with Disabilities (CRPD) Article 9 accessibility and EU Web Accessibility Directive for digital identity services?", "CRPD Art. 9; EU Web Accessibility Directive 2016/2102", "No digital inclusion; digital identity systems are inaccessible to persons with disabilities, elderly citizens, and those without digital skills", "Agent implements WCAG 2.1 AA for digital identity interfaces, but does not provide alternative access channels or implement full CRPD Art. 9 accessibility requirements", "Full digital inclusion with WCAG 2.1 AA+ implementation, CRPD Art. 9 multi-channel access (digital and non-digital), assisted identity enrollment for vulnerable populations, digital literacy support, and universal design per EU Accessibility Directive", 15),
    q("GOV-DCR-7", "Security", "Does the agent implement cryptographic security for digital identity per ISO/IEC 29115:2013 entity authentication assurance level 4 requirements and NIST SP 800-63B authenticator assurance level 3?", "ISO/IEC 29115:2013 §7.3 LoA4; NIST SP 800-63B AAL3", "No cryptographic identity security; digital identity verification relies on low-assurance credentials without phishing-resistant multi-factor authentication or hardware-bound key management", "Agent implements MFA for identity services and uses PKI certificates, but does not meet ISO/IEC 29115 LoA4 requirements or NIST SP 800-63B AAL3 hardware-bound authenticator requirements", "Full cryptographic identity security with ISO/IEC 29115 LoA4 compliance, NIST SP 800-63B AAL3 phishing-resistant authenticators, hardware security module integration, biometric binding with liveness detection, and cryptographic audit trail for all identity assertions", 15),
    q("GOV-DCR-8", "Governance", "Does the agent implement breach notification and identity compromise response per GDPR Article 33 72-hour notification and EU NIS2 Directive Article 23 for identity infrastructure incidents?", "GDPR Art. 33; EU NIS2 Art. 23", "No identity breach response; identity system incidents are handled without GDPR Art. 33 notification timelines or NIS2 significant incident escalation procedures", "Agent detects identity system anomalies and can initiate breach notification, but does not automate GDPR Art. 33 72-hour notification or NIS2 Art. 23 competent authority reporting", "Full identity incident response with automated GDPR Art. 33 notification within 72 hours, NIS2 Art. 23 significant incident reporting, affected identity holder notification per Art. 34, credential revocation workflows, and forensic-ready audit evidence preservation", 10),
    q("GOV-DCR-9", "Compliance", "Does the agent implement EU AI Act Article 5(1)(d) prohibition on AI social scoring by public authorities and Council of Europe AI Convention 2024 Article 14 remedy and procedural safeguards for citizens affected by AI identity decisions?", "EU AI Act Art. 5(1)(d); CoE AI Convention Art. 14", "No social scoring prohibition or remedy compliance; government identity AI may implement social scoring without Art. 5(1)(d) assessment and citizens lack CoE Convention Art. 14 remedy for AI-influenced identity decisions", "Agent restricts scoring-based identity decisions and provides basic appeal mechanisms, but does not implement Art. 5(1)(d) social scoring prohibition assessment or CoE Convention Art. 14 procedural safeguards", "Full EU AI Act Art. 5(1)(d) social scoring prohibition with automated detection, CoE AI Convention Art. 14 remedy and procedural safeguards, citizen notification of AI-influenced decisions, effective contestability mechanisms, and transparent governance reporting to national human rights institutions", 12),
  
    // GAP-36-C1: eIDAS 2.0 Art. 5a (EUDI Wallet); assurance level high
      q('GOV-DCR-10', 'Compliance', 'Does the agent implement eIDAS 2.0 Article 5a EU Digital Identity Wallet requirements with explicit support for wallet assurance level high, including (1) assurance claim governance, (2) evidence bundles for high assurance (issuance + authentication + attribute attestation), (3) relying-party verification flows, (4) cross-border acceptance checks, and (5) auditable wallet lifecycle controls (issuance, suspension, revocation, recovery)?', 'eIDAS 2.0 Art. 5a (EUDI Wallet); assurance level high', 'No Art. 5a wallet control: wallet assurance level high is not defined, evidenced, or auditably enforced', 'Some wallet features exist (e.g., selective disclosure), but assurance level high governance and evidence are incomplete or non-auditable', 'Full Art. 5a EUDI Wallet implementation with assurance level high governance, relying-party verification, cross-border acceptance, and auditor-ready evidence packs for issuance/authentication/attestation lifecycles', 18),

      // GAP-36-C2: EU AI Act Annex III §8 (high-risk) — lifecycle obligations
      q('GOV-DCR-11', 'Governance', 'For EU AI Act Annex III §8 high-risk use cases in digital identity and citizen-rights systems, does the agent implement the full high-risk lifecycle (risk management system, dataset governance, event logging, technical documentation, post-market monitoring, incident reporting, and a fundamental-rights impact assessment workflow for public-sector deployments), with evidence exports suitable for oversight inquiries?', 'EU AI Act Annex III §8 (high-risk) — lifecycle obligations', 'No Annex III lifecycle: identity AI lacks risk management, data governance, logging, and FRIA evidence', 'Some controls exist (e.g., transparency, incident response), but lifecycle evidence and conformity-assessment readiness are incomplete', 'Full Annex III §8 lifecycle operationalization with conformity-assessment-grade evidence packs, FRIA workflow, and ongoing monitoring/reporting', 18),

      // GAP-36-C3: GDPR Art. 9(2)(a)
      q('GOV-DCR-12', 'Privacy', 'When special-category attributes are stored or shared via the digital identity wallet, does the agent implement GDPR Art. 9(2)(a) explicit consent with (1) purpose-scoped consent prompts, (2) granular attribute-level consent, (3) withdrawal/refresh rules, (4) consent receipt + audit logs, and (5) safeguards against coerced consent in public-service contexts?', 'GDPR Art. 9(2)(a)', 'No explicit-consent controls: special-category attributes are processed/shared without explicit consent evidence or withdrawal handling', 'Consent is captured, but is not granular/purpose-scoped or lacks auditable receipts and withdrawal enforcement', 'Full Art. 9(2)(a) explicit-consent governance with granular consent receipts, withdrawal enforcement, and audit-ready logs tied to attribute disclosure events', 15),

      // GAP-36-M1: ISO/IEC 29115:2013 §7 (AL3)
      q('GOV-DCR-13', 'Security', 'Does the agent implement ISO/IEC 29115:2013 §7 assurance level AL3 for entity authentication (and map wallet flows to AL3), including identity proofing strength, authenticator requirements, binding/recovery, phishing resistance expectations appropriate to AL3, and evidence for auditors that AL3 controls are consistently applied across services?', 'ISO/IEC 29115:2013 §7 (AL3)', 'No AL3 mapping: assurance controls are inconsistent and cannot be evidenced against §7 AL3', 'Some strong auth controls exist, but AL3 mapping and audit evidence are incomplete', 'Full §7 AL3 operationalization with clear control mapping, consistent enforcement, and auditor-ready evidence packs', 12),

      // GAP-36-m1: eIDAS 2.0 (control mapping governance)
      q('GOV-DCR-14', 'Governance', 'Does the program maintain a versioned eIDAS 2.0 control-to-article mapping for the EUDI Wallet (ensuring Art. 5a anchors are used where required), with review on regulatory updates and automated checks for citation consistency across questions and outputs?', 'eIDAS 2.0 (control mapping governance)', 'No mapping governance: citations drift and requested anchors (e.g., Art. 5a) are not consistently used', 'Mapping exists but updates are manual and inconsistently applied', 'Versioned, reviewed control mapping with automated citation-consistency checks and audit-defensible references', 6),
      q("GOV-DCR-15", "Rights", "When a decision based on the output of an Annex III high-risk AI system produces legal effects for a person, can the affected person obtain a clear and meaningful explanation of the AI system's role and the main elements of the decision, as EU AI Act Article 86 provides?", "EU AI Act Art. 86", "Affected persons cannot obtain any explanation of the AI system's role", "Explanations are given on request, but they are generic and not specific to the decision", "Decision-specific explanations generated from logged inputs and outputs, delivered in plain language within a set time, and tracked through to any appeal", 8),
  ]
};

export const danceOfDemocracy: IndustryPack = {
  id: "dance-of-democracy",
  stationId: "governance",
  name: "Dance of Democracy",
  description: "Electing candidates representing constituent aspirations in the process of governing — AI agents supporting democratic processes, voter engagement, electoral integrity, and political communication with strict safeguards against manipulation and disinformation.",
  regulatoryBasis: ["EU AI Act Art. 5 (prohibited electoral manipulation)", "EU Digital Services Act Art. 34 (electoral risk)", "OSCE/ODIHR Electoral Standards", "Council of Europe Recommendation CM/Rec(2017)5", "Venice Commission AI in Elections Guidelines", "EU Code of Practice on Disinformation 2022", "GDPR Art. 9(d) (political opinion data)"],
  riskTier: "critical",
  euAIActClassification: "Annex III §8(b) — systems intended to influence the outcome of an election or referendum or voting behaviour; Art. 5(1)(a) prohibits manipulative or deceptive techniques",
  sdgAlignment: ["SDG 16 — Peace, Justice and Strong Institutions", "SDG 10 — Reduced Inequalities"],
  certificationPath: "L1 Basic electoral information services → L2 Disinformation detection → L3 Full DSA electoral risk compliance → L4 OSCE/CoE standards alignment → L5 Autonomous democratic support with verified integrity, full transparency, and anti-manipulation governance",
  keyRisks: ["Electoral manipulation through micro-targeted AI political messaging", "Voter suppression through AI-managed access to electoral information", "Disinformation amplification undermining informed voting", "Foreign interference facilitation through AI communication tools", "Algorithmic political bias affecting democratic representation"],
  certificationThreshold: 85,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["EU AI Act Art. 5(1)(a)", "EU DSA Art. 34", "EU GDPR Art. 9(d)", "Council of Europe Rec CM/Rec(2017)5", "EU Code of Practice on Disinformation 2022"],
  questions: [
    q("GOV-DD-1", "Compliance", "Does the agent strictly comply with EU AI Act Article 5(1)(a) prohibition on subliminal AI systems and techniques to manipulate electoral behavior beyond free will?", "EU AI Act Art. 5(1)(a)", "No prohibition safeguards; AI electoral services may use subliminal techniques, psychological manipulation, or behavioral exploitation to influence voting", "Agent implements basic safeguards against manipulative electoral AI, but does not maintain comprehensive Art. 5(1)(a) compliance assessment or prohibited technique prevention", "Full Art. 5(1)(a) compliance with prohibited manipulation technique prevention, AI electoral influence impact assessment, anti-manipulation testing per academic adversarial research, and transparent electoral AI governance documentation", 25),
    q("GOV-DD-2", "Safety", "Does the agent implement electoral disinformation prevention per EU Code of Practice on Disinformation 2022 Commitment 22 and DSA Article 34 electoral risk assessment for very large platforms?", "EU Code of Practice on Disinformation 2022 §22; EU DSA Art. 34", "No disinformation prevention; AI-curated electoral content amplifies false information without detection or correction mechanisms", "Agent implements fact-checking integration for electoral content and flags suspected disinformation, but does not implement DSA Art. 34 electoral risk assessment or Code of Practice Commitment 22 reporting", "Full electoral disinformation governance with DSA Art. 34 risk assessment for elections, Code of Practice Commitment 22 implementation, electoral content labeling per EU AI Act Art. 50, cross-platform coordination detection, and electoral period enhanced monitoring", 20),
    q("GOV-DD-3", "Privacy", "Does the agent protect political opinion data per GDPR Article 9(d) special category processing exemptions with minimal processing and robust access controls for electoral services?", "GDPR Art. 9(1) and 9(2)(d)", "No political data protection; electoral AI processes political opinion as regular personal data without Art. 9 special category safeguards", "Agent applies Art. 9 special category controls for explicit political data, but does not prevent inferential political profiling or implement minimal processing for voter analytics", "Full GDPR Art. 9 political data governance with processing limitation to Art. 9(2)(d) exemption scope, prohibition on political micro-targeting, voter analytics data minimization, special category DPIA, and political data processing transparency", 15),
    q("GOV-DD-4", "Transparency", "Does the agent implement electoral AI transparency per Council of Europe Recommendation CM/Rec(2017)5 §7 algorithmic transparency for political communication systems?", "CoE Rec CM/Rec(2017)5 §7; Venice Commission AI Guidelines", "No electoral transparency; AI-generated or AI-curated political content is not disclosed, and recommendation algorithms are opaque", "Agent implements basic AI content disclosure for electoral communications, but does not address CoE Rec §7 full algorithmic transparency or Venice Commission AI in elections guidance", "Full electoral AI transparency per CoE Rec §7, AI-generated electoral content labeling per EU AI Act Art. 50, recommendation algorithm transparency for political content, electoral period audit reporting, and Venice Commission guidelines compliance", 15),
    q("GOV-DD-5", "Governance", "Does the agent implement OSCE/ODIHR electoral integrity standards for AI-assisted voter registration, information services, and results management systems?", "OSCE/ODIHR Handbook on Electoral Technology; OSCE Commitments §7", "No electoral integrity controls; AI-assisted electoral administration lacks OSCE/ODIHR standards alignment or independent verification mechanisms", "Agent implements basic integrity controls for electoral AI systems, but does not implement OSCE/ODIHR election assessment framework or independent audit support", "Full OSCE/ODIHR standards alignment with electoral technology security assessment, observer access mechanisms, results management integrity verification, recount support capability, and OSCE post-election technology review documentation", 25),
    q("GOV-DD-6", "Security", "Does the agent implement cybersecurity for electoral infrastructure per CISA Election Security Guidance and EU NIS2 Article 21 essential entity requirements for voter registration and results systems?", "CISA Election Security Guidance 2024; EU NIS2 Art. 21", "No electoral cybersecurity; voter registration databases and results management systems are unprotected against adversarial attacks, supply chain compromise, or insider threats", "Agent implements basic access controls and audit logging for electoral systems, but does not apply CISA election security guidance or NIS2 Art. 21 essential entity requirements", "Full electoral cybersecurity with CISA election security guidance implementation, NIS2 Art. 21 essential entity controls, supply chain verification for electoral software, insider threat detection, penetration testing before each election cycle, and cybersecurity incident response with electoral authority coordination", 15),
    q("GOV-DD-7", "Transparency", "Does the agent implement campaign finance AI transparency per FECA (Federal Election Campaign Act) and EU political advertising transparency regulation for AI-generated political content?", "FECA 52 U.S.C. §30104; EU Political Advertising Regulation 2024", "No campaign finance transparency; AI-generated political advertising lacks mandatory disclosure, spending attribution, or regulatory compliance with campaign finance law", "Agent tracks campaign finance expenditure for AI services and provides basic disclosure, but does not implement automated FECA reporting or EU political advertising transparency regulation compliance", "Full campaign finance transparency with FECA §30104 AI expenditure reporting, EU Political Advertising Regulation compliance, AI-generated ad labeling, spending attribution, cross-platform campaign coordination monitoring, and electoral authority disclosure filing automation", 15),
    q("GOV-DD-8", "Ethics", "Does the agent implement accessibility in democratic participation per CRPD Article 29 (participation in political and public life) and HAVA (Help America Vote Act) accessibility requirements?", "CRPD Art. 29; HAVA 52 U.S.C. §21081", "No democratic accessibility; AI-mediated electoral services are inaccessible to voters with disabilities, non-native language speakers, or low digital literacy", "Agent provides accessible interfaces for core electoral information, but does not implement CRPD Art. 29 full participation requirements or HAVA accessibility mandates for voting system AI", "Full democratic accessibility with CRPD Art. 29 participation safeguards, HAVA-compliant accessible voting AI, multilingual electoral information, assisted participation for voters with disabilities, digital literacy support, and non-digital alternative channel preservation", 15),
    q("GOV-DD-9", "Compliance", "Does the agent implement EU Political Advertising Regulation 2024 transparency requirements for AI-generated political content and GDPR Article 22(4) safeguards for automated political profiling decisions?", "EU Political Advertising Reg 2024; GDPR Art. 22(4)", "No political advertising transparency or automated profiling safeguards; AI-generated political content lacks EU Political Advertising Regulation disclosure and political profiling operates without GDPR Art. 22(4) safeguards", "Agent implements basic political content labeling and restricts profiling-based targeting, but does not automate EU Political Advertising Regulation transparency requirements or GDPR Art. 22(4) suitable safeguards for political profiling", "Full EU Political Advertising Regulation compliance with AI-generated political content transparency, sponsor disclosure, targeting criteria publication, GDPR Art. 22(4) safeguards for automated political profiling, and electoral period enhanced transparency reporting", 12),
  
    // GAP-37-C1: EU AI Act Art. 5(1)(b) (prohibited exploitation of vulnerabilities; Council-required anchor)
      q('GOV-DD-10', 'Compliance', 'Does the agent strictly comply with EU AI Act Article 5(1)(b) by preventing any electoral AI technique that exploits vulnerabilities (age, disability, or social/economic situation) to materially distort voting-related behavior, including coercive targeting, suppression messaging, or undue influence that undermines free political choice?', 'EU AI Act Art. 5(1)(b)', 'No safeguards: electoral AI can target vulnerable groups with coercive or exploitative messaging to distort behavior', 'Has basic policies and some guardrails, but vulnerability exploitation is not systematically detected, tested, or prevented across targeting and content-generation pipelines', 'Full Art. 5(1)(b) compliance with vulnerability-exploitation threat modeling, pre-deployment testing/red-teaming, targeting restrictions, election-period heightened controls, monitoring for coercive patterns, and auditor-ready evidence of prohibited-practice prevention', 25),

      // GAP-37-C2: EU Digital Services Act (DSA) 2022/2065 Art. 34(1)(c) (systemic risks for electoral processes/civic discourse) + Art. 35 (mitigation)
      q('GOV-DD-11', 'Safety', 'For services in scope of DSA systemic-risk duties, does the agent perform a clause-precise DSA Article 34(1)(c) risk assessment for electoral processes and civic discourse (including recommender/ads systems, amplification dynamics, and coordinated inauthentic behavior) and implement DSA Article 35 mitigations with measurable effectiveness reporting during election periods?', 'EU DSA 2022/2065 Art. 34(1)(c), Art. 35', 'No election systemic-risk assessment or mitigation: risks to civic discourse/elections are unmanaged and unmeasured', 'Performs general misinformation review and some mitigations, but does not run an Art. 34(1)(c)-anchored assessment nor track Art. 35 mitigation effectiveness with election-period escalation', 'Full Art. 34(1)(c)/35 program with documented risk assessment, mitigation selection and effectiveness metrics, election-period escalation playbooks, independent review support, and regulator-ready evidence exports', 20),

      // GAP-37-C3: OSCE/ODIHR §3.2 (Council-required anchor)
      q('GOV-DD-12', 'Governance', 'Does the agent meet OSCE/ODIHR §3.2-aligned election technology integrity expectations by providing independent verification support (pre-election testing, audit access, observer-accessible evidence), verifiability of results processes, and transparent change-control over AI-influenced electoral workflows?', 'OSCE/ODIHR §3.2', 'No ODIHR-grade verifiability: no independent verification, limited audit access, and opaque AI influence over election workflows', 'Allows some audits and logs, but observer access, change-control transparency, and verifiability evidence are incomplete or inconsistently provided', 'Full §3.2 alignment with independent verification protocols, observer-accessible evidence packages, tamper-evident logs, strict change-control, and repeatable audit procedures for AI-influenced election operations', 20),

      // GAP-37-C4: GDPR Art. 9(1) (political opinions) and Art. 9(2)(d) (not-for-profit bodies exemption; Council-required anchor)
      q('GOV-DD-13', 'Privacy', 'Where political opinions (GDPR Art. 9(1)) are processed in electoral services, does the agent (a) determine and document whether GDPR Art. 9(2)(d) is applicable (not-for-profit body, legitimate activities, appropriate safeguards, no disclosure outside without consent), (b) enforce data minimization and access controls, and (c) prevent inferential political profiling beyond the chosen lawful basis with audit-ready evidence?', 'GDPR Art. 9(1), Art. 9(2)(d)', 'No Art. 9 governance: political opinion data is processed without a defensible Art. 9 basis, safeguards, or minimization', 'Has some special-category controls, but Art. 9(2)(d) applicability constraints, non-disclosure safeguards, and inferential profiling prevention are incomplete', 'Full Art. 9 governance with documented basis selection, enforceable safeguards/non-disclosure controls, minimization, strict access controls, DPIA/records linkage, and evidence exports for supervisory authority review', 15),

      // GAP-37-M1: Council of Europe CM/Rec(2017)5 (algorithmic systems)
      q('GOV-DD-14', 'Governance', 'Does the agent implement Council of Europe CM/Rec(2017)5-aligned accountability and remedy for electoral algorithmic systems, including clear responsibility assignment, oversight escalation, user-facing contestability/appeal pathways, and retention of evidence sufficient to support independent review during election periods?', 'CoE CM/Rec(2017)5', 'No accountability/remedy: electoral algorithmic decisions are opaque, unowned, and not meaningfully contestable', 'Provides limited appeals and some governance, but responsibilities, timelines, and evidence retention for independent review are incomplete', 'Full CM/Rec(2017)5 accountability with owned controls, escalation/oversight, contestability mechanisms, election-period SLAs, and audit-ready evidence supporting independent review and remedies', 10),

      // GAP-37-m1: Control-to-law citation governance (Council-required anchor precision)
      q('GOV-DD-15', 'Governance', 'Does the program maintain a versioned, Council-anchor-aligned control-to-law mapping for the Dance of Democracy pack (EU AI Act Art. 5(1)(b), DSA Art. 34(1)(c), OSCE/ODIHR §3.2, CoE CM/Rec(2017)5, GDPR Art. 9(2)(d)), with periodic review to prevent citation drift and ensure evidence expectations remain audit-defensible?', 'Citation mapping governance', 'No mapping governance: citations drift and requested anchors are inconsistently used', 'Mapping exists but updates are manual and inconsistently applied', 'Versioned control mapping with review workflow and automated checks for citation consistency across questions and outputs', 6),
  ]
};

export const petitionToLaw: IndustryPack = {
  id: "petition-to-law",
  stationId: "governance",
  name: "Petition to Law",
  description: "The process from petition through bill, legislation, budgetary provision, to law — AI agents supporting legislative processes, democratic drafting, public consultation, and lawmaking transparency with safeguards for democratic integrity and inclusive participation.",
  regulatoryBasis: ["UN E-Government Survey Guidelines", "EU Interoperability Framework (EIF) v2", "GDPR Art. 6(1)(e) (public task)", "US FOIA (5 U.S.C. §552)", "EU INSPIRE Directive 2007/2/EC", "ISO 25000 SQuaRE", "EU Open Data Directive 2019/1024", "UN SDG 16.6 (effective institutions)"],
  riskTier: "very-high",
  euAIActClassification: "Not listed in Annex III (§8 covers judicial authorities and election influence, not legislative drafting); Art. 50 transparency applies",
  sdgAlignment: ["SDG 16 — Peace, Justice and Strong Institutions", "SDG 17 — Partnerships for the Goals"],
  certificationPath: "L1 Basic e-petition systems → L2 Open data/FOI compliance → L3 EU EIF interoperability → L4 Full legislative AI transparency → L5 Autonomous democratic drafting support with verified inclusivity, transparency, and constitutional safeguards",
  keyRisks: ["Exclusion of marginalized voices from AI-mediated legislative processes", "Opaque AI influence on legislative drafting and law formation", "Manipulation of public consultation through AI-generated submissions", "Loss of democratic traceability in AI-assisted lawmaking", "Algorithmic bias in petitions processed determining legislative priority"],
  certificationThreshold: 78,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["EU EIF v2", "EU Open Data Directive 2019/1024", "GDPR Art. 6(1)(e)", "US FOIA (5 U.S.C. §552)", "ISO 25000 SQuaRE"],
  questions: [
    q("GOV-PL-1", "Transparency", "Does the agent implement legislative process transparency per EU EIF v2 Principle 5 (Transparency) and UN SDG 16.6 effective, accountable, and transparent institutions requirements?", "EU EIF v2 Principle 5; UN SDG 16.6", "No legislative transparency; AI involvement in drafting, analyzing, or prioritizing legislative content is not disclosed to citizens or legislators", "Agent documents AI roles in legislative processes and provides access logs, but does not implement EU EIF Principle 5 full transparency or SDG 16.6 accountability reporting", "Full legislative transparency with EU EIF Principle 5 implementation, AI involvement disclosure in all legislative activities, public-accessible legislative AI register, SDG 16.6 institution effectiveness reporting, and parliamentary accountability dashboards", 15),
    q("GOV-PL-2", "Compliance", "Does the agent implement public consultation inclusivity per UN E-Government Survey 2024 digital participation standards and OECD Recommendation on Open Government Article 2?", "UN E-Government Survey 2024; OECD OG Rec Art. 2", "No inclusive consultation; AI-mediated public participation favors digitally literate citizens and under-represents marginalized communities", "Agent provides multilingual consultation and basic accessibility, but does not implement UN E-Government participation standards or OECD OG Recommendation inclusivity requirements", "Full inclusive consultation with UN E-Government participation framework, OECD OG Art. 2 compliance, multi-channel access (digital and non-digital), minority language support, accessibility per WCAG 2.1 AA, and representativeness monitoring for consultation responses", 15),
    q("GOV-PL-3", "Governance", "Does the agent implement open legislative data per EU Open Data Directive 2019/1024 Articles 3-5 and EU INSPIRE Directive for geographic legislative data with open format publication?", "EU Open Data Directive 2019/1024 Art. 3-5; EU INSPIRE 2007/2/EC", "No open legislative data; bills, petitions, and legislative processes are not published in machine-readable open formats per EU Open Data requirements", "Agent publishes core legislative documents in open formats, but does not implement full EU Open Data Directive compliance or INSPIRE-compliant geospatial legislative data", "Full open data implementation with EU Open Data Directive Art. 3-5 compliance, INSPIRE-compliant geographic legislative data, legislative linked data publication, API access to legislative corpus, and reuse-friendly licensing per Creative Commons", 12),
    q("GOV-PL-4", "Privacy", "Does the agent protect petitioner privacy per GDPR Article 6(1)(e) public task basis and Article 9 for sensitive petitions involving special category data about signatories?", "GDPR Art. 6(1)(e); Art. 9; Art. 17", "No petitioner privacy; petition systems collect and retain signatory data beyond necessity without GDPR Art. 6(1)(e) proportionality assessment", "Agent applies GDPR lawful basis for petition processing and implements basic retention policies, but does not conduct proportionality assessments or implement Art. 9 special category protections for sensitive petition topics", "Full petition privacy with GDPR Art. 6(1)(e) proportionality assessment, Art. 9 special category protection for sensitive petitions, minimized signatory data retention, anonymized public petition reporting, and petitioner rights fulfillment automation", 12),
    q("GOV-PL-5", "Safety", "Does the agent prevent AI manipulation in legislative processes per EU AI Act Article 5 prohibited social scoring and subliminal manipulation prohibitions for government AI systems?", "EU AI Act Art. 5(1)(c)-(d)", "No legislative AI manipulation safeguards; petition prioritization and legislative AI tools may implement social scoring or manipulative techniques", "Agent implements basic safeguards against biased petition processing, but does not conduct Art. 5 prohibited practice assessment for government legislative AI", "Full Art. 5 compliance for government legislative AI with prohibited social scoring prevention, subliminal manipulation prohibition, human oversight for AI-assisted legislative drafting, and constitutional law review integration for AI-generated legislative proposals", 12),
    q("GOV-PL-6", "Traceability", "Does the agent maintain end-to-end legislative traceability from petition to enacted law per ISO 9241-210 human-centered system design and international parliamentary digital standards?", "ISO 9241-210:2019; IPU Digital Parliament Guidelines", "No legislative traceability; the connection from citizen petition through legislative stages to enacted law cannot be traced by citizens", "Agent provides basic petition status tracking and legislative stage visibility, but does not implement end-to-end traceability or IPU Digital Parliament standard compliance", "Full legislative traceability with petition-to-law journey visualization, amendment trail documentation, voting record integration, IPU Digital Parliament standards compliance, citizen notification of petition outcomes, and legislative impact assessment publication", 12),
    q("GOV-PL-7", "Governance", "Does the agent implement FOIA/access to information compliance per the EU Open Data Directive (EU) 2019/1024 re-use of public sector information (which repealed Directive 2003/98/EC) and proactive disclosure obligations?", "EU Open Data Directive 2019/1024; Council of Europe Access to Information Convention (CETS 205)", "No access to information compliance; legislative AI systems do not support FOIA requests or proactive disclosure of legislative data", "Agent supports basic information request processing and publishes selected legislative datasets, but does not implement full Open Data Directive 2019/1024 re-use framework or proactive disclosure program", "Full access to information compliance with Open Data Directive 2019/1024 re-use framework, CoE CETS 205 proactive disclosure, automated FOIA response capability, legislative data quality assurance, and open license publication for all legislative documents", 12),
    q("GOV-PL-8", "Ethics", "Does the agent implement AI ethics in government per Council of Europe AI Convention 2024 Chapter III and OECD AI Principles 1.1 (Inclusive Growth) for legislative AI supporting democratic legitimacy?", "CoE AI Convention 2024 Ch. III; OECD AI Principles 1.1", "No democratic AI ethics; legislative AI deployment lacks CoE Convention Chapter III safeguards or OECD Principle 1.1 inclusive governance assessment", "Agent implements human oversight for legislative AI decisions and basic ethics review, but does not maintain Council of Europe AI Convention Chapter III compliance or democratic legitimacy assessment", "Full democratic AI ethics with CoE AI Convention Chapter III implementation, OECD Principle 1.1 inclusive growth assessment for legislative AI, human dignity safeguards, democratic process integrity verification, and parliamentary oversight mechanism integration", 10),
    q("GOV-PL-9", "Compliance", "Does the agent implement Council of Europe AI Convention 2024 Article 10 transparency and oversight requirements for AI in legislative processes and EU Interoperability Act 2024 mandatory interoperability assessment for government AI systems?", "CoE AI Convention Art. 10; EU Interoperability Act 2024", "No CoE Convention transparency or EU Interoperability Act compliance; AI legislative process agents lack Art. 10 transparency requirements and government AI systems are not assessed for mandatory interoperability", "Agent implements basic transparency for AI-assisted legislative activities, but does not address CoE Convention Art. 10 specific oversight requirements or EU Interoperability Act mandatory assessment for government AI", "Full CoE AI Convention Art. 10 transparency with legislative AI oversight mechanisms, EU Interoperability Act mandatory interoperability assessment, cross-border legislative data exchange capability, and transparent AI governance reporting to parliamentary oversight bodies", 12),
  
    // GAP-38-C1: law
      q('GOV-PL-10', 'Open Data', 'Does the agent implement EU Open Data Directive (EU) 2019/1024 Article 5 by ensuring legislative/petition documents and datasets are made available (1) in machine-readable formats, (2) with complete metadata, (3) with bulk download and where data is dynamic API access, (4) with publication and update SLAs, and (5) with evidence artifacts (metadata schema, API docs, change logs, uptime metrics) to demonstrate ongoing compliance?', 'EU Open Data Directive (EU) 2019/1024 Art. 5', 'No Art. 5 implementation: data is not machine-readable, lacks metadata, and provides no API or bulk access for reuse', 'Some open formats/feeds exist, but metadata, API or bulk access, update SLAs, and compliance evidence are incomplete', 'Full Art. 5 compliance with machine-readable releases, metadata completeness, API and bulk access for dynamic datasets, publication and update SLAs, and audit-ready evidence artifacts', 18),

      // GAP-38-C2: law
      q('GOV-PL-11', 'Interoperability', 'For any geospatial legislative datasets (affected regions, constituency maps, project locations, zoning overlays), does the agent implement INSPIRE Directive 2007/2/EC Article 7 interoperability by aligning datasets and services to INSPIRE implementing rules (harmonised data models, schemas, code lists), validating conformance, and publishing conformance reports and transformation pipelines as evidence?', 'EU INSPIRE 2007/2/EC Art. 7', 'No INSPIRE interoperability: geospatial legislative data is ad hoc and cannot be harmonised or validated against INSPIRE implementing rules', 'Some geospatial data is published, but schema harmonisation, conformance validation, and evidence reports are incomplete', 'Full Art. 7 interoperability with INSPIRE-aligned models, automated conformance validation, documented transformations, and published conformance reports suitable for oversight', 15),

      // GAP-38-M1: law
      q('GOV-PL-12', 'Quality', 'Does the agent implement ISO 25000 SQuaRE §2512 by defining a data and system quality model for petition-to-law datasets (e.g., completeness, accuracy, timeliness, consistency, provenance), computing quality measures, publishing quality dashboards/reports with each release, and retaining audit evidence (measurement definitions, sampling, defect logs, remediation actions)?', 'ISO 25000 SQuaRE §2512', 'No SQuaRE quality measurement: datasets lack defined quality measures, dashboards, or remediation evidence', 'Some quality checks exist, but measures are incomplete, not tied to §2512, or not published with evidence of remediation', 'Full §2512 operationalization with defined quality measures, automated measurement, published quality reports per release, defect/remediation tracking, and audit-ready evidence bundles', 12),

      // GAP-38-M2: law
      q('GOV-PL-13', 'Participation', 'Does the agent implement inclusive public consultation and e-participation in a way that is explicitly mapped to the UN E-Government Survey 2022 e-participation framework (e-information, e-consultation, e-decision-making), including multi-channel participation, accessibility, representativeness monitoring, and published participation metrics suitable for annual benchmarking?', 'UN E-Government Survey 2022 (e-participation)', 'No UN EGov 2022 mapping: participation features are ad hoc and not benchmarkable against 2022 criteria', 'Some participation measures exist, but mapping to UN EGov 2022 components and benchmarking metrics is incomplete', 'Full UN EGov Survey 2022 alignment with mapped participation services, accessibility and inclusion controls, representativeness monitoring, and published benchmark-ready metrics', 10),

      // GAP-38-m1: law
      q('GOV-PL-14', 'Governance', 'Does the program maintain a versioned control-to-citation map for PSI/Open Data and access-to-information obligations (e.g., mapping any legacy 2003/98 references to 2019/1024 where required), with periodic review and automated checks to keep statutory anchors consistent across questions, datasets, and evidence exports?', 'Citation mapping governance', 'No citation governance: references drift and anchors are inconsistent across artifacts', 'Some mapping exists but is manual and inconsistently applied', 'Versioned mapping with periodic review and automated consistency checks ensuring audit-defensible statutory anchors', 6),
      q("GOV-PL-15", "Transparency", "When the agent generates or manipulates text published to inform the public on legislative or petition matters, does the deployer disclose that the text was artificially generated or manipulated, as EU AI Act Article 50(4) requires unless the text underwent human review with editorial responsibility?", "EU AI Act Art. 50(4)", "AI-generated public texts are published without disclosure", "Disclosure is applied to some channels, and the human-review exception is claimed without records", "Every published AI-generated text carries a disclosure, or a record shows the human reviewer and the editor responsible, checked before publication", 8),
  ]
};

export const citizenServices: IndustryPack = {
  id: "citizen-services",
  stationId: "governance",
  name: "Citizen Services",
  description: "Citizens engaging in government services to lead law-abiding responsible lives — AI agents delivering public services with equity, accessibility, transparency, and accountability, covering digital service delivery, benefits administration, and public safety services.",
  regulatoryBasis: ["EU Single Digital Gateway Regulation 2018/1724", "eIDAS 2.0 Regulation 2024/1183", "GDPR Art. 6(1)(e)", "WCAG 2.1 AA / EU Accessibility Directive 2016/2102", "ISO 9241-210:2019 (Human-Centered Design)", "EU AI Act Annex III §8", "UN E-Government Development Index Standards", "Section 508"],
  riskTier: "very-high",
  euAIActClassification: "Annex III §5(a) — public authorities evaluating eligibility for essential public assistance benefits and services",
  sdgAlignment: ["SDG 16 — Peace, Justice and Strong Institutions", "SDG 10 — Reduced Inequalities", "SDG 3 — Good Health and Well-Being"],
  certificationPath: "L1 Basic online service delivery → L2 Accessible, GDPR-compliant services → L3 EU Single Digital Gateway compliance → L4 Full eIDAS 2.0 + EU AI Act compliance → L5 Autonomous citizen-centric AI services with verified equity, accessibility, and democratic accountability",
  keyRisks: ["Systemic service denial for vulnerable populations through AI gatekeeping", "Benefits fraud enabled by AI-exploitable verification gaps", "Algorithmic discrimination in eligibility determinations", "Privacy violations from AI-enabled government data aggregation", "Loss of non-digital access channels for elderly/disabled citizens"],
  certificationThreshold: 80,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["EU SDG 2018/1724", "eIDAS 2.0", "GDPR Art. 6(1)(e)", "WCAG 2.1 AA", "EU AI Act Annex III §5/8", "ISO 9241-210:2019"],
  questions: [
    q("GOV-CS-1", "Accessibility", "Does the agent implement universal service accessibility per EU Web Accessibility Directive 2016/2102 Article 4 and WCAG 2.1 AA success criteria for all citizen-facing service channels?", "EU Accessibility Directive 2016/2102 Art. 4; WCAG 2.1 AA", "No accessibility compliance; citizen service AI is inaccessible to persons with disabilities, lacks WCAG 2.1 AA conformance, and provides no alternative access channels", "Agent implements WCAG 2.1 AA for primary service interfaces, but does not apply accessibility to all channels or maintain accessibility statements per Art. 7", "Full accessibility with WCAG 2.1 AA+ implementation, EU Accessibility Directive Art. 4 compliance, multi-channel service delivery (web, mobile, telephone, in-person), accessibility feedback mechanism, annual accessibility statement per Art. 7, and ATAG 2.0 authoring tool compliance", 20),
    q("GOV-CS-2", "Compliance", "Does the agent implement EU Single Digital Gateway Regulation 2018/1724 Article 6 quality criteria for online procedures and Article 12 user feedback requirements?", "EU SDG 2018/1724 Art. 6, 12", "No EU SDG compliance; digital service delivery does not meet Art. 6 quality criteria including completeness, accuracy, and cross-border accessibility", "Agent implements core EU SDG Art. 6 quality requirements, but does not maintain Art. 12 user experience statistics or cross-border service integration", "Full EU SDG compliance with Art. 6 quality criteria for all procedures, cross-border service delivery per Art. 5, Art. 12 user feedback system, quality statistics reporting to European Commission, and Your Europe portal integration", 15),
    q("GOV-CS-3", "Ethics", "Does the agent implement non-discrimination per EU AI Act high-risk requirements for AI systems used in essential government services including benefits administration?", "EU AI Act Art. 10, 14; ECHR Art. 14", "No non-discrimination controls; AI eligibility assessments may discriminate based on protected characteristics without detection or monitoring", "Agent performs periodic bias audits for service AI and implements basic fairness constraints, but does not maintain EU AI Act Art. 10 data governance requirements or continuous discrimination monitoring", "Full non-discrimination governance with EU AI Act Art. 10 training data requirements, continuous disparate impact monitoring per ECHR Art. 14, automated adverse outcome investigation, non-discrimination impact assessment for new service AI, and transparent fairness reporting", 15),
    q("GOV-CS-4", "Transparency", "Does the agent implement EU AI Act Article 14 human oversight for high-risk AI in essential public services and Article 13 transparency for citizens receiving AI-influenced decisions?", "EU AI Act Art. 13, 14", "No human oversight or citizen transparency; AI-influenced government service decisions are made without citizen notification or accessible human review mechanism", "Agent implements human review capability for flagged AI decisions, but does not provide Art. 13 citizen transparency or systematic human oversight per Art. 14 requirements", "Full EU AI Act compliance with Art. 13 citizen notification of AI involvement, Art. 14 human oversight with meaningful review capability, citizen explanation of AI-influenced decisions, contestability mechanisms, and national competent authority system registration", 15),
    q("GOV-CS-5", "Privacy", "Does the agent implement proportionate data use per GDPR Article 6(1)(e) public task processing limitation and Article 5(1)(b) purpose limitation for citizen service AI systems?", "GDPR Art. 5(1)(b); Art. 6(1)(e)", "No proportionate data use; citizen service AI accesses and retains all available government data without necessity assessment or purpose limitation controls", "Agent implements purpose limitation for primary service functions and restricts cross-purpose data use, but does not conduct systematic proportionality assessments or automated data minimization", "Full proportionate data governance with GDPR Art. 6(1)(e) necessity assessment for each service AI, Art. 5(1)(b) purpose limitation technical controls, cross-agency data sharing proportionality gates, citizen data transparency dashboards, and automated retention enforcement", 15),
    q("GOV-CS-6", "Governance", "Does the agent implement service quality assurance per ISO 9241-210:2019 human-centered design principles and UN E-Government Development Index citizen satisfaction requirements?", "ISO 9241-210:2019; UN E-Government Survey 2024", "No service quality framework; citizen service AI is deployed without user research, usability testing, or systematic quality measurement", "Agent implements user feedback collection and basic usability assessment, but does not apply ISO 9241-210 human-centered design process or UN E-Government Survey quality standards", "Full human-centered design with ISO 9241-210 iterative design process, user research with representative citizen panels, UN E-Government satisfaction measurement, continuous service improvement cycle, and accessible service design for diverse citizen needs", 20),
    q("GOV-CS-7", "Security", "Does the agent implement cybersecurity for government digital services per NIST CSF 2.0 Government Profile and FedRAMP Rev. 5 authorization requirements?", "NIST CSF 2.0 Government Community Profile; FedRAMP Rev. 5", "No government cybersecurity framework; citizen-facing AI services are deployed without NIST CSF government profile implementation or FedRAMP-equivalent authorization", "Agent implements NIST CSF core functions for service security and has completed basic security assessment, but does not maintain FedRAMP-equivalent continuous monitoring or government community profile alignment", "Full government cybersecurity with NIST CSF 2.0 Government Community Profile implementation, FedRAMP Rev. 5 equivalent authorization and continuous monitoring, penetration testing, supply chain risk management for service AI components, and incident response integrated with CISA coordination", 15),
    q("GOV-CS-8", "Ethics", "Does the agent implement proactive identification of vulnerable citizen populations per EU AI Act recitals 47-49 and UN SDG 10 Reduced Inequalities to prevent service exclusion?", "EU AI Act Recitals 47-49; UN SDG 10; UN E-Gov Survey 2024", "No vulnerability assessment; citizen service AI does not identify or proactively support populations at risk of digital exclusion including elderly, disabled, homeless, or undocumented individuals", "Agent monitors service utilization patterns and identifies underserved groups, but does not implement proactive outreach or EU AI Act recital-aligned vulnerability protection", "Full vulnerability governance with EU AI Act recital-aligned vulnerable population identification, proactive service design for at-risk groups, UN SDG 10 equity monitoring, non-digital alternative channels, outreach to digitally excluded populations, and transparent equity reporting to oversight bodies", 15),
    q("GOV-CS-9", "Compliance", "Does the agent implement EU AI Act Article 27 fundamental rights impact assessment for high-risk AI in public services and European Commission AI Liability Directive proposal provisions for citizen redress in AI-caused service failures?", "EU AI Act Art. 27; AI Liability Directive Proposal", "No fundamental rights impact assessment or AI liability compliance; high-risk citizen service AI lacks Art. 27 FRIA and citizens have no structured redress mechanism for AI-caused service failures", "Agent conducts basic impact assessment for citizen service AI, but does not implement EU AI Act Art. 27 fundamental rights impact assessment methodology or prepare for AI Liability Directive redress obligations", "Full EU AI Act Art. 27 fundamental rights impact assessment for all high-risk citizen service AI, AI Liability Directive readiness with disclosure obligations, citizen redress mechanisms, causal chain documentation for AI-influenced service decisions, and national competent authority FRIA reporting", 12),
  
    // GAP-39-C1: law
      q('GOV-CS-10', 'Compliance', 'For all SDG-scoped procedures, does the agent ensure the full procedure is available fully online end-to-end (including identification/authentication, guidance, form completion, evidence submission, e-signature where applicable, fee/payment, status tracking, decision delivery, and appeal/redress initiation), with documented exceptions and accessibility-preserving alternative channels, per SDG Regulation (EU) 2018/1724 Article 2(2)?', 'EU SDG 2018/1724 Art. 2(2)', 'Procedure is not fully online: one or more mandatory steps require in-person/phone/mail workarounds or manual staff intervention, with no exception governance or evidence', 'Most steps are online, but identity/evidence/payment/decision delivery or redress steps still require offline actions or are inconsistently available across procedures', 'All SDG procedures are end-to-end fully online with exception governance, evidence of completion rates, cross-border accessibility checks, and auditable proof that offline steps are not mandatory except where legally justified', 15),

      // GAP-39-C2: law
      q('GOV-CS-11', 'Interoperability', 'Does the agent support eIDAS 2.0 cross-border use (per §6) by enabling (1) cross-border identification/authentication acceptance, (2) EUDI Wallet or equivalent credential presentation flows where applicable, (3) relying-party verification and attribute validation, (4) multilingual/cross-border error handling and support, and (5) evidence exports demonstrating successful cross-border transactions and interoperability testing?', 'eIDAS 2.0 §6 (cross-border)', 'No cross-border support: identity/credential flows work only for domestic users and fail for cross-border credentials or foreign-issued attributes', 'Some cross-border scenarios work, but coverage is incomplete, usability is poor, and there is limited evidence of interoperability testing and relying-party validation', 'Full cross-border readiness with interoperable identity/credential acceptance, relying-party verification, consistent UX across Member States, and audit-ready evidence of cross-border transactions and conformance testing', 18),

      // GAP-39-C3: law
      q('GOV-CS-12', 'Accessibility', 'Across all citizen-service user journeys (including AI-assisted decision notices, identity steps, uploads, and payments), does the agent ensure WCAG 2.1 SC 2.4.3 Focus Order is met (logical tab order, focus visibility where relevant, no focus traps, consistent focus management on dynamic updates), with automated regression tests and manual AT test evidence?', 'WCAG 2.1 SC 2.4.3', 'No focus-order control: keyboard navigation order is illogical, dynamic steps trap focus, or assistive technology users cannot complete procedures', 'Some pages meet focus order, but complex journeys (wizards/modals/dynamic forms) have inconsistent focus management and limited test evidence', 'End-to-end focus-order compliance across all journeys with automated checks, AT-supported manual test evidence, and change-control gates preventing regressions', 12),

      // GAP-39-M1: law
      q('GOV-CS-13', 'Accessibility', 'For web-based citizen services, does the agent meet Section 508 Revised Standards (36 CFR Part 1194 Appendices A and C) requirements (including text alternatives, keyboard access, non-interference with assistive tech, form label/field associations, timing control, and accessible documentation), and produce evidence bundles (test reports, exception logs, remediation tracking) suitable for procurement/audit?', 'Section 508 Revised Standards (36 CFR Part 1194 Appendices A and C)', 'No 508 mapping: accessibility is asserted but not evidenced against Revised 508 Standards, with gaps in forms/keyboard/AT compatibility', 'Partial mapping: some criteria are met and tested, but gaps remain and evidence is not consistently retained or auditable', 'Full Revised 508 Standards compliance with traceable criteria mapping, repeatable testing, remediation SLAs, and audit-ready evidence bundles', 10),
      q("GOV-CS-14", "Interoperability", "For procedures in scope of the Single Digital Gateway Regulation (EU) 2018/1724, does the agent support the Article 14 once-only technical system, retrieving evidence directly from competent authorities at the user's explicit request and letting the user preview it before use?", "EU SDG 2018/1724 Art. 14", "Citizens must upload evidence that authorities already hold", "Some evidence types are retrieved through the once-only system, but preview and explicit request are not enforced", "All available evidence types retrieved through the once-only technical system on explicit request, with preview before use, and logged exchanges", 8),
      q("GOV-CS-15", "Transparency", "Where the agent supports decisions on eligibility for public assistance benefits and services (EU AI Act Annex III point 5(a)), does the authority inform each applicant that a high-risk AI system is being used, as Article 26(11) requires?", "EU AI Act Annex III §5(a); EU AI Act Art. 26(11)", "Applicants are not told that AI is involved in eligibility decisions", "A general statement exists on the website, not in the applicant's own case", "Notice given in each case before the decision, stating the system's purpose and the right to an explanation, with the notice recorded on the case file", 8),
  ]
};

export const publicPrivateCollaboration: IndustryPack = {
  id: "public-private-collaboration",
  stationId: "governance",
  name: "Public and Private Collaboration",
  description: "Connecting public institutions (national/state governments, WHO, UN) and private institutions in growth-oriented transformations — AI agents orchestrating public-private partnerships for sustainable development with accountability, anti-corruption safeguards, and equitable value distribution.",
  regulatoryBasis: ["UN SDG 17 Partnership Framework", "UN Guiding Principles on Business and Human Rights (UNGPs)", "OECD PPP Framework", "World Bank PPP Guidelines", "UNCAC (UN Convention Against Corruption)", "ISO 26000:2010 §6.6", "G20 Principles for Responsible AI in Government", "FATF R1 (AML in PPP)"],
  riskTier: "very-high",
  euAIActClassification: "Annex III §5(a) where public-assistance eligibility decisions are delegated to the partnership; otherwise not listed",
  sdgAlignment: ["SDG 17 — Partnerships for the Goals", "SDG 16 — Peace, Justice and Strong Institutions", "SDG 10 — Reduced Inequalities"],
  certificationPath: "L1 Basic PPP governance → L2 UNCAC anti-corruption controls → L3 OECD/World Bank PPP framework → L4 Full UNGPs human rights due diligence → L5 Autonomous accountability-verified partnership orchestration with SDG impact measurement",
  keyRisks: ["Corruption facilitation through AI-mediated contract procurement", "Value extraction asymmetry benefiting private partners over public interest", "Anti-competitive behavior enabled by AI partnership intelligence", "Human rights violations in PPP projects without adequate due diligence", "AI-enabled revolving door between public regulators and private interests"],
  certificationThreshold: 80,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["UN SDG 17", "UNGPs", "OECD PPP Framework", "UNCAC", "ISO 26000:2010 §6.6", "G20 Responsible AI Principles"],
  questions: [
    q("GOV-PPC-1", "Ethics", "Does the agent implement anti-corruption controls per UNCAC Articles 7 and 9 requirements for public procurement and financial management transparency in AI-mediated PPP activities?", "UNCAC Art. 7, 9", "No anti-corruption controls; AI-mediated PPP procurement lacks UNCAC-required transparency, conflict of interest disclosure, or competitive tendering safeguards", "Agent implements basic procurement transparency and conflict of interest screening, but does not systematically apply UNCAC Art. 7 public sector integrity or Art. 9 procurement controls", "Full UNCAC compliance with Art. 7 public sector integrity controls, Art. 9 procurement transparency, beneficial ownership verification, conflict of interest automated screening, bribery risk assessment in PPP activities, and anti-corruption audit trail per UNCAC Chapter IV", 20),
    q("GOV-PPC-2", "Governance", "Does the agent implement OECD Principles for Public Governance of PPPs §5 full value for money assessment and §6 transparency and accountability for AI-managed partnership decisions?", "OECD PPP Governance Principles §5-6", "No value for money assessment; AI partnership decisions optimize for deal completion without OECD §5 full VfM analysis or §6 public accountability requirements", "Agent tracks PPP performance against contracted objectives and flags deviations, but does not implement OECD §5 full lifecycle VfM assessment or §6 transparency mechanisms", "Full OECD PPP compliance with §5 lifecycle VfM assessment (quantitative and qualitative), §6 public transparency reporting, independent audit support, risk-adjusted performance monitoring, and parliament/oversight body reporting capability", 15),
    q("GOV-PPC-3", "Ethics", "Does the agent implement human rights due diligence per UN Guiding Principles §17-21 for private partners in PPP projects with potential adverse human rights impacts?", "UNGPs §17-21", "No human rights due diligence; PPP projects are evaluated without UNGPs §17-21 human rights impact assessment or remediation mechanisms for private partner activities", "Agent includes human rights risk indicators in partner assessment, but does not implement full UNGPs §17-21 due diligence cycle or operational grievance mechanisms", "Full UNGPs due diligence with §17-21 human rights impact assessment for all PPP private partners, ongoing monitoring, stakeholder engagement with affected communities per §18, grievance mechanism per §29, and transparent human rights reporting", 15),
    q("GOV-PPC-4", "Transparency", "Does the agent implement PPP contract transparency per Open Contracting Data Standard (OCDS) and World Bank PPP Disclosure Framework for public access to partnership terms?", "OCDS v1.2; World Bank PPP Disclosure Framework", "No contract transparency; PPP agreements are confidential without public disclosure of terms, performance data, or renegotiation outcomes", "Agent publishes basic PPP contract summaries and performance metrics, but does not implement OCDS v1.2 structured data publication or World Bank PPP Disclosure Framework requirements", "Full PPP transparency with OCDS v1.2 contract data publication, World Bank PPP Disclosure Framework compliance, renegotiation disclosure, real-time performance data, beneficial ownership disclosure, and public-accessible partnership registry", 15),
    q("GOV-PPC-5", "Compliance", "Does the agent implement SDG 17 Indicator 17.17.1 multi-stakeholder partnership monitoring and ISO 26000:2010 §6.6.2 community involvement principles for PPP impact assessment?", "UN SDG 17 Indicator 17.17.1; ISO 26000:2010 §6.6.2", "No SDG impact monitoring; PPP activities are not measured against SDG 17 partnership quality or ISO 26000 community involvement standards", "Agent tracks selected SDG 17 indicators and measures partnership outputs, but does not implement SDG 17.17.1 full multi-stakeholder monitoring or ISO 26000 §6.6.2 community development principles", "Full SDG 17 monitoring with Indicator 17.17.1 implementation, ISO 26000 §6.6.2 community involvement integration, outcome attribution methodology, private sector development contribution measurement, and transparent SDG impact reporting for all PPP activities", 15),
    q("GOV-PPC-6", "Security", "Does the agent implement information security for PPP systems per ISO 27001:2022 and G20 Principles for Responsible AI in Government §4 security and privacy requirements?", "ISO 27001:2022; G20 AI Principles §4", "No PPP information security; sensitive partnership information and procurement data lacks ISO 27001 controls or G20 Responsible AI security requirements", "Agent implements basic access controls and encryption for PPP data, but does not maintain ISO 27001 certification or G20 AI security framework compliance", "Full ISO 27001 implementation for PPP information assets, G20 Responsible AI §4 security compliance, classified information management for sensitive partnership terms, security incident response for PPP systems, and third-party security audit support", 10),
    q("GOV-PPC-7", "Governance", "Does the agent implement fiscal risk management per IMF PFRAM (PPP Fiscal Risk Assessment Model) and OECD DAC Blended Finance Guidelines for public finance protection?", "IMF PFRAM; OECD DAC Blended Finance Principles", "No fiscal risk management; PPP AI does not assess or monitor contingent liabilities, guarantees, or fiscal exposure from partnership commitments", "Agent tracks PPP fiscal commitments and flags budget impacts, but does not implement IMF PFRAM-level fiscal risk quantification or OECD DAC blended finance monitoring", "Full fiscal risk governance with IMF PFRAM implementation, contingent liability assessment, guarantee exposure monitoring, OECD DAC blended finance compliance, fiscal risk disclosure per IMF standards, and parliamentary budget office integration for oversight", 10),
    q("GOV-PPC-8", "Compliance", "Does the agent implement competition law compliance per EU Treaty on the Functioning of the EU Articles 101-102 and national competition authority requirements for AI-managed PPP market activities?", "TFEU Art. 101-102; EU Directive 2014/24 (Public Procurement)", "No competition compliance; AI-managed PPP activities may involve anti-competitive market allocation, bid rigging, or public procurement manipulation without detection", "Agent monitors PPP activities for obvious competition law violations and maintains procurement compliance, but does not implement systematic TFEU Art. 101-102 assessment or AI-enabled collusion detection", "Full competition compliance with TFEU Art. 101-102 monitoring, AI-enabled collusion detection in procurement, EU Directive 2014/24 public procurement compliance, competition authority reporting capability, market concentration assessment for PPP portfolios, and antitrust risk assessment for all AI-managed partnership decisions", 10),
    q("GOV-PPC-9", "Compliance", "Does the agent implement FATF Recommendation 1 risk-based approach for AI-managed PPP financial flows and EU Anti-Money Laundering Regulation 2024 beneficial ownership transparency for PPP corporate structures?", "FATF R1; EU AMLR 2024", "No AML risk-based approach for PPP financial flows; AI-managed partnership financial transactions lack FATF R1 risk assessment and PPP corporate structures are not assessed for EU AMLR beneficial ownership transparency", "Agent implements basic financial due diligence for PPP partners, but does not apply FATF R1 risk-based approach to AI-managed PPP financial flows or EU AMLR beneficial ownership verification for complex PPP structures", "Full FATF R1 risk-based approach for AI-managed PPP financial flows, EU AMLR beneficial ownership transparency for PPP corporate structures, enhanced due diligence for high-risk jurisdictions, suspicious transaction monitoring, and financial intelligence unit reporting capability", 12),
  
    // GAP-40-C1: UNCAC Art. 9(1)(c)
      q('GOV-PPC-10', 'Transparency', 'Does the agent implement UNCAC Article 9(1)(c) procurement transparency for PPP procurements by ensuring (1) pre-published tender rules and objective evaluation criteria, (2) traceable scoring and evaluation records for all bids, (3) publication of award rationales and conflict-of-interest declarations, (4) bidder debrief and complaint and appeal workflows, and (5) audit-ready evidence exports showing that AI-assisted recommendations did not override objective criteria?', 'UNCAC Art. 9(1)(c)', 'No Art. 9(1)(c) transparency: criteria are opaque, evaluation is not reproducible, and bidders have no defensible debrief and appeal evidence', 'Some procurement artifacts exist (criteria, logs), but evaluation reproducibility, disclosure, and complaint handling are incomplete or not tied to AI-assisted steps', 'Full Art. 9(1)(c) procurement transparency with objective criteria publication, reproducible evaluation trails, debrief and appeals, and AI decision traceability suitable for anti-corruption audit', 20),

      // GAP-40-C2: OECD PPP Framework §5.1 (VfM)
      q('GOV-PPC-11', 'Governance', 'Does the agent implement OECD PPP Framework §5.1 value-for-money (VfM) by producing an ex ante lifecycle business case that includes (1) a public sector comparator (PSC) and counterfactual, (2) quantified risk allocation and risk-transfer valuation, (3) transparent discounting and demand and usage assumptions, (4) sensitivity and renegotiation scenario analysis, and (5) an evidence bundle (models, inputs, approvals) linking AI recommendations to the VfM rationale?', 'OECD PPP Framework §5.1 (VfM)', 'No VfM discipline: decisions are made without a PSC and counterfactual, quantified risk valuation, or evidence linking recommendations to VfM', 'Some cost-benefit work exists, but PSC, risk valuation, sensitivity and renegotiation analysis, and evidence bundles are incomplete', 'Full §5.1 VfM implementation with PSC, risk valuation, sensitivity and renegotiation scenarios, and auditor-ready evidence packages for oversight review', 18),

      // GAP-40-C3: FATF R16 (Wire transfers)
      q('GOV-PPC-12', 'Compliance', 'For PPP-related wire transfers (including cross-border payments), does the agent implement FATF Recommendation 16 by (1) capturing and validating originator and beneficiary information, (2) ensuring required information travels with the transfer through intermediaries, (3) screening against sanctions, PEP, and adverse media where applicable, (4) handling missing or invalid information with exception workflows, and (5) retaining audit evidence linking each payment to contract milestones and beneficial ownership data?', 'FATF R16 (Wire transfers)', 'No R16 controls: transfers lack required originator and beneficiary information integrity and cannot be traced end-to-end', 'Captures payment metadata, but travel-rule style propagation, exception handling, screening, and audit linkage to PPP milestones are incomplete', 'Full R16 compliance with validated originator and beneficiary data, propagation controls, screening plus exception workflows, and audit-ready traceability tying payments to PPP governance artifacts', 15),

      // GAP-40-M1: ISO 26000:2010 §6.6.7
      q('GOV-PPC-13', 'Ethics', 'Does the agent implement ISO 26000:2010 §6.6.7 anti-corruption by ensuring (1) anti-bribery and anti-corruption policy enforcement across partners, (2) third-party and intermediary due diligence, (3) gifts and hospitality and facilitation-payment controls, (4) whistleblowing and reporting intake with non-retaliation protections, and (5) auditable controls for political contributions and lobbying interactions in PPP contexts?', 'ISO 26000:2010 §6.6.7', 'No ISO 26000 anti-corruption program: anti-bribery controls are ad hoc and not consistently applied to partners and intermediaries', 'Policies and some checks exist, but third-party due diligence, gifts and hospitality controls, reporting channels, and evidence retention are incomplete', 'Full §6.6.7 anti-corruption implementation with partner-wide controls, due diligence, reporting mechanisms, and audit-ready evidence bundles', 12),

      // GAP-40-M2: G20 AI Gov Principles §3
      q('GOV-PPC-14', 'Accountability', 'Does the agent implement G20 Responsible AI in Government §3 by ensuring AI-influenced PPP decisions (procurement shortlists, risk allocation recommendations, renegotiation triggers) have (1) documented rationale and explainability suitable for publication and oversight, (2) human accountability assignment, (3) contestability and appeal pathways for affected bidders and stakeholders, and (4) an auditable decision log separating AI suggestions from final human decisions?', 'G20 AI Gov Principles §3', 'No §3 accountability: AI influence is opaque and cannot be explained, contested, or mapped to accountable decision-makers', 'Some documentation exists, but explainability, contestability, and separation of AI suggestions from final decisions is inconsistent', 'Full §3 operationalization with publishable rationales, human accountability, contestability workflows, and audit-ready logs of AI vs human decision steps', 10),

      // GAP-40-m1: citation mapping governance
      q('GOV-PPC-15', 'Governance', 'Does the program maintain a versioned control-to-citation map for PPP governance (UNCAC, OECD, FATF, ISO 26000, G20), ensuring Council-required anchors (UNCAC Art. 9(1)(c), OECD §5.1, FATF R16, ISO 26000 §6.6.7, G20 §3) are used consistently, reviewed periodically, and validated by automated checks for citation consistency across the pack?', 'Citation mapping governance', 'No mapping governance: citations drift and Council-required anchors are inconsistently applied', 'A mapping exists but updates are manual and inconsistently enforced', 'Versioned, reviewed mapping with automated consistency checks and audit-defensible clause anchors', 6),
  ]
};
