/** Technology station industry packs. Registered in ../../industryPacks.ts (PACK_CONTENT). */
import type { IndustryPack } from "../../industryPacks.js";
import { q } from "./shared.js";

// ---------------------------------------------------------------------------
// TECHNOLOGY STATION (5 packs)
// ---------------------------------------------------------------------------

export const cognitionToIntelligence: IndustryPack = {
  id: "cognition-to-intelligence",
  stationId: "technology",
  name: "Cognition to Intelligence",
  description: "Contextual data interpretation moving from master data through meta, empirical, analytical, to contextual intelligence — profiled, personalized, and preferentiated — AI agents that transform raw data into actionable, trusted intelligence with explainability and bias controls.",
  regulatoryBasis: ["EU AI Act 2024/1689", "GDPR Art. 22", "IEEE 7001:2021 (Transparency)", "ISO/IEC 42001:2023", "NIST AI RMF 1.0", "UNESCO AI Ethics Recommendation 2021", "OECD AI Principles"],
  riskTier: "very-high",
  euAIActClassification: "Chapter V obligations for general-purpose AI models (Art. 53; Art. 51 classification with systemic risk) where the agent provides or integrates a GPAI model; Art. 50 transparency for systems interacting with natural persons",
  sdgAlignment: ["SDG 9 — Industry, Innovation and Infrastructure", "SDG 10 — Reduced Inequalities", "SDG 16 — Peace, Justice and Strong Institutions"],
  certificationPath: "L1 Basic data processing → L2 GDPR-compliant profiling controls → L3 EU AI Act high-risk compliance → L4 ISO 42001 AI management certified → L5 Autonomous explainable intelligence with continuous bias monitoring and democratic oversight",
  keyRisks: ["Discriminatory automated decisions affecting rights per GDPR Art. 22", "Context collapse in personalization leading to filter bubbles", "Opaque intelligence surfaces eroding human agency", "Data quality degradation amplified by AI inference chains", "Over-personalization enabling manipulation and behavioral nudging"],
  certificationThreshold: 72,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["EU AI Act 2024/1689", "GDPR Art. 22", "IEEE 7001:2021", "ISO/IEC 42001:2023", "NIST AI RMF 1.0"],
  questions: [
    q("TECH-CI-1", "Transparency", "Does the agent provide meaningful explainability per EU AI Act Article 13 and IEEE 7001:2021 transparency process requirements for all intelligence outputs?", "EU AI Act Art. 13; IEEE 7001:2021", "No explainability; AI intelligence outputs are black-box with no explanation of reasoning, confidence, or input data usage", "Agent provides post-hoc explanations for key outputs using LIME/SHAP-style attribution, but does not implement IEEE 7001 transparency process documentation", "Full IEEE 7001 transparency with human-interpretable explanations per EU AI Act Art. 13, causal chain documentation, uncertainty quantification, and explainability accessibility for non-technical stakeholders", 15),
    q("TECH-CI-2", "Ethics", "Does the agent prevent discriminatory automated decisions per GDPR Article 22 and EU AI Act Article 10 data governance for training data bias?", "GDPR Art. 22; EU AI Act Art. 10(3)", "No discrimination prevention; automated profiling and decisions may discriminate based on protected characteristics without detection or mitigation", "Agent performs periodic bias audits and applies post-processing bias mitigation, but does not implement continuous discrimination monitoring or pre-processing data governance", "Full non-discrimination governance with continuous bias monitoring across protected characteristics, pre-processing data representativeness assessment per EU AI Act Art. 10(3), GDPR Art. 22 human review for significant decisions, and bias incident reporting", 15),
    q("TECH-CI-3", "Governance", "Does the agent implement AI system lifecycle management per ISO/IEC 42001:2023 Annex A controls including risk assessment and continuous improvement?", "ISO/IEC 42001:2023 Annex A", "No AI management system; intelligence AI operates without systematic risk assessment, monitoring, or improvement processes", "Agent maintains basic AI system documentation and performs periodic risk assessments, but does not implement full ISO 42001 Annex A control set", "Full ISO 42001 AIMS implementation with Annex A controls, continuous AI risk assessment and treatment, AI system performance monitoring, stakeholder impact assessment, and systematic improvement cycle documentation", 12),
    q("TECH-CI-4", "Compliance", "Does the agent implement NIST AI RMF Map function requirements for contextual risk identification in deployed intelligence systems?", "NIST AI RMF 1.0 MAP 1.1-5.2", "No AI risk mapping; deployed intelligence systems lack systematic contextualization of risks and impacts", "Agent performs initial risk mapping per NIST AI RMF MAP function, but does not maintain continuous risk categorization or impact assessment updates", "Full NIST AI RMF MAP function implementation with continuous risk categorization, impact assessment across stakeholder categories, risk tolerance documentation, and integration with MEASURE and MANAGE functions", 12),
    q("TECH-CI-5", "Privacy", "Does the agent enforce data minimization per GDPR Article 5(1)(c) in intelligence generation, preventing unnecessary personal data retention in AI inference pipelines?", "GDPR Art. 5(1)(c); Art. 17", "No data minimization in AI pipelines; personal data is retained indefinitely in training data, model weights, and inference caches without purpose review", "Agent implements retention policies and periodically reviews data necessity, but does not enforce automated data minimization in AI inference or implement right to erasure in model artifacts", "Full data minimization with automated retention enforcement per GDPR Art. 5(1)(c), differential privacy in training pipelines, right to erasure implementation covering model artifacts, inference cache purging, and privacy-preserving intelligence generation", 12),
    q("TECH-CI-6", "Ethics", "Does the agent align with UNESCO AI Ethics Recommendation 2021 Principle 4 (Data Protection) and Principle 9 (Privacy and Oversight) in intelligence personalization?", "UNESCO AI Ethics Recommendation 2021 Principles 4, 9", "No ethics alignment; intelligence personalization operates without UNESCO ethics principle integration or human oversight mechanisms", "Agent implements basic human oversight checkpoints and respects user privacy preferences, but does not systematically assess UNESCO ethics principle alignment", "Full UNESCO ethics alignment with Principles 4/9 integration, human oversight architecture per Principle 9, ethical impact assessment for intelligence systems, stakeholder engagement in ethics governance, and public transparency reporting", 10),
    q("TECH-CI-7", "Transparency", "Does the agent support human agency per OECD AI Principles 1.3 (Transparency and Explainability) and 1.4 (Robustness) in intelligence systems affecting material decisions?", "OECD AI Principles 1.3, 1.4", "No human agency support; intelligence systems make recommendations without transparency or robustness validation", "Agent supports human review of AI recommendations and provides explanations, but does not implement OECD robustness requirements or contestability mechanisms", "Full OECD principle compliance with human agency preservation, contestability mechanisms for material AI decisions, robustness testing per Principle 1.4, transparency documentation per Principle 1.3, and regular accountability assessments", 12),
    q("TECH-CI-8", "Security", "Does the agent implement adversarial robustness per NIST AI RMF MEASURE 2.6 and OWASP ML Security Top 10 for model extraction and inference attacks?", "NIST AI RMF MEASURE 2.6; OWASP ML Top 10", "No adversarial robustness; intelligence models are vulnerable to extraction, evasion, and poisoning attacks without detection", "Agent implements basic input validation and anomaly detection, but does not perform systematic adversarial testing or implement OWASP ML security controls", "Full adversarial robustness with NIST AI RMF MEASURE 2.6 metrics, adversarial testing per OWASP ML Top 10, model extraction prevention, inference attack detection, continuous robustness monitoring, and incident response for AI security events", 12),
    q("TECH-CI-9", "Compliance", "Does the agent implement EU AI Act Article 50 transparency obligations for AI-generated content including synthetic media labeling and NIST AI RMF GOVERN 1.1 organizational AI risk governance for intelligence systems?", "EU AI Act Art. 50; NIST AI RMF GOVERN 1.1", "No Art. 50 transparency or organizational AI governance; intelligence systems generate content without synthetic media labeling and lack NIST AI RMF organizational risk governance structure", "Agent implements basic AI content disclosure and organizational AI policies, but does not automate EU AI Act Art. 50 synthetic media labeling or implement NIST AI RMF GOVERN 1.1 organizational governance structure", "Full EU AI Act Art. 50 compliance with automated synthetic media labeling, AI-generated content watermarking, NIST AI RMF GOVERN 1.1 organizational governance with documented risk tolerance, accountability structures, and transparent AI content provenance for all intelligence outputs", 12),
  
    // GAP-31-C1: EU AI Act Art. 50(1) (GPAI transparency)
      q('TECH-CI-10', 'Transparency', 'Does the agent implement EU AI Act Article 50(1) GPAI transparency by (1) clearly disclosing when outputs are AI-generated/AI-assisted, (2) providing provenance (model/system identity, version, and data sources categories), and (3) ensuring disclosures persist across downstream exports/APIs and are auditable (logs/evidence bundles)?', 'EU AI Act Art. 50(1)', 'No GPAI transparency: outputs are presented as human-authored or source-verified with no disclosure or provenance', 'Discloses AI use in some UI surfaces, but provenance and persistence across exports/APIs are inconsistent and not auditable', 'Full Art. 50(1) transparency with consistent disclosure, machine-readable provenance metadata, downstream persistence, and audit-ready disclosure logs for every intelligence artifact', 15),

      // GAP-31-C2: GDPR Art. 22(3)
      q('TECH-CI-11', 'Rights', 'For decisions with legal or similarly significant effects, does the agent implement GDPR Article 22(3) safeguards by enabling (1) human intervention, (2) user ability to express their point of view, and (3) contestation/appeal with documented outcomes, timelines, and audit trails?', 'GDPR Art. 22(3)', 'No safeguard workflow; users cannot request human review or contest outcomes, and decisions are final/opaque', 'Offers a manual escalation path, but viewpoint capture, decision logging, and appeal outcomes are inconsistently recorded', 'End-to-end Art. 22(3) rights workflow with SLA-tracked human review, user submissions, reasoned decisions, outcome notifications, and immutable audit logs linking model outputs to human determinations', 15),

      // GAP-31-C3: ISO/IEC 42001:2023 §6.1
      q('TECH-CI-12', 'Governance', 'Does the agent support ISO/IEC 42001:2023 §6.1 planning by maintaining an AI risk/opportunity register, defining actions with owners and due dates, integrating actions into operational processes (change/release), and tracking effectiveness metrics with evidence suitable for AIMS audit?', 'ISO/IEC 42001:2023 §6.1', 'No planning loop; risks are informal, actions are undocumented, and improvements are ad hoc', 'Maintains a basic risk register and some actions, but integration into ops processes and effectiveness evidence is incomplete', 'Full §6.1 planning with versioned registers, accountable action plans, operational integration, effectiveness measurement, and audit-ready evidence packs', 12),

      // GAP-31-M1: IEEE 7001:2021 §6.3 (Level 3)
      q('TECH-CI-13', 'Transparency', 'Does the agent achieve IEEE 7001:2021 §6.3 Level 3 transparency by producing traceable, reproducible explanations (inputs, transformations, uncertainty), role-appropriate explanation views, and maintained transparency-process artifacts (templates, logs, review records) for each intelligence output?', 'IEEE 7001:2021 §6.3 (Level 3)', 'No IEEE 7001 transparency process; explanations are absent or purely narrative with no traceability', 'Provides explanations and some logs, but lacks Level-3 traceability, reproducibility, and maintained process artifacts', 'Meets Level 3 with traceable explanation records, uncertainty disclosure, role-specific views, and complete transparency-process documentation & review evidence', 10),

      // GAP-31-M2: NIST AI RMF 1.0 GOVERN
      q('TECH-CI-14', 'Governance', 'Does the agent operationalize NIST AI RMF GOVERN by defining accountable roles (RACI), escalation triggers (harm, drift, bias), incident response playbooks, and third-party/model-provider governance (due diligence, monitoring, and termination criteria) for intelligence systems?', 'NIST AI RMF 1.0 GOVERN', 'No operational governance; no defined roles, triggers, or incident playbooks for AI issues', 'Defines some roles and incident handling, but escalation triggers, third-party governance, and evidence are incomplete', 'Full GOVERN implementation with accountable roles, measurable triggers, incident playbooks, third-party governance, and audit-ready governance evidence', 10),
      q("TECH-CI-15", "Governance", "Where the agent integrates a general-purpose AI model, does the program obtain and keep current the information and documentation the model provider must supply to downstream providers under EU AI Act Article 53(1)(b), and use it in the agent's own risk assessment?", "EU AI Act Art. 53(1)(b)", "The model's capabilities and limitations are not documented by the integrator", "Provider documentation is collected once, but it is not tracked across model versions or used in risk assessment", "Provider documentation versioned per model release, limitations mapped to agent risks and controls, and model upgrades gated on reviewing the new documentation", 8),
  ]
};

export const networkedEcosystems: IndustryPack = {
  id: "networked-ecosystems",
  stationId: "technology",
  name: "Connectivity to Networked Ecosystems",
  description: "Data connectivity across customer, enterprise, and industry ecosystems — flipping financial ecosystems to human ecosystems — AI agents orchestrating data flows, API ecosystems, and platform integrations with emphasis on interoperability, data rights, and ecosystem trust.",
  regulatoryBasis: ["GDPR Art. 20 (Data Portability)", "EU Data Act 2023/2854", "EU Data Governance Act 2022/868", "CCPA/CPRA §1798.100(d)", "ISO/IEC 27001:2022", "EU NIS2 Directive 2022/2555", "OWASP API Security Top 10 2023", "OpenID Connect / OAuth 2.1"],
  riskTier: "high",
  euAIActClassification: "Annex III §2 where a safety component of critical digital infrastructure; otherwise not listed — Art. 50 transparency applies",
  sdgAlignment: ["SDG 9 — Industry, Innovation and Infrastructure", "SDG 17 — Partnerships for the Goals", "SDG 10 — Reduced Inequalities"],
  certificationPath: "L1 Basic API security → L2 GDPR data portability compliance → L3 EU Data Act/DGA compliance → L4 Full ecosystem trust architecture → L5 Autonomous ecosystem orchestration with verified data rights and sovereignty",
  keyRisks: ["Data sovereignty erosion through ecosystem lock-in", "API abuse enabling unauthorized data aggregation", "Ecosystem monopolization through AI-managed data access", "Privacy violations through ecosystem data correlation", "Critical infrastructure dependency on single ecosystem providers"],
  certificationThreshold: 70,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["GDPR Art. 20", "EU Data Act 2023/2854", "EU Data Governance Act 2022/868", "ISO/IEC 27001:2022", "OWASP API Top 10 2023"],
  questions: [
    q("TECH-NE-1", "Compliance", "Does the agent implement EU Data Act 2023/2854 Chapter II data access rights including product data access, portability, and third-party data sharing obligations?", "EU Data Act 2023/2854 Ch. II Art. 4-8", "No Data Act compliance; product-generated data is not accessible to users or third parties per Chapter II requirements", "Agent supports basic data access requests per EU Data Act, but does not implement automated portability, third-party sharing obligations, or data holder compliance documentation", "Full EU Data Act compliance with automated product data access per Art. 4, portability API per Art. 5, third-party sharing governance per Art. 6-8, data holder compliance documentation, and real-time data access logging", 15),
    q("TECH-NE-2", "Security", "Does the agent implement API security per OWASP API Security Top 10 2023 including broken object level authorization (API1) and security misconfiguration (API8) prevention?", "OWASP API Security Top 10 2023", "No systematic API security; APIs expose data without authorization controls, rate limiting, or security configuration management", "Agent implements authentication and basic authorization for APIs, but does not systematically address all OWASP API Top 10 vulnerabilities or perform API security testing", "Full OWASP API Security Top 10 mitigation with automated vulnerability scanning, broken object-level authorization enforcement, API gateway security configuration, rate limiting, injection prevention, and continuous API security monitoring", 15),
    q("TECH-NE-3", "Governance", "Does the agent implement data intermediary compliance per EU Data Governance Act 2022/868 Chapter III requirements for data sharing services?", "EU Data Governance Act 2022/868 Ch. III Art. 10-15", "No data intermediary governance; ecosystem data sharing lacks DGA Chapter III requirements for neutrality, transparency, and registration", "Agent implements basic data sharing transparency and neutrality controls, but does not meet full DGA Art. 10-15 requirements for registered data intermediary services", "Full DGA Chapter III compliance with data intermediary registration, neutrality enforcement, transparent service terms, data subject rights support, separation of intermediary and other activities, and competent authority notification", 12),
    q("TECH-NE-4", "Privacy", "Does the agent enforce data portability per GDPR Article 20 and CCPA §1798.100(d) with automated structured data export in interoperable formats?", "GDPR Art. 20; CCPA §1798.100(d)", "No portability implementation; personal data cannot be exported by users in machine-readable formats per GDPR Art. 20 or CCPA requirements", "Agent supports basic data export functionality, but does not implement full GDPR Art. 20 direct transmission or maintain comprehensive data portability across all data categories", "Full portability with automated GDPR Art. 20 structured export, direct controller-to-controller transmission, CCPA data download support, interoperable format standardization, and portability request tracking with statutory deadline enforcement", 12),
    q("TECH-NE-5", "Interoperability", "Does the agent implement open standards for ecosystem connectivity per W3C Web standards, OpenAPI 3.1, and EU Interoperability Framework (EIF) technical interoperability layer?", "W3C Standards; OpenAPI 3.1; EU EIF v2", "No open standards; ecosystem integration uses proprietary APIs and formats creating vendor lock-in and interoperability barriers", "Agent implements OpenAPI documentation and standard authentication protocols, but does not apply EU EIF technical interoperability principles across all ecosystem connections", "Full open standards implementation with OpenAPI 3.1 documentation, EU EIF technical layer compliance, W3C semantic interoperability, vendor lock-in prevention measures, and ecosystem diversity monitoring", 10),
    q("TECH-NE-6", "Security", "Does the agent implement identity federation per OpenID Connect / OAuth 2.1 and NIST SP 800-63-3 identity assurance levels for ecosystem access management?", "OpenID Connect; OAuth 2.1; NIST SP 800-63-3", "No identity federation; ecosystem access uses siloed identity systems without federation standards or assurance level verification", "Agent implements OAuth 2.0 authorization and basic OIDC federation, but does not enforce NIST SP 800-63-3 assurance levels or implement step-up authentication for sensitive ecosystem operations", "Full identity federation with OIDC/OAuth 2.1 implementation, NIST SP 800-63-3 IAL/AAL enforcement, step-up authentication for sensitive operations, federation trust framework documentation, and continuous identity assurance monitoring", 12),
    q("TECH-NE-7", "Governance", "Does the agent implement ecosystem trust governance per ENISA Cybersecurity for Connected and Automated Mobility and EU eIDAS 2.0 trust service requirements?", "ENISA CCAM; EU eIDAS 2.0 Regulation", "No ecosystem trust framework; participant verification and trust establishment are informal without standards-based trust anchors", "Agent validates ecosystem participant certificates and maintains trust anchors, but does not implement full eIDAS 2.0 qualified trust service requirements or ENISA trust framework", "Full ecosystem trust governance with eIDAS 2.0 qualified trust service integration, PKI management, trust anchor maintenance, ecosystem participant verification, qualified electronic signature support, and trust framework audit trail", 12),
    q("TECH-NE-8", "Transparency", "Does the agent implement algorithmic transparency per EU Digital Markets Act Article 6(12) for core platform services and fair access principles?", "EU DMA Art. 6(12); EU Data Act Art. 33", "No algorithmic transparency; ecosystem ranking, access, and data monetization decisions are opaque without fairness assessment", "Agent provides basic transparency reports for ecosystem ranking and access decisions, but does not implement full DMA Art. 6(12) requirements or contestability mechanisms", "Full DMA compliance with algorithmic transparency for ranking and access decisions, non-discrimination monitoring, business user access audits, contestability mechanisms, and transparent data access pricing per EU Data Act Art. 33", 12),
    q("TECH-NE-9", "Compliance", "Does the agent implement EU Digital Markets Act Article 6(12) algorithmic transparency for core platform services and EU Data Act Article 33 fair data access pricing for AI-managed ecosystem data monetization?", "EU DMA Art. 6(12); EU Data Act Art. 33", "No DMA algorithmic transparency or Data Act pricing compliance; AI ecosystem agents manage ranking and data access without DMA Art. 6(12) transparency or Art. 33 fair pricing requirements", "Agent provides basic transparency for ecosystem ranking decisions, but does not implement DMA Art. 6(12) full algorithmic transparency requirements or EU Data Act Art. 33 fair data access pricing", "Full DMA Art. 6(12) algorithmic transparency with ranking parameter disclosure, non-discrimination monitoring, EU Data Act Art. 33 fair data access pricing, FRAND-equivalent terms for ecosystem data, and contestability mechanisms for AI-managed access decisions", 12),
  
    // GAP-32-C1: OAuth 2.1 §4.1 (PKCE)
      q('TECH-NE-10', 'Security', 'Does the agent implement OAuth 2.1 authorization code flow with PKCE per OAuth 2.1 §4.1 (S256), including strict redirect URI matching, state/nonce anti-CSRF protections, prevention of PKCE downgrade, and auditable evidence (logs/telemetry) that PKCE is enforced for all public clients?', 'OAuth 2.1 §4.1 (PKCE)', 'No PKCE enforcement; authorization code flows can proceed without code_challenge / code_verifier or allow insecure downgrade, and evidence is missing', 'PKCE is implemented for some clients, but enforcement is inconsistent (e.g., legacy exceptions), redirect/state handling is incomplete, or evidence is not audit-ready', 'Full OAuth 2.1 §4.1 PKCE enforcement (S256) for all public clients, strict redirect URI + state/nonce validation, downgrade prevention, continuous conformance testing, and immutable audit logs demonstrating PKCE policy compliance', 15),

      // GAP-32-C2: EU Data Governance Act (Regulation (EU) 2022/868) — Article 12
      q('TECH-NE-11', 'Governance', 'If the agent provides data intermediation services, does it operationalize DGA Art. 12 by enforcing neutrality and separation (no data use for other purposes, ring-fenced operations), implementing appropriate technical and organizational measures for secure intermediation, and maintaining audit-ready evidence (policies, access logs, segregation controls, and periodic compliance attestations)?', 'EU DGA 2022/868 Art. 12', 'No Art. 12 controls; intermediary operations are commingled, data may be reused for other purposes, and evidence is missing', 'Some neutrality/separation controls exist, but segregation, security measures, and audit evidence are incomplete or inconsistently enforced across services/partners', 'Full Art. 12 implementation with enforced non-use constraints, operational separation, technical/organizational controls, continuous monitoring, and audit-ready evidence bundles aligned to competent authority expectations', 15),

      // GAP-32-M1: OWASP API Security Top 10 2023 — API1 (BOLA)
      q('TECH-NE-12', 'Security', 'Does the agent prevent OWASP API1 (Broken Object Level Authorization) by enforcing object ownership/tenant isolation on every object access, using centralized authorization (policy enforcement points), and maintaining automated authorization test coverage (positive/negative cases) with logs suitable for incident reconstruction?', 'OWASP API Top 10 2023 — API1', 'No object-level authorization; endpoints rely on client-provided identifiers without ownership/tenant checks and lack authorization tests', 'Implements some object/tenant checks, but coverage is inconsistent, authorization logic is duplicated, or test evidence is incomplete', 'Full API1 prevention with centralized authorization, consistent ownership/tenant checks, automated authZ test suites per endpoint/resource, and audit-ready access decision logs', 12),

      // GAP-32-m1: EU Data Act 2023/2854 — Article 4
      q('TECH-NE-13', 'Compliance', 'Does the agent implement EU Data Act Art. 4 access obligations in an operationally usable way (secure access interface, timely/continuous access where applicable, SLA evidence for no undue delay, and audit logs proving access was provided to users upon request)?', 'EU Data Act 2023/2854 Art. 4', 'Access is ad hoc/manual; interfaces are insecure or slow, and timeliness/continuity evidence is missing', 'Access interfaces exist, but timeliness/continuity SLAs and evidence are incomplete or inconsistently met', 'Full Art. 4 operationalization with secure interfaces, timeliness/continuity controls, SLA monitoring, and audit-ready access evidence bundles', 8),
      q("TECH-NE-14", "Data Access by Design", "For connected products placed on the market after 12 September 2026, are product data and related service data accessible to the user by default, easily, securely and free of charge, as EU Data Act 2023/2854 Article 3(1) requires?", "EU Data Act 2023/2854 Art. 3", "Users cannot access the data their product generates", "Data is available on request through support, not directly or by default", "Direct, default access in a structured, machine-readable format, with metadata, free of charge, verified for each product line placed on the market after 12 September 2026", 8),
      q("TECH-NE-15", "Supply Chain Security", "Does the ecosystem operator manage information security risks in the ICT supply chain of the APIs, SDKs and services the agent depends on, consistent with ISO/IEC 27001:2022 Annex A control 5.21?", "ISO/IEC 27001:2022 A.5.21", "Third-party APIs and SDKs are adopted without security review", "Major suppliers are reviewed at onboarding, but transitive dependencies and changes are not tracked", "Dependency inventory including transitive components, security requirements in supplier agreements, change monitoring, and documented exit paths for critical suppliers", 8),
  ]
};

export const osSustainableOutcomes: IndustryPack = {
  id: "os-sustainable-outcomes",
  stationId: "technology",
  name: "Operating System for Sustainable Outcomes",
  description: "The transactional system orchestrating strategic movement of people, goods, and money — creating wealth and value while enabling sustainable outcomes — AI agents as the core orchestration layer for economic and social systems with resilience, accountability, and outcome measurement.",
  regulatoryBasis: ["ISO 27001:2022", "SOC 2 Type II", "EU DORA Art. 9 ICT risk management", "ISO 22301:2019", "EU NIS2 Directive 2022/2555", "ITIL v4", "ISO/IEC 20000-1:2018", "GDPR Art. 32"],
  riskTier: "critical",
  euAIActClassification: "Annex III §2 (critical digital infrastructure) and §4 (workers' management) where those uses apply",
  sdgAlignment: ["SDG 8 — Decent Work and Economic Growth", "SDG 9 — Industry, Innovation and Infrastructure", "SDG 12 — Responsible Consumption and Production"],
  certificationPath: "L1 Basic operational monitoring → L2 ITIL/ISO 20000 service management → L3 SOC 2 + ISO 27001 certified → L4 DORA compliant resilience → L5 Autonomous sustainable orchestration with verified outcomes and continuous accountability",
  keyRisks: ["Systemic failure propagation through interconnected orchestration failures", "Accountability gaps in AI-mediated economic transactions", "Inequitable outcome distribution amplified by algorithmic optimization", "Regulatory arbitrage enabled by multi-jurisdiction AI orchestration", "Operational resilience failures in critical transaction pathways"],
  certificationThreshold: 78,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["ISO 27001:2022", "SOC 2 Type II", "EU DORA Art. 9", "ISO 22301:2019", "EU NIS2 2022/2555", "ISO/IEC 20000-1:2018"],
  questions: [
    q("TECH-OS-1", "Resilience", "Does the agent implement digital operational resilience per EU DORA Article 9 ICT risk management framework requirements for financial sector orchestration systems?", "EU DORA Art. 9; EU DORA Art. 10", "No operational resilience framework; orchestration system lacks ICT risk assessment, business continuity planning, or DORA-compliant controls", "Agent implements basic ICT risk management and recovery procedures, but does not meet full DORA Art. 9 framework requirements or maintain documented ICT risk register", "Full DORA compliance with comprehensive ICT risk management per Art. 9, risk identification and classification, protection measures, detection and response capabilities, recovery objectives, and continuous resilience testing per Art. 25", 15),
    q("TECH-OS-2", "Governance", "Does the agent maintain service management per ISO/IEC 20000-1:2018 §8 service delivery requirements and ITIL v4 value chain activities?", "ISO/IEC 20000-1:2018 §8; ITIL v4", "No service management; orchestration services are delivered without systematic management, SLA monitoring, or continual improvement", "Agent monitors service performance against SLAs and manages incidents, but does not implement full ISO 20000-1 service delivery requirements or ITIL v4 value chain", "Full ISO/IEC 20000-1 implementation with service delivery per §8, ITIL v4 value chain integration, service catalog management, change management, and continual service improvement with outcome measurement", 12),
    q("TECH-OS-3", "Security", "Does the agent implement security operations per SOC 2 Type II Trust Service Criteria CC6-CC9 logical and physical access controls and system operations?", "SOC 2 Type II CC6-CC9", "No SOC 2 alignment; logical access, operations, and change management do not meet Trust Service Criteria requirements", "Agent implements core CC6 access controls and CC7 system operations monitoring, but does not maintain SOC 2 Type II evidence or address full CC8-CC9 requirements", "Full SOC 2 Type II compliance with CC6-CC9 implementation, continuous control monitoring, automated evidence collection, audit-ready documentation, and annual SOC 2 report support", 12),
    q("TECH-OS-4", "Transparency", "Does the agent implement outcome accountability per GRI Standards 201-207 economic performance reporting and UN SDG impact measurement framework?", "GRI Standards 201-207; UN SDG Impact Standards", "No outcome accountability; orchestration system optimizes for efficiency without measuring or reporting social and economic outcomes", "Agent tracks economic performance metrics and generates basic GRI-aligned reports, but does not implement full SDG impact measurement or stakeholder outcome reporting", "Full outcome accountability with GRI 201-207 economic reporting, UN SDG impact measurement per SDG Impact Standards, stakeholder outcome distribution analysis, negative externality identification, and transparent sustainable outcome reporting", 12),
    q("TECH-OS-5", "Compliance", "Does the agent implement business continuity per ISO 22301:2019 §8.4 business continuity plans with RTO/RPO verification for critical orchestration pathways?", "ISO 22301:2019 §8.4", "No business continuity planning; critical orchestration pathways lack recovery time and point objectives or tested continuity plans", "Agent maintains business continuity plans for core pathways and tests recovery procedures, but does not implement full ISO 22301 §8.4 requirements or verify RTO/RPO achievement", "Full ISO 22301 implementation with tested BCPs for all critical pathways, verified RTO/RPO achievement, multi-scenario disaster simulation, supply chain continuity integration, and continuous BCP maintenance and improvement", 12),
    q("TECH-OS-6", "Ethics", "Does the agent implement equitable access to orchestration services per EU AI Act recitals and UNESCO AI Ethics Recommendation Principle 10 (Fairness and Non-Discrimination)?", "EU AI Act Recitals 47-49; UNESCO AI Principles 10", "No equity controls; orchestration algorithms optimize outcomes without equity assessment or equitable access requirements", "Agent monitors access distribution and applies basic fairness constraints, but does not implement systematic equity assessment or UNESCO Principle 10 alignment", "Full equity governance with algorithmic fairness assessment per EU AI Act recitals, equitable access monitoring, disparate impact analysis, underserved community access provisions, and transparent equity reporting per UNESCO Principle 10", 10),
    q("TECH-OS-7", "Security", "Does the agent implement NIS2 cybersecurity measures per EU NIS2 Directive 2022/2555 Article 21 for essential entity digital infrastructure?", "EU NIS2 2022/2555 Art. 21", "No NIS2 cybersecurity measures; orchestration system does not implement essential entity security requirements per Art. 21", "Agent implements several Art. 21 security measures including incident handling and supply chain security, but does not address all required measures", "Full NIS2 compliance with all Art. 21 measures, 24-hour incident notification capability, supply chain security, cryptographic controls, access control, and regular cybersecurity testing per Art. 21(2)(i)", 12),
    q("TECH-OS-8", "Governance", "Does the agent maintain audit trails per GDPR Article 30 records of processing activities and ISO/IEC 27001:2022 A.8.15 logging and monitoring requirements?", "GDPR Art. 30; ISO 27001:2022 A.8.15", "No comprehensive audit trails; orchestration activities are not systematically logged with sufficient detail for accountability or incident investigation", "Agent maintains transaction logs and GDPR Art. 30 ROPA, but does not implement full ISO 27001 A.8.15 logging requirements or automated log integrity protection", "Full audit trail with GDPR Art. 30 ROPA automation, ISO 27001 A.8.15 logging implementation, log integrity protection, retention management, forensic-ready evidence preservation, and real-time anomaly detection in audit streams", 15),
    q("TECH-OS-9", "Compliance", "Does the agent implement EU DORA Article 25 digital operational resilience testing including threat-led penetration testing (TLPT) and Article 28 third-party ICT risk management for AI orchestration service providers?", "EU DORA Art. 25; Art. 28", "No DORA resilience testing or third-party risk management; AI orchestration systems lack Art. 25 TLPT and Art. 28 third-party ICT risk assessment for AI service providers in the orchestration chain", "Agent performs basic penetration testing and vendor risk assessment, but does not implement DORA Art. 25 threat-led penetration testing methodology or Art. 28 third-party ICT risk management lifecycle", "Full DORA Art. 25 TLPT implementation with TIBER-EU methodology, Art. 28 third-party ICT risk management for AI orchestration providers, contractual security requirements, exit strategy documentation, and continuous third-party monitoring with competent authority reporting", 12),
  
    // GAP-33-C1: EU DORA (EU) 2022/2554 Art. 9(4) (TLPT anchor)
      q('TECH-OS-10', 'Resilience', 'Does the agent implement threat-led penetration testing (TLPT) governance and execution aligned to the Councils required mapping for EU DORA Art. 9(4), including (1) a TLPT policy and scoping methodology, (2) engagement governance and independence, (3) red-team execution with threat intelligence, (4) findings remediation tracking, and (5) an auditor/supervisor-ready evidence bundle (scope, rules of engagement, reports, remediation, and retest outcomes)?', 'EU DORA (EU) 2022/2554 Art. 9(4) (TLPT anchor)', 'No TLPT: no threat-led testing program, no governance, and no evidence bundles', 'Performs some penetration testing and occasional scenario exercises, but TLPT governance, independence, and evidence bundles are incomplete or not mapped to the required DORA anchor', 'Full TLPT program with governance, scoped threat-led testing, independence controls, remediation + retesting, and supervisor-ready evidence mapped to the required DORA Art. 9(4) anchor', 15),

      // GAP-33-C2: GDPR Art. 32(1)(b) (restore availability and access)
      q('TECH-OS-11', 'Privacy', 'Does the agent implement GDPR Art. 32(1)(b) by maintaining (1) backup + restore procedures for personal-data processing systems, (2) restore time objectives and restore drills demonstrating timely restoration, (3) integrity checks and access restoration verification, and (4) evidence retention (logs, drill reports, corrective actions) suitable for supervisory authority review?', 'GDPR Art. 32(1)(b)', 'No restore capability: backups/restores are undefined, untested, or cannot demonstrate timely restoration of availability/access', 'Has backups and can restore in common cases, but restore drills, objectives, integrity verification, and evidence bundles are incomplete', 'Full Art. 32(1)(b) readiness with defined restore objectives, regular restore testing, integrity + access verification, and audit-ready evidence bundles demonstrating timely restoration', 15),

      // GAP-33-M1: ISO 22301:2019 §8.4.4 (recovery procedures)
      q('TECH-OS-12', 'Resilience', 'Does the agent implement ISO 22301:2019 §8.4.4 recovery procedures by defining invocation criteria, step-by-step recovery runbooks for critical orchestration pathways, communications/roles during recovery, exercise/testing outputs, and evidence retention that demonstrates procedures are current and effective?', 'ISO 22301:2019 §8.4.4', 'No recovery procedures: BC plans are high-level and not executable, exercised, or evidenced', 'Has recovery runbooks and exercises some scenarios, but invocation criteria, communications roles, and evidence bundles are incomplete', 'Full §8.4.4 compliance with executable recovery procedures, role/communication plans, regular exercises, after-action improvements, and auditor-ready evidence', 12),

      // GAP-33-M2: ISO/IEC 20000-1:2018 §8.6 (service continuity / availability management)
      q('TECH-OS-13', 'Governance', 'Does the agent implement ISO/IEC 20000-1:2018 §8.6 by defining service continuity and availability targets for orchestration services, mapping critical dependencies (third parties and internal components), testing continuity/availability plans, managing exceptions, and producing evidence packs (targets, test reports, corrective actions, and trend metrics)?', 'ISO/IEC 20000-1:2018 §8.6', 'No continuity/availability management: targets and dependencies are unknown and continuity plans are not tested or evidenced', 'Defines some targets and performs ad hoc tests, but dependency mapping, evidence, and exception governance are incomplete', 'Full §8.6 compliance with continuity/availability targets, dependency mapping, scheduled testing, exception handling, and audit-ready evidence bundles', 12),

      // GAP-33-M3: ITIL v4 §5.2.7 (practice anchor)
      q('TECH-OS-14', 'Operations', 'Does the agent operationalize the ITIL v4 §5.2.7 practice expectations by defining practice ownership, KPIs (availability, incident MTTR, recovery drill success), runbooks/workflows, continual improvement backlog, and evidence outputs that demonstrate the practice is executed and improved over time for orchestration services?', 'ITIL v4 §5.2.7', 'No ITIL practice operationalization: no practice KPIs, runbooks, or continual improvement evidence', 'Some ITIL-like processes exist, but KPIs, ownership, and evidence outputs are incomplete or inconsistent', 'Full ITIL practice operationalization with owned KPIs, runbooks, continual improvement, and audit-ready evidence demonstrating sustained execution', 10),

      // GAP-33-m1: Citation mapping governance (clause-precise anchors)
      q('TECH-OS-15', 'Governance', 'Does the program maintain a versioned control-to-clause mapping (DORA/ISO/ITIL/GDPR) with periodic review, so each question/control is anchored to the exact Council-required article/section and evidence expectations remain audit-defensible over time?', 'Citation mapping governance', 'No mapping governance: citations drift and controls are not traceably anchored', 'Mapping exists but review/versioning is manual and can lag updates', 'Strong mapping governance with versioning, periodic review, and checks that controls cite the Council-required anchors consistently', 6),
  ]
};

export const infotainment: IndustryPack = {
  id: "infotainment",
  stationId: "technology",
  name: "Infotainment",
  description: "The combination of information and entertainment shared and consumed by people — physically and digitally available on-demand — AI agents curating, generating, and distributing content with emphasis on accuracy, consumer protection, content moderation, and copyright compliance.",
  regulatoryBasis: ["EU Digital Services Act (DSA) 2022/2065", "EU Digital Markets Act (DMA) 2022/1925", "GDPR Art. 9 (sensitive data)", "COPPA §312", "WCAG 2.1 AA", "EU Copyright Directive 2019/790", "EU Media Freedom Act 2024", "DMCA §512"],
  riskTier: "high",
  euAIActClassification: "Not listed in Annex III except §8(b) systems intended to influence elections or voting behaviour; Art. 50(4) deep-fake disclosure and Art. 5(1)(a) manipulation prohibition apply",
  sdgAlignment: ["SDG 16 — Peace, Justice and Strong Institutions", "SDG 4 — Quality Education", "SDG 10 — Reduced Inequalities"],
  certificationPath: "L1 Basic content moderation → L2 DSA/GDPR baseline compliance → L3 DSA VLOP-level obligations → L4 Full DMA + Copyright compliance → L5 Autonomous trusted infotainment with verified accuracy, equity, and democratic safeguards",
  keyRisks: ["Misinformation amplification through algorithmic recommendation", "Harmful content exposure to minors despite automated moderation", "Synthetic media deception undermining democratic discourse", "Copyright violation through AI-generated derivative content", "Filter bubble reinforcement through over-personalization"],
  certificationThreshold: 72,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["EU DSA 2022/2065", "EU DMA 2022/1925", "GDPR Art. 9", "COPPA", "WCAG 2.1 AA", "EU Copyright Directive 2019/790", "EU Media Freedom Act 2024"],
  questions: [
    q("TECH-INF-1", "Compliance", "Does the agent implement Digital Services Act Article 34 systemic risk assessment for very large online platform recommendation systems and content curation?", "EU DSA 2022/2065 Art. 34-35", "No systemic risk assessment; content recommendation does not assess fundamental rights impacts, civic discourse, or public security risks per DSA Art. 34", "Agent performs basic risk assessment for recommendation systems, but does not implement full Art. 34 VLOP risk assessment methodology or Art. 35 mitigation measures", "Full DSA Art. 34 systemic risk assessment with annual independent audit support, Art. 35 mitigation measures for identified risks, algorithmic accountability reporting, and transparency to DSC supervisory authority", 15),
    q("TECH-INF-2", "Safety", "Does the agent implement child protection per DSA Article 28 prohibitions and COPPA §312 requirements for minor-directed content and advertising?", "EU DSA Art. 28; COPPA §312.2-5", "No age-appropriate design; content is not differentiated for minors, and profiling-based advertising targeting minors is not prevented", "Agent implements basic age verification and restricts targeted advertising for known minors, but does not apply full DSA Art. 28 prohibition scope or COPPA §312 requirements", "Full child protection with DSA Art. 28 implementation, COPPA-compliant parental consent for under-13, age-appropriate design per UK Children's Code, behavioral advertising prohibition for minors, and child safety risk assessment", 15),
    q("TECH-INF-3", "Transparency", "Does the agent implement algorithmic recommendation transparency per DSA Article 27 recommender system transparency and right to opt-out of profiling-based recommendations?", "EU DSA Art. 27; EU AI Act Art. 50", "No recommendation transparency; users cannot understand why content is recommended or opt out of profile-based curation", "Agent provides basic explanation of recommendation criteria, but does not implement full DSA Art. 27 transparency report or non-profiling alternative recommendation option", "Full DSA Art. 27 compliance with recommendation system transparency report, non-profiling alternative option, parameter-based personalization control, accessible explanation per EU AI Act Art. 50, and periodic DSA transparency reporting", 12),
    q("TECH-INF-4", "Compliance", "Does the agent implement copyright compliance per EU Copyright Directive 2019/790 Article 17 upload filters and Article 15 press publishers' rights for AI-generated content?", "EU Copyright Directive 2019/790 Art. 15, 17", "No copyright compliance; AI-generated content may reproduce copyrighted material and press publications without licensing or Art. 17 upload filter requirements", "Agent implements basic copyright detection for uploaded content, but does not address Art. 15 press publisher rights, AI training data licensing, or proactive copyright avoidance in generated content", "Full copyright compliance with Art. 17 upload filter implementation, Art. 15 press publisher rights management, AI training data licensing documentation, generated content originality verification, and rights management metadata preservation", 12),
    q("TECH-INF-5", "Safety", "Does the agent implement misinformation detection per EU Media Freedom Act 2024 editorial independence requirements and DSA Article 16 notice-and-action for illegal content?", "EU Media Freedom Act 2024; EU DSA Art. 16", "No misinformation controls; AI content curation amplifies false information without detection, labeling, or correction mechanisms", "Agent implements fact-check integration for high-reach content and flags suspected misinformation, but does not implement EU Media Freedom Act editorial integrity protections or systematic correction workflow", "Full misinformation governance with AI-generated content labeling per EU AI Act Art. 50, EU Media Freedom Act compliance, fact-check integration, correction workflow, EU code of practice on disinformation alignment, and transparency reporting", 12),
    q("TECH-INF-6", "Accessibility", "Does the agent ensure content accessibility per WCAG 2.1 AA success criteria and EU Web Accessibility Directive 2016/2102 for all content types including audio, video, and interactive media?", "WCAG 2.1 AA; EU Web Accessibility Directive 2016/2102", "No accessibility controls; content is not assessed for WCAG compliance and lacks captions, audio descriptions, or accessible interactive elements", "Agent implements WCAG 2.1 AA for text and images, but does not apply accessibility requirements to all media types or implement automated accessibility testing in content pipelines", "Full WCAG 2.1 AA implementation with automated accessibility testing, audio description for video content, caption quality assurance, keyboard navigability, screen reader optimization, and accessibility statement per EU Directive 2016/2102", 10),
    q("TECH-INF-7", "Privacy", "Does the agent implement privacy-preserving personalization per GDPR Article 5(1)(b) purpose limitation and ePrivacy Directive Article 5(3) cookie consent for behavioral tracking?", "GDPR Art. 5(1)(b); ePrivacy Directive Art. 5(3)", "No privacy-preserving personalization; behavioral tracking occurs without valid consent, and profiling data is used beyond original collection purpose", "Agent implements cookie consent and respects opt-outs, but does not implement privacy-preserving personalization techniques or purpose limitation in behavioral analytics", "Full privacy-preserving personalization with contextual recommendation without persistent profiling, ePrivacy-compliant consent for behavioral tracking, purpose limitation enforcement, on-device personalization where possible, and privacy impact assessment for recommendation systems", 12),
    q("TECH-INF-8", "Governance", "Does the agent implement content governance per DSA Article 14 terms of service transparency and Article 20 internal complaint-handling requirements for platform content decisions?", "EU DSA Art. 14, 20", "No content governance; moderation decisions are opaque, terms of service lack clarity on AI content decisions, and users cannot appeal content actions", "Agent maintains transparent terms of service and provides appeals mechanisms, but does not implement full DSA Art. 20 internal complaint-handling with timeliness requirements", "Full DSA content governance with Art. 14 transparent ToS, Art. 20 internal complaint-handling within required timeframes, content decision explanation, out-of-court dispute settlement access, and annual content moderation transparency report", 12),
    q("TECH-INF-9", "Compliance", "Does the agent implement EU AI Act Article 50(2) deep fake labeling obligations and EU Media Freedom Act 2024 editorial independence requirements for AI-generated news and media content?", "EU AI Act Art. 50(2); EU Media Freedom Act 2024", "No deep fake labeling or editorial independence compliance; AI content platforms generate and distribute synthetic media without Art. 50(2) labeling and AI-curated news lacks Media Freedom Act editorial independence safeguards", "Agent implements basic AI content disclosure, but does not automate Art. 50(2) deep fake detection and labeling or implement EU Media Freedom Act editorial independence protections for AI-curated news", "Full EU AI Act Art. 50(2) deep fake labeling with automated detection, machine-readable provenance metadata, EU Media Freedom Act editorial independence safeguards, AI-generated news transparency, and content authenticity infrastructure per C2PA standard", 12),
  
    // GAP-34-C1: EU Digital Services Act (DSA) 2022/2065 Art. 17(1) (statement of reasons)
      q('TECH-INF-10', 'Transparency', 'Does the agent issue a DSA Article 17(1) statement of reasons for each content moderation decision (removal, restriction, demonetization, suspension), including (a) decision type and legal/ToS basis, (b) main parameters/facts relied on, (c) whether automated tools were used, and (d) clear redress/complaint options?', 'EU DSA 2022/2065 Art. 17(1)', 'No statement of reasons: users receive opaque moderation outcomes with no decision basis, automation disclosure, or redress guidance', 'Provides partial reasons and appeal links, but fields are inconsistent and automation involvement/parameters are not disclosed in a structured, auditable way', 'Full Art. 17(1) compliance with structured statements of reasons, automation involvement disclosure, standardized reason taxonomies, evidence retention, user-facing redress pathways, and regulator-ready reporting extracts', 15),

      // GAP-34-C2: EU Digital Markets Act (DMA) 2022/1925 Art. 5(2) (self-preferencing or ranking neutrality)
      q('TECH-INF-11', 'Competition', 'Does the agent prevent self-preferencing in ranking/recommendation and related access conditions per DMA Article 5(2), ensuring that the platform does not treat its own content/services more favorably than third-party content/services (including through ranking, recommendation, default placements, or preferential interface access)?', 'EU DMA 2022/1925 Art. 5(2)', 'No DMA control: own-content/service boosting is allowed and not detected/audited; third parties have no effective parity protections', 'Implements a fairness policy and some monitoring, but parity testing is incomplete and exceptions/defaults are not consistently governed', 'Full Art. 5(2) compliance with parity-by-design ranking controls, continuous self-preference detection (A/B audits), default-placement governance, third-party parity KPIs, and audit-ready evidence for regulator review', 15),

      // GAP-34-M1: EU Copyright Directive 2019/790 Art. 17(4), 17(7)-(9)
      q('TECH-INF-12', 'Compliance', 'Does the agent implement EU Copyright Directive 2019/790 Article 17 OCSSP obligations end-to-end: (a) best-efforts licensing/authorization, (b) best-efforts to ensure unavailability of notified works, (c) stay-down for sufficiently substantiated notices, (d) safeguards for lawful uses (quotation/criticism/review, parody/pastiche), and (e) effective complaint and redress with timely human review?', 'EU Copyright Directive 2019/790 Art. 17(4), 17(7)-(9)', 'No Art. 17 OCSSP controls; content is either unfiltered or filtered without lawful-use safeguards and without complaint/redress guarantees', 'Implements some detection/licensing workflows, but lawful-use safeguards and complaint/redress timeliness are inconsistent', 'Full Art. 17 compliance with licensing workflows, stay-down controls tied to substantiated notices, exception-preserving safeguards, timely human review, and audit-ready evidence of proportionality and redress outcomes', 12),

      // GAP-34-M2: COPPA Rule 16 CFR §312.3 (Notice)
      q('TECH-INF-13', 'Privacy', 'Does the agent provide COPPA-compliant notices per 16 CFR §312.3, including a clear online privacy policy describing information practices for children and direct notice to parents prior to collection/use/disclosure of a childs personal information?', 'COPPA Rule 16 CFR §312.3', 'No COPPA notices; privacy policy and direct parental notices are missing or incomplete for child-directed services', 'Provides an online privacy notice and some parent notices, but disclosures are incomplete or not delivered at the required time/before collection', 'Full §312.3 compliance with complete online privacy notice, timely direct parental notice prior to collection, versioned notice retention, and evidence logs supporting enforcement/audit readiness', 12),

      // GAP-34-M3: EU Media Freedom Act 2024 Art. 4
      q('TECH-INF-14', 'Governance', 'Does the agent implement EU Media Freedom Act 2024 Article 4-aligned safeguards for media integrity, including protection of editorial independence/non-interference and user/recipient-facing transparency about editorial/recommender influence over news/media prominence?', 'EU Media Freedom Act 2024 Art. 4', 'No Media Freedom Act safeguards; editorial/ranking decisions can be manipulated (including by the platform) without controls or transparency', 'Has some integrity guidelines and transparency, but safeguards and evidence are incomplete and not tied to Art. 4 duties', 'Full Art. 4 compliance with editorial independence safeguards, anti-interference controls, transparency of prominence/ranking influences for news/media, incident escalation, and audit-ready evidence of integrity protections', 10),

      // GAP-34-m1: EU DSA 2022/2065 Art. 14, 17
      q('TECH-INF-15', 'Governance', 'Does the pack maintain an article-precise DSA control map that separates (a) Art. 14 ToS transparency, (b) Art. 17 statement-of-reasons artifacts, and (c) downstream user redress pathways, with periodic review to prevent citation drift and ensure evidence expectations remain audit-defensible?', 'EU DSA 2022/2065 Art. 14, 17', 'No control map; requirements are mixed and evidence is inconsistent across features', 'Mapping exists but is manually maintained and may drift over time', 'Versioned DSA control-to-evidence mapping with review workflow and automated checks for citation consistency and evidence completeness across the pack', 6),
  ]
};

export const partnershipsProsperity: IndustryPack = {
  id: "partnerships-prosperity",
  stationId: "technology",
  name: "Partnerships for Peace & Prosperity",
  description: "Global collaboration and sharing to create intellectual property in an open shared environment — AI agents facilitating multi-stakeholder partnerships, open innovation ecosystems, and IP co-creation with emphasis on governance, fair access, and prevention of exploitation.",
  regulatoryBasis: ["EU Data Act 2023/2854 Ch. V", "Creative Commons Licensing", "TRIPS Agreement", "WIPO Internet Treaties", "EU FRAND Licensing Guidelines", "WTO IP Framework", "UN SDG 17 Partnership Framework", "ISO 26000:2010"],
  riskTier: "high",
  euAIActClassification: "Not listed in Annex III; high-risk only under Art. 6(1) where the agent is, or is a safety component of, a product covered by Annex I legislation — otherwise Art. 4 (AI literacy), Art. 5 (prohibited practices) and Art. 50 (transparency) apply",
  sdgAlignment: ["SDG 17 — Partnerships for the Goals", "SDG 9 — Industry, Innovation and Infrastructure", "SDG 10 — Reduced Inequalities"],
  certificationPath: "L1 Basic partnership governance → L2 IP rights management → L3 FRAND/open source compliance → L4 Full SDG 17 partnership framework → L5 Autonomous partnership orchestration with verified equity, IP protection, and measurable prosperity outcomes",
  keyRisks: ["IP exploitation by dominant partners through AI-facilitated access", "Open source license violation in AI-generated code", "Partnership value extraction without reciprocal benefit", "Trade secret leakage through AI collaboration tools", "Exclusion of developing economy partners from AI-mediated partnerships"],
  certificationThreshold: 68,
  lastReviewed: "2026-10-03",
  complianceFrameworks: ["EU Data Act 2023/2854 Ch. V", "TRIPS Agreement", "WIPO Copyright Treaty", "ISO 26000:2010", "UN SDG 17"],
  questions: [
    q("TECH-PP-1", "Governance", "Does the agent manage IP rights in partnership ecosystems per TRIPS Agreement Articles 27-34 patent rights and Article 10 copyright protection for AI-generated collaborative outputs?", "TRIPS Agreement Art. 10, 27-34", "No IP rights management; partnership AI creates joint outputs without clear ownership, licensing terms, or TRIPS-compliant protection", "Agent tracks IP ownership in partnership outputs and applies standard licensing templates, but does not implement automated TRIPS compliance or proactive IP conflict detection", "Full IP governance with automated TRIPS-compliant rights management, joint IP ownership agreements, AI authorship disclosure, patent landscape monitoring, copyright registration support, and IP dispute prevention through clear contribution tracking", 15),
    q("TECH-PP-2", "Compliance", "Does the agent enforce open source license compliance per SPDX 2.3 specification and FOSSA/REUSE standards for AI-generated code and collaborative software outputs?", "SPDX 2.3 Specification; REUSE v3.0", "No open source compliance; AI-generated code incorporates open source components without license tracking, attribution, or compatibility verification", "Agent scans for open source usage and identifies license types, but does not enforce compatibility rules or automate SPDX-compliant attribution", "Full SPDX 2.3 compliance with automated license detection, compatibility matrix enforcement, REUSE-compliant attribution, copyleft obligation fulfillment, and software bill of materials for all partnership-generated software", 15),
    q("TECH-PP-3", "Ethics", "Does the agent implement equitable partnership governance per ISO 26000:2010 §6.7 community involvement and development principles and UN SDG 17 multi-stakeholder partnership criteria?", "ISO 26000:2010 §6.7; UN SDG 17 Indicator 17.16.1", "No equity governance; partnership orchestration optimizes for efficiency and dominant partner interests without equitable participation frameworks", "Agent monitors partnership contribution metrics and flags imbalanced participation, but does not implement ISO 26000 §6.7 community development principles or SDG 17 partnership quality assessment", "Full equitable partnership governance with ISO 26000 §6.7 integration, SDG 17 multi-stakeholder partnership quality assessment, developing economy partner inclusion mechanisms, benefit-sharing frameworks, and transparent partnership governance reporting", 12),
    q("TECH-PP-4", "Transparency", "Does the agent implement FRAND licensing terms per EU FRAND Guidelines and ETSI IPR Policy §6 for essential patents in collaborative standard-setting activities?", "EU FRAND Guidelines 2023; ETSI IPR Policy §6", "No FRAND compliance; essential patent licensing in collaborative standards involves opaque terms without FRAND commitment verification", "Agent tracks FRAND declarations and basic licensing terms, but does not verify FRAND compliance or facilitate dispute resolution for licensing disagreements", "Full FRAND governance with EU FRAND Guidelines compliance, ETSI IPR Policy §6 commitment tracking, licensing terms transparency, FRAND rate validation support, and arbitration-ready documentation for licensing disputes", 12),
    q("TECH-PP-5", "Compliance", "Does the agent implement EU Data Act Chapter V provisions for international data sharing in partnerships including data altruism and scientific research data flows?", "EU Data Act 2023/2854 Ch. V Art. 33-37", "No data sharing governance in partnerships; cross-border data flows and research data sharing lack EU Data Act Chapter V compliance", "Agent implements basic data sharing agreements for partnerships, but does not address EU Data Act Art. 33-37 international data sharing requirements or data altruism provisions", "Full EU Data Act Chapter V compliance with data altruism framework, scientific research data sharing governance per Art. 35, international transfer safeguards per Art. 36-37, and transparent data sharing terms documentation", 10),
    q("TECH-PP-6", "Security", "Does the agent protect trade secrets in partnership AI systems per EU Trade Secrets Directive 2016/943 Articles 2 and 4 reasonable measures requirements?", "EU Trade Secrets Directive 2016/943 Art. 2, 4", "No trade secret protection; confidential partnership information shared with AI systems lacks classification, access controls, or reasonable measures per Art. 2", "Agent implements access controls for confidential information and tracks sharing agreements, but does not implement systematic trade secret protection per Art. 2 reasonable measures standard", "Full trade secret governance with Art. 2 reasonable measures implementation, AI system access classification for confidential information, employee/partner confidentiality training, trade secret inventory, and incident response for potential misappropriation per Art. 4", 12),
    q("TECH-PP-7", "Governance", "Does the agent implement partnership impact measurement per UN SDG 17 indicator 17.16.1 multi-stakeholder monitoring frameworks and GRI 203 Indirect Economic Impacts?", "UN SDG 17 Indicator 17.16.1; GRI 203", "No partnership impact measurement; collaborative outcomes are not systematically measured against SDG targets or GRI economic impact standards", "Agent tracks partnership outputs and estimates economic impact, but does not implement UN SDG 17 multi-stakeholder monitoring or GRI 203 indirect economic impact reporting", "Full impact measurement with SDG 17 indicator 17.16.1 tracking, GRI 203 indirect economic impact reporting, prosperity distribution analysis across partners, and transparent partnership impact disclosure for stakeholders", 12),
    q("TECH-PP-8", "Ethics", "Does the agent implement responsible AI in partnerships per OECD AI Principles 1.5 (Accountability) and UNESCO AI Ethics Recommendation §49 (Responsibility sharing in multi-stakeholder environments)?", "OECD AI Principles 1.5; UNESCO AI Ethics §49", "No accountability framework for partnership AI; responsibility for AI outcomes in multi-stakeholder environments is unclear and unassigned", "Agent documents accountability assignments for partnership AI systems, but does not implement systematic accountability frameworks per OECD Principle 1.5 or UNESCO §49", "Full accountability governance with OECD Principle 1.5 implementation, UNESCO §49 responsibility sharing framework, accountability matrix for partnership AI decisions, redress mechanisms for AI harms, and transparent accountability reporting", 12),
    q("TECH-PP-9", "Compliance", "Does the agent implement EU Trade Secrets Directive 2016/943 Article 2 reasonable measures standard for AI collaboration environments and WIPO Copyright Treaty Article 11 technological protection measures for AI-generated partnership IP?", "EU Trade Secrets Directive 2016/943 Art. 2; WIPO WCT Art. 11", "No trade secret or TPM compliance; AI collaboration environments lack Art. 2 reasonable measures for confidential information and WIPO WCT Art. 11 technological protection for AI-generated IP", "Agent implements basic access controls for partnership data, but does not systematically apply Art. 2 reasonable measures standard or WIPO WCT Art. 11 technological protection for AI-generated collaborative IP", "Full EU Trade Secrets Directive Art. 2 reasonable measures with AI-specific access classification, WIPO WCT Art. 11 technological protection for AI-generated IP, trade secret inventory management, misappropriation detection, and IP protection audit trail for partnership governance", 12),
  
    // GAP-35-C1: law
      q('TECH-PP-10', 'Compliance', 'Does the agent operationalize TRIPS Agreement Article 28 patent rights (rights to prevent third parties from making, using, offering for sale, selling, or importing) for AI-assisted inventions created in partnerships by (1) documenting inventorship/ownership allocation, (2) defining licensing scopes/field-of-use and sublicensing rights, and (3) preparing enforcement-ready evidence (lab notebooks, model training provenance, contribution logs) for disputes and cross-border enforcement?', 'TRIPS Agreement Art. 28', 'No Art. 28 operationalization: AI inventions are shared without clear exclusive-rights scope, licensing authority, or enforcement evidence', 'Defines ownership and basic licenses, but Art. 28 rights scope, field-of-use restrictions, and enforcement evidence bundles are incomplete or inconsistent across partners', 'Full Art. 28-ready patent governance with explicit rights mapping (make/use/sell/import), joint-ownership and licensing playbooks, field-of-use + sublicensing controls, contribution provenance, and enforcement/evidence bundles ready for injunction/invalidity scenarios', 15),

      // GAP-35-C2: law
      q('TECH-PP-11', 'Compliance', 'Does the agent comply with WIPO WPPT Article 7 (performers right of reproduction) by ensuring that partnership projects involving recorded performances (including AI voice/performance capture and synthetic performance generation) have (1) performer consent and scope-limited reproduction licenses, (2) fixation and reproduction tracking, (3) attribution/royalty allocation terms where applicable, and (4) evidence logs linking each use to the relevant authorization?', 'WIPO WPPT Art. 7', 'No WPPT controls: performances are ingested/reproduced/republished via AI tools without performer-authorized reproduction rights or evidence of consent', 'Obtains consent in common cases, but scope limitations (media/territory/term), AI-specific reproduction tracking, and evidence retention are inconsistent', 'Full WPPT Art. 7 compliance with structured performer consent + reproduction licensing, AI capture/synthesis usage logging, scope enforcement (term/territory/media), attribution/royalty metadata, and audit-ready proof of authorization for every reproduction', 12),

      // GAP-35-C3: law
      q('TECH-PP-12', 'Security', 'Does the agent protect trade secrets in partnership data access/sharing under the EU Data Act Article 24 by (1) classifying trade-secret elements in shared datasets, (2) applying technical/organizational safeguards (access controls, secure enclaves/redaction, purpose limitation), (3) enforcing confidentiality + non-disclosure terms downstream, and (4) maintaining evidence to justify withholding/restricting trade-secret data where permitted?', 'EU Data Act 2023/2854 Art. 24', 'No Art. 24 safeguards: partnership data sharing exposes trade secrets without classification, redaction, or enforceable confidentiality controls', 'Implements basic confidentiality and access controls, but trade-secret classification/redaction and downstream enforcement/audit evidence are incomplete', 'Full Data Act Art. 24 trade secret governance with granular classification, redaction/enclave sharing patterns, contract + technical enforcement of confidentiality, and audit-ready evidence supporting any restrictions/withholding decisions', 15),

      // GAP-35-M1: law
      q('TECH-PP-13', 'Governance', 'Where partnership outputs implicate sanitary/phytosanitary (SPS) measures, does the agent apply WTO SPS Agreement Article 5.7 by (1) identifying when scientific evidence is insufficient, (2) implementing provisional measures with documented rationale, (3) actively seeking additional information for a more objective risk assessment, and (4) reviewing/updating measures within a reasonable period with recorded decision trails?', 'WTO SPS Agreement Art. 5.7', 'No SPS 5.7 discipline: measures are recommended/implemented without evidencing insufficiency, provisional status, information-gathering, or review timelines', 'Uses a precautionary approach informally, but does not document provisional status, evidence-gathering plans, and review timelines in a trade-dispute-resilient way', 'Full SPS Art. 5.7 governance with structured triggers for insufficiency, provisional-measure templates, evidence acquisition plans, periodic review SLAs, and audit-ready decision records supporting proportionality and WTO defensibility', 10),

      // GAP-35-m1: law
      q('TECH-PP-14', 'Governance', 'Does the program maintain a WIPO treaty-to-right mapping (WCT vs WPPT) for partnership outputs (authors rights vs performers neighboring rights), ensuring each content workflow (capture, reproduction, distribution, TPM/DRM) is mapped to the correct treaty article(s) and reviewed periodically by legal/compliance?', 'WIPO WCT/WPPT (mapping governance)', 'No mapping governance: WIPO treaty references are generic, WPPT-specific rights are missed, and citations are not reviewed', 'Maintains a mapping in documentation, but it is not kept current with workflow changes or used to gate AI content operations', 'Robust mapping governance with versioning, legal review, and workflow gating so that WCT/WPPT obligations are correctly applied and evidence is produced per right/article', 6),
      q("TECH-PP-15", "Fair Contracting", "Does the agent screen data-sharing terms proposed to or by partner enterprises for unfair contractual terms under EU Data Act 2023/2854 Article 13, and flag unilaterally imposed terms on data access and use for legal review?", "EU Data Act 2023/2854 Art. 13", "Data-sharing terms are not reviewed for fairness", "Legal reviews new templates, but negotiated changes and partner-imposed terms are not screened", "Every data-sharing term set is screened against the Article 13 list of unfair terms, findings are routed to legal with the clause cited, and the review outcome is retained", 8),
  ]
};
