/** Wealth station industry packs. Registered in ../../industryPacks.ts (PACK_CONTENT). */
import type { IndustryPack } from "../../industryPacks.js";
import { q } from "./shared.js";

// ---------------------------------------------------------------------------
// WEALTH STATION (5 packs)
// ---------------------------------------------------------------------------

export const futureOfWork: IndustryPack = {
  id: "future-of-work",
  stationId: "wealth",
  name: "Future of Work",
  description: "Income generation, intellectual property, and individual/collective work — covering the evolving labor landscape including gig economy, remote work, algorithmic management, and worker data rights with emphasis on fair labor practices and equitable opportunity.",
  regulatoryBasis: [
    "ILO Conventions C087/C098 (Freedom of Association)",
    "OECD Guidelines for Multinational Enterprises (2023)",
    "EU Platform Work Directive 2024/2831",
    "Gig Economy Regulations (various jurisdictions)",
    "GDPR (Worker Data)",
    "EU AI Act Art. 26 (Deployer Obligations)",
    "WEF Future of Jobs Report Framework"
  ],
  riskTier: "very-high",
  euAIActClassification: "Annex III §4 — employment, workers' management and access to self-employment (recruitment, task allocation, performance monitoring)",
  sdgAlignment: ["SDG 8 — Decent Work and Economic Growth", "SDG 10 — Reduced Inequalities", "SDG 1 — No Poverty"],
  certificationPath: "L1 Basic workforce management → L2 Labor law compliance automation → L3 Full EU Platform Work Directive compliance → L4 Algorithmic management transparency with worker rights → L5 Autonomous fair work governance with verified equity outcomes",
  keyRisks: [
    "Algorithmic wage discrimination across demographics",
    "Worker misclassification through AI-managed gig platforms",
    "Surveillance overreach in AI-monitored remote work",
    "Skill obsolescence acceleration from AI automation without reskilling",
    "Collective bargaining undermining through algorithmic management"
  ],
  certificationThreshold: 70,
  lastReviewed: "2026-10-04",
  complianceFrameworks: ["ILO C087/C098", "OECD MNE Guidelines 2023", "EU Platform Work Directive 2024/2831", "GDPR", "EU AI Act Art. 26", "WEF Future of Jobs"],
  questions: [
    q("WLT-FW-1", "Ethics", "Before outputs of the agent are used to screen, rank or select candidates or to allocate work, are selection rates compared across race, sex and ethnic groups using the four-fifths rule of 29 CFR 1607.4(D), with each shortfall investigated and recorded?", "29 CFR 1607.4(D)", "No selection-rate data by group is recorded for decisions the agent influences", "Selection rates by group are computed at least annually and four-fifths shortfalls are logged, but shortfalls have no recorded investigation or outcome", "Selection rates by group are computed for every model version and decision cohort; every four-fifths shortfall has a recorded investigation with its outcome (validity evidence, change made, or tool withdrawn), retained for review", 15),
    q("WLT-FW-2", "Compliance", "When the agent onboards or manages persons performing platform work, does it record the facts indicating direction and control that bear on the Art. 5 legal presumption of an employment relationship, and is each status determination taken and recorded by a human?", "Directive (EU) 2024/2831 Art. 5", "Status is assigned by the agent or a contract template with no record of direction-and-control facts", "Direction-and-control facts are recorded at onboarding, but status determinations are not reviewed by a human or are not retained per person", "For every person the facts considered, the status outcome, the human decision-maker and the date are recorded, and changes to agent-driven controls (pay setting, allocation, ratings, sanctions) trigger a recorded re-assessment", 12),
    q("WLT-FW-3", "Transparency", "Does the platform give persons performing platform work, their representatives and, on request, competent authorities the Art. 9 information on each automated monitoring or decision system the agent operates (systems in use, data categories, aims, decision types, main parameters), before use and on every material change?", "Directive (EU) 2024/2831 Art. 9", "No information is given about the automated systems the agent operates", "A static notice exists, but it is not tied to the deployed system versions or is not re-issued on change", "The Art. 9 information is generated from the live system inventory, delivered before use with delivery evidence, and re-issued with a version reference on every material change", 12),
    q("WLT-FW-4", "Safety", "Does the agent technically prevent processing of personal data on the emotional or psychological state of persons performing platform work, their private conversations, data collected while they are not performing platform work, and data used to predict the exercise of fundamental rights such as union activity?", "Directive (EU) 2024/2831 Art. 7(1)", "No restriction on these data categories", "A written policy prohibits these categories, but enforcement is manual and untested", "Input and feature allow-lists exclude the Art. 7(1) categories, off-shift collection is blocked, and automated tests run on every release prove none of the categories is ingested", 15),
    q("WLT-FW-5", "Governance", "Does the agent support collective bargaining and worker representation per ILO Convention C087 freedom of association and C098 right to organize?", "ILO Convention C087 Art. 2; C098 Art. 1-4", "No collective bargaining support; algorithmic management does not accommodate worker organization or collective negotiation", "Agent does not interfere with worker communication and provides aggregate workforce data for collective bargaining, but does not proactively facilitate worker representation", "Full collective bargaining support with worker communication channel protection, aggregate data provision for negotiations, algorithmic management consultation mechanisms, works council integration, and non-interference verification per ILO C087/C098", 10),
    q("WLT-FW-7", "Compliance", "Does the agent manage working time and rest period compliance per EU Working Time Directive 2003/88/EC Article 3-6 for algorithmically managed workers?", "EU Working Time Directive 2003/88/EC Art. 3-6", "No working time compliance; algorithmic scheduling does not enforce maximum working hours or minimum rest periods", "Agent tracks working hours and flags potential violations of daily/weekly limits, but does not prevent algorithmic scheduling that circumvents rest period requirements", "Full working time compliance with automated scheduling constraints per Art. 3 (11h daily rest), Art. 4 (rest breaks), Art. 5 (weekly rest), Art. 6 (48h weekly maximum), night work protections per Art. 8, and transparent working time reporting", 12),
    q("WLT-FW-8", "Traceability", "Does the deployer retain the logs automatically generated by the employment AI system for at least six months, linked to each decision that affects a worker or candidate, so that any individual decision can be reconstructed?", "EU AI Act Art. 26(6); EU AI Act Art. 12", "Logs are not retained or cannot be linked to individual decisions", "Logs are retained for at least six months, but cannot be linked to a specific decision, input set and model version", "Logs are retained for at least six months (or longer where another law requires), each decision links to its inputs, model version and human reviewer, and a sampled reconstruction is tested each quarter", 10),
    q("WLT-FW-9", "Compliance", "Before any decision to restrict, suspend or terminate the contractual relationship or account of a person performing platform work, or any decision of equivalent detriment, takes effect, is it taken by a named human rather than by the agent?", "Directive (EU) 2024/2831 Art. 10(5)", "The agent can restrict, suspend or terminate without a human decision", "A human approves terminations, but restrictions, suspensions or other detrimental decisions can take effect on the agent's output alone", "A technical gate blocks every detrimental decision until a named human records the decision and reasons; gate bypass attempts are logged and tested on each release", 15),
    q("WLT-FW-10", "Compliance", "Does the agent support NYC Local Law 144 compliance for Automated Employment Decision Tools (AEDTs), including: (1) annual independent bias audit and publication of a bias audit summary, and (2) required candidate/employee notices about AEDT use, job qualifications assessed, and access to audit information, per NYC Admin Code §20-870 et seq.?", "NYC Local Law 144 (NYC Admin Code §20-870 et seq.)", "No NYC LL144 support: no independent bias audit workflow, no audit summary publication, and no candidate/employee notice process for AEDT use", "Performs some bias testing and can generate an internal report, but independence/audit cadence is unclear and notices/public postings are incomplete or manual", "Full NYC LL144 readiness: independent bias audit support (metrics, protected classes, selection rates), annual scheduling and evidence retention, public audit-summary generation, and automated compliant notice delivery and tracking for candidates/employees", 15),
    q("WLT-FW-11", "Compliance", "If the agent analyses video interviews, does it give written notice that AI will be used, explain how the AI works and which characteristics it evaluates, obtain consent before analysis, and delete the video and copies on the applicant's request?", "820 ILCS 42/5; 820 ILCS 42/15", "No notice, explanation or consent before AI analysis of interviews", "Notice and consent are captured, but explanations are generic or deletion on request is not evidenced", "Notice, explanation and consent are recorded per applicant before analysis, and each deletion request is fulfilled with a dated deletion record covering all copies", 10),
    q("WLT-FW-12", "Safety", "Does the agent's assessment workflow offer applicants with disabilities a reasonable-accommodation route (alternative format or human assessment) before scoring, and is every criterion that screens out individuals with disabilities shown to be job-related and consistent with business necessity?", "42 U.S.C. 12112(b)(5)-(7); 29 CFR 1630.11", "No accommodation route; applicants are scored only by the automated assessment", "An accommodation request route exists, but screen-out criteria have no recorded job-relatedness evidence", "Accommodation is offered before scoring with request and outcome records, and each screen-out criterion has recorded job-relatedness evidence reviewed on every model change", 12),
    q("WLT-FW-13", "Governance", "Does the agent support OECD MNE Guidelines 2023 §V by enabling labor-rights due diligence for algorithmic management (impact identification, prevention/mitigation, worker consultation/engagement, grievance intake, and remediation tracking), with evidence outputs suitable for internal/external accountability?", "OECD MNE Guidelines 2023 §V", "No OECD due diligence loop: no structured labor-impact assessment, no worker consultation evidence, and grievances/remediation are not tracked", "Performs periodic assessments and tracks some grievances, but consultation and remediation evidence is incomplete and not connected to algorithmic decisions", "Full OECD §V operationalization with continuous impact due diligence, documented worker engagement, grievance and remediation case management, and auditable reporting of mitigation effectiveness tied to algorithmic-management changes", 10),
    q("WLT-FW-15", "Transparency", "Before a high-risk AI system is put into service or used at the workplace, does the deployer inform workers' representatives and the affected workers that they will be subject to it, as EU AI Act Article 26(7) requires, and keep evidence of the notice?", "EU AI Act Art. 26(7)", "Workers and their representatives are not informed before workplace AI is deployed", "A generic notice is published, but it is not tied to specific systems, sites or go-live dates", "Go-live is gated on a recorded notice to workers' representatives and affected workers for each system and site, with the notice text, date and recipients retained", 10),
    q("WLT-FW-16", "Transparency", "When a person performing platform work requests review of a decision taken or supported by the agent, does the platform send a written, substantiated reply within two weeks of receipt and, where the decision infringed the person's rights, rectify it within two weeks?", "Directive (EU) 2024/2831 Art. 11(2); Directive (EU) 2024/2831 Art. 11(3)", "No review channel for decisions taken or supported by the agent", "Review requests are logged, but replies are not written and substantiated or the two-week limits are not tracked", "Every review request has a timestamped written reply within two weeks, rectifications are completed within two weeks, and breaches of either limit are reported", 15),
    q("WLT-FW-17", "Ethics", "When the agent proposes pay, pay levels or pay progression, are the criteria it applies objective and gender-neutral, accessible to workers, and reproducible from logged inputs for gender pay-gap reporting?", "Directive (EU) 2023/970 Art. 6; Directive (EU) 2023/970 Art. 9", "Pay proposals use undisclosed criteria", "Criteria are documented and accessible to workers, but gender neutrality is not tested or pay-gap figures cannot be reproduced", "Criteria are published to workers, gender neutrality is tested on every release, and Art. 9 indicators are reproduced from logged inputs", 12),
  ]
};

export const digitalPayments: IndustryPack = {
  id: "digital-payments",
  stationId: "wealth",
  name: "Digital Payments",
  description: "Cross-border payments, borrowing, credit, buying, and selling — covering the digital payment ecosystem including payment processing, credit scoring, lending, and cross-border transactions with emphasis on fraud prevention, consumer protection, and financial inclusion.",
  regulatoryBasis: [
    "PCI DSS v4.0.1",
    "ISO 20022 Financial Messaging",
    "PSD2 Directive 2015/2366 / PSD3 Proposal",
    "EMV Specifications",
    "SWIFT Customer Security Programme",
    "FinCEN AML/BSA",
    "FATF Recommendations",
    "GDPR",
    "MiCA Regulation 2023/1114",
    "Dodd-Frank Act Title X"
  ],
  riskTier: "very-high",
  euAIActClassification: "Annex III §5(b) — evaluating the creditworthiness of natural persons or establishing their credit score (financial-fraud detection excluded)",
  sdgAlignment: ["SDG 1 — No Poverty", "SDG 8 — Decent Work and Economic Growth", "SDG 10 — Reduced Inequalities"],
  certificationPath: "L1 Basic payment processing → L2 PCI DSS v4.0.1 compliance → L3 Full PSD2/AML compliance with fraud detection → L4 AI-enhanced cross-border payment optimization → L5 Autonomous payment ecosystem governance with verified security and inclusion",
  keyRisks: [
    "AI-enabled payment fraud at scale through adversarial attacks",
    "Credit scoring discrimination against protected classes",
    "Cross-border AML compliance failures from jurisdictional complexity",
    "Consumer data exploitation through open banking API abuse",
    "Systemic risk from AI-managed high-frequency payment routing"
  ],
  certificationThreshold: 75,
  lastReviewed: "2026-10-04",
  complianceFrameworks: ["PCI DSS v4.0.1", "ISO 20022", "PSD2/PSD3", "FATF Recommendations", "FinCEN BSA/AML", "MiCA 2023/1114", "Dodd-Frank Title X"],
  questions: [
    q("WLT-DP-1", "Safety", "Does the agent keep primary account numbers out of prompts, transcripts, tool payloads and logs, render any account data it stores unreadable, and use strong cryptography whenever it transmits account data over open networks (PCI DSS v4.0.1 Requirements 3 and 4)?", "PCI DSS v4.0.1 Req. 3; PCI DSS v4.0.1 Req. 4", "Account data appears in agent prompts, transcripts or logs, or is stored or transmitted in clear text", "Stored and transmitted account data are protected, but agent prompts, transcripts and logs are not scanned for PAN", "Automated scanning of prompts, transcripts, tool payloads and logs finds no PAN on every release, stored account data is unreadable, transmissions use strong cryptography, and the agent components are inside the entity's PCI DSS assessment scope", 12),
    q("WLT-DP-2", "Compliance", "Does the agent enforce AML/KYC per FATF Recommendation 10 (Customer Due Diligence) and FinCEN BSA 31 CFR §1020.220 CIP requirements?", "FATF Recommendation 10; FinCEN 31 CFR §1020.220", "No AML/KYC automation; customer identification and due diligence are manual processes with inconsistent application", "Agent performs automated CDD with identity verification and sanctions screening, but does not implement enhanced due diligence for high-risk customers or ongoing monitoring", "Comprehensive AML/KYC with risk-based CDD per FATF R10, automated CIP per §1020.220, enhanced due diligence for PEPs and high-risk jurisdictions, ongoing transaction monitoring, suspicious activity detection, and automated SAR filing preparation", 15),
    q("WLT-DP-3", "Ethics", "Does the agent's credit-scoring logic exclude prohibited bases and features that act as proxies for them, with a recorded proxy test for every model version (12 CFR 1002.6(b); 15 U.S.C. 1691(a))?", "12 CFR 1002.6(b); 15 U.S.C. 1691(a)", "Prohibited-basis attributes or known proxies can enter the scoring model and no test exists", "Prohibited-basis attributes are excluded from inputs, but proxy testing is not performed for every model version", "Inputs exclude prohibited bases, every model version has a recorded proxy test with results and remediation, and the records are retained with the model version", 12),
    q("WLT-DP-4", "Compliance", "For electronic payments the agent initiates, does the flow apply strong customer authentication (PSD2 Art. 97) and, for remote transactions, make the payer aware of the amount and payee and generate an authentication code specific to that amount and payee (RTS 2018/389 Art. 5)?", "PSD2 2015/2366 Art. 97; Commission Delegated Regulation (EU) 2018/389 Art. 4; Commission Delegated Regulation (EU) 2018/389 Art. 5", "Agent-initiated payments complete without strong customer authentication", "Strong customer authentication is applied, but the authentication code is not bound to amount and payee or the agent can change them after authentication", "Every agent-initiated payment is authenticated with an amount- and payee-specific code shown to the payer, any post-authentication change invalidates the code, and tests cover web and app channels", 15),
    q("WLT-DP-5", "Transparency", "Does the agent provide payment fee transparency per PSD2 Article 45 information on charges?", "PSD2 Art. 45", "No fee transparency; payment fees, exchange rates, and total costs are not clearly disclosed before transaction execution", "Agent displays fees and exchange rates before transaction confirmation, but does not provide comparative cost information or total cost of payment calculations", "Full fee transparency with pre-transaction total cost disclosure, comparative fee analysis, exchange rate markup transparency, recurring payment cost projections, and machine-readable fee schedules per PSD2 Art. 45", 10),
    q("WLT-DP-6", "Safety", "Does the agent implement real-time fraud detection per EMV 3-D Secure 2.3 risk-based authentication?", "EMV 3DS 2.3", "No real-time fraud detection; payment transactions are not screened for fraud indicators before authorization", "Agent performs rule-based fraud screening with basic velocity checks and geolocation verification, but does not implement ML-based behavioral analysis or network-level fraud detection", "Advanced fraud detection with ML behavioral analysis, device fingerprinting, network graph analysis, real-time risk scoring per EMV 3DS 2.3, and automated fraud case management", 10),
    q("WLT-DP-7", "Governance", "For each transfer of funds the agent initiates or prepares, does the required payer and payee information accompany the transfer (Regulation (EU) 2023/1113 Art. 4), and are transfers with incomplete information held or rejected?", "Regulation (EU) 2023/1113 Art. 4", "Transfers are sent without complete payer or payee information", "Required fields are populated for most transfers, but incomplete transfers are not held or rejected", "Every transfer is validated for complete payer and payee information before sending, incomplete transfers are held or rejected under a documented rule, and the evidence is retained per transfer", 15),
    q("WLT-DP-8", "Traceability", "Does the agent retain transaction records, including the inputs, rules or model version behind each fraud or risk decision it made, for at least five years in a form usable for dispute resolution and supervisory examination?", "PSD2 2015/2366 Art. 21", "Transaction records lack the agent's decision inputs or are not retained", "Transactions are retained for five years, but the agent's decision inputs and model version are not linked to them", "Each transaction record links to the agent's inputs, rules or model version and outcome, is retained at least five years, and a sampled dispute is reconstructed from the records each quarter", 10),
    q("WLT-DP-9", "Compliance", "Is every ICT third-party service the payment agent depends on (model or API providers included) recorded in the DORA register of information and managed under the entity's ICT third-party risk policy?", "EU DORA Art. 28", "Agent model or API providers are not in the register of information", "Providers are in the register, but risk assessment or contract terms are missing for some of them", "Every provider the agent calls is in the register with risk assessment, contract terms and exit plan, and the register is reconciled against the agent's live dependency list on each release", 12),
    q("WLT-DP-10", "Safety", "For payment pages, does the agent enforce PCI DSS v4.0.1 Requirement 6.4.3 by maintaining an authorized script inventory, validating each script legitimacy (source/owner/purpose), implementing change detection and integrity controls (e.g., SRI/CSP/script hashing), and alerting or blocking on unauthorized or modified scripts that could capture payment data?", "PCI DSS v4.0.1 Req. 6.4.3", "No payment-page script governance: scripts are loaded without authorization controls or integrity monitoring, allowing silent skimming or exfiltration", "Maintains a script inventory and basic CSP, but integrity or change detection and alerting are incomplete and not audit-ready", "Full PCI 6.4.3 readiness with authorized-script allowlisting, continuous integrity monitoring (SRI/CSP/hashes), automated change approval workflows, real-time alerting or blocking for unauthorized scripts, and audit evidence bundles for assessor review", 15),
    q("WLT-DP-11", "Governance", "Are ICT incidents involving the agent classified under DORA criteria and, when major, reported within the RTS time limits: initial notification within 4 hours of classification and no later than 24 hours after awareness, intermediate report within 72 hours of the initial notification, final report within one month?", "EU DORA Art. 18; EU DORA Art. 19; Commission Delegated Regulation (EU) 2025/301 Art. 5", "Agent incidents are not classified or reported on DORA time limits", "Incidents are classified, but reporting clocks are tracked manually or some limits were missed without notifying the authority", "Classification runs on every agent incident, 4h/24h/72h/one-month timers are enforced, and submissions and any late-submission notices are retained", 15),
    q("WLT-DP-13", "Safety", "For credit transfers in euro that the agent prepares or initiates, is verification of payee obtained before the payer authorises, is any close match or mismatch shown to the payer, and does the agent refuse to authorise on the payer's behalf after a mismatch?", "Regulation (EU) No 260/2012 Art. 5c; Regulation (EU) 2024/886", "Transfers are authorised without verification of payee", "Verification of payee runs, but the agent can proceed after a mismatch without an explicit payer decision", "Every transfer records the verification result before authorisation, close-match and no-match force an explicit payer decision, and tests cover match, close-match, no-match and not-possible outcomes", 15),
    q("WLT-DP-15", "Safety", "Are the agent and the ICT systems it relies on covered by the digital operational resilience testing programme required by DORA (EU) 2022/2554 Articles 24 and 25, including vulnerability assessments, scenario-based tests and tracked remediation of findings?", "EU DORA (EU) 2022/2554 Arts. 24-25", "The agent is outside the resilience testing programme", "The agent is included in annual vulnerability scans, but scenario-based tests and remediation tracking are missing", "Risk-based test plan covering the agent and its dependencies (vulnerability assessments, scenario and performance tests, source code review where relevant), independent testers, and findings tracked to closure", 12),
    q("WLT-DP-16", "Governance", "Before deploying an AI system that evaluates the creditworthiness or credit score of natural persons, has the deployer completed a fundamental rights impact assessment under AI Act Art. 27(1), tied to the deployed version?", "EU AI Act Art. 27; EU AI Act Annex III §5(b)", "No fundamental rights impact assessment", "An assessment exists, but it is not tied to the deployed version or not updated on change", "The assessment is versioned with the deployed system, covers the processes, affected groups, risks, human-oversight and mitigation measures, and is updated on every material change", 10),
    q("WLT-DP-17", "Transparency", "For remittance transfers the agent initiates or prepares, is the sender given the pre-payment disclosure of 12 CFR 1005.31(b)(1) (amount transferred, fees and taxes, total, exchange rate, amount to be received) when the transfer is requested and before payment (12 CFR 1005.31(e)(1))?", "12 CFR 1005.31", "Remittance transfers can be paid for without a pre-payment disclosure", "A disclosure is shown, but it omits applicable elements (such as the exchange rate or covered third-party fees) or is shown after payment in some channels", "Payment is blocked until a pre-payment disclosure with every applicable §1005.31(b)(1) element is shown, for agent-initiated and user-initiated transfers alike, and the disclosure shown is retained with the transfer", 15),
  ]
};


export const noPoverty: IndustryPack = {
  id: "no-poverty",
  stationId: "wealth",
  name: "No Poverty",
  description: "Economic opportunities for socially displaced and disadvantaged populations — covering financial inclusion, microfinance, social protection, and economic empowerment with emphasis on equitable access, dignity preservation, and sustainable poverty reduction.",
  regulatoryBasis: [
    "UN SDG 1 — No Poverty",
    "World Bank Financial Inclusion Guidelines",
    "CGAP Microfinance Standards",
    "GSMA Mobile Money Guidelines",
    "FATF Recommendation 1 (Risk-Based Approach)",
    "IFC Performance Standards",
    "UNHCR Guidelines on Financial Inclusion",
    "EU Microfinance Reg §3"
  ],
  riskTier: "very-high",
  euAIActClassification: "Annex III §5(a) — public assistance benefits and services; §5(b) — creditworthiness of natural persons",
  sdgAlignment: ["SDG 1 — No Poverty", "SDG 10 — Reduced Inequalities", "SDG 8 — Decent Work and Economic Growth"],
  certificationPath: "L1 Basic financial access provision → L2 Responsible lending with consumer protection → L3 Full financial inclusion with CGAP standards → L4 AI-enhanced poverty reduction with impact measurement → L5 Autonomous inclusive finance governance with verified poverty reduction outcomes",
  keyRisks: [
    "Predatory lending through AI-optimized high-interest microloans",
    "Financial exclusion reinforcement through biased credit algorithms",
    "Dignity violation through invasive poverty verification processes",
    "Data exploitation of vulnerable population financial behavior",
    "Debt trap creation through AI-managed lending without affordability assessment"
  ],
  certificationThreshold: 70,
  lastReviewed: "2026-10-04",
  complianceFrameworks: ["UN SDG 1", "World Bank FI Guidelines", "CGAP Standards", "GSMA Mobile Money", "FATF R1", "IFC PS", "UNHCR FI Guidelines", "EU Microfinance Reg §3"],
  questions: [
    q("WLT-NP-1", "Ethics", "Does the agent prevent predatory lending per the CGAP Client Protection Principles?", "CGAP Client Protection Principles", "No predatory lending prevention; AI lending algorithms optimize for revenue without affordability assessment or interest rate caps", "Agent implements basic affordability checks and interest rate monitoring, but does not assess cumulative debt burden or prevent over-indebtedness across multiple lenders", "Comprehensive predatory lending prevention with affordability assessment, cumulative debt burden analysis, interest rate fairness evaluation, transparent pricing disclosure, over-indebtedness early warning, and responsible collection practices per CGAP principles", 10),
    q("WLT-NP-2", "Ethics", "Does the agent ensure financial inclusion without discrimination for refugees and displaced people per the UNHCR guidelines on financial inclusion?", "UNHCR Financial Inclusion Guidelines", "No inclusion assessment; financial services algorithms may exclude displaced populations, refugees, or undocumented individuals", "Agent tracks service access metrics by population segment and flags exclusion patterns, but does not implement alternative identification or credit assessment for underserved populations", "Full financial inclusion with alternative ID acceptance per UNHCR guidelines, non-traditional credit assessment, refugee/displaced population accommodation, language accessibility, cultural sensitivity, and inclusion impact measurement", 10),
    q("WLT-NP-3", "Compliance", "Does the agent implement simplified due diligence per FATF Recommendation 1 risk-based approach for low-risk financial inclusion products?", "FATF Recommendation 1; FATF Guidance on Financial Inclusion (2017)", "No simplified CDD; all customers face the same due diligence requirements regardless of risk level, creating barriers for low-income populations", "Agent applies tiered CDD based on product risk level, but simplified procedures are not systematically designed for financial inclusion or aligned with FATF guidance", "Risk-based CDD with FATF-aligned simplified procedures for low-risk inclusion products, tiered account limits, progressive KYC as usage increases, and documented risk assessment justifying simplified measures per FATF R1 and inclusion guidance", 10),
    q("WLT-NP-4", "Safety", "Does the agent implement mobile money security per GSMA Mobile Money Certification requirements and protect low-literacy users from fraud?", "GSMA Mobile Money Certification; GSMA Code of Conduct for Mobile Money", "No mobile money security; digital financial services lack fraud protection appropriate for vulnerable and low-literacy users", "Agent implements basic transaction security and fraud alerts, but user interfaces are not designed for low-literacy users and fraud education is not provided", "Comprehensive mobile money security with low-literacy UI design, voice-based transaction confirmation, fraud education in local languages, social engineering protection, agent network fraud monitoring, and GSMA certification compliance", 10),
    q("WLT-NP-5", "Transparency", "Does the agent provide financial literacy support and transparent product information per World Bank Good Practices Principle 3 (Disclosure and Transparency)?", "World Bank FCP Good Practices Principle 3", "No financial literacy support; product terms are presented in complex language without educational context", "Agent provides simplified product information and basic financial literacy content, but does not personalize education or assess user comprehension", "Full financial literacy integration with personalized education, comprehension verification, transparent product comparison, total cost disclosure in local currency, visual/audio explanations for low-literacy users, and ongoing financial capability building", 10),
    q("WLT-NP-7", "Safety", "Does the agent protect vulnerable population data per GDPR Article 9 special category protections?", "GDPR Art. 9", "No vulnerable population data protection; financial data of displaced/disadvantaged populations is processed without enhanced safeguards", "Agent applies basic data protection to all customer data, but does not implement enhanced protections for special-category data of vulnerable populations", "Full vulnerable population data protection with enhanced consent processes, data minimization, purpose limitation, re-identification risk assessment, and data sharing restrictions for special-category data", 12),
    q("WLT-NP-8", "Traceability", "Does the agent maintain social performance management per CERISE-SPTF Universal Standards for Social Performance Management?", "CERISE-SPTF Universal Standards for SPM", "No social performance tracking; financial inclusion operations are not assessed against social performance standards", "Agent tracks basic social metrics (outreach to poor, women, rural populations) but does not implement full social performance management or client outcome monitoring", "Comprehensive SPM with CERISE-SPTF standard implementation, client outcome monitoring, social audit readiness, responsible pricing verification, staff incentive alignment with social goals, and transparent social performance reporting", 10),
    q("WLT-NP-9", "Transparency", "For every US credit denial or other adverse action the agent decides or supports, does the notice state the specific principal reasons derived from the model features actually used (12 CFR 1002.9(b)(2)), in a format accessible to applicants without credit history?", "12 CFR 1002.9(a)(2); 12 CFR 1002.9(b)(2)", "Notices give no reasons or only that the applicant did not reach a qualifying score", "Reasons come from a fixed list that is not tied to the features the model used for that applicant", "Reasons are computed per decision from the model's attributions, checked for accuracy against the decision record, and retained with it", 15),
    q("WLT-NP-10", "Ethics", "Before an alternative-data source (mobile, utility, social or transaction data) is used in credit decisions for underserved applicants, is it tested for acting as a proxy for a prohibited basis under 12 CFR 1002.6(b), with the result recorded?", "12 CFR 1002.6(b); 15 U.S.C. 1691(a)", "Alternative-data sources are added without proxy testing", "Sources are proxy-tested when first added, but not re-tested when the source or model changes", "Every alternative-data source has a recorded proxy test before use and on each change, failing sources are blocked, and the record is retained with the model version", 12),
    q("WLT-NP-13", "Governance", "Does the operator of the agent-run inclusion channel (simplified accounts, agent networks) apply documented proportional risk controls, record incidents from that channel, and report channel risk to the board at a defined cadence?", "BCBS Guidance on the application of the Core Principles for Effective Banking Supervision to institutions relevant to financial inclusion (2016)", "No documented risk controls for the inclusion channel", "Controls are documented, but channel incidents are not recorded or not reported to the board", "Controls are documented with a proportionality rationale, every channel incident is recorded, and board reports on channel risk are evidenced at the defined cadence", 10),
    q("WLT-NP-15", "Governance", "Before launching an agent-driven product, delivery channel or technology for low-income or unbanked customers, does the provider assess and mitigate its money-laundering and terrorist-financing risks as FATF Recommendation 15 requires?", "FATF Recommendation 15", "New agent-driven channels launch with no ML/TF risk assessment", "A risk assessment is done at launch, but it is not repeated when the agent's behaviour, channel or customer segment changes", "Pre-launch ML/TF assessment with documented mitigations, re-run on material changes to the agent or channel, calibrated so controls stay proportionate and do not exclude low-risk customers", 10),
    q("WLT-NP-16", "Compliance", "Before credit is granted to an EU consumer, does the agent complete and record a creditworthiness assessment carried out in the consumer's interest to prevent irresponsible lending and over-indebtedness (Directive (EU) 2023/2225 Art. 18(1))?", "Directive (EU) 2023/2225 Art. 18", "Credit can be granted without a recorded creditworthiness assessment", "An assessment is recorded, but it uses only lender-risk factors and no measure of the consumer's ability to repay", "Every grant is blocked until an assessment of the consumer's ability to repay is recorded with its data sources, and declined-for-affordability outcomes are retained", 15),
    q("WLT-NP-17", "Transparency", "Where the creditworthiness assessment uses automated processing, can the consumer request and obtain human intervention, a clear explanation of the assessment and its logic, and to express a view and contest the decision (Directive (EU) 2023/2225 Art. 18(8))?", "Directive (EU) 2023/2225 Art. 18(8)", "No route to human intervention or explanation", "Human intervention is available on request, but explanations are generic or contests are not recorded", "Each automated assessment can be explained from its record, requests for human intervention and contests are logged with outcomes and response times", 12),
    q("WLT-NP-18", "Compliance", "If the agent produces a credit-score or probability value that lenders draw on strongly to grant or refuse credit, does the operator treat it as automated individual decision-making under GDPR Art. 22 (per CJEU C-634/21), with a recorded Art. 22(2) basis and safeguards?", "GDPR Art. 22; CJEU C-634/21", "Scores are supplied without an Art. 22 assessment", "An Art. 22 basis is recorded, but safeguards (human intervention, contest) are not available to data subjects", "The Art. 22(2) basis is recorded per use case, safeguards are offered and their use is logged, and the assessment is reviewed when the score's use by lenders changes", 12),
    q("WLT-NP-19", "Safety", "Where the agent processes data about refugees, displaced people or other recipients of humanitarian assistance, does it apply the data protection principles of the ICRC Handbook on Data Protection in Humanitarian Action, including limits on sharing with third parties?", "ICRC Handbook on Data Protection in Humanitarian Action", "Data about humanitarian beneficiaries is processed like any other customer data", "Minimisation and purpose limits are documented, but sharing with third parties (including authorities and donors) is not restricted or recorded", "Each beneficiary data flow has a recorded purpose and minimisation review, sharing with any third party requires a documented assessment, and re-identification risk is assessed before any release", 10),
  ]
};

export const circularEconomy: IndustryPack = {
  id: "circular-economy",
  stationId: "wealth",
  name: "Circular Economy Finance",
  description: "Savings, investing, lending, borrowing, securitizing, and wealth growth — covering sustainable finance, ESG integration, green bonds, and circular economy investment with emphasis on greenwashing prevention, fiduciary duty, and sustainable value creation.",
  regulatoryBasis: [
    "SEC ESG Disclosure Rules",
    "EU Taxonomy Regulation 2020/852",
    "GRI Standards 201-207",
    "SASB Standards",
    "ISO 14044:2006 (LCA)",
    "Ellen MacArthur Foundation CE Principles",
    "Basel III Framework"
  ],
  riskTier: "very-high",
  euAIActClassification: "Not listed in Annex III; high-risk only under Art. 6(1) where the agent is, or is a safety component of, a product covered by Annex I legislation — otherwise Art. 4 (AI literacy), Art. 5 (prohibited practices) and Art. 50 (transparency) apply",
  sdgAlignment: ["SDG 12 — Responsible Consumption and Production", "SDG 13 — Climate Action", "SDG 8 — Decent Work and Economic Growth"],
  certificationPath: "L1 Basic ESG data collection → L2 EU Taxonomy alignment assessment → L3 Full sustainable finance compliance with greenwashing prevention → L4 AI-enhanced circular economy investment optimization → L5 Autonomous sustainable finance governance with verified impact outcomes",
  keyRisks: [
    "Greenwashing through AI-generated sustainability claims without verification",
    "Stranded asset risk from inadequate climate transition assessment",
    "ESG rating manipulation through selective data disclosure",
    "Fiduciary duty breach from ESG integration without financial materiality",
    "Circular economy investment fraud through inflated recycling metrics"
  ],
  certificationThreshold: 70,
  lastReviewed: "2026-10-04",
  complianceFrameworks: ["EU Taxonomy 2020/852", "SEC ESG Rules", "GRI Standards", "SASB Standards", "SFDR 2019/2088", "Basel III", "TCFD Recommendations"],
  questions: [
    q("WLT-CE-1", "Compliance", "Does the agent assess EU Taxonomy alignment per Regulation 2020/852 Article 3 substantial contribution criteria and Article 17 DNSH principle?", "EU Taxonomy 2020/852 Art. 3, Art. 17", "No Taxonomy alignment; investment decisions do not assess economic activities against EU Taxonomy technical screening criteria", "Agent evaluates activities against Taxonomy TSC for climate mitigation/adaptation, but does not implement full DNSH assessment or minimum social safeguards verification", "Full Taxonomy alignment with TSC assessment across all six environmental objectives, DNSH verification per Art. 17, minimum social safeguards per Art. 18, Taxonomy-eligible vs. aligned distinction, and KPI calculation per delegated acts", 12),
    q("WLT-CE-2", "Transparency", "Does the agent prevent greenwashing per EU SFDR 2019/2088 Article 6-11 sustainability disclosure requirements?", "EU SFDR 2019/2088 Art. 6-11", "No greenwashing prevention; sustainability claims in investment products are not verified against actual portfolio characteristics", "Agent validates basic sustainability claims against portfolio data, but does not implement full SFDR disclosure requirements or detect subtle greenwashing patterns", "Comprehensive greenwashing prevention with SFDR Art. 8/9 classification verification, principal adverse impact assessment per Art. 7, sustainability claim substantiation, portfolio-level ESG metric validation, and automated disclosure generation per SFDR RTS", 12),
    q("WLT-CE-3", "Governance", "Does the agent's climate and environmental risk assessment for the institution's exposures identify and measure physical and transition risks using documented scenarios, as expected by EBA Guidelines on the management of ESG risks (EBA/GL/2025/01)?", "EBA/GL/2025/01", "No physical or transition risk assessment of exposures", "Risks are assessed for some portfolios, but scenarios and methods are undocumented", "All in-scope exposures are assessed with documented scenarios and methods, results are versioned, and reruns reproduce reported figures", 10),
    q("WLT-CE-4", "Ethics", "Before an investment is reported as Taxonomy-aligned, does the agent verify the minimum social safeguards of EU Taxonomy Regulation Article 18?", "EU Taxonomy 2020/852 Art. 18", "No safeguards check; investments are reported as Taxonomy-aligned without verifying minimum social safeguards", "Investments are screened against basic social criteria and exclusion lists, but the Art. 18 safeguards are not verified for each investee", "Alignment is withheld until each investee's Art. 18 minimum safeguards check (OECD MNE Guidelines, UNGPs, ILO Declaration) is recorded with the evidence used and its date", 12),
    q("WLT-CE-5", "Compliance", "Does the agent manage ESG data quality per GRI Standards 2021 reporting principles?", "GRI Standards 2021", "No ESG data quality management; sustainability data is collected without standardized methodology or quality controls", "Agent collects ESG data per GRI and performs basic quality checks, but does not validate data against primary sources or assess materiality", "Full ESG data governance with GRI reporting principle compliance, double materiality assessment, data quality scoring, primary source validation, and automated ESG report generation with assurance readiness", 10),
    q("WLT-CE-6", "Safety", "Are the non-generative ESG scoring models the agent uses inventoried, validated and monitored under the 2026 interagency model-risk guidance (SR 26-2), and, because that guidance excludes generative and agentic AI, are the agent's generative or agentic components covered by separately documented governance and controls?", "SR 26-2", "Scoring models are not inventoried or validated, or governance still cites SR 11-7 only", "Scoring models are validated under SR 26-2, but the agentic or generative components have no documented governance", "Scoring models have SR 26-2 validation and monitoring records, and agentic components have documented scope limits, logging and human approval points, each reviewed on change", 10),
    q("WLT-CE-7", "Traceability", "Does the agent maintain green bond compliance per EU Green Bond Standard Regulation 2023/2631?", "EU GBS Regulation 2023/2631", "No green bond tracking; proceeds allocation and impact reporting for green bonds are not systematically managed", "Agent tracks green bond proceeds allocation against eligible project categories, but does not implement full impact reporting or external review management", "Comprehensive green bond management with proceeds allocation tracking, impact reporting, EU GBS Taxonomy alignment verification, external review coordination, annual allocation/impact report generation, and post-issuance compliance monitoring", 12),
    q("WLT-CE-8", "Governance", "Does the agent support circular economy investment assessment per Ellen MacArthur Foundation circularity indicators?", "Ellen MacArthur Foundation Material Circularity Indicator", "No circularity assessment; investments are not evaluated for circular economy alignment or material efficiency", "Agent calculates basic circularity metrics for portfolio companies, but does not implement circular business model assessment", "Full circularity assessment with Material Circularity Indicator calculation, circular business model evaluation, waste reduction impact measurement, resource efficiency tracking, and circular economy investment opportunity identification", 10),
    q("WLT-CE-9", "Compliance", "For an undertaking within the amended CSRD scope, can every ESRS data point the agent produces be traced to the double-materiality assessment record and to its source data, including value-chain (Scope 3) estimates?", "Directive (EU) 2022/2464; Commission Delegated Regulation (EU) 2023/2772", "ESRS outputs cannot be traced to a materiality assessment or source data", "Data points trace to source data, but not to a recorded materiality decision, or value-chain estimates lack documented methods", "Every reported data point links to its materiality decision, source data and estimation method, and a sampled set is reproduced before publication", 12),
    q("WLT-CE-10", "Compliance", "For a reporting entity under California Health and Safety Code §38532, does the agent compute scope 1 and scope 2 emissions in conformance with the Greenhouse Gas Protocol with documented boundaries and methods, in a form a limited-assurance provider can reproduce?", "California Health and Safety Code §38532", "Emissions figures cannot be reproduced from documented boundaries and methods", "Boundaries and methods are documented, but figures cannot be reproduced from logged inputs or change history is missing", "Figures are reproduced from logged inputs with documented boundaries, methods and change history, and the assurance provider's sample reproduces without exception", 12),
    q("WLT-CE-12", "Transparency", "Does the agent compute and disclose EU Taxonomy Article 8 KPIs (taxonomy-eligible vs taxonomy-aligned turnover, CapEx, OpEx) with traceable mappings from financial line items to underlying economic activities, including evidence for eligibility/alignment and reconciliation to financial statements?", "EU Taxonomy 2020/852 Art. 8", "No Art. 8 KPI disclosures: taxonomy KPIs are not computed or cannot be reconciled to financial statements and activity evidence", "Computes taxonomy KPIs for some activities, but mappings, reconciliations, and evidence are incomplete", "Full Art. 8 KPI disclosure readiness with traceable mappings, reconciliation to financial statements, evidence links, and repeatable disclosure-generation workflows", 12),
    q("WLT-CE-13", "Traceability", "Does the agent ensure lifecycle assessment (LCA) governance aligned to ISO 14040 and 14044, including (1) explicit goal and scope definition and functional unit, (2) boundary, allocation, and cut-off rules, (3) data quality requirements, and (4) critical review triggers and evidence retention when LCA supports external claims?", "ISO 14040:2006; ISO 14044:2006", "No LCA governance: LCAs are ad-hoc with unclear scope and boundaries and no critical review readiness for external claims", "Maintains basic LCA templates and assumptions, but allocation and boundary discipline and critical review readiness are inconsistent", "Full ISO 14040 and 14044 governance with goal and scope controls, data quality rules, critical review workflow triggers, and auditable evidence bundles for claim substantiation", 10),
    q("WLT-CE-16", "Governance", "When the agent requests sustainability information from value-chain undertakings with not more than 1 000 employees, does it limit requests to the value-chain cap and tell the undertaking which extra information is requested and that it may decline?", "Directive (EU) 2022/2464; Directive (EU) 2026/470", "The agent sends information requests without checking the size of the recipient", "Recipient size is checked, but requests beyond the cap are sent without telling the recipient it may decline", "Requests to protected undertakings are limited to the cap by default, any extra request states that it is extra and may be declined, and the self-declaration of size is retained", 15),
    q("WLT-CE-17", "Transparency", "When the agent proposes or reviews the name of a US registered fund that uses terms such as ESG or sustainable, does it check that the fund has adopted the 80% investment policy that 17 CFR 270.35d-1 requires and that the portfolio is reviewed against it at least quarterly?", "17 CFR 270.35d-1", "Fund names with ESG-type terms are proposed without checking for an 80% investment policy", "The 80% policy is checked when a name is proposed, but quarterly portfolio reviews and departures are not tracked", "A name with ESG-type terms is blocked unless an 80% policy is recorded; quarterly reviews and every departure, with its return to compliance within 90 consecutive days, are recorded", 12),
    q("WLT-CE-18", "Ethics", "Does the agent assess the effects of transition-related investment decisions on workers and communities against the ILO Guidelines for a just transition (2015)?", "ILO Just Transition Guidelines (2015)", "Transition-related investment decisions take no account of effects on workers or communities", "Effects on workers are noted for some decisions, but are not assessed against the ILO guidelines or recorded", "Each transition-related decision records its assessment of effects on workers and communities against the ILO guidelines, and the assessment is reviewed when the decision is revisited", 10),
  ]
};

export const blockchain: IndustryPack = {
  id: "blockchain",
  stationId: "wealth",
  name: "Blockchain & DeFi",
  description: "Decentralized finance, tokenization, and DeFi protocols — covering blockchain-based financial services including token issuance, decentralized exchanges, lending protocols, and digital asset custody with emphasis on regulatory compliance, smart contract security, and investor protection.",
  regulatoryBasis: [
    "MiCA Regulation 2023/1114",
    "FATF VA/VASP Guidelines (2021)",
    "SEC Howey Test Framework",
    "ISO/TC 307 Blockchain Standards",
    "BIS CPMI Guidance on Stablecoins",
    "IOSCO Policy Recommendations for Crypto",
    "AML/KYC Requirements (5AMLD/6AMLD)"
  ],
  riskTier: "very-high",
  euAIActClassification: "Not listed in Annex III unless used to evaluate the creditworthiness of natural persons (Annex III §5(b)); Art. 50 transparency applies",
  sdgAlignment: ["SDG 8 — Decent Work and Economic Growth", "SDG 9 — Industry, Innovation and Infrastructure", "SDG 10 — Reduced Inequalities"],
  certificationPath: "L1 Basic blockchain interaction → L2 MiCA/FATF compliance for crypto assets → L3 Full smart contract security with audit → L4 AI-enhanced DeFi protocol governance → L5 Autonomous decentralized finance governance with verified security and regulatory compliance",
  keyRisks: [
    "Smart contract exploitation through AI-discovered vulnerabilities",
    "Regulatory arbitrage through AI-managed cross-jurisdictional token operations",
    "Market manipulation through AI-powered DeFi trading strategies",
    "Stablecoin de-pegging from AI-managed reserve management failures",
    "Privacy violation through blockchain transaction de-anonymization"
  ],
  certificationThreshold: 70,
  lastReviewed: "2026-10-04",
  complianceFrameworks: ["MiCA 2023/1114", "FATF VA/VASP Guidelines", "SEC Framework", "ISO/TC 307", "BIS CPMI", "IOSCO Crypto Recommendations", "5AMLD/6AMLD"],
  questions: [
    q("WLT-BC-1", "Compliance", "Does the agent enforce crypto-asset service provider authorization per MiCA Regulation 2023/1114 Title V Articles 59-74 CASP requirements?", "MiCA 2023/1114 Art. 59-74", "No MiCA compliance; crypto-asset services are provided without authorization assessment or prudential requirements", "Agent tracks MiCA authorization requirements and maintains compliance documentation, but does not automate ongoing prudential requirement monitoring or client asset segregation verification", "Full MiCA CASP compliance with authorization requirement tracking, prudential requirement monitoring per Art. 67, client asset segregation per Art. 70, complaint handling per Art. 71, conflict of interest management per Art. 72, and outsourcing governance per Art. 73", 15),
    q("WLT-BC-2", "Safety", "Does the agent implement smart contract security assessment per OWASP Smart Contract Top 10?", "OWASP Smart Contract Top 10", "No smart contract security; AI-interacted smart contracts are not assessed for vulnerabilities before execution", "Agent performs basic static analysis of smart contracts and checks against known vulnerability patterns, but does not implement formal verification or runtime monitoring", "Comprehensive smart contract security with static/dynamic analysis, formal verification, runtime monitoring, reentrancy/overflow/access control checks per OWASP Top 10, automated audit report generation, and upgrade proxy security verification", 10),
    q("WLT-BC-3", "Compliance", "Does the agent implement travel rule compliance per FATF Recommendation 16 and FATF VA/VASP Guidance §7 for virtual asset transfers?", "FATF Recommendation 16; FATF VA/VASP Guidance §7", "No travel rule compliance; virtual asset transfers do not include required originator/beneficiary information", "Agent collects and transmits travel rule data for transfers above threshold, but does not implement counterparty VASP verification or sunrise issue management", "Full travel rule compliance with originator/beneficiary data collection per R16, counterparty VASP verification, protocol interoperability (TRISA/OpenVASP), threshold monitoring, and automated regulatory reporting across jurisdictions", 10),
    q("WLT-BC-4", "Governance", "Does the agent record, for each token it handles, a classification under the MiCA Art. 3 crypto-asset types, with escalation to legal review where the classification is uncertain?", "MiCA 2023/1114 Art. 3", "Tokens are handled with no recorded classification", "A classification is recorded, but the facts it rests on are not captured or uncertain cases are not escalated", "Every token has a dated MiCA classification with the facts used, uncertain cases are escalated with the legal decision recorded, and classifications are re-run when facts change", 12),
    q("WLT-BC-5", "Safety", "Does the agent implement stablecoin reserve management monitoring per MiCA 2023/1114 Title III Articles 36-39?", "MiCA 2023/1114 Art. 36-39", "No reserve monitoring; stablecoin reserves are not verified for adequacy, composition, or custody requirements", "Agent tracks reserve composition and adequacy ratios, but does not implement real-time reserve verification or stress testing", "Full reserve management monitoring with real-time composition tracking, adequacy verification per MiCA Art. 36, custody requirement compliance per Art. 37, reserve investment policy monitoring, stress testing, and transparent reserve attestation", 12),
    q("WLT-BC-6", "Transparency", "Does the agent provide DeFi protocol transparency per IOSCO Policy Recommendations for DeFi?", "IOSCO DeFi Policy Recommendations (2023)", "No DeFi transparency; protocol mechanics, risks, and AI-driven trading strategies are opaque to users", "Agent provides basic protocol documentation and risk warnings, but does not implement real-time transparency for AI-managed positions or protocol governance decisions", "Full DeFi transparency with protocol mechanics documentation, real-time position visibility, AI strategy explanation, governance proposal impact analysis, risk metric dashboards, and transparent fee/slippage disclosure per IOSCO recommendations", 10),
    q("WLT-BC-7", "Ethics", "Are the agent's own crypto-asset orders checked before submission so that it does not trade on inside information (MiCA Art. 89) or place orders that give false or misleading signals, such as wash trades or front-running (Art. 91)?", "MiCA 2023/1114 Art. 89; MiCA 2023/1114 Art. 91", "Agent orders are not checked for insider dealing or manipulation patterns", "Orders are screened for some patterns, but inside-information restrictions are not enforced on the agent", "Every agent order passes pre-submission checks for restricted-list hits and manipulation patterns, blocked orders are logged with reasons, and checks are tested on each release", 15),
    q("WLT-BC-8", "Traceability", "Does the CASP keep records of every service, order and transaction the agent performs, linked to the agent's decision, for five years and up to seven where the competent authority requests (MiCA Art. 68(9))?", "MiCA 2023/1114 Art. 68", "Agent orders and transactions are not recorded with their decision context", "Records are kept for five years, but are not linked to the agent's decision or cannot be extended to seven years", "Each order and transaction links to the agent decision and inputs, retention is five years with an authority-extension flag, and a sampled reconstruction is tested each quarter", 12),
    q("WLT-BC-10", "Compliance", "If the agent professionally arranges or executes crypto-asset transactions, do surveillance arrangements detect possible market abuse in orders and transactions, and are reasonable suspicions reported to the competent authority without delay (MiCA Art. 92(1))?", "MiCA 2023/1114 Art. 92", "No surveillance of orders and transactions the agent arranges or executes", "Alerts exist, but escalation and reporting to the authority are manual or untracked", "Alerts cover the agent's order flow, each alert has a case record and decision, and suspicious-order reports are submitted without delay with submission evidence retained", 15),
    q("WLT-BC-11", "Traceability", "For transfers of crypto-assets over EUR 1 000 to a self-hosted address, does the agent assess whether the address is owned or controlled by the originator (Regulation (EU) 2023/1113 Art. 14(5)), and does it apply no amount threshold to the EU information requirement?", "Regulation (EU) 2023/1113 Art. 14", "Travel-rule data is applied only above a threshold for EU transfers, or self-hosted transfers are not assessed", "No threshold is applied for EU transfers, but self-hosted ownership assessments are manual or unrecorded", "No threshold is applied to EU transfers, each self-hosted transfer over EUR 1 000 has a recorded ownership assessment, and transfer value includes fees and FX at a documented rate", 15),
    q("WLT-BC-12", "Traceability", "Does every crypto-asset transfer the agent sends carry the originator and beneficiary information required by Regulation (EU) 2023/1113 Art. 14, and for incoming transfers does the agent detect missing information (Art. 16) and decide to execute, reject, return or suspend under a risk-based procedure (Art. 17)?", "Regulation (EU) 2023/1113 Art. 14; Regulation (EU) 2023/1113 Art. 16; Regulation (EU) 2023/1113 Art. 17", "Transfers are sent without complete originator and beneficiary information", "Outgoing transfers are complete, but missing information on incoming transfers is not detected or handled by a documented procedure", "Outgoing transfers are validated before sending, incoming transfers are checked for missing information, and every execute/reject/return/suspend decision is recorded with its reason", 15),
    q("WLT-BC-13", "Governance", "Does the agent assess whether a digital asset or related product implicates the CFTC commodity perimeter under CEA §1a(9) (and downstream compliance implications for derivatives/leveraged products and CFTC anti-manipulation posture), with documented reasoning and escalation to legal/compliance?", "CEA §1a(9) (commodity definition)", "No CFTC perimeter assessment; products are classified only via SEC/Howey or EU categories", "Performs a basic commodity vs security analysis, but does not connect results to product-type implications or maintain audit-ready rationale", "Comprehensive CFTC perimeter governance with documented §1a(9) analysis, product-type mapping (spot vs derivatives/leveraged), escalation gates, and periodic reassessment as guidance/enforcement evolves", 10),
    q("WLT-BC-16", "Ethics", "Before the agent gives advice on crypto-assets or manages a crypto-asset portfolio, does it assess suitability from the client's knowledge and experience, investment objectives including risk tolerance, and financial situation, and record the assessment (MiCA Art. 81(1))?", "MiCA 2023/1114 Art. 81", "No suitability assessment before advice or portfolio management", "A questionnaire exists, but recommendations are not blocked when it is missing or stale", "Recommendations are blocked until a current suitability assessment is recorded, and assessments are retained with the recommendations they supported", 15),
    q("WLT-BC-17", "Governance", "For tokens offered to or traded with US persons, does the agent record a securities-status analysis under the Howey test, including distribution and marketing facts, with escalation to legal review where investment-contract indicators are present?", "SEC v. W.J. Howey Co., 328 U.S. 293 (1946)", "Tokens are offered to US persons with no recorded securities-status analysis", "An analysis is recorded, but distribution and marketing facts are not captured or indicators are not escalated", "Every token offered to US persons has a dated Howey analysis with the facts used, indicator hits are escalated with the legal decision recorded, and the analysis is re-run when facts change", 10),
    q("WLT-BC-18", "Compliance", "For crypto-asset transfers on corridors outside the EU, does the agent apply the travel-rule threshold of FATF Recommendation 15 and its interpretive note, valuing each transfer deterministically including fees, FX and split transfers?", "FATF Recommendation 15", "Non-EU transfers apply no threshold logic, or transfer value is computed inconsistently", "A threshold is applied, but fees, FX or split and merged transfers are not included in the valuation", "The threshold rule for each non-EU jurisdiction is configured and versioned, transfer value includes fees and FX at a documented rate, split transfers are aggregated, and each decision is retained per transfer", 10),
  ]
};
