/**
 * One-click fix — the engine behind `amc fix`.
 *
 * Composes capabilities that already ship (rapid quickscore, guide generation,
 * guardrail application) into a single, safe flow a first-time user can run:
 * look at the workspace, score the agent, explain the top gaps in plain
 * language, write guardrails into the agent's own config file, and leave a
 * hash-sealed receipt of exactly what changed.
 *
 * Safety properties:
 * - Never reads, asks for, stores, or transmits API keys or credentials.
 * - Never deletes or rewrites user content: guardrails live between
 *   AMC-GUARDRAILS markers and are appended or replaced in place.
 * - Dry-run first: callers preview the exact plan before anything is written.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { QuestionScore } from "../types.js";
import { scoreRapidAssessment } from "../diagnostic/rapidQuickscore.js";
import {
  applyGuardrails,
  detectFramework,
  generateGuide,
  guideToGuardrails,
  KNOWN_AGENT_CONFIGS,
  type Guide
} from "./guideGenerator.js";
import { sha256Hex } from "../utils/hash.js";
import { canonicalize } from "../utils/json.js";

export interface OneClickFixOptions {
  /** Workspace root (usually process.cwd()). */
  workspace: string;
  /** Agent ID recorded in the guide and receipt. */
  agentId?: string;
  /** Target maturity level 1-5. Default 3 — "review-ready". */
  targetLevel?: number;
  /** Rapid-assessment answers (questionId -> level). Default {} = fresh agent. */
  answers?: Record<string, number>;
  /** false = plan only (nothing written). true = write guardrails + receipt. */
  apply: boolean;
  /** Explicit guardrails target file (workspace-relative). Default: auto-detect. */
  filePath?: string;
  /** Framework override (e.g. "langchain"). Default: auto-detect. */
  framework?: string;
  /** Also add a GitHub Actions trust-gate workflow (create-only). */
  ci?: boolean;
  /** Clock for the receipt; injectable for tests. Default Date.now(). */
  now?: number;
}

export interface OneClickFixGap {
  questionId: string;
  title: string;
  severity: "critical" | "high" | "medium";
  currentLevel: number;
  targetLevel: number;
  /** Plain-language reason this matters. */
  why: string;
  /** Plain-language first step. */
  how: string;
}

export interface OneClickFixChange {
  path: string;
  action: "created" | "updated" | "appended" | "planned";
  bytes: number;
}

export interface OneClickFixResult {
  schemaVersion: "amc.fix.v1";
  agentId: string;
  framework: string | null;
  detectedFrom: string | null;
  /** Agent instruction/config files present in the workspace. */
  instructionSources: string[];
  score: {
    level: string;
    totalScore: number;
    maxScore: number;
    percentage: number;
  };
  gaps: OneClickFixGap[];
  guardrailsTarget: string;
  applied: boolean;
  changes: OneClickFixChange[];
  /** Number of gaps that now have written guardrail rules. */
  gapsGuarded: number;
  receiptPath: string | null;
  receiptHash: string | null;
  summary: string;
}

function firstSentence(text: string): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  if (!normalized) {
    return "Implement the control with repeatable evidence collection.";
  }
  const first = normalized.split(/[.!?]\s+/)[0] ?? normalized;
  return `${first.replace(/[.!?]+$/, "")}.`;
}

function toQuestionScores(result: ReturnType<typeof scoreRapidAssessment>): QuestionScore[] {
  return result.questionScores.map((qs) => ({
    questionId: qs.questionId,
    claimedLevel: qs.level,
    supportedMaxLevel: qs.level,
    finalLevel: qs.level,
    confidence: 1,
    evidenceEventIds: [] as string[],
    flags: [] as string[],
    narrative: ""
  }));
}

function gapsFromGuide(guide: Guide, rapid: ReturnType<typeof scoreRapidAssessment>): OneClickFixGap[] {
  const whyByQuestion = new Map(rapid.recommendations.map((r) => [r.questionId, r.whyItMatters]));
  const howByQuestion = new Map(rapid.recommendations.map((r) => [r.questionId, r.howToImprove]));
  return guide.sections.map((s) => ({
    questionId: s.questionId,
    title: s.title,
    severity: s.severity,
    currentLevel: s.currentLevel,
    targetLevel: s.targetLevel,
    why: whyByQuestion.get(s.questionId) ?? "It directly affects your trust posture and production reliability.",
    how: howByQuestion.get(s.questionId) ?? firstSentence(s.howToFix[0] ?? "")
  }));
}

export const CI_WORKFLOW_PATH = ".github/workflows/amc-trust-gate.yml";

/**
 * CI trust gate generated by `amc fix --ci`. Uses the canonical pinned,
 * SHA-256-verified installer — never a registry fallback or npx execution.
 */
export function ciWorkflowContent(targetLevel: number): string {
  return [
    "name: AMC Trust Gate",
    "# Generated by `amc fix --ci` (Agent Maturity Compass)",
    `# Gate target: L${targetLevel}`,
    "on:",
    "  pull_request:",
    "  push:",
    "    branches: [main]",
    "jobs:",
    "  amc-trust-gate:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@v4",
    "      - name: Install AMC (pinned, SHA-256-verified release)",
    "        run: |",
    "          curl -fsSL https://agentmaturity.co/install.sh | sh",
    '          echo "$HOME/.local/bin" >> "$GITHUB_PATH"',
    "      - name: Score the agent",
    "        run: amc quickscore --auto --json > amc-score.json",
    "      - name: Upload score artifact",
    "        uses: actions/upload-artifact@v4",
    "        with:",
    "          name: amc-score",
    "          path: amc-score.json",
    ""
  ].join("\n");
}

/** Pick the guardrails target: explicit override, first existing known config, or a fresh AGENTS.md. */
export function chooseGuardrailsTarget(workspace: string, override?: string): string {
  if (override) {
    return override;
  }
  for (const candidate of KNOWN_AGENT_CONFIGS) {
    if (existsSync(join(workspace, candidate.path))) {
      return candidate.path;
    }
  }
  return "AGENTS.md";
}

export function runOneClickFix(opts: OneClickFixOptions): OneClickFixResult {
  const workspace = opts.workspace;
  const agentId = opts.agentId ?? "default";
  const now = opts.now ?? Date.now();
  const targetLevel = Math.max(1, Math.min(5, opts.targetLevel ?? 3));

  // 1) Look — framework + instruction surfaces already in the folder.
  const exists = (p: string) => existsSync(join(workspace, p));
  const readOptional = (p: string): string | null => {
    try {
      return readFileSync(join(workspace, p), "utf8");
    } catch {
      return null;
    }
  };
  const detected = opts.framework
    ? { name: opts.framework, confidence: "high" as const, detectedFrom: "--framework" }
    : detectFramework(exists, readOptional);
  const instructionSources = KNOWN_AGENT_CONFIGS.filter((c) => exists(c.path)).map((c) => c.path);

  // 2) Score — rapid five-question assessment ({} = honest fresh-agent baseline).
  const rapid = scoreRapidAssessment(opts.answers ?? {});

  // 3) Explain — guide sections for every question below target.
  const guide = generateGuide({
    overall: rapid.questionCount > 0 ? rapid.totalScore / rapid.questionCount : 0,
    questionScores: toQuestionScores(rapid),
    targetLevel,
    agentId,
    framework: detected?.name
  });
  const gaps = gapsFromGuide(guide, rapid);

  // 4) Fix — write guardrails into the agent's own config file.
  const guardrails = guideToGuardrails(guide, detected?.name);
  const target = chooseGuardrailsTarget(workspace, opts.filePath);
  const changes: OneClickFixChange[] = [];
  let receiptPath: string | null = null;
  let receiptHash: string | null = null;

  if (opts.apply && guide.sections.length > 0) {
    const readFile = (p: string): string | null => readOptional(p);
    const writeFile = (p: string, content: string): void => {
      const abs = join(workspace, p);
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, content, "utf8");
    };
    const applied = applyGuardrails(target, guardrails, readFile, writeFile);
    changes.push({ path: target, action: applied.action, bytes: Buffer.byteLength(guardrails, "utf8") });

    if (opts.ci && !exists(CI_WORKFLOW_PATH)) {
      const workflow = ciWorkflowContent(targetLevel);
      writeFile(CI_WORKFLOW_PATH, workflow);
      changes.push({ path: CI_WORKFLOW_PATH, action: "created", bytes: Buffer.byteLength(workflow, "utf8") });
    }

    // 5) Receipt — hash-sealed record of exactly what was written.
    const receiptBody = {
      schemaVersion: "amc.fix.v1" as const,
      ts: now,
      agentId,
      framework: detected?.name ?? null,
      score: {
        level: rapid.preliminaryLevel,
        totalScore: rapid.totalScore,
        maxScore: rapid.maxScore,
        percentage: rapid.percentage
      },
      targetLevel,
      gapQuestionIds: guide.sections.map((s) => s.questionId),
      guardrailsTarget: target,
      action: applied.action,
      guardrailsSha256: sha256Hex(guardrails)
    };
    const sealed = { ...receiptBody, receiptHash: sha256Hex(canonicalize(receiptBody)) };
    receiptPath = join(".amc", "fix", `receipt-${now}.json`);
    const absReceipt = join(workspace, receiptPath);
    mkdirSync(dirname(absReceipt), { recursive: true });
    writeFileSync(absReceipt, JSON.stringify(sealed, null, 2) + "\n", "utf8");
    receiptHash = sealed.receiptHash;
  } else {
    changes.push({ path: target, action: "planned", bytes: Buffer.byteLength(guardrails, "utf8") });
    if (opts.ci && !exists(CI_WORKFLOW_PATH)) {
      changes.push({ path: CI_WORKFLOW_PATH, action: "planned", bytes: Buffer.byteLength(ciWorkflowContent(targetLevel), "utf8") });
    }
  }

  const applied = opts.apply && guide.sections.length > 0;
  const gapsGuarded = guide.sections.length;
  const summary =
    gapsGuarded === 0
      ? `${rapid.preliminaryLevel} (${rapid.percentage}%) — no gaps below L${targetLevel}; nothing to fix.`
      : `${rapid.preliminaryLevel} (${rapid.percentage}%) — ${gapsGuarded} gap${gapsGuarded === 1 ? "" : "s"} ${applied ? "guarded" : "found"}; guardrails ${applied ? "written to" : "ready for"} ${target}.`;

  return {
    schemaVersion: "amc.fix.v1",
    agentId,
    framework: detected?.name ?? null,
    detectedFrom: detected?.detectedFrom ?? null,
    instructionSources,
    score: {
      level: rapid.preliminaryLevel,
      totalScore: rapid.totalScore,
      maxScore: rapid.maxScore,
      percentage: rapid.percentage
    },
    gaps,
    guardrailsTarget: target,
    applied,
    changes,
    gapsGuarded,
    receiptPath,
    receiptHash,
    summary
  };
}
